### PR TITLE
Basic Viewers: Voronoi Diagram, 2D Periodic Triangulation and Nef_3

### PR DESCRIPTION
**Pull request by gdamiand**
Implement draw() functionality for Voronoi Diagram. Voronoi vertices, dual vertices, segments, rays, and bounded faces can be visualized using this functionality. The documentation is also added.

Release Management
Affected package(s): Voronoi_Diagram_2, 2D Periodic Triangulation and Nef_3

### CODE REVIEW

**Comment by gdamiand** [comment]
This PR is almost ready (again) for testing.

I am not able to solve the error with licence. @sloriot , @maxGimeno , @lrineau can you help me please ?

**Comment by sloriot** [comment]
Should be good now!

The license statement is no longer needed now, only the SPDX tag.

**Comment by gdamiand** [comment]
Thanks @sloriot  !!

**Comment by gdamiand** [comment]
There is one error but it seems to be a timeout during the test of dependencies ???

**Comment by gdamiand** [comment]
@sloriot  Do you consider this PR ready for testing ?

**Comment by maxGimeno** [comment]
@gdamiand  I restarted the CI and it passed, so I'll start testing the PR tonight if there is not too many conflicts with other PRs.

**Comment by gdamiand** [comment]
Thanks @maxGimeno .

**Comment by maxGimeno** [comment]
Errors: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-9.shtml#Polyhedron_Demo
The function add_point_in_buffer(), in Buffer_for_vao, has been changed into a non-static one, and it broke every item in the demo.

**Comment by gdamiand** [comment]
Should be solved by https://github.com/CGAL/cgal/pull/4224/commits/157116f7c87cee4b1abbff61155cc66f851f7427.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-18.shtml

**Comment by lrineau** [comment]
It seems this PR adds new documentation. Has anyone reviewed the documentation?  Maybe there is a small feature that is not mentioned in the PR. Let me know.

**Comment by gdamiand** [comment]
I did the review. There is no small feature but the gsoc page https://cgal.geometryfactory.com/CGAL/Members/wiki/GSoC2019/BasicViewer.

**Pull request merged**
