### PR TITLE
Installation - matching bug is fixed in MSVC >= 2015

### LINKED ISSUE #5021: CGAL_CFG_MATCHING_BUG is not needed by MSVC >= 2015
## Issue Details

I commented all the `#define` of `Installation\include\CGAL\MSVC_compiler_config.h` and compiled the tests and examples of Mesh_3. It turns out that the macros defined to avoid the "matching bug" are not needed anymore with MSVC 2019 (version 16).
I tried a few examples with the compilers of MSVC 2015, 2017 and 2019 and they behave similarly (no error).

Should we start thinking of removing them?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC >= 2015
* Release or debug mode: both
* CGAL version:  releases/CGAL-5.0-branch

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

MSVC 2015 and later versions do not have the "matching bug" worked around by CGAL macros `CGAL_CFG_MATCHING_BUG_n`.

This PR removes the code that was necessary with previous versions of MSVC.

Note that since CGAL supports C++14, it does not support MSVC 2013 and earlier anymore.

## Release Management

* Affected package(s): Installation, Arrangement_on_surface_2, Circular_kernel_2, Circular_kernel_3, Filtered_kernel, Kernel_23, Periodic_2_triangulation_2, Periodic_3_triangulation_3, Periodic_4_hyperbolic_triangulation_2, STL_Extension, Triangulation_3
Note I have manually ran `ctest` on most of the above packages for MSVC 2019.

* Issue(s) solved (if any): fix #5021
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
The other macro that got removed because it is obsolete is `CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG `.
Grepping it gives the following list of comments :
```
 grep CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG -R . --include *.h
./Filtered_kernel/include/CGAL/Filtered_construction.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./Filtered_kernel/include/CGAL/Filtered_predicate.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./Filtered_kernel/include/CGAL/Filtered_predicate_with_state.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./Filtered_kernel/include/CGAL/Lazy.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./Skin_surface_3/include/CGAL/Skin_surface_base_3.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
./Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h:  // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
```

Should I simply remove the comments?

**Comment by lrineau** [comment]
> The other macro that got removed because it is obsolete is `CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG `.
> Grepping it gives the following list of comments :
> 
> ```
>  grep CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG -R . --include *.h
> ./Filtered_kernel/include/CGAL/Filtered_construction.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./Filtered_kernel/include/CGAL/Filtered_predicate.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./Filtered_kernel/include/CGAL/Filtered_predicate_with_state.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./Filtered_kernel/include/CGAL/Lazy.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./NewKernel_d/include/CGAL/NewKernel_d/Filtered_predicate2.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./Skin_surface_3/include/CGAL/Skin_surface_base_3.h:    // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ./Skin_surface_3/include/CGAL/triangulate_mixed_complex_3.h:  // Protection is outside the try block as VC8 has the CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
> ```
> 
> Should I simply remove the comments?

No. That one is different. We should try in another PR.

**Comment by lrineau** [comment]
Travis: https://travis-ci.com/github/CGAL/cgal/jobs/391183873#L3176
```
.. Look for trailing whitespaces...
The following files have trailing whitespaces:
Circular_kernel_2/include/CGAL/Circular_kernel_2/function_objects_polynomial_circular.h
```

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-18.shtml

**Pull request merged**
