### PR TITLE
PMP isotropic_remeshing - add example using `allow_move_functor`

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

add an example using named parameter introduced in PR #8150

## Release Management

* Affected package(s):
* Issue(s) solved (if any): partially solves #8134
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by lrineau** [comment]
Nice feature. Note https://github.com/CGAL/cgal/pull/8150#discussion_r1605006265, that could be fixed in _this_ PR.

**Comment by janetournois** [comment]
> Nice feature. Note [#8150 (comment)](https://github.com/CGAL/cgal/pull/8150#discussion_r1605006265), that could be fixed in _this_ PR.

done

**Comment by janetournois** [comment]
My choice would be to write as-readable-as-possible examples, as long as it does not impact performance

**Comment by lrineau** [comment]
Jane, this PR was submitted as a draft. You have removed the TODO label. Is it still a draft?

**Comment by sloriot** [comment]
PMP test failings in CGAL-6.0-Ic-276

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-282

**Comment by afabri** [comment]
Is the suffix `_functor` really needed?

**Pull request merged**
