### PR TITLE
Add a new test for documented named parameters

### PR DESCRIPTION
**Pull request by sloriot**
Note the check should fail otherwise the script does not work

### CODE REVIEW

**Comment by lrineau** [comment]
> It can be merged only after #6072 and #6068 (otherwise all PRs will have their check failing)

Problem: this PR is for `5.3.x-branch`, but #6072 is for `master`.

**Comment by sloriot** [comment]
It was only a github issue, the branch was based on 5.3. Fixed now

**Comment by sloriot** [comment]
Branch rebased, now waiting for the green light of github action to merge this PR.

**Comment by sloriot** [comment]
@lrineau all good, ready to be merged.

**Comment by lrineau** [comment]
master is now broken, according to Github Actions: https://github.com/CGAL/cgal/runs/4078389895?check_suite_focus=true#step:4:32

**Pull request merged**
