### PR TITLE
Warning fix

### PR DESCRIPTION
**Pull request by maxGimeno**
- addition of casts to silence warnings in Viewer.

### CODE REVIEW

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-20][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-20.shtml

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-21][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-21.shtml

**Comment by lrineau** [comment]
Merged in [CGAL-4.8-Ic-22](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-22.shtml).

**Comment by lrineau** [comment]
Merged in [CGAL-4.8-Ic-23](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-23.shtml).

**Comment by janetournois** [comment]
I just added commit 7fc8ba2012a8974cb39cd4357c852a77441b289b to the branch in cgal-dev,
and pushed it to integration (to be tested in Ic-23).

**Comment by lrineau** [comment]
@janetournois: Which commit 7fc8ba7?!

**Comment by janetournois** [comment]
7fc8ba2012a8974cb39cd4357c852a77441b289b in cgal-dev

**Comment by lrineau** [comment]
I have pushed 7fc8ba2012a8974cb39cd4357c852a77441b289b to this pull-request. I will merge it, now.

**Pull request merged**
