### PR TITLE
ImageIO: Add offset from vtk

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

take offset from vtkImage and add it to cgal image.
## Release Management

* Affected package(s):ImageIO

### CODE REVIEW

**Comment by alefy** [comment]
Hello Everyone,

I think that I have encountered an issue with this modification, in particular when using Mesh_3.

This modification introduces an offset in Image_3 which is defined as the origin of the (VTK) image.

However, in Mesh_3, compute_bounding_box(...) in both Labeled_image_mesh_domain_3.h and Labeled_mesh_domain_3.h does not account for this offset and Mesh_3 may fail to mesh later on when using create_gray_image_mesh_domain(...) for instance.

For me, a quick modification to Image_3.h to define the getters for tx(), ty(), tz() and modification of compute_bounding_box() in Labeled_image_mesh_domain_3.h and Labeled_mesh_domain_3.h appears to have solved the  #issue.

I have tested the solution with CGAL 4.13.1.

Let me know if you want additional information.

Best regards,
Adrien Lefieux

**Comment by lrineau** [comment]
It seems you are right, @alefy. I am surprised we did not see that issue using our 3D demo. Can you share your patch?

**Comment by alefy** [comment]
Dear Laurent,

Here is a quick patch from CGAL_4.13.1

[CGAL-4.13.1_issueoffset.txt](https://github.com/CGAL/cgal/files/3301664/CGAL-4.13.1_issueoffset.txt)

I can clone the master branch, do the change and validate it if you prefer, but it will take me more time.

Best,
Adrien

**Comment by lrineau** [comment]
Thanks for the patch. I have create the PR https://github.com/CGAL/cgal/pull/4014. It will go into out integration process, and will land in CGAL-4.13.2, CGAL-4.14.1, and CGAL-5.0...

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jun 18, 2019, 4:17 PM GMT+2](https://github.com/CGAL/cgal/pull/3539#issuecomment-503156013 "2019-06-18T14:17:44Z - Replied by Github Reply Comments"):
> Thanks for the patch. I have create the PR https://github.com/CGAL/cgal/pull/4014. It will go into out integration process, and will land in CGAL-4.13.2, CGAL-4.14.1, and CGAL-5.0...

This PR is now merged in the branch for CGAL-4.14.1.

**Pull request merged**
