### PR TITLE
Polyhedron demo: filter the AABB_tree representation

### LINKED ISSUE #4909: Polyhedron demo: AABB Tree
## Issue Details

It would be interesting to have a slider which shows the AABBs of level `N`.   And similarly the boxes traversed by a ray.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
The Scene_aabb_item is not very readable, as it shows every box of the tree of a surface mesh.  
In this PR, I added options in the menu of the item to display only the Nth level of the tree and or only the intersected cells (by the cut plane) : 
- The basic tree of an elephant:

full

- the new menu: 
menu

- the new tooltip:

tooltip

- Only one level of the same tree:

lvl

-  The same level intersected by the plane:

plane

## Release Management

* Issue(s) solved (if any): fix #4909

### CODE REVIEW

**Comment by afabri** [comment]
Can you also draw  all the boxes intersected when you move the green plane?   I would then expect to see the top levels and less and less low level boxes.

**Comment by maxGimeno** [comment]
@afabri if you want all the boxes, set the slider to the far left. On this screen shot there the slider is far to the right, so you don't have the low level boxes, but you can.

**Comment by lrineau** [comment]
There are multiple warnings with this PR:
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-6.shtml#Polyhedron_Demo

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-12.shtml

**Pull request merged**
