### PR TITLE
Update the Three documentation

### LINKED ISSUE #2004: Polyhedron_demo : Update and fix the doc
## Issue Details

The doc for the Three package is wrong at several levels. It needs to be partially re-written.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

The reference manual has been rewritten in a way that is supposed to be more clear and useful.
New doc visible [here](https://cgal.geometryfactory.com/~mgimeno/Three/Three/index.html).
## Release Management

* Affected package(s):Polyhedron_demo, Three
* Issue(s) solved (if any): fix #2004

### CODE REVIEW

**Comment by lrineau** [comment]
The Polyhedron_demo does not build: https://travis-ci.org/CGAL/cgal/jobs/219258495

**Comment by lrineau** [comment]
The Travis compilation still fail. Does it  build locally?

**Comment by lrineau** [comment]
This PR has conflicts with `master`.

**Comment by lrineau** [comment]
Travis build failure: https://travis-ci.org/CGAL/cgal/jobs/237514233

I actually does not understand the build failure. What failed was the build of the header file `CGAL_ImageIO/include/CGAL/Image_3_impl.h`, but that header does not seem modified by the PR!

**Comment by maxGimeno** [comment]
I just restarted the job and this time it didn't fail.

**Comment by lrineau** [comment]
New warnings:
```
Scene.h:58:7: warning: 'erase' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:129:8: warning: 'postDraw' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:130:8: warning: 'paintEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:131:8: warning: 'paintGL' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:134:8: warning: 'mousePressEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:135:8: warning: 'wheelEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:137:8: warning: 'keyPressEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:139:8: warning: 'contextMenuEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:141:8: warning: 'keyReleaseEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:144:8: warning: 'resizeGL' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:43:8: warning: 'draw' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:45:8: warning: 'drawVisualHints' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:47:8: warning: 'fastDraw' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:48:8: warning: 'isExtensionFound' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:50:8: warning: 'initializeGL' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:52:8: warning: 'drawWithNames' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:57:8: warning: 'postSelection' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:59:8: warning: 'beginSelection' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:61:8: warning: 'endSelection' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:63:8: warning: 'setScene' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:65:8: warning: 'antiAliasing' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:67:8: warning: 'inFastDrawing' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:69:8: warning: 'inDrawWithNames' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Viewer.h:71:8: warning: 'attribBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

```
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-34.shtml#Polyhedron_Demo

**Pull request merged**
