### PR TITLE
Generate CMakelists

### LINKED ISSUE #384: Add all CMakeLists.txt in the repository
Add all CMakeLists.txt in the repository instead of generating them when configuring cgal.

We discussed that several times, and it seems everybody find this is a good idea.

### PR DESCRIPTION
**Pull request by sloriot**
... and remove Core requirement when non needed

Fix #384

### CODE REVIEW

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-1/Mesh_2/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz
> /no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/Mesh_2/test_conforming.cpp:(.text._ZN4CGAL25side_of_oriented_circleC2IN4CORE4ExprEEENS_19Same_uncertainty_ntINS_4SignET_E4typeERKS5_S9_S9_S9_S9_S9_S9_S9_[_ZN4CGAL25side_of_oriented_circleC2IN4CORE4ExprEEENS_19Same_uncertainty_ntINS_4SignET_E4typeERKS5_S9_S9_S9_S9_S9_S9_S9_]+0xb6): undefined reference to `CORE::AddSubRep<CORE::Sub>::operator new(unsigned long)'

**Comment by lrineau** [comment]
And more generally, there are suspicious errors in the columns on MacOS
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-1.shtml

**Comment by lrineau** [comment]
@sloriot ping!

**Comment by sloriot** [comment]
updated

**Comment by lrineau** [comment]
Will be tested in CGAL-4.9-Ic-6.

**Pull request merged**
