### PR TITLE
Fix CTest on windows

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

I think I have managed to fix CTest on Windows, and that should also fix our attempts with Azure.

@maxGimeno Can you please try this branch in Azure?

## Release Management

* Affected package(s): all
* License and copyright ownership: maintenance by GF

### CODE REVIEW

**Comment by lrineau** [comment]
@maxGimeno What is the relation between this PR and #4128? They seem to share commits.

Have we eventually manage to test the commits of this PR?

**Comment by maxGimeno** [comment]
We tested this PR on Azure, it worked. I don't see any common commit though.  
I don't see any shared commit on github, are you sure ? 
And shouldn't you base this commit on 4.13 as you told me for #4128 ?

**Comment by lrineau** [comment]
I cannot rebase it on 4.13, because it modifies files that did not yet exist in 4.13, but I was able to base it on 4.14. There one minor conflict with `master`. I suggest the PR to be tested ASAP.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-129.shtml

**Pull request merged**
