### PR TITLE
Read PLY polygon soup

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

This is a first step for solving the issue https://github.com/CGAL/cgal/issues/2196:
* it adds some (internal) needed methods/functions in the existing PLY headers (in point set processing)
* it adds functions to read/write PLY polygon soups (and to write face graphs)
* it adds mesh polygon soup support to the PLY plugin

So far, this PR only modifies internal code and demo code. To fully solve the issue https://github.com/CGAL/cgal/issues/2196, there should also be a small feature to document `read_OFF()` and these new PLY functions.

## Release Management

* Affected package(s): Polyhedron demo, Point Set Processing, Polyhedron IO (but no API change and no new documented function)
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/2196
* Dependences: https://github.com/CGAL/cgal/pull/2138 (should not be merged before this one)

### CODE REVIEW

**Comment by lrineau** [comment]
There is a Travis build error: https://travis-ci.org/CGAL/cgal/jobs/252398163#L4568

Do you reproduce it locally?

**Comment by sgiraudot** [comment]
Yes, it should be fixed now.

**Comment by lrineau** [comment]
I have selected CGAL-4.12 for this PR, unless we have good reason for force its way into CGAL-4.11.

**Comment by sloriot** [comment]
I tried merging this PR in the testsuite but got some strange merge conflict. I wonder whether you forgot to rebase after the depent PR was integrated?

**Comment by sgiraudot** [comment]
Rebasing gives me conflicts everywhere for a reason I don't understand (this is not the first time I have trouble with this, I know `git rebase` is supposed to be the best way to rebase on master, but I much prefer the method based on remerging the branch into a fresh master…).

I'm working on it.

**Comment by sloriot** [comment]
New errors on one platform:
```
CGAL-4.12-Ic-5/results_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.txt	
+Point_set_3 n
+Point_set_3_Examples n
+Point_set_processing_3_Examples n
+Polyhedron_Demo n
+Scale_space_reconstruction_3_Examples n
```

**Comment by sgiraudot** [comment]
They should be fixed now.

**Comment by sloriot** [comment]
@sgiraudot must handle colors that are not encoded using `int`.

**Comment by sgiraudot** [comment]
(It's the indices of the polyhedron that do not work if they are not `int`, colors works fine, but it's a detail.)

**Pull request merged**
