### PR TITLE
Mesh_3: fix two bugs

### PR DESCRIPTION
**Pull request by lrineau**

### CODE REVIEW

**Comment by janetournois** [comment]
the missing `const` was misleading the compiler when `CGAL_LINKED_WITH_TBB` is defined. Tests should be green now.

**Comment by janetournois** [comment]
I remerged this PR into integration

**Comment by janetournois** [comment]
testsuite looks good

**Comment by lrineau** [comment]
It will be retested tonight. The test results from CGAL-4.9-Ic-148 were far too incomplete.

**Pull request merged**
