### PR TITLE
Arr_2: removal optimisation

### PR DESCRIPTION
**Pull request by sloriot**
Add a new method for removing redundant edges after the overlay used for computing boolean operations off a set of polygons.

We directly modify the dcel to remove all edges/vertices/faces at once

Small feature [page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BSO_update_dcel_concept)

### CODE REVIEW

**Comment by sloriot** [comment]
cc @efifogel

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-7](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-7.shtml)

**Comment by sloriot** [comment]
Testsuite seems to output a memory leak.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-14](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-14.shtml)

**Comment by lrineau** [comment]
The PR is marked with the "small feature" tag, but the URL of the small feature itself is not mentioned. Please edit the first message to add the URL.

**Comment by sloriot** [comment]
Done

**Pull request merged**
