### PR TITLE
shorten include directive and use compiler include path instead

### PR DESCRIPTION
**Pull request by sloriot**
This is a nice to have feature for some users

### CODE REVIEW

**Comment by sloriot** [comment]
@lrineau do you see any possible issue?

**Comment by lrineau** [comment]
No. With `include_directories(${CMAKE_SOURCE_DIR}/src/${LIBRARY_NAME})`, it should work everywhere.

**Comment by sloriot** [comment]
This is not working in branch build: the command should be `include_directories(${CMAKE_SOURCE_DIR}/${LIBRARY_NAME}/src/${LIBRARY_NAME})` which would break the flat layout behavior and would not be sufficient as the `.cpp` files for the lib CGAL are spread in different packages. The header only feature will anyway make this useless so I close this PR.

**Comment by lrineau** [comment]
(For the moment the header-only feature is not ready.)

To allow its use in the flat and Git layouts, that could be:
```cmake
if(IS_DIRECTORY ${CMAKE_SOURCE_DIR}/${LIBRARY_NAME}/src/${LIBRARY_NAME})
  include_directories(${CMAKE_SOURCE_DIR}/${LIBRARY_NAME}/src/${LIBRARY_NAME})
endif()
if(IS_DIRECTORY ${CMAKE_SOURCE_DIR}/src/${LIBRARY_NAME})
  include_directories(${CMAKE_SOURCE_DIR}/src/${LIBRARY_NAME}),
endif()
```

With a `file(GLOB)` it can be adapted to multiple packages.

**Pull request closed without merging**
