### PR TITLE
Convex_hull_3: Make it work for OpenMesh

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add examples for using 3D convex hull functions with open mesh.  And fix a bug in convex hull code as it does use more than in the concept `MutableFaceGraph`.

## Release Management

* Affected package(s): Convex_hull_3

### CODE REVIEW

**Comment by lrineau** [comment]
This PR could be against the bug-fix release CGAL-4.10.1, instead of CGAL-4.11-beta1.

What is best for the user who reported the issue?

**Comment by lrineau** [comment]
There is unfortunately a check, added by Sébastien (cc @sloriot), that blocks the integration into `master` today.

```
.. Checking if all CMakeLists.txt project names are correct...
CMakeLists with incorrect project name
Convex_hull_3/examples/Convex_hull_3/CMakeLists.txt
```
https://travis-ci.org/CGAL/cgal/jobs/255203948#L4304

The name `Convex_hull_3_Examples` will have to be restored.

Andreas, which tool did you use to generate the CMake file? It will have to be patched accordingly.

**Comment by afabri** [comment]
cgal_create_CMakeLists

**Comment by afabri** [comment]
It is now the same project name as in master. No idea if that needs another round of integration.

**Comment by lrineau** [comment]
If I run the check scripts manually that will be sufficient.

**Pull request merged**
