### PR TITLE
Replace boost::shared_ptr used in public API

### PR DESCRIPTION
**Pull request by sloriot**
Follow up of #5649 

Not sure how we should handle the deprecation of public API in that case so this PR

### CODE REVIEW

**Comment by sloriot** [comment]
What do you think of doing the change and adding a macro so that user can switch back to boost::? It is a little work on our side but at least user friendly.

**Comment by lrineau** [comment]
Which API is impacted?

**Comment by sloriot** [comment]
Straight skeleton and classification packages.

**Comment by sloriot** [comment]
Breaking the API won't bring anything so I'm closing this.

**Pull request closed without merging**
