### PR TITLE
Mesh_3 - fix a memory leak in testsuite

### PR DESCRIPTION
**Pull request by janetournois**
this seems to be some debug code that should not have been committed there

@cjamin do you have any clue why you added this?

### CODE REVIEW

**Comment by janetournois** [comment]
merged in [CGAL-4.8-Ic-97](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml)

**Comment by janetournois** [comment]
merged in [CGAL-4.8-Ic-97](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml)

**Comment by cjamin** [comment]
I don't remember exactly, but it was probably some temporary code to test the MSVC memory leak detector. And I commited it by mistake, sorry!

**Comment by janetournois** [comment]
it's what I thought, thanks :-)

**Pull request merged**
