### PR TITLE
Intel Compiler: protect warning removal with push/pop

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-136

**Comment by sloriot** [comment]
This does not work. @afabri Could you indicate to Intel that their fix is not correct?

**Comment by lrineau** [comment]
@sloriot @afabri I do not know what to say. ...Ping!

**Comment by sloriot** [comment]
The testsuite no longer features the buggy compiler and no solution was found. I close this PR.

**Pull request closed without merging**
