### PR TITLE
Mesh 3 : document manifold criterion

### LINKED ISSUE #2009: Document the Mesh_3 manifold criterion
After the merge of #1876, the next step is to document the feature.

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR documents the manifold criterion for `Mesh_3`
It is not a "simple" mesh criterion as the others, and can be combined with the others, including the topology criterion for facets.

## Release Management

* Affected package : Mesh_3
* Issue solved : fix #2009
* Feature/Small Feature : [Mesh_3 manifold criterion](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Mesh_3_manifold_criterion)

pre-approved --Laurent Rineau 17:03, 3 October 2017 (CEST)

### CODE REVIEW

**Comment by MaelRL** [comment]
Tiny stuff in the doc: `The manifold property of output mesh may nevertheless result from the choice of appropriate meshing criteria.".`
- _the_ output mesh
- suggestion: `[...] might nevertheless result from an appropriate choice of meshing criteria` ?

**Comment by janetournois** [comment]
TODO : we need to precise the conditions on the input. It does not only have to be manifold : the sharp edges should either be protected, or cut away, to be able to terminate.

**Comment by lrineau** [comment]
Jane, https://github.com/CGAL/cgal/pull/2491#issuecomment-336056734:
>TODO : we need to precise the conditions on the input. It does not only have to be manifold : the sharp edges should either be protected, or cut away, to be able to terminate.

Should that block the merge of this PR?

**Comment by janetournois** [comment]
Yes. I think we should add it to be on the safe side. I can take care of it this week. Is it ok wrt the milestones?

**Comment by janetournois** [comment]
This PR should be ready now

**Pull request merged**
