### PR TITLE
Range and Segment Trees: Sync code and doc

### LINKED ISSUE #3742: dD Range and Segment Trees : Mismatch name Doc and Files
_Please use the following template to help us solving your issue._

## Issue Details

The class **Segment_tree_traits_map_3** has this name in the doc https://doc.cgal.org/latest/SearchStructures/classCGAL_1_1Segment__tree__traits__map__3.html .
But in the code in **"CGAL/Range_segment_tree_traits.h"** on line 312, it has the name **Segment_tree_map_traits_3** . So they are a confusion between the documentation and the file

## Environment

* Operating system (Linux, 64 bits):
* Compiler: gcc
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version: 4.13
* Boost version: 1.65.1.0ubuntu1
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Thank you @lvalque  for pointing this out. 

## Release Management

* Affected package(s): SearchStructures
* Issue(s) solved (if any): fix #3742

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-143.shtml

**Comment by afabri** [comment]
> Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-143.shtml

I don't agree, as I made commits after that.

**Comment by maxGimeno** [comment]
Oops, i didn't see that. No, master is I-144

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-145.shtml

**Pull request merged**
