### PR TITLE
Mesh_3 - fix feature protection for images

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR fixes protection of features from - this is experimental code.
cc @lrineau 

## Release Management

* Affected package(s): Mesh_3

### CODE REVIEW

**Comment by lrineau** [comment]
:facepalm:

**Comment by lrineau** [comment]
Be careful with the assertion line 310: https://github.com/CGAL/cgal/pull/5580/files#diff-0becef6bf7c9500c27305b5a9bc92941d02425a4b3538bbcb4e119502c0b3e08R310

**Comment by janetournois** [comment]
it is inside the `if(!aabb_tree.empty())`, so it should be ok, don't you think?

**Comment by lrineau** [comment]
> it is inside the `if(!aabb_tree.empty())`, so it should be ok, don't you think?

Oh yes, sorry.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-106.shtml

**Pull request merged**
