### PR TITLE
Accelerate vertex removal in a 3D triangulation and saving a mesh

### PR DESCRIPTION
**Pull request by afabri**
by switching to hash maps

### CODE REVIEW

**Comment by mglisse** [comment]
Is there an official policy about which hashtable map to use in which case? I thought CGAL::Unique_hash_map was best when the hash function is know to be injective on keys, and that we were using it for whatever_handle (maybe unless we need the `remove` operation). Has it been deprecated since?

**Comment by lrineau** [comment]
@afabri Andreas, you are the one supposed to answer Marc.

**Comment by afabri** [comment]
There is no policy.   In Triangulation_3.h we use an unorderdered map as well as a Unique hash map, as the latter cannot easily be made injective.

**Comment by lrineau** [comment]
@MoniqueTeillaud  I do not think that PR needs a small feature, because that is an minor improvement on the internals of T_3. But with this message I want that you are aware. That is what we decided at last developers meeting.

**Comment by lrineau** [comment]
@afabri The commit abd9bfb1256d3f84c3ed2a9024c465a5b838b221 is the cause of the non-determinism, and the red cells in test results.
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-25.shtml#Mesh_3

**Comment by lrineau** [comment]
Cc @MoniqueTeillaud

**Pull request merged**
