### PR TITLE
2D Reconstruction Simplification, new package, GSoC 2014

### PR DESCRIPTION
**Pull request by cjamin**
Feature page: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Reconstruction_simplification_2

Tested in CGAL-4.7-Ic-71

### CODE REVIEW

**Comment by lrineau** [comment]
I can see that you have remerged this pull-request yourself in `integration`, @cjamin. Good.

Is there an update for the review status?

**Comment by lrineau** [comment]
The script `./Scripts/developer_scripts/test_merge_of_branch` has detected that your branch has permissions issues with the following files:
```
Reconstruction_simplification_2/demo/Reconstruction_simplification_2/data/round_rect00.xy
Reconstruction_simplification_2/demo/Reconstruction_simplification_2/data/skyline_noisy00.xy
Reconstruction_simplification_2/demo/Reconstruction_simplification_2/data/stair-noise00.xy
Reconstruction_simplification_2/examples/Reconstruction_simplification_2/data/stair.xy
Reconstruction_simplification_2/test/Reconstruction_simplification_2/data/stair-noise00.xy
```
Probably they are marked incorrectly as executable.

**Comment by lrineau** [comment]
@cjamin: Can you add me in the list of collaborators for your fork https://github.com/cjamin/cgal ? The direct setting page is: https://github.com/cjamin/cgal/settings/collaboration (Github will re-authenticate you, for security reason). Once I am collaborator of your fork, I can do small changes (like the fix of permissions) myself.

**Comment by cjamin** [comment]
We resubmitted the manual yesterday. Waiting for reviewers @afabri and @ericberberich's comments.

I just added you as collaborators, since I don't know how to deal with these permission issues on Windows.

**Comment by lrineau** [comment]
I fixed permissions with commit 156b1b2, pushed both in `cgal-public-dev` and in your forlk (and thus in this pull-request as well).

**Comment by lrineau** [comment]
The next error reported by the script is the lack of copyright and license notices for the file `Reconstruction_simplification_2/include/CGAL/console_color.h`. What should it be?

**Comment by cjamin** [comment]
It's a "cross-platform" version of this code: http://www.codeproject.com/Articles/16431/Add-color-to-your-std-cout
The page says "Copyleft". What should we do?

**Comment by afabri** [comment]
Remove this feature

**Comment by cjamin** [comment]
Done.

Clément

**Comment by sloriot** [comment]
I cleaned up the branch history and the weight of the branch is now 1.9M.
The compress size of the manual figures is 1.3M

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-91

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-92

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-121

**Comment by lrineau** [comment]
[There is something wrong with the documentation][1]. It can probably be fixed trivially though.
```
../CGAL-4.8-Ic-121/doc/Documentation/packages.txt:983: Warning: unable to resolve reference to `Chapter_2D_Reconstruction_Simplification' for \ref command
../CGAL-4.8-Ic-121/doc/Documentation/packages.txt:983: Warning: unable to resolve reference to `PkgReconstructionSimplification2' for \ref command
```
[1]: https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.8-Ic-121/Documentation.log

**Comment by sloriot** [comment]
I'll fixed it in the merge commit, something related to the merge conflict I guess.

**Comment by cjamin** [comment]
Testsuite is fine.

**Comment by sloriot** [comment]
I ran `git filter-branch -f --tree-filter   'rm -rf Reconstruction_simplification_2/doc/fig/process.png Reconstruction_simplification_2/doc/Reconstruction_simplification_2/fig/overview.png Reconstruction_simplification_2/examples/Reconstruction_simplification_2/data/stair-noise00.xy'  acc69fc3..HEAD   --not cgal/master` to reduce the size of the branch and it is now 1.2Mo
I cannot find a way to decrease it more.

**Pull request merged**
