### PR TITLE
Add missing null descriptor functions in graph_traits of triangulations

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by lrineau** [comment]
Bug: the documented concept talks about a free function `null_face(Graph)`, and so on, and not a static function in the `graph_traits`. What is right?

**Comment by afabri** [comment]
The static function.

**Comment by lrineau** [comment]
Indeed `graph_traits<G>::null_vertex()` is part of the Boost `Graph` concept.

Then... How can it work with LCC?

**Comment by sloriot** [comment]
if it is not used we won't see it (as for the functions added in this PR).

**Comment by sloriot** [comment]
The doc issue is addressed in a separate PR. @lrineau can you mark the PR as ready or do you see another issue with this PR?

**Comment by afabri** [comment]
Note that the way we document the free functions related to a concept are now documented the doxygen way, and no longer with a table so that it looks like the BGL documentation in boost.

**Pull request merged**
