### PR TITLE
[Feature] Shape Regularization New Package

### PR DESCRIPTION
**Pull request by danston**
This PR proposes a new CGAL package called `Shape_regularization` for regularizing 2D contours, a set of 2D unordered segments, and 3D planes. It also includes a new shape regularization framework based on the Quadratic Programming problem.

This PR was proposed for acceptance.

Tasks:
- [x] Check memory leaking.

## Release Management

**This PR depends on #5741.**

* Affected package(s): Feature, New Package
* Issue(s) solved (if any): no issues
* Feature/Small Feature (if any): [Feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Shape_regularization) proposed for acceptance 4 June 2021
* Link to compiled documentation (obligatory for small feature): [docs](https://cgal.geometryfactory.com/~danston/Shape_regularization/index.html)
* License and copyright ownership: GF

### CODE REVIEW

**Comment by danston** [comment]
A few points before testing:
- I tested it locally and it is ok.
- I checked it for memory leaks and it is ok.
- This PR should be tested together with the #5741 since it depends on the new OSQP solver.
- What should we do about [OSQP](https://osqp.org/)? I think, in order to test this PR and in general, the OSQP should be installed on all testing platforms. If not installed, only the contour regularization code will be tested, which is certainly not enough for publishing this package.

**Comment by lrineau** [comment]
@danston Please edit the first message (https://github.com/CGAL/cgal/pull/5742#issue-658419897) to mention the other PR this PR depends on.

**Comment by danston** [comment]
@maxGimeno This PR has no longer dependencies and can be tested. Thanks.

**Comment by sloriot** [comment]
There are several runtimes errors reported in [https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-20.shtml](CGAL-5.4-Ic-20)

**Comment by danston** [comment]
@sloriot  I think now this PR can be tested again. Thanks!

**Comment by danston** [comment]
The last commit should fix these errors: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-23/Shape_regularization/TestReport_lrineau_Fedora-with-LEDA.gz

**Comment by maxGimeno** [comment]
tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-26.shtml

**Comment by danston** [comment]
@sloriot Could you please review the discussed changes and push them to the test suite in case it is ok. Thanks!

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-28

**Comment by MaelRL** [comment]
Would be nice to have a cgal.org news entry for this new package.

**Comment by danston** [comment]
I have done it. @MaelRL I will send you it in pm.

**Comment by MaelRL** [comment]
Done in https://www.cgal.org/2021/11/16/shape-regularization/.

Thanks!

**Pull request merged**
