### PR TITLE
Arrangement_2:  Add types and functions to become a FaceGraph

### PR DESCRIPTION
**Pull request by afabri**
Partial fix for Issue #1004 

The conversion between edges and halfeges is lacking.

### CODE REVIEW

**Comment by lrineau** [comment]
Is this PR finished? What does it add actually?

**Comment by afabri** [comment]
It is not finished and I better had marked it as WIP.
The goal is to make Arrangements model of  FaceGraph, but honestly I do not even know which algorithm one might run on an arrangement. Also I am not sure what to do with holes, edges with the same face on both sides, isolated points....

**Comment by efifogel** [comment]
The following make sense and is useful:

  | Graph Vertices               | Graph Edges         | Name
-----------------------------------------------------------------
1 | Arr Vertices                 | Arr Edges           | primary
2 | Arr Faces                    | Arr Edges           | Dual
3 | Arr vertices, Edges, & Faces | Incidence relations | Complete

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
@afabri @efifogel What is the status of this PR? It was left unmodified for a long time.

**Comment by efifogel** [comment]
I'm not (directly) involved with the development of this feature.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Then @afabri, can you comment?

**Comment by sloriot** [comment]
@afabri, I suggest we close this PR.

**Comment by lrineau** [comment]
More than two years old... I close the pull-request.

**Pull request closed without merging**
