### PR TITLE
Addition of some informations about the items

### PR DESCRIPTION
**Pull request by maxGimeno**
- Addition of the extremities of the bounding box and the
  number of isolated vertices.

### CODE REVIEW

**Comment by sgiraudot** [comment]
The feature works fine.
Just a question, though: why do every scene item now have "isolated vertices" ? It makes sense for polygon soups, but I don't get how this is relevant for point sets for example?

**Comment by maxGimeno** [comment]
You are right. I shall change it then.

2015-09-29 10:56 GMT+02:00 Simon Giraudot <notifications@github.com>:

**Comment by sgiraudot** [comment]
Okay, everything is fine now.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-10](Merged in [CGAL-4.8-Ic-10](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-13](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-13.shtml)

**Pull request merged**
