### PR TITLE
Add a plugin for inset and offset of a polyhedron

### PR DESCRIPTION
**Pull request by sloriot**
This is a minimal plugin working with Surface_mesh and the polyhedron item that can generate naive inset and offset meshes.

### CODE REVIEW

**Comment by lrineau** [comment]
There is a warning in the polyhedron demo:
```
Plugins/Surface_mesh/Offset_meshing_plugin.cpp:77:52: warning: unused parameter 'parent' [-Wunused-parameter]
```

**Comment by lrineau** [comment]
> This is a minimal plugin working with Surface_mesh and the polyhedron item that can generate naive inset and offset meshes.

As far as I can see, only Polyhedron_3 can be used as input, and not Surface_mesh.

**Comment by sloriot** [comment]
Yep, to use Surface_mesh it should need to be ported to `Mesh_3`. @maxGimeno Are you interested?

**Comment by maxGimeno** [comment]
I'll look into it.

**Comment by sloriot** [comment]
Actually, a `Surface_mesh` can be handled that's just a matter of handling the output.

**Pull request merged**
