### PR TITLE
Force html output (needed with lxml greater than 4.6.5)

### PR DESCRIPTION
**Pull request by sloriot**
Follow up of #7101

### CODE REVIEW

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-160

**Comment by sloriot** [comment]
(need to be double checked once in master with a call to build:doc)

**Comment by lrineau** [comment]
@sloriot This PR has been merged, and has a https://github.com/CGAL/cgal/labels/TODO%20after%20merge.

**Comment by lrineau** [comment]
Do you need help on something? Where should we look at?

**Comment by sloriot** [comment]
I need to look again locally and see if I can reproduce. I only looked at one package the last time so I might have missed something.

**Comment by afabri** [comment]
I guess this PR is to avoid the artefacts in the navtree of the documentation built on github. If so it would make sense to write it in the description of  a PR.

**Comment by sloriot** [comment]
Actually it is working, but of course if we build the doc of a branch, that branch needs the patches from this branch.

**Pull request merged**
