### PR TITLE
Mesh 3 : fix limit case in polylines protection

### PR DESCRIPTION
**Pull request by janetournois**
The Mesh_3 polylines protection algorithm incrementally inserts weighted points on input feature polylines. This PR deals with the limit case where protecting balls refinement attempts to insert a protecting ball very close (~10^-18) beyond the "endpoint/starting point" (arbitrarily chosen) of a cyclic polyline.

this PR fixes issue #416

### CODE REVIEW

**Comment by janetournois** [comment]
Merged in CGAL-4.8-Ic-44

**Comment by janetournois** [comment]
The testsuite Ic-44 is good concerning Mesh_3.

**Comment by lrineau** [comment]
Should not we merge also those changes in `CGAL-4.7-branch`?

**Comment by sloriot** [comment]
Backported to 4.7

**Pull request merged**
