### PR TITLE
SearchStructures: Figure not shown

### PR DESCRIPTION
**Pull request by albert-github**
Converted range2.png to:
```
range2.png: PNG image data, 633 x 263, 8-bit/color RGB, non-interlaced
```

### CODE REVIEW

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-79

**Comment by lrineau** [comment]
Albert, can you please point to us:
  - the original doc page, at doc.cgal.org, that was wrong, and
  - the new page, somewhere in https://cgal.github.io/6908/doc_v0/Manual/index.html ?

**Comment by albert-github** [comment]
Normally I give a reference, but apparently I forgot it here, it is in the original issue #6907 though.
(the later is less clear as the title of the PR has been changed from
- issue #6907 SearchStructures: Figure not shown

to
- SearchStructures: Figure not shown

It is the main page if the `SearchStructures` so `SearchStructures/index.html` and to be even more precise: https://doc.cgal.org/latest/SearchStructures/index.html#title4 or https://cgal.github.io/6908/doc_v0/SearchStructures/index.html#title4

**Pull request merged**
