### PR TITLE
PMP : remove useless includes

### PR DESCRIPTION
**Pull request by janetournois**
this PR intends to cleanup the extra "includes" that can be found in the PMP package.

### CODE REVIEW

**Comment by janetournois** [comment]
this PR will be tested in [CGAL-4.9-Ic-148](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-148.shtml)

**Comment by janetournois** [comment]
testsuite looks good

**Comment by lrineau** [comment]
The result results from [CGAL-4.9-Ic-148] were incomplete (20 columns missing). I will re-test the PR tonight.


[CGAL-4.9-Ic-148]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-148.shtml

**Comment by lrineau** [comment]
I think that PR could have had side effects.

Could the [compilation error `use of undeclared identifier 'BOOST_STATIC_ASSERT'][*] be related to such a removed header?

[*]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-151/BGL/TestReport_lrineau_ArchLinux-clang-Release.gz

**Comment by lrineau** [comment]
I am not so sure, today. It seems the same messages about `BOOST_STATIC_ASSERT` are in [CGAL-4.9-Ic-153] too.

[CGAL-4.9-Ic-153]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-153/Number_types/TestReport_lrineau_ArchLinux-clang-Release.gz

**Pull request merged**
