### PR TITLE
L Infinity Segment Delaunay Graphs, new package

### PR DESCRIPTION
**Pull request by philaris**
The new package is in the sdglinf-philaris branch that can be merged to master.

Feature page in the wiki:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Segment_Delaunay_graph_Linf_2

The package is already merged in integration and tested during several days. The latest test was in CGAL-4.7-Ic-66:
https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-66.shtml
I think that the testsuite is fine, but there are some warnings and errors that appear also in other packages.

### CODE REVIEW

**Comment by lrineau** [comment]
What are the scripts in `Segment_Delaunay_graph_Linf_2/developer_scripts/`? The directory `developer_scripts/` of our internal releases is already a mess, and I would like not to increase the entropy there.

**Comment by lrineau** [comment]
:x: There are license issues with the files in `GraphicsView/` and `Segment_Delaunay_graph_Linf_2`. Please use the scripts `./Scripts/developer_scripts/detect_packages_licenses; git diff` to detect the issues, and `./Scripts/developer_scripts/licensecheck` on individual files to debug the issue.

**Comment by lrineau** [comment]
:white_check_mark: I agree the [test results of CGAL-4.7-Ic-66](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-66.shtml) are good for your package: as far as I know, your branch only impacts `Segment_Delaunay_graph_Linf_2`, `CGAL_ipelets`, and `Voronoi_diagram_2`.

:x: However, I think there is a [segfault here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-66/Voronoi_diagram_2/TestReport_afabri_x64_Cygwin-Windows8_MSVC2010-Release-64bits.gz). Is it related to your branch?

:x: The current `HEAD` of `cgal-dev/sdglinf-philaris` has never been merged in `integration` during last week. I think the issue is that you keep rebasing the branch, and then the commits are all changed. Can you stop rebasing, and then remerge again your branch in `integration`?

**Comment by philaris** [comment]
The files in developer_scripts mostly create and translate inputs for debugging in different formats. They could prove helpful in the future for debugging. I can delete them, but I am wondering if I could put them somewhere so that they are not copied to your internal release directory.

**Comment by afabri** [comment]
There is a file dont_submit

**Comment by lrineau** [comment]
@philaris I understand. Unless you think those scripts are of general use (and in that case they be shipped with a small piece of documentation), I agree with Andreas that those scripts should be:
  - in a `dont_submit` file (add a file `Segment_Delaunay_graph_Linf_2/dont_submit` that just contains the line `developer_scripts`,
  - or in a subdirectory `developers_scripts/Segment_Delaunay_graph_Linf_2` (or another better name),
  - or both.

Anyway, that will not prevent your package to go into CGAL-4.7-beta1. But the license issues must be fixed as soon as possible, and for sure before the branch can be merged in `master`.

**Comment by philaris** [comment]
Thanks for the answers @afabri and @lrineau. I used `dont_submit`. I agree that the license is more important, but I am not sure how to fix it. Is there some documentation in the wiki? I tried what @lrineau suggested and it seems both files have the issue of `*No copyright* UNKNOWN`.

**Comment by afabri** [comment]
Header files such as Segment_Delaunay_graph_Linf_2/include/CGAL/Orientation_Linf_2.h
do not have a license header.   Copy paste from  Segment_Delaunay_graph_2/include/CGAL/Segment_Delaunay_graph_2.h

I lost track about who owns the copyright. Your institute? Or you  consider it as a minor contribution, and it is Inria.  Put as year 2015.  Put whoever developed as developer.

**Comment by lrineau** [comment]
@philaris No header file in `Segment_Delaunay_graph_Linf_2/include/CGAL/` has any license nor copyright notices.

In the feature page you said "GPL" for the license, and "Università della Svizzera italiana" for the owner. So I think that all the headers should start with the lines:
```
// Copyright (c) 2015  Università della Svizzera italiana.
// All rights reserved.
//
// This file is part of CGAL (www.cgal.org).
// You can redistribute it and/or modify it under the terms of the GNU
// General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// Licensees holding a valid commercial license may use this file in
// accordance with the commercial license agreement provided with the software.
//
// This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
// WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
//
// $URL$
// $Id$
// 
//
// Author(s)     : Panagiotis Cheilaris

```

**Comment by philaris** [comment]
Yes, thank you @afabri and @lrineau for the help. I could not look into it for a while. @sandeepkumardey, can you try to do the changes in the sdglinf-philaris branch of cgal-dev. Then I will update the pull request myself.

@afabri, about commercialization, don't we do the standard thing? Should we find somebody from USI to contact you? Anyway, I will also involve Evanthia in an email.

**Comment by sandeepkumardey** [comment]
@philaris the changes are completed in all the .h files in the sdglinf-philaris branch of cgal-dev.

**Comment by lrineau** [comment]
@philaris Can you please add me in the list of collaborators of your fork https://github.com/philaris/cgal ? The direct link to the setting page is: https://github.com/philaris/cgal/settings/collaboration

Github will ask you to reauthenticate yourself, for security reason. My Github ID is `lrineau`.

Once I am in your collaborators for your fork of CGAL, I will get the rights to modify your branch in that repository, and thus act on the code of this pull-request.

**Comment by philaris** [comment]
@sandeepkumardey Thanks!

@lrineau I added you as a collaborator. I did not have a chance to push the latest commit of Sandeep yet. Do you plan to do it now that you are a collaborator?

**Comment by lrineau** [comment]
@philaris You can do it. I am busy with the issue on the wiki server.

**Comment by lrineau** [comment]
@sandeepkumardey: the file `GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphLinfGraphicsItem.h` also need a license header.

**Comment by sandeepkumardey** [comment]
@lrineau Thank you. License header is added to the file GraphicsView/include/CGAL/Qt/SegmentDelaunayGraphLinfGraphicsItem.h

**Comment by lrineau** [comment]
@philaris: I did push the newest commit from @sandeepkumardey to your fork, and thus to this pull-request (you can see them intertwined with the discussion above).

**Comment by lrineau** [comment]
Now my script no longer see any issue, but a size issue:
  - :x: the compressed weight of the branch is 1.0MB. What could be so heavy in this branch? Do you have big pictures?

**Comment by sandeepkumardey** [comment]
Actually in the cgal-dev/Segment_Delaunay_graph_Linf_2/doc/Segment_Delaunay_graph_Linf_2/fig folder, each figure is stored in 4 formats, .eps, .ipe, .png, .svg, we can remove the 3 format and can keep only the .svg format.

**Comment by philaris** [comment]
@lrineau I cannot find the reason it is so big. At some point, I had some more extensive tests, but they never made it to the sdglinf-philaris branch. I even checked that now with:
`git log -- Segment_Delaunay_graph_Linf_2/test/Segment_Delaunay_graph_Linf_2/data/a20ptsmin.cin`
This a20ptsmin.cin file was part of the extensive tests.

@sandeepkumardey The images do not seem that big, but I agree that .eps and .png should be removed. I think we should keep .ipe though, because they are the original format and they are not that big. @lrineau This means that the history has to be cleaned with git filter-branch, right? I am not sure I will be able to do that today.

**Comment by lrineau** [comment]
Don't do anything right now. Sébastien is having a look at the history. 1MB, compressed, might be the right size for a new package like yours.

**Comment by sloriot** [comment]
I could save 100K removing sdg at the root but I don't expect we could win more that an additional 100K. I would leave the branch as is, the size is acceptable.

**Comment by lrineau** [comment]
OK. I have the pull-request in `integration` as it is, with HEAD equal to 8ac6c15.

**Comment by lrineau** [comment]
One minor thing is missing:
  - :x: the file `Installation/changes.html` should be amended, to announce the new feature.

Please merge your branch in `integration` again once you have committed the modification to `changes.html`.

**Comment by sandeepkumardey** [comment]
modification to changes.html is committed.
@philaris : Can you please check it, and add any other detail if you want, and merge in integration.

**Comment by philaris** [comment]
@lrineau @sloriot Related to the size of the branch, I tried the following approach with a few adaptations: <http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history>. The total uncompressed size for Segment_Delaunay_graph_Linf_2 files in the sdglinf-philaris branch is about 1.2MB and since there are some big source files in the order of 100KB it does not seem illogical.

**Comment by lrineau** [comment]
In my opinion, the weight of the branch is acceptable, since that is a brand new package.

**Comment by lrineau** [comment]
@andreas, can you tried to compile the demo with Qt5, and adapts its code/`CMakeLists`?

**Comment by lrineau** [comment]
The demo is in `GraphicsView/demo/Segment_Delaunay_graph_Linf_2/`.

**Comment by afabri** [comment]
it compiles and runs.

**Comment by lrineau** [comment]
The [test results in 4.7-Ic-77](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-77.shtml#Segment_Delaunay_graph_Linf_2) were good.

The Qt4 demo was not really tested, but anyway we are switching to Qt5. The tests will be done in the `CGAL-Qt5_support-GF` branch.

**Comment by lrineau** [comment]
This pull request has been merged in `master`. Now the work for the demo is in the Qt5 branch. See #154.

**Comment by lrineau** [comment]
TODO: move the feature in the wiki, and add the commit b043876 as the commit that merged the feature in `master`.

**Pull request merged**
