### PR TITLE
A fix by Iddo for the case where the curve is closed 

### PR DESCRIPTION
**Pull request by efifogel**
This consists of a fix, provided by Iddo (one of the original authors of the Arrangement Bezier traits class) for the case where the Bezier curve is closed (first and last points are the same)

This bug was reported by Tim de Jong <tim@raatdejong.nl> 

All tests pass locally.
If all tests pass after integration, it should be merged with master.

### CODE REVIEW

**Comment by sloriot** [comment]
@efifogel would it make  sense to add the test failing in the testsuite?

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-139

**Comment by efifogel** [comment]
Yes, it would.
I've just added it.
Thank.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-140

**Comment by sloriot** [comment]
Rebased over 4.7-branch

**Comment by sloriot** [comment]
Merged in 4.7 and master branch

**Pull request merged**
