### PR TITLE
Remove boost thread dependency

### PR DESCRIPTION
**Pull request by sloriot**
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/threadlocal_and_mutex

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-52

**Comment by lrineau** [comment]
I should be a small feature, because that will change the user experience. We should review/discuss the documentation changes. And http://www.cgal.org/download/windows.html as well.

**Comment by lrineau** [comment]
The PR has linker issues with g++4.1 and g++4.4 (CentOS 5 and CentOS 6 platforms).

**Comment by sloriot** [comment]
It must be related with  86a2225. I'm missing a else...

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-53

**Comment by sloriot** [comment]
@lrineau : done

**Comment by sloriot** [comment]
@afabri: could you take care of the small feature page?
[doc](https://github.com/CGAL/cgal/pull/493/files#diff-e1f393a91b7709c4d3a8e73c552a98a7)
[changes](https://github.com/CGAL/cgal/pull/493/files#diff-e8f411bf32727101bd2fe4a4f2939980)

**Comment by afabri** [comment]
Unless you find it incomplete, it is documented in the installation manual.

**Comment by sloriot** [comment]
Merged in GAL-4.8-Ic-55

**Comment by lrineau** [comment]
> No description provided.
For such an important modification, I think the pull-request should have a description. It could include a link to a small feature, but there should be a summary of the small feature page, for self-consistency for non-developers.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-60

**Comment by sloriot** [comment]
There is an issue on this platform but I don't know if it is related.
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-61/Installation/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz

**Comment by mglisse** [comment]
In the list of gcc flags, you are missing -std=c++98 (equivalent to c++03), -std=c++1z, and for each -std=c++XX there is a corresponding -std=gnu++XX.

**Comment by afabri** [comment]
@sloriot  can you please merge it in integration.

**Comment by sgiraudot** [comment]
I took care of it. Merged in [4.8-Ic-76](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-76.shtml).

**Comment by sloriot** [comment]
It seems test platforms with the platform testing the flag `c++1z` has bugs in the compiler so not all the tests were complete.
@lrineau Shall we merge the branch anyway?

**Comment by lrineau** [comment]
Which test platform?

**Comment by sloriot** [comment]
ArchLinux-clang-CXX14, ArchLinux-clang-CXX1z, ArchLinux-clang-Release,  	ArchLinux-clang.
See for example `Kernel_23` results.

**Comment by lrineau** [comment]
It looks like compiler bugs. We should merge the branch in CGAL, and report the bug to LLVM/clang.

**Comment by sloriot** [comment]
I'll merge the branch. Shall we open an issue for reporting the compiler bug?

**Pull request merged**
