### PR TITLE
PMP: Add local versions of `stitch_borders` and `stitch_boundary_cycles`

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

- Factorize implementations of `stitch_boundary_cycle()` and `stitch_borders()` (and thus enhance `stitch_boundary_cycles` to do more than zipping)
- Add a local version of stitch borders (useful to speed up offset and self-intersecting clipping)

## Release Management

* Affected package(s): `Polygon_mesh_processing`
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): [Local stitch_borders](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Local_sitch_borders) -- **pre-approved on 2020/07/31**
* License and copyright ownership: GeometryFactory

### CODE REVIEW

**Comment by sloriot** [comment]
While reading the doc I notice that we did not mention that two halfedges to be stitched should not already share a common vertex. Would you mind adding it?

**Comment by afabri** [comment]
> should not

must not

**Comment by maxGimeno** [comment]
Errors in the demo plugin: 
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-232/Polyhedron_Demo/TestReport_lrineau_Fedora-with-LEDA.gz

**Comment by maxGimeno** [comment]
errors : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-2/Polygon_mesh_processing/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz

**Comment by maxGimeno** [comment]
error : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-18/AABB_tree_Examples/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-23.shtml

**Comment by lrineau** [comment]
This PR has a conflict with others that were merged today. I tried to solve the conflicts but then the result failed to compile. Please merge `master` in this PR.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-27.shtml

**Comment by lrineau** [comment]
@sloriot @MaelRL This PR seems to have broken cgal-swig-bindings: https://travis-ci.com/github/CGAL/cgal-swig-bindings/jobs/403883997#L5983

**Pull request merged**
