### PR TITLE
Install fix nsi

### PR DESCRIPTION
**Pull request by sloriot**
Related to #137

### CODE REVIEW

**Comment by sloriot** [comment]
@bo0ts: could you please generate the .exe using the modified script and sent it to @afabri so that he can check that issues reported in #137 are fixed by this PR?

**Comment by bo0ts** [comment]
Forwarded it to @afabri. Links are fine now, but the default install dir should not be `C:\${CGAL_SRC}`, but `C:\dev\${CGAL_SRC}`. It might be a good idea to make this depend on wether this directory already exists or not.

**Comment by sloriot** [comment]
@afabri did you have time to test it?

**Comment by sloriot** [comment]
@afabri tested it and it was working.

**Pull request merged**
