### PR TITLE
Silence for warnings

### PR DESCRIPTION
**Pull request by sakrist**
Added simple initialisation to silence warnings.

### CODE REVIEW

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by lrineau** [comment]
The patch caused compilation errors on Windows, when `<windows.h>` is included.

@afabri, can you explain @sakrist how to protect the use of the `min` and `max` functions? I do not remember where the parenthesis must be added. Is that the following?
```C++
double xmin = (std::numeric_limits<double>::min)(); 
```

**Comment by sakrist** [comment]
@lrineau @afabri already emailed to me.
I will fix it shortly.

**Comment by afabri** [comment]
To avoid problems with the min and max macros defined by Microsoft
you have to change

std::numeric_limits<double>::min()

to

(std::numeric_limits<double>::min)()

and the same for max

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-21][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-21.shtml

**Comment by lrineau** [comment]
@sakrist. This pull-request is now merged into our `master` branch. Thanks.

**Comment by sakrist** [comment]
Cool! Thanks

**Pull request merged**
