### PR TITLE
Add move-semantic for c3t3, and a test

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Add move-semantic for c3t3. Required for #4803.

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: maintenance by GF

### CODE REVIEW

**Comment by maxGimeno** [comment]
There are some timeouts in the testsuite : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-183.shtml
I don't know if it is related

**Comment by lrineau** [comment]
Can you be more specific, please, so that I do not search the whole testsuite to find which column has a suspicious timeout?

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Generator_Examples/TestReport_lrineau_Ubuntu-latest-GCC6.gz

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Periodic_3_mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz

https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz

**Comment by lrineau** [comment]
> [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Generator_Examples/TestReport_lrineau_Ubuntu-latest-GCC6.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Generator_Examples/TestReport_lrineau_Ubuntu-latest-GCC6.gz)

This one is fine today: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-184/Generator_Examples/TestReport_lrineau_Ubuntu-latest-GCC6.gz

> [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6-Release.gz)
> 
> [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Periodic_3_mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Periodic_3_mesh_3/TestReport_lrineau_Ubuntu-Latest-NO_DEPRECATED_CODE.gz)
> 
> [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-183/Triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz)

Those three still timeout today. I will try to reproduce.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-190.shtml

**Pull request merged**
