### PR TITLE
Doc update doxygen versions

### LINKED ISSUE #5840: Let Doxygen 1.8.4 have a peaceful retirement. Prepare 1.9.1
> I agree it would be nice let Doxygen 1.8.4 have a peaceful retirement. That column helped us transition from 1.8.4 to 1.8.13, but it would be a good time to start the transition from 1.8.13 to... 1.9.1?

We could shift the columns:
  - move 1.8.13 to the first one,
  - have 1.9.1 as the second one,
  - and keep doxygen-master in the last one.
  
@maxGimeno Would it be easy to implement?

_Originally posted by @lrineau in https://github.com/CGAL/cgal/issues/5800#issuecomment-876351121_

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Fixes the python scripts and replace the  tests for 1.8.4 by tests for 1.9.1.

Also see https://github.com/CGAL/cgal-documentation-dockerfile/pull/1

## Release Management

* Affected package(s):Documentation
* Issue(s) solved (if any): fix #5840

### CODE REVIEW

**Comment by sloriot** [comment]
Seems buggy:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.4-Ic-6/

**Comment by maxGimeno** [comment]
How was it generated ?

**Comment by lrineau** [comment]
For the moment, the Doxygen testsuite is triggered by [`Scripts/developer_scripts/run_doxygen_testsuite`](https://github.com/CGAL/cgal/blob/5759a800e35e36fb09666c5d5f94f6479b778d63/Scripts/developer_scripts/run_doxygen_testsuite). What should change?

**Comment by lrineau** [comment]
It seems this PR depends on https://github.com/CGAL/cgal-documentation-dockerfile/pull/1 that itself depends on https://github.com/CGAL/cgal/pull/4448, that is an abandoned PR.

**Comment by lrineau** [comment]
I have checked the script from https://github.com/CGAL/cgal-documentation-dockerfile/pull/1 and it works well.

One issue: it applies only on a Git branch, and not a release. We will have to find a way to pass the internal release full name to the scripts. For the moment, it uses the release name from `Installation/lib/cmake/CGAL/CGALConfigVersion.cmake`, but that is not right: the internal release build number is not there.

**Pull request closed without merging**
