### PR TITLE
PMP: Generalize some corefinement code

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Dissociate somes types in corefinement code to enhance customization possibilities.

## Release Management

* Affected package(s): `Polygon_mesh_processing`
* Issue(s) solved (if any): - 
* License and copyright ownership: No changes (GF).

### CODE REVIEW

**Comment by sloriot** [comment]
I think #4790 replaces this PR in term of function but we probably want to keep the vpm change. Shall you open another PR?

**Comment by maxGimeno** [comment]
Missing example : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-199.shtml#Polygon_mesh_processing_Examples

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-200.shtml

**Comment by lrineau** [comment]
Conflicts with #4790.

**Comment by maxGimeno** [comment]
There are travis errors : https://travis-ci.com/github/CGAL/cgal/jobs/389009383#L4804

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-23.shtml

**Pull request merged**
