### PR TITLE
Add an example do the union of a set of meshes in parallel

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by lrineau** [comment]
Don't you want to put that example in the user manual as well? Or do you want it only in the code, so that you can refer to it in answers to user questions?

**Comment by sloriot** [comment]
Yep second option.

**Comment by maxGimeno** [comment]
Error : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-51/Polygon_mesh_processing_Examples/TestReport_lrineau_Debian-stable-Release.gz

**Comment by sloriot** [comment]
No idea where those includes came from. I amended by last commit.

**Comment by maxGimeno** [comment]
Success in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-55.shtml

**Pull request merged**
