### PR TITLE
Polyhedron demo: add libpolyhedron_demo

### PR DESCRIPTION
**Pull request by lrineau**
Separate the `Polyhedron_demo` class from the `main()` function.

### CODE REVIEW

**Comment by lrineau** [comment]
Merged in CGAL-4.8-Ic-38

**Comment by sloriot** [comment]
Breaking on windows

**Comment by lrineau** [comment]
That should be fixed by the commit 75b463ee7e4050f35e36f75bdb6be1777ae05819 that I just added to this PR.

Merged into [CGAL-4.8-Ic-39][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-39.shtml

**Comment by lrineau** [comment]
The linking errors were indeed fixed on Windows.

**Pull request merged**
