### PR TITLE
PMP : add utility functions

### PR DESCRIPTION
**Pull request by janetournois**
This PR introduces new utility functions to the PMP package.

It implements the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_PMP_utility_functions), pre-approved on Nov 12th

### CODE REVIEW

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-55.shtml)

**Comment by sloriot** [comment]
Testsuite is red

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-56](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-56.shtml)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-57

**Pull request merged**
