### PR TITLE
CGAL:   In testcode do not use CGAL_assertion  but assert 

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

We must use CGAL_assertion only inside CGAL code and not in the test code itself.  I fix it for 2D Periodic Triangulations but I think we have to fix it in other places (e.g. P3T3 @MaelRL )

## Release Management

* Affected package(s): P2T2
* Issue(s) solved (if any):    See this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-141/Periodic_2_triangulation_2/TestReport_gimeno_ArchLinux-clang-CXX17-Release.gz)

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by lrineau** [comment]
Is that something we would like to enforce, using a test in the CI?

**Comment by janetournois** [comment]
I would say yes, and there are more to be fixed

**Comment by lrineau** [comment]
Can be checked/detected with:
```shell
grep -rE '\bCGAL_(assertion|(pre|post)condition)(_msg)? *\(' */test
grep -rE '\bassert *\(' */include/CGAL
```

**Comment by afabri** [comment]
@mglisse is the single `CGAL_assertion`  [here ](https://github.com/CGAL/cgal/blob/master/Triangulation/test/Triangulation/test_delaunay.cpp#L61)on purpose. I ask as there are at the same time several `assert`.

**Comment by mglisse** [comment]
> @mglisse is the single `CGAL_assertion` [here ](https://github.com/CGAL/cgal/blob/master/Triangulation/test/Triangulation/test_delaunay.cpp#L61)on purpose. I ask as there are at the same time several `assert`.

I have no idea why it is there, but replacing it with assert looks good to me.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-10

**Comment by lrineau** [comment]
We still have a few calls to `CGAL_postcondition`:
```
Algebraic_foundations/test/Algebraic_foundations/Chinese_remainder_traits.cpp:         CGAL_postcondition_msg(pq < p*(2*max_coeff), " chinese remainder failed ");
Modifier/test/Modifier/test_modifier.cpp:        CGAL_postcondition( i > 0);
Polyhedron/test/Polyhedron/test_polyhedron.cpp:    CGAL_postcondition( P.is_valid());
Polynomial/test/Polynomial/include/CGAL/gen_sparse_polynomial.h:        CGAL_postcondition(result.degree() >= 0);
```
(Tested with `grep -rE '\bCGAL_(assertion|(pre|post)condition)(_msg)? *\(' */test`)

And we still have calls to `assert` in a few CGAL headers:
```
BGL/include/CGAL/boost/graph/Seam_mesh.h
BGL/include/CGAL/boost/graph/selection.h
CGAL_Core/include/CGAL/CORE/poly/Sturm.h
Combinatorial_map/include/CGAL/Combinatorial_map.h
Combinatorial_map/include/CGAL/Dart.h
Generalized_map/include/CGAL/Generalized_map.h
GraphicsView/include/CGAL/Buffer_for_vao.h
GraphicsView/include/CGAL/Qt/Basic_viewer_qt.h
Hyperbolic_triangulation_2/include/CGAL/Hyperbolic_triangulation_2/internal/Hyperbolic_Delaunay_triangulation_traits_2_functions.h
Linear_cell_complex/include/CGAL/boost/graph/graph_traits_Linear_cell_complex_for_combinatorial_map.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_base.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_constructors.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_incremental_builder.h
Linear_cell_complex/include/CGAL/Linear_cell_complex_operations.h
Nef_3/include/CGAL/draw_nef_3.h
Point_set_3/include/CGAL/Point_set_3.h
Polygon_mesh_processing/include/CGAL/Polyhedral_envelope.h
STL_Extension/include/CGAL/Compact_container.h
STL_Extension/include/CGAL/Concurrent_compact_container.h
STL_Extension/include/CGAL/STL_Extension/internal/boost/relaxed_heap.hpp
Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Square_border_parameterizer_3.h
Surface_mesh_topology/include/CGAL/draw_face_graph_with_paths.h
Surface_mesh_topology/include/CGAL/Face_graph_wrapper.h
Surface_mesh_topology/include/CGAL/Surface_mesh_topology/internal/Path_generators.h
```

**Comment by afabri** [comment]
Do I need a new branch or PR?

**Comment by lrineau** [comment]
You can reuse a branch, but that will require a new PR.

**Pull request merged**
