### PR TITLE
Polyhedron 3 improve mesh 3 plugin gf

### PR DESCRIPTION
**Pull request by afabri**
Address Issue  #530
- Make Mesh_3 plugin parallel
- Shift voxel data by 1/2 voxel

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-65

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-67

**Comment by sloriot** [comment]
Testsuite is red

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-68

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-69

**Comment by lrineau** [comment]
@afabri @janetournois 
There is an issue with the commit  0523d04: if the c3t3 item is considered empty as soon as there is not cell in the complex... But the c3t3 item is used for a lot more than meshing gray level images!

If Mesh_3 is used to mesh surfaces only, with no 3D volume, then the displayed c3t3 item seems empty!

**Comment by lrineau** [comment]
Actually, the new way to compute the bbox was because of far points, in c3t3 in parallel mode.

@cjamin I have a question, about "far points" in the c3t3. Are they the only vertices for which the `in_dimension()` of the vertex return -1?

**Comment by lrineau** [comment]
Sorry @cjamin. I wrote the previous comment twice, by error. This is the PR were the discussion should be.

**Comment by lrineau** [comment]
@janetournois @afabri @cjamin: I have fixed the commit https://github.com/CGAL/cgal/commit/0523d04cf4493c87d9e78c25646537423e970f28 in the PR #865. To compute the bbox, I iterate on the vertices, but skip the vertices for which `in_dimensin()==-1` (they are the far points).

**Comment by janetournois** [comment]
ok perfect, thanks @lrineau

**Pull request merged**
