### PR TITLE
Boolean_set_operations_2/Gps_polygon_validation.h: Fix validity check

### PR DESCRIPTION
**Pull request by sloriot**
Holes are allowed to be relatively simple.

### CODE REVIEW

**Comment by maxGimeno** [comment]
ERRORS: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-3/Boolean_set_operations_2/TestReport_lrineau_Debian-stable-Release.gz

**Comment by sloriot** [comment]
@efifogel Note that I have to modify a test that was explicitly testing a polygon with a hole being relatively simple (but not simple) and that it was NOT valid before my patch. You still confirm that it was a bug, right?

**Comment by efifogel** [comment]
Yes, absolutely.
The tests were developed by another person, so it even somehow makes
sense....
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Successfully tested in [5.4-Ic-8](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-8.shtml)

**Pull request merged**
