### PR TITLE
BGL: document Dual

### PR DESCRIPTION
**Pull request by bo0ts**
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BGL_Dual

Document the Dual class

### CODE REVIEW

**Comment by bo0ts** [comment]
#652 introduced bad changes to the `Doxyfile.in` which #668 will fix. I'll rebase this PR on top of master as soon #668 is merged.

**Comment by bo0ts** [comment]
Rebased and merges cleanly now

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-108

**Comment by sloriot** [comment]
There are warnings in the BGL tests and errors with properties in the polyhedron demo.

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-4][4]

[4]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-4.shtml

**Comment by lrineau** [comment]
A doxygen error: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.9-Ic-4/BGL.log
> citelist:4: Warning: Unexpected new line character
> /home/cgal-testsuite/cgal_doc_build/CGAL-4.9-Ic-4/include/CGAL/boost/graph/Dual.h:36: Warning: unable to resolve reference to `BGL_surface_mesh/surface_mesh_dual.cpp' for \ref command

Now that Philipp no longer works for the CGAL project, who will be responsible for this small feature and PR? @sloriot, @afabri?

**Comment by afabri** [comment]
I just fixed it and pushed it to my mine

**Comment by lrineau** [comment]
@bo0ts @afabri: I have pushed the commit ddc71b5 from Andreas to Philipp's fork, so that it appears in this PR.

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-5][5].

[5]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-5.shtml

**Pull request merged**
