### PR TITLE
Cone spanners 2 new package

### PR DESCRIPTION
**Pull request by afabri**
See https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Cone_based_spanners

### CODE REVIEW

**Comment by sloriot** [comment]
@ws4u There are some errors and warnings in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-34.shtml)

**Comment by ws4u** [comment]
For the errors from platform Fedora-32-Release and from platform
x64_Cygwin, the failed execution of cones_exact, it is because the
computation exceeds the CORE library's limit. I've reduced the number of
cones to compute from 17 to 6 now, and pushed my change.

For the error from platform ArchLinux-CXX14, "error: use of deleted
function 'boost::detail::stored_edge_property", according to the following
page:
http://stackoverflow.com/questions/25395805/compile-error-with-boost-graph-1-56-0-and-g-4-6-4
,
this is a bug of boost 1.56, while boost 1.55 doesn't have such a problem.

Btw, I have a problem to pull the changes from the origin. For instance,
Andreas has updated the Installtion/changes.html, but I cannot pull his
version. Could you let me know how to fix this problem?

---
Best regards,
Weisheng

**Comment by sloriot** [comment]
@ws4u If you don't have any local commit or modification, you can simply do:
`git fetch origin`
`git reset --hard origin/Cone_spanners_2-new_package-UWS`

Note that this will work because the `afabri` remote and `cgal-dev` are now synchronized. This means that a modification should be pushed in both remotes to avoid issues.

One solution is to have only one remote and both of you use the same (either `afabri` or `ws4u` since we need a public one for the PR).

**Comment by afabri** [comment]
Thank you @sloriot  for having sorted out  things. I think my pull request should be replaced by a pull request of Weisheng, as he is the author of the package.   @ws4u, you can register me as collaborator in the settings  of your fork.

**Comment by sloriot** [comment]
@ws4u You can do that by visiting https://github.com/ws4u/cgal/settings/collaboration, provided you already clicked on `Fork` [here](https://github.com/CGAL/cgal)

**Comment by ws4u** [comment]
@sloriot and @afabri , thanks for your efforts. Now I have successfully pulled and merged the changes from the origin, and I have added Andreas as a collaborator as well. 

I have two simple local commits (reducing the cone number from 17 to 6 and updating the packet description a little). And I have done 'git push' to push them to origin. Please let me know if this is incorrect.

**Comment by sloriot** [comment]
@ws4u Almost! a commit was here twice for some reason. Simply do:
`git checkout Cone_spanners_2-new_package-UWS`
`git fetch origin`
`git reset --hard origin/Cone_spanners_2-new_package-UWS`
and you should be done.

**Comment by sloriot** [comment]
@ws4u You should consider opening your own PR to replace this one. That way you'll be able to update it yourself. Let me know if you need some help with that.

**Comment by ws4u** [comment]
@sloriot , I've run the three commands you mentioned. But after them, I lose my own changes. Also, I notice the Installation/changes.html doesn't contain the latest change made by Andreas. Is there anything wrong?

The outputs of executing the above three commands are as follows:
`$ git checkout Cone_spanners_2-new_package-UWS
Already on 'Cone_spanners_2-new_package-UWS'

$ git fetch origin
Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
Enter passphrase for key '/local/home/weisheng/.ssh/id_rsa': 
remote: Counting objects: 416, done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 416 (delta 245), reused 126 (delta 126), pack-reused 50
Receiving objects: 100% (416/416), 207.83 KiB | 164.00 KiB/s, done.
Resolving deltas: 100% (245/245), completed with 54 local objects.
From github.com:CGAL/cgal-dev
 + 2280cf9...d3dabb0 Cone_spanners_2-new_package-UWS -> origin/Cone_spanners_2-new_package-UWS  (forced update)
   688af43..cba2fd4  integration -> origin/integration
   5d594fd..9b39cac  testsuite-Wednesday -> origin/testsuite-Wednesday

$ git reset --hard origin/Cone_spanners_2-new_package-UWS
HEAD is now at d3dabb0 remove extra line added during merge conflict resolution`

It seems I'm tracking `github.com:CGAL/cgal-dev`, not `github.com:CGAL/cgal`. I looked at the forked repo `afabri/cgal`, and I didn't find the `Cone_spanners_2` there,  and the same is for my forked repo `ws4u/cgal`.

I pushed my changes yesterday. Are they pushed to origin/Cone_spanners_2-new_package-UWS? Is this a branch in the repo `github.com:CGAL/cgal-dev`?  

Am I missing something in my local git setup? For instance, I cannot remember whether I've done the following when I set up my git in the very beginning:
`> cd my_cgal_folder
> git remote add cgal git@github.com:CGAL/cgal.git
> git fetch --all`

Thanks.

**Comment by sloriot** [comment]
My bad, I forgot to push in cgal-dev. Should be good now.

**Comment by ws4u** [comment]
@sloriot . I have fetched again, and this time my local repo is updated successfully. I also have pushed to  my fork ws4u/cgal, and created a pull request: https://github.com/CGAL/cgal/pull/1066

Are you going to merge it into integration? Or I can do it locally by following the procedure described in the wiki.

**Comment by sloriot** [comment]
Replaced by #1066

**Pull request closed without merging**
