### PR TITLE
CGAL/IO/helpers.h: fix VC++ /W4 warning

### LINKED ISSUE #6127: #include "CGAL/Surface_mesh.h" warning in Visual Studio
## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 10
* Compiler: Visual Studio 2019
* Release or debug mode: Debug
* CGAL version: 5.3
* Boost version: 1.77
* 
## Steps to reproduce

```
vcpkg install cgal
```

CMakeLists.txt
```
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)

cmake_minimum_required(VERSION 3.20)

project(example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W4 /WX")

find_package(CGAL REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PUBLIC CGAL::CGAL)
```

main.cpp
```
__pragma(warning(push,0))
#include "CGAL/Surface_mesh.h"
__pragma(warning(pop))

int main() { return 0; }
```

This results in compilation error:

```
1>C:\vcpkg\installed\x64-windows\include\CGAL/IO/helpers.h(56): message : see reference to function template instantiation '_OutIt std::transform<std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,std::_String_iterator<std::_String_val<std::_Simple_types<_Elem>>>,int(__cdecl *)(int)>(const _InIt,const _InIt,_OutIt,_Fn)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Elem=char,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,
1>            _Fn=int (__cdecl *)(int)
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\algorithm(2216,24): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
1>Done building project "example.vcxproj" -- FAILED.
```

After looking into https://github.com/CGAL/cgal/blob/4610cf3c666b512816fd643df6082f5720111a8b/Stream_support/include/CGAL/IO/helpers.h#L57 according to the hint from Visual Studio, I was able to get it to compile by changing 

```
std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
```
to
```
std::transform(ext.begin(), ext.end(), ext.begin(), [](char c) { return static_cast<char>(std::tolower(c)); });
```

It would be nice to get this fix or some other better equivalent fix into 5.4 especially when for some reason I can't disable this warning despite having `__pragma(warning(push,0))` and `__pragma(warning(pop))` sandwiching the CGAL headers.

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix a warning.

## Release Management

* Affected package(s):  Surface_mesh
* Issue(s) solved (if any): fix #6127

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-115

**Comment by sloriot** [comment]
@lrineau @afabri said he does not want to fix the new warnings introduced because it is an old compiler. So either we merge this PR that fix no warning detected by our testsuite or we merge it and got a new yellow square.

**Comment by lrineau** [comment]
I wonder if the CGAL project is ready to deal with warnings level 4 from VC++. Is that really something we want? If that is the case, then we should test with `/W4` in at least one of our Windows platforms.

**Comment by MaelRL** [comment]
> @lrineau @afabri said he does not want to fix the new warnings introduced because it is an old compiler. So either we merge this PR that fix no warning detected by our testsuite or we merge it and got a new yellow square.

What's the link between this PR and warnings in Kernel_23? We could just not add W4 to the testsuite and still merge this PR, as long as it doesn't break the testsuite and fixes the warning (with a local /W4 test).

**Comment by afabri** [comment]
I think we have all the same understanding that this fixes just one warning as reported by a user, and it is NOT our goal to fix all `/W4` warnings, and we do not plan to have a testsuite with `/W4`.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-216

**Pull request merged**
