### PR TITLE
Basic viewer bugfix

### LINKED ISSUE #4291: draw_polyhedron.h does not compile when Nef_polyhedron_3.h is included.
## Issue Details
A compilation error occurs when I include the Nef_polyhedron_3.h and the draw_polyhedron.h headers in the same executable. The problem seems to be a namespacing issue of the newell_single_step_3 function which exists both in polygon_mesh_to_nef_3.h and the Qt/Basic_viewer_qt.h . 

The full error I get is the following;

```
[ 92%] Building CXX object CMakeFiles/test_.dir/test.cpp.o
In file included from /usr/local/include/CGAL/Qt/Basic_viewer_qt.h:56:0,
                 from /usr/local/include/CGAL/draw_polyhedron.h:25,
                 from /home/chamzask/test/test.cpp:6:
/usr/local/include/CGAL/Buffer_for_vao.h: In function ‘CGAL::Local_vector CGAL::internal::compute_normal_of_face(const std::vector<CGAL::Point_3<CGAL::Epick> >&)’:
/usr/local/include/CGAL/Buffer_for_vao.h:68:74: error: call of overloaded ‘newell_single_step_3(const value_type&, const value_type&, CGAL::Local_vector&)’ is ambiguous
       newell_single_step_3(points[i], points[(i+1)%points.size()], normal);
                                                                          ^
/usr/local/include/CGAL/Buffer_for_vao.h:50:8: note: candidate: void CGAL::internal::newell_single_step_3(const Point&, const Point&, Vector&) [with Point = CGAL::Point_3<CGAL::Epick>; Vector = CGAL::Vector_3<CGAL::Epick>]
   void newell_single_step_3(const Point& p, const Point& q, Vector& n)
        ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h:32:0,
                 from /usr/local/include/CGAL/Nef_polyhedron_3.h:57,
                 from /home/chamzask/test/test.cpp:5:
/usr/local/include/CGAL/normal_vector_newell_3.h:40:6: note: candidate: void CGAL::newell_single_step_3(const Handle&, const Handle&, Vector&) [with Handle = CGAL::Point_3<CGAL::Epick>; Vector = CGAL::Vector_3<CGAL::Epick>]
 void newell_single_step_3( const Handle& p, const Handle& q, Vector& n )
      ^~~~~~~~~~~~~~~~~~~~
CMakeFiles/test_.dir/build.make:62: recipe for target 'CMakeFiles/test_.dir/test.cpp.o' failed
make[2]: *** [CMakeFiles/test_.dir/test.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/test_.dir/all' failed
make[1]: *** [CMakeFiles/test_.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

## Source Code
To reproduce simply add the line ```  #include <CGAL/Nef_polyhedron_3.h> ``` in [this demo](https://doc.cgal.org/latest/Polyhedron/Polyhedron_2draw_polyhedron_8cpp-example.html)

before the ```  #include <CGAL/Nef_polyhedron_3.h> ``` line

like this : 
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/IO/Polyhedron_iostream.h>
#include <CGAL/Polyhedron_3.h>

#include <CGAL/Nef_polyhedron_3.h>
#include <CGAL/draw_polyhedron.h>

#include <fstream>
typedef CGAL::Exact_predicates_inexact_constructions_kernel Kernel;
typedef CGAL::Polyhedron_3<Kernel> Polyhedron;
int main(int argc, char* argv[]) {
    Polyhedron P;
    std::ifstream in1((argc > 1) ? argv[1] : "data/cross.off");
    in1 >> P;
    CGAL::draw(P);
    return EXIT_SUCCESS;
}

```

## Environment

* Operating system (Ubuntu 18.04 64 bits):
* Compiler:
* Release or debug mode: Release Mode
* Specific flags used (if any):
* CGAL version: master (latest)
* Boost version: Boost version: 1.65.1
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by gdamiand**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Update cgal basic viewer to solve a linker error when used with nef.

## Release Management

* Affected package(s): Cgal basic viewer
* Issue(s) solved (if any): fix #4291

### CODE REVIEW

**Comment by lrineau** [comment]
Guillaume, is the bug only in `master`, or was it already present in 4.14 and 4.14.1?

**Comment by gdamiand** [comment]
It was already in 4.14.

**Comment by lrineau** [comment]
You should rebase this branch onto `cgal/releases/CGAL-4.14-branch`, so that the bug can be fixed in CGAL-4.14.2 as well as in 5.0.

**Comment by gdamiand** [comment]
Rebase has too many conflicts... I suggest to keep this pr only for 5.0 since this is not a major bug.

**Pull request merged**
