### PR TITLE
Doc: Don't use small caps

### LINKED ISSUE #5248: Strange typesetting of words like BGL
## Issue Details

I was looking into some output and saw near the end of the page BGL/namespaceCGAL.html a bit a strange formatted "Bgl":
small_Bgl
instead of what I expected:
upper_BGL

This straight away thinking of the issue #4634, this issue was solved in #4641 by using a regular font.

So I did a search for the so called "small-caps" in the HTML output and found: 
- Api
- Bgl
- Boost
- C++
- C++11
- Ceres
- CGAL
- Core
- Dcel
- Eigen
- Esbtl
- ESBTL
- GLPK
- Gmp
- gmpxx
- Gmpxx
- Gnu
- LASlib
- LEDA
- libpointmatcher
- Metis
- METIS
- Mpfi
- MPFI
- Mpfr
- MPFR
- Ntl
- NTL
- OpenCV
- OpenGR
- Pdb
- Qt
- Rs
- Rs3
- SCIP
- STL
- Tbb
- TensorFlow
- Unix
- Visual Studio
- Vtk
- zlib

The question is: What is the right spelling for the different entities, especially:
- Bgl
- gmpxx / Gmpxx
- Gnu
- Metis / METIS
- Mpfi / MPFI
- Mpfr / MPFR
- Ntl / NTL

I haven't, yet, made a pull request of it as I think it is a bit an opinion problem of where to use `\sc{...}` and where not though I think that at least the words with differences in lower / upper case should be fixed

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Don't use small caps in the doc.
## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #5248

### CODE REVIEW

**Review by sloriot — APPROVED** [review]

**Comment by maxGimeno** [comment]
\dcel not found in 1.8.4

**Comment by lrineau** [comment]
> \dcel not found in 1.8.4

We really should forget and bury 1.8.4. It was released 19-05-2013, and there has been 19 releases of Doxygen since then.

**Comment by maxGimeno** [comment]
I agree.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-74.shtml

**Pull request merged**
