### PR TITLE
Polyhedron_demo: Add an Alpha_shape_plugin

### LINKED ISSUE #2038: Polyhedron_demo: Unify the 3D demos
## Issue Details
Integrate all the 3D demos in the polyhedron_demo
Integration of T3 and P3T3 demos might pose a  problem with the "animation" mode.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
- Add a specific alpha_shape item and an alpha_shape_plugin.
- Add a creation of polygon_soup from alpha_shape_item
## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): partially fix #2038

### CODE REVIEW

**Comment by lrineau** [comment]
@janetournois @afabri

This PR will need a manual review of the functionality and the UI, especially on Windows.

**Comment by lrineau** [comment]
@janetournois  and @afabri This PR still wait for a review of the UI and functionality.

**Comment by afabri** [comment]
@janetournois I will have a look

**Comment by afabri** [comment]
- The triangles are colored
- With alpha=0 I nevertheless get triangles for one data set
- alpha is not a percentage.
- When I have only one Point set item, the action that creates the widget should automatically create the alpha shape item.

**Comment by maxGimeno** [comment]
The triangles are not connected.

**Comment by lrineau** [comment]
@afabri It seems Maxime has implemented the modifications you asked for. Could you confirm?

**Comment by lrineau** [comment]
There are other warnings about `override`:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-20/Polyhedron_Demo/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz

**Comment by maxGimeno** [comment]
I already fixed them in 838e6bb

**Comment by lrineau** [comment]
Are you sure? I do not see anything about `override` or `Q_OVERRIDE` in https://github.com/CGAL/cgal/commit/838e6bb653740a2a86031cf8cf933944274729df.

**Comment by maxGimeno** [comment]
Oh,you are right, I forgot to push

**Comment by maxGimeno** [comment]
Done.

**Comment by lrineau** [comment]
Thanks. Now I see the fix in https://github.com/CGAL/cgal/pull/2081/commits/73007cc17c16321777b5fd36c60881e043eb71f8.

**Comment by lrineau** [comment]
@afabri It seems Maxime has implemented the modifications you asked for. Could you confirm?

**Comment by afabri** [comment]
It does what I expect.

**Pull request merged**
