### PR TITLE
Advancing front: generalize filter

### PR DESCRIPTION
**Pull request by sgiraudot**
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Advancing_front-Generalize_filter

Tested in [4.8-Ic-67](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-67.shtml). Warnings have been fixed and errors are not related to this PR.

Pre-approved by @afabri who asked the following question on the wiki: "_Should `HUGE_VAL` be replaced with `std::numeric_limits<double>::max()` ?_"

I kept `HUGE_VAL` because that was what was used in the first place in the _Advancing front_ package, but indeed using the STD fashion seems more consistent with what is done in CGAL usually. Any opinions?

### CODE REVIEW

**Comment by lrineau** [comment]
Note that:
- `HUGE_VAL` is [`std::numeric_limits<double>::infinity`][inf], the infinity,
- whereas [`std::numeric_limits<double>::max`][max] is `DBL_MAX`, the maximal finite double value.

[inf]: http://en.cppreference.com/w/cpp/types/numeric_limits/infinity
[max]: http://en.cppreference.com/w/cpp/types/numeric_limits/max

**Comment by sgiraudot** [comment]
Thanks for the precision!

Okay, so it makes sense to replace `HUGE_VAL` by `infinity`. I checked on the original code, at some point we have `x=HUGE_VAL` where the type of `x` is `Kernel::FT`, so it would anyway be safer to use the STD fashion (for example if the kernel is a simple cartesian based on `float`).

I will take care of it.

**Comment by sgiraudot** [comment]
Merged in [4.8-Ic-91](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-91.shtml).

**Comment by sgiraudot** [comment]
Merged in [4.8-Ic-92](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-92.shtml).

**Comment by sgiraudot** [comment]
Testsuite is all green.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-93

**Comment by sgiraudot** [comment]
I think the [last details](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Advancing_front-Generalize_filter#Approval_.2F_Discussion) have been sorted out and the tests are all okay. Can it be considered as approved?

**Comment by sloriot** [comment]
It will be on the 20th of January.

**Comment by sgiraudot** [comment]
Oh yes that's right, I thought the pre-approved date was older than that. Thanks!

**Pull request merged**
