### PR TITLE
Add bbox() to MeshDomain_3

### PR DESCRIPTION
**Pull request by lrineau**
The small feature: [`Features/Small Features/MeshDomain 3::bbox()`][1]:
> In the parallel mode of Mesh_3, there is a piece of code that computes an "estimated bounding box" of the domain, using 1000 random points! Whereas all models of `MeshDomain_3` already have a natural bounding box. This small feature adds a requirement that models of `MeshDomain_3` provide `BBox_3 bbox() const` so that the code of Mesh_3 can use that real bounding box instead of computing an estimated one. 

[1]: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/MeshDomain_3::bbox%28%29

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-77

**Comment by sloriot** [comment]
In the Mesh_3 testsuite, the execution of `test_meshing_polyhedron` seems to fail on `llvm-clang-with-g++-4.8` but the log is not very informative.

**Comment by janetournois** [comment]
this small feature has been pre-approved  on 17 December 2015

just check my 2 comments about typos please :-)

**Comment by lrineau** [comment]
I can reproduce the error on `llvm-clang-with-g++-4.8` but the error is random, and quite rare. It seems related to a bug of the parallelism Clément knows about for a long time: the parallel mode sometime does insert a important percentage of extra vertices, compared to the sequential mode. That is what happens here: instead of about 350 cells, the mesh has 421 cells.

I had a look at the meshes in both cases, and they are quite similar qualitatively. The difference is only the number of vertices and cells.

I suggest the PR is merged again, to check if the error is reproduced.

**Comment by lrineau** [comment]
@janetournois : I have fixed the typos.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-91

**Pull request merged**
