### PR TITLE
Polyhedron_demo: Shuffle_polygon_soup for Surface_mesh

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This PR completes the Orient_polygon_soup_plugin by implementing the shuffling for surface_mesh and adds a load function to the polygon_soup_item that takes a surface_mesh_item as argument.
## Release Management

* Affected package(s):Polyhedron_demo

### CODE REVIEW

**Comment by sloriot** [comment]
There are some new warnings:
```
/Users/cgaltester/cgal_test/CGAL-4.12-Ic-4/cmake/platforms/x86-64_Darwin-13.0_Apple-clang-5.0_Release/test/Polyhedron_Demo/Plugins/PMP/Orient_soup_plugin.cpp:32:35: warning: '&&' within '||' [-Wlogical-op-parentheses]
```

**Comment by lrineau** [comment]
ping @maxGimeno

**Comment by maxGimeno** [comment]
Why ping me ? did e142740 not fix the warning ?

**Comment by lrineau** [comment]
You are right. I did not see the commit.

**Pull request merged**
