### PR TITLE
Small feature Triangulation segment traverser

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Draft pull request to review the code changes of the small feature "Add utility class to traverse 3D triangulation along line segment".

## Release Management

* Affected package(s): Triangulation_3
* Feature/Small Feature (if any): [Small_Features/Triangulation_segment_traverser](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Triangulation_segment_traverser)
* Link to compiled documentation (obligatory for small feature) : TBD
* License and copyright ownership: GPLv3+, Inria
* TODO: 
- [ ] @sloriot: look if the branch must be filtered

### CODE REVIEW

**Comment by afabri** [comment]
Why did my push not trigger travis?

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jan 7, 2020, 2:57 PM GMT+1](https://github.com/CGAL/cgal/pull/4219#issuecomment-571597003 "2020-01-07T13:57:19Z - Replied by Github Reply Comments"):
> Why did my push not trigger travis?

This PR has a conflict with `master`, about `Triangulation_3/benchmark/Triangulation_3/CMakeLists.txt`. That is why Travis could not test it. But as the PR is a "Draft", the Github UI does not show the conflict.

**Comment by maxGimeno** [comment]
Do we postpone this PR ?

**Comment by sloriot** [comment]
Replaced by #4639

**Pull request closed without merging**
