### PR TITLE
Polyhedron_demo : Self_intersection_plugin available for Scene_surface_mesh_item and works on all selected surfaces.

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR makes the Self_intersection_plugin applicable to a Scene_surface_mesh_item. If the input item is one, then the output item is another Scene_surface_mesh_item containing only the intersecting facets, instead of a Scene_polyhedron_selection_item (for obvious reasons). 
Once a selection_item is available for Surface_meshes, the code should be easily factorizable.

### CODE REVIEW

**Comment by maxGimeno** [comment]
In waiting for the second part that will fix #1679

**Comment by maxGimeno** [comment]
Ready.

**Comment by lrineau** [comment]
@maxGimeno https://github.com/CGAL/cgal/pull/1675#issuecomment-259650890:
> In waiting for the second part that will fix #1679

What did you mean?

**Comment by lrineau** [comment]
OK... I have seen your "Ready" at https://github.com/CGAL/cgal/pull/1675#issuecomment-259655166.

**Pull request merged**
