### PR TITLE
Fix CMP0071 warning

### LINKED ISSUE #2318: Support CMP0071
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-79/Alpha_shapes_3_Demo/TestReport_lrineau_ArchLinux-CXX14.gz

```
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  AUTOMOC/AUTOUIC: Ignoring GENERATED source file:

    "/home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/test/Alpha_shapes_3_Demo/ui_MainWindow.h"

This warning is for project developers.  Use -Wno-dev to suppress it.
```
We should set the policy `CMP0071` to `NEW`.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This PR fixes the warnings about CMP0071 in some demos.
## Release Management

* Affected package(s):AABB_tree Alpha_shapes_3 Linear_cell_complex Periodic_3_triangulation_3 Polyhedron Surface_mesher Triangulation_3
* Issue(s) solved (if any): fix #2318

### CODE REVIEW

**Comment by sloriot** [comment]
Did you mean to target 4.11 or even 4.10?

**Comment by maxGimeno** [comment]
I don't know when this started happening. Maybe.

**Comment by sloriot** [comment]
It is caused by a newer version of CMake so in can even be applied to 4.10. Do you mind rebasing?

**Comment by maxGimeno** [comment]
done

**Comment by sloriot** [comment]
It seems that it did not work. See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-5/Polyhedron_Demo/TestReport_lrineau_ArchLinux-CXX14.gz) for example. Did you try locally? Was it fixing the issue?

**Comment by maxGimeno** [comment]
I tried locally but it is perfectly uiseless as I never had those warnings.

**Comment by maxGimeno** [comment]
That should work now.

**Pull request merged**
