### PR TITLE
T2,T3,Mesh_2: backticks, lowercase, capitalize

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

tiny fixes.

## Release Management

* Affected package(s): Triangulation_2, Triangulation_3, Mesh_2

### CODE REVIEW

**Comment by albert-github** [comment]
Wouldn't it be better to use instead of the text `returns`  the doxygen command `\returns` or use the `\retval` command (might apply to a number of other functions as well, also outside Mesh_3).

**Comment by sloriot** [comment]
if we use \return we will always have the long version of the doc of a function and somtimes it is just useless to have it.

**Comment by albert-github** [comment]
Indeed, for small descriptions this will indeed be a problem and the case(s) I saw are indeed just a "lookup" function where the return value us just the (brief) description of the function.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-143.shtml

**Comment by afabri** [comment]
> 
> 
> Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-143.shtml

I don't agree, as I made commits after that.

**Comment by maxGimeno** [comment]
@afabri I think you posted in the wrong PR.There was no activity since I flagged it as Under Testing 4 days ago.

**Pull request merged**
