### PR TITLE
Lcc writeoff for 3 d gdamiand

### PR DESCRIPTION
**Pull request by gdamiand**
Bug fix in size methods of range in Combinatorial map.

In the previous version, const iterator are constructed at each loop using the non const version. This is ok but leads to useless additional time.

This is corrected in this patch by modifying the loop used in size methods; and by modifying CMap_cell_iterator iterator in order to add the missing constructor using a dart in parameter.

Update also the undocumented function write_off to use the size function.

Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.6-Ic-144.shtml

### CODE REVIEW

**Comment by sloriot** [comment]
Which release are you targetting?

**Comment by gdamiand** [comment]
4.6, Laurent said it will be ok.

**Comment by sloriot** [comment]
The patch being non trivial, the commits must have been through integration.
Could you provide the internal release id of the corresponding testsuite?

**Comment by lrineau** [comment]
I already have had a discussion with Guillaume about this branch. We wanted to test the pull-request process.

I approved the pull request, targeting CGAL-4.6.

**Pull request merged**
