### PR TITLE
SMP: mute ARAP and Orbifold output by default

### PR DESCRIPTION
**Pull request by MaelRL**
## Release Management

* Affected package(s): `Surface_mesh_parameterization`
* Issue(s) solved (if any): --

### CODE REVIEW

**Comment by maxGimeno** [comment]
https://travis-ci.org/CGAL/cgal/jobs/516081793#L5650

**Comment by afabri** [comment]
> 
> 
> https://travis-ci.org/CGAL/cgal/jobs/516081793#L5650

I just fixed that for #3833  so my guess is  that this is either a problem in master, or at least it was a problem in master before the branching point.

**Comment by maxGimeno** [comment]
It is a plausible possibilty.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Apr 8, 2019, 12:52 PM GMT+2](https://github.com/CGAL/cgal/pull/3844#issuecomment-480782958 "2019-04-08T10:52:06Z - Replied by Github Reply Comments"):
> > 
> > 
> > https://travis-ci.org/CGAL/cgal/jobs/516081793#L5650
> 
> I just fixed that for #3831 so my guess is  that this is either a problem in master, or at least it was a problem in master before the branching point.

Note that the base branch of the PR is `releases/CGAL-4.13-branch`, and not `master`. Travis tests the result of the merge of the PR into the base branch of the PR, not `master`.

**Comment by maxGimeno** [comment]
I checked, the error is in master

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Apr 8, 2019, 3:26 PM GMT+2](https://github.com/CGAL/cgal/pull/3844#issuecomment-480830597 "2019-04-08T13:26:08Z - Replied by Github Reply Comments"):
> I checked, the error is in master

It is because of commit b392643a98e5f2ae8615c6fe70b23ed277a6e48e, fixed by 27f10ee7c9b00235a033edca338498e87900ae05: I have committed by error a modification of a CGAL example so that it uses `OBJ_reader` instead of `OFF_reader`. And thus `OBJ_reader` got tested. It has never compiled, but it was not tested.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-10.shtml

**Pull request merged**
