### PR TITLE
Add <CGAL/atomic.h> and CGAL_CAN_USE_CXX11_ATOMIC

### PR DESCRIPTION
**Pull request by lrineau**
- Change the way the macros `CGAL_CAN_USE_CXX11_THREAD_LOCAL` and
  `CGAL_CAN_USE_CXX11_MUTEX` are defined, so that other compilers are
  also supported.

- Add the macro `CGAL_CAN_USE_CXX11_ATOMIC` and the header
  `<CGAL/atomic.h>`.

### CODE REVIEW

**Comment by lrineau** [comment]
Merged in CGAL-4.8-Ic-101.

**Comment by sloriot** [comment]
Unless I'm wrong, all the runtimes errors in 101 are due to this branch

**Comment by sloriot** [comment]
My bad, problems come from the branch modifying CORE.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-103

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-104

**Pull request merged**
