### PR TITLE
Aos polycurve tests wkhan

### PR DESCRIPTION
**Pull request by efifogel**
Small Feature: /Arrangement polycurve
Target: CGAL 4.7

### CODE REVIEW

**Comment by lrineau** [comment]
It is tested in [CGAL-4.7-Ic-6](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-6.shtml). I am waiting for all test results to be submitted by test machines. So far so good.

**Comment by lrineau** [comment]
My mistake. It was actually not tested in CGAL-4.7_Ic-6, only in Ic-5. And the test result were not so good: there are a lot of errors in the testsuite of Arr_2, and particularly new errors, when one compare Ic-1 and Ic-5:
```
--- CGAL-4.7-Ic-1/results_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-32bits.txt  2015-04-09 16:15:08.000000000 +0200
+++ CGAL-4.7-Ic-5/results_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-32bits.txt  2015-04-14 15:26:34.000000000 +0200
+Arrangement_on_surface_2 n
--- CGAL-4.7-Ic-1/results_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-64bits.txt  2015-04-09 13:46:22.000000000 +0200
+++ CGAL-4.7-Ic-5/results_afabri_x64_Cygwin-Windows8_MSVC2013-Debug-64bits.txt  2015-04-14 12:55:46.000000000 +0200
+Arrangement_on_surface_2 n
--- CGAL-4.7-Ic-1/results_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.txt        2015-04-09 07:25:28.000000000 +0200
+++ CGAL-4.7-Ic-5/results_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.txt        2015-04-14 07:16:22.000000000 +0200
+Arrangement_on_surface_2 n
--- CGAL-4.7-Ic-1/results_afabri_x64_Cygwin-Windows8_MSVC2013-Release-64bits.txt        2015-04-09 09:35:36.000000000 +0200
+++ CGAL-4.7-Ic-5/results_afabri_x64_Cygwin-Windows8_MSVC2013-Release-64bits.txt        2015-04-14 09:45:43.000000000 +0200
+Arrangement_on_surface_2 n
--- CGAL-4.7-Ic-1/results_cgaltester_x86-64_Darwin-13.0_Apple-clang-3.2_Debug.txt       2015-04-09 09:06:32.000000000 +0200
+++ CGAL-4.7-Ic-5/results_cgaltester_x86-64_Darwin-13.0_Apple-clang-3.2_Debug.txt       2015-04-14 09:06:10.000000000 +0200
+Arrangement_on_surface_2 n
```

See [the test results of Arr_2 in CGAL-4.7-Ic-5](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-5.shtml#Arrangement_on_surface_2).

**Comment by efifogel** [comment]
Hi Laurent,

You are referring to the results of the integration that took place 3 days
ago.
I've skipped one day (2 days ago---skipped).
After applying a fix I've integrated the branch again yesterday. It seems
that everything is in order now, and I believe it can integrated with
"master".

I've noticed that there is a warning or error (depending on the platform)
that comes from the triangulation package (which is used in the test suite
of the Arrangement in one test):

/Users/cgaltester/cgal_test/CGAL-4.7-Ic-7/include/CGAL/Hilbert_sort_on_sphere_3.h:35:22:
warning: in-class initializer for static data member of type 'const double'
is a GNU extension [-Wgnu]
        static const double _sqrt_of_one_over_three = 0.57735026919;
                            ^                         ~~~~~~~~~~~~~
Efi


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Your branch is probably already ready. By the test results of [CGAL-4.7-Ic-7][7] were too bad in general to allow merges in `master`. I have remerged your branch into `integration`, so that it is tested again tonight. I will do it each (working-)day until we can see:
  - either that Arr_2 has still new errors or warnings,
  - or that it can be safely be merged into `master`.

Meanwhile, you can also work on another branch, and submit another pull-request. This one is almost done.

[7]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-7.shtml

**Comment by efifogel** [comment]
Very well.
I'll wait till it's in master though, cause I want to integrate it with my
other branch before I continue with the test of the other branch. I know I
can do it independently, but now, since we are close, I prefer to wait
another day or so.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
Hi Laurent,

I believe that the result of the testsuite were satisfying.
Please let me know when the integration with master is done.

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
[CGAL-4.7-Ic-8][8] was also a bad release. Since CGAL-4.6 was released, there is a bottleneck in `integration` because everybody wants to get new branches tested. I will re-merged to test in [CGAL-4.7-Ic-11][11] tonight.

[8]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-8.shtml
[11]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-11.shtml

**Comment by efifogel** [comment]
Notice though that the Arrangement related results were good (despite of
other problems in that release).

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I do not care. As the release manager, I do not want to dig in all lines and columns of the testsuite to see which branch has impacted what. Your branch may, or may not, impact other packages than Arrangement_2. Unless we are very close to a dead-line, I simplify my work: either an internal release is good, or it is not. If it is good, then all pull-requests and merged branches can be merged into `master`. Otherwise, I just remerge for next day.

Blame Andreas for the delays, not me! :-)

**Comment by efifogel** [comment]
ok, no worries...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I did more checking, using the script `Scripts/developer_scripts/test_merge_of_branch`. The branch `cgal-dev/Aos-Polycurve_tests-wkhan` triggers CMake errors when `WITH_examples`, `WITH_tests`, and `WITH_demos` are all `TRUE`:
```
-- Configuring test in test/Arrangement_on_surface_2
-- Requested component: Core
-- Requested component: MPFR
-- Requested component: GMP
CMake Error at Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgram.cmake:19 (add_executable):
  add_executable cannot create target "polylines" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory
  "/home/lrineau/Git/other-cgal/build/examples/Arrangement_on_surface_2".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  build/test/Arrangement_on_surface_2/CMakeLists.txt:29 (create_single_source_cgal_program)
```
Two different targets ("programs") in CGAL cannot have the same name. The test `polylines` should be renamed `arr_2_test_polylines`, to be safe.

**Comment by sloriot** [comment]
@efifogel You have to rename
Arrangement_on_surface_2/examples/Arrangement_on_surface_2/polylines.cpp or
Arrangement_on_surface_2/test/Arrangement_on_surface_2/polylines.cpp otherwise they have the same target name and this will produce a cmake error.

**Comment by efifogel** [comment]
Yes, I realized.The test was created by a student I think.
Anyway, good catch!
I've already pushed the renaming (after verifying that the tests work
fine...) to the pull request branch.


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
The tests in [CGAL-4.7-Ic-11][11] were good, and the script no longer report any issue with the branch. Actually the merge costs 685Ko, which is quite a lot, but it seems that it is due to the test files. Are they all used?

**Comment by efifogel** [comment]
Yes they are all used.

BW, I get that the diff is 644kb, but maybe I've missed a file or something.

Difference between the polycurve branch and master in kb:

documentation: 29
examples:      84.3
include:       19
tests:        511.9
-------------------
total:        644.2

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
@efifogel I think you compare the working trees. The metric used by the script takes into account all the commits introduced by the branch, compressed. If a lot of files were modified during the life of the branch, that makes a heavy branch.

**Comment by lrineau** [comment]
If all the changes were introduced at once as a single commit (using `git merge --squash`) then that commit, compressed, would weight only 286kB, instead of 685kB.

**Pull request merged**
