### PR TITLE
Spatial sorting spatial sorting on sphere pmachado

### PR DESCRIPTION
**Pull request by sloriot**
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/spatial_sorting_on_sphere

Tested in 4.7-Ic-8

The testsuite has one warning fixed by 7969f1b

### CODE REVIEW

**Comment by lrineau** [comment]
I think the changes file should be modified, no?

**Comment by lrineau** [comment]
Has Inria received and stored carefully the CLA? Do we have an electronic copy of it?

**Comment by sloriot** [comment]
The small feature page indicates that the CAA has been signed and approved by INRIA.

**Comment by lrineau** [comment]
Actually the page says that Pedro signed the CAA, but not that the Inria signed/acknowledged it.

**Comment by sloriot** [comment]
Then I confirm it's the case.

**Comment by sloriot** [comment]
[4.7-Ic-9](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-9.shtml) looks good. I think the branch can be merged now.

**Comment by lrineau** [comment]
Le Sunday 19 April 2015 23:57:48 Sebastien Loriot a écrit :
> [4.7-Ic-9](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4
> .7-Ic-9.shtml) looks good. I think the branch can be merged now.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/CGAL/cgal/pull/59#issuecomment-94374459

In CGAL-4.7-Ic-9, the following packages were problematic (red or yellow):
  - Ridges
  - Polyhedron_Demo
  - Surface_mesh_simplification
  - Surface_modeling
  - Surface_mesh_Examples

I have remerged the PR #59 for tonight.

-- 
Laurent Rineau, PhD
R&D Engineer at GeometryFactory           http://www.geometryfactory.com/
Release Manager of the CGAL Project       http://www.cgal.org/

**Comment by lrineau** [comment]
I think you should also cherry-pick the commit cb38257cd2325252a9079460cf4465e9b5f9c131, to remove the merge conflict.

**Comment by lrineau** [comment]
The merge costs 1.3Mo. Can somebody check that the weight of the file correspond?

I also rather disagree with part of the implementation. I wonder why the header `<CGAL/spatial_sorting.h>` will always define the functions for spatial sorting on sphere, whereas that header is used by all CGAL triangulations (2D/3D, periodic or not) that are not on the sphere. I really think that the new functionality on the sphere should be in a dedicated header.

**Comment by sloriot** [comment]
I removed documents used for the review and now the merge is 416KB

**Comment by lrineau** [comment]
The tests in [CGAL-4.7-Ic-11][11] were good. But the branch has been modified since it was merged. I have remerged it for tonight 4.7-Ic-12.

[11]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-11.shtml

**Comment by lrineau** [comment]
The file `Spatial_sorting/doc/Spatial_sorting/fig_src/HilbertOnSphereIllustration.pdf` is not at all a source file. It is just PDF that contains an image, the same image as `Spatial_sorting/doc/Spatial_sorting/fig/HilbertOnSphereIllustration.png`.

**Comment by sloriot** [comment]
I filtered out the file

**Pull request merged**
