### PR TITLE
Update Regular_triangulation_euclidean_traits_3.h

### PR DESCRIPTION
**Pull request by MoniqueTeillaud**
added missing type Point_3

### CODE REVIEW

**Comment by lrineau** [comment]
I merged that pull-request in `integration`, for testing tonight. That is useless, because the patch is so trivial that we can see it does not break anything. I will merge this pull-request tomorrow.

**Comment by lrineau** [comment]
Your patch was tested last night. The result can be seen here:

https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.7-Ic-72/output/Triangulation_3/classCGAL_1_1Regular__triangulation__euclidean__traits__3.html

Unfortunately, that page will be removed automatically in one week (to save disk space). I can no merge your pull-request into `master`.

**Comment by lrineau** [comment]
Next time, try to give a better name to the branch `patch-1` is not a good name for a branch. I think you have edited the file directly in the web user interface of Github. There is a line in the UI that allows to chose a better name for the temporary branch that is created.

**Comment by MoniqueTeillaud** [comment]
sure, patch-1 is not a good name... I have not seen the place where github allows to modify it, I will look for it more carefully next time.

**Pull request merged**
