### PR TITLE
Boolean Set Operations: Fix brief descriptions

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add a "\\" after "resp." so that doxygen is not mislead by the "." as end of a brief description.

## Release Management

* Affected package(s): Boolean_set_operations_2
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by afabri** [comment]
It is fixed in the built documentation, e.g., for[ `join()`](https://cgal.github.io/8131/v0/Boolean_set_operations_2/group__boolean__join.html#gabb13a0ed958cda84ea0e4d2857c9d67a) to check that it works in principle.  In case someone (@sloriot , @efifogel )wants to check  it in detail I think it is easier to just read the diff in the "Files Changed" tab instead of going through all html pages.

**Comment by sloriot** [comment]
I'd prefer using "respectively"

**Comment by afabri** [comment]
@JacksonCampolattaro do you have an opinion on the usage of  _respectively_ or _resp._  [here](https://cgal.github.io/8131/v0/Boolean_set_operations_2/group__boolean__join.html#gabb13a0ed958cda84ea0e4d2857c9d67a)?    I am even wondering if it should only be used in the second parenthesis.

**Comment by JacksonCampolattaro** [comment]
> @JacksonCampolattaro do you have an opinion on the usage of _respectively_ or _resp._ [here](https://cgal.github.io/8131/v0/Boolean_set_operations_2/group__boolean__join.html#gabb13a0ed958cda84ea0e4d2857c9d67a)? I am even wondering if it should only be used in the second parenthesis.

I prefer using the full word; the sentence is already pretty dense, so abbreviation could make it less clear.

I'm not used to seeing respecively used in the middle of a sentence; I don't think it's wrong, but reversing the phrasing would be more intuitive to me:

> If substituted with [CGAL::Tag_true](https://cgal.github.io/8131/v0/STL_Extension/group__PkgSTLExtensionUtilities.html#gab3e2296107b5d26c32c8183028a217f1) (default), pgn1 and pgn2 are bounded by polylines before the operation is performed, converting them into a general polygon and a general polygon with holes, respectively.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-228

**Pull request merged**
