### PR TITLE
Trapezoid map fixes

### PR DESCRIPTION
**Pull request by sloriot**
The incremental update and rebuild function seemed to be broken. Also avoid recursive calls to `~Handle()`.

### CODE REVIEW

**Comment by maxGimeno** [comment]
Execution error:
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-157.shtml#Arrangement_on_surface_2

**Comment by lrineau** [comment]
I actually think that the issue is from PR #4284. I have bisected the error and found a commit from it. See https://github.com/CGAL/cgal/pull/4284#issuecomment-541593006.

**Comment by maxGimeno** [comment]
Sorry I didn't see #4284 was in integration :/

**Comment by maxGimeno** [comment]
warnings on mac : 
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-158.shtml#Arrangement_on_surface_2

**Comment by lrineau** [comment]
I fix the warning in https://github.com/CGAL/cgal/pull/4278/commits/7143b69bb162aa86ba0aac62ccdf7974ab44f274.

**Comment by lrineau** [comment]
Why "Not yet approved"?  I have already merged the PR in `master`. Should I delay merging it in 4.14-branch?

**Comment by sloriot** [comment]
Michal will be doing a review next week and it seems that all the issues reported are not yet fixed. Not a big deal if 5.0 is not released before this PR is integrated.

**Comment by lrineau** [comment]
It seems the PR can be merge now. Do you confirm?

**Comment by sloriot** [comment]
The review meeting is scheduled on the 29th of October.

**Comment by sloriot** [comment]
After an online meeting,  @MichalKleinbort and @efifogel approved the changes.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-183.shtml#Arrangement_on_surface_2

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Nov 6, 2019, 2:35 PM GMT+1](https://github.com/CGAL/cgal/pull/4278#issuecomment-550311121 "2019-11-06T13:35:33Z - Replied by Github Reply Comments"):
> error in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-183.shtml#Arrangement_on_surface_2

The test `test_point_location_dynamic` crashes on several platforms:
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-183/Arrangement_on_surface_2/TestReport_afabri_x64_Cygwin-Windows10_MSVC2015-Debug-64bits.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-183/Arrangement_on_surface_2/TestReport_Friedrich_Ubuntu-gcc-7.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-183/Arrangement_on_surface_2/TestReport_lrineau_Fedora-32.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-183/Arrangement_on_surface_2/TestReport_lrineau_Fedora-with-LEDA.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-183/Arrangement_on_surface_2/TestReport_lrineau_Ubuntu-no-gmp-no-leda.gz

**Comment by sloriot** [comment]
@efifogel looks like the point location that is failing on some platforms is the landmark one. Are you familiar with this one? If yes, would you mind have a look? (This PR is one of the last blocking the release)

**Comment by efifogel** [comment]
Sure, I'll look into it for starters. Stay tuned...

**Comment by efifogel** [comment]
Hi Sebastien,

I cannot seem to reproduce the problem.
I'm running Ubuntu 16.04.
I've installed gcc 7; see output of 'gcc-7 --version' below and used it.

gcc-7 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0

but they all pass.
Any idea how I can try to reproduce?

Efi
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
@sloriot  What is the status of thi PR ?

**Comment by sloriot** [comment]
We don't know how to reproduce the error from the testsuite.

**Pull request closed without merging**
