### PR TITLE
Nef_2: Add an example for exploration

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add an example that explores a `Nef_polyhedron_2` for unbounded as well as for bounded objects. 

## Release Management

* Affected package(s): Nef_2

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot, can you do me the favor and read the section in the [documentation ](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.0-Ic-2/output1/Nef_2/index.html#Nef_2Exploration)and tell me if my explanations are understandable.

**Comment by maxGimeno** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-5.shtml

**Comment by lrineau** [comment]
I will not merge this PR, because in https://github.com/CGAL/cgal/pull/3822#issuecomment-479353444 @afabri asked @sloriot for a review, and it is still pending.

**Comment by afabri** [comment]
> 
> 
> I will not merge this PR, because in [#3822 (comment)](https://github.com/CGAL/cgal/pull/3822#issuecomment-479353444) @afabri asked @sloriot for a review, and it is still pending.

Note that I uploaded the precompiled documentation, so no need to run doxygen locally.

**Comment by afabri** [comment]
@sloriot  it is successfully tested.

**Pull request merged**
