### PR TITLE
Basic viewer bugfix

### LINKED ISSUE #4380: Simple Viewer:  wrong type
## Issue Details

[Here ](https://github.com/CGAL/cgal/blob/master/GraphicsView/include/CGAL/Buffer_for_vao.h#L74)  `Local_point` should probably be `Local_kernel_point_3`.

### PR DESCRIPTION
**Pull request by gdamiand**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Bug fixes:
* solves issue #4380.
* draw 2D objects in XY plane instead of XZ to have correct normal.

## Release Management

* Affected package(s): GraphicsView
* Issue(s) solved (if any): fix #4380

### CODE REVIEW

**Comment by gdamiand** [comment]
@lrineau Do I need to do a second PR for master ?

**Comment by maxGimeno** [comment]
> @lrineau Do I need to do a second PR for master ?

@gdamiand  We only do that when a PR introduces non-trivial conflicts when merged in integration. I may ask you to do it if it is the case

**Comment by gdamiand** [comment]
> > @lrineau Do I need to do a second PR for master ?
> 
> @gdamiand We only do that when a PR introduces non-trivial conflicts when merged in integration. I may ask you to do it if it is the case

Ok thanks @maxGimeno , we will see.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-53.shtml

**Comment by lrineau** [comment]
This PR conflicts with PR #4224, that was merged in `master` after the release of CGAL-5.0. @maxGimeno, how have you merged this PR in `integration`?

**Comment by gdamiand** [comment]
@lrineau How can I see the conflicts with master and how can I solve the them ? (usually I used the github interface for that, but here this is not possible since this PR is based on cgal 5.0)

**Comment by lrineau** [comment]
Something like that:
```shellsession
$ git checkout --no-track -b Basic_viewer_bugfix-gdamiand-for-master Basic_viewer_bugfix-gdamiand
Switched to a new branch 'Basic_viewer_bugfix-gdamiand-for-master'
$ git pull cgal master
From github.com:CGAL/cgal
 * branch                    master     -> FETCH_HEAD
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Midpoint_and_length.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Edge_profile_impl.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Detail/Lindstrom_Turk_core_impl.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Policies/Edge_collapse/Detail/Lindstrom_Turk_core.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/HalfedgeGraph_Polyhedron_3.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse_impl.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Edge_collapse.h
Removing Surface_mesh_simplification/include/CGAL/Surface_mesh_simplification/Detail/Common.h
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_visitor_surface_mesh.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_surface_mesh.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_polyhedron.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_linear_cell_complex.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_enriched_polyhedron.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_surface_mesh.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrained_border_polyhedron.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cmd
Removing Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_all_short_edges.cmd
Removing Surface_mesh_simplification/doc/Surface_mesh_simplification/Concepts/EdgeProfile.h
Removing STL_Extension/include/CGAL/Hash_handles_with_or_without_timestamps.h
Removing Mesh_3/include/CGAL/Mesh_3/Detect_polylines_in_polyhedra_fwd.h
Removing Mesh_3/include/CGAL/Mesh_3/Detect_polylines_in_polyhedra.h
Auto-merging Linear_cell_complex/include/CGAL/draw_linear_cell_complex.h
Auto-merging GraphicsView/include/CGAL/Buffer_for_vao.h
CONFLICT (content): Merge conflict in GraphicsView/include/CGAL/Buffer_for_vao.h
Recorded preimage for 'GraphicsView/include/CGAL/Buffer_for_vao.h'
Automatic merge failed; fix conflicts and then commit the result.

```

You can see that there is a conflict in `GraphicsView/include/CGAL/Buffer_for_vao.h`. Once you have managed to solve it:
```shellsession
$ git push -u mine Basic_viewer_bugfix-gdamiand-for-master
```
and then you can create a new PR, identical to this one, but for CGAL-5.1.

**Comment by gdamiand** [comment]
Thanks @lrineau ; I just create the PR #4473 for master.

**Comment by gdamiand** [comment]
By the way, this PR can be merged in CGAL 5.0.

**Comment by lrineau** [comment]
> By the way, this PR can be merged in CGAL 5.0.

No it cannot, because release branches are always merged into `master`, and this PR cannot be merged into `master`.

**Comment by maxGimeno** [comment]
> This PR conflicts with PR #4224, that was merged in `master` after the release of CGAL-5.0. @maxGimeno, how have you merged this PR in `integration`?

It seems it has been in integration for 6 days before I marked it as Tested, so yes I merged it into integration. 
I had some minor conflicts to resolve at some points, maybe some originated from this PR, I don't know.

**Pull request merged**
