### PR TITLE
Mesh 2 add optimizers gf

### PR DESCRIPTION
**Pull request by janetournois**
This branch implements Lloyd optimization for Mesh_2.

* Small feature 
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/lloyd_optimize_mesh_2
pre-approved on April 10 by @lrineau 

* the branch was (almost) successfully tested in the release 4.7-Ic-33
One warning remains to be fixed.

### CODE REVIEW

**Comment by lrineau** [comment]
A few new files do not have Copyright notice or license.
```
renoir ~/Git/cgal $ ./Scripts/developer_scripts/licensecheck -r Mesh_2/include | grep -vF 'GPL (v3 or later)'
Mesh_2/include/CGAL/Constrained_voronoi_diagram_2.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/lloyd_optimize_mesh_2.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/Constrained_Delaunay_triangulation_face_base_2.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/internal/container_fwd_fixed.hpp: BSL (v1.0)
Mesh_2/include/CGAL/Mesh_2/Lipschitz_sizing_field_2.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/Mesh_2/Sizing_field_2.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/Mesh_2/Mesh_sizing_field.h: *No copyright* UNKNOWN
Mesh_2/include/CGAL/Mesh_2/Lloyd_move_2.h: *No copyright* UNKNOWN
```

What is more, for the moment that pull-request declare that 211 files are modified. But that is because #73 is not yet merged in `master`. I'll do the integration of #73 before, but I still continue to merge this pull-request #90 in `integration`. The tests results so far were good.

**Comment by janetournois** [comment]
I just fixed the missing copyrights

**Comment by lrineau** [comment]
(I Cc @sloriot, because the question is mostly for him.)

Sébastien, the branch is rather heavy (4Mo). I have seen the following commits: c0c6e8f de07dec 5a8b35e, that add/remove images, and some of them are pretty big:
```
* 5a8b35e update image. 3 meshes don't really fit
|  Mesh_2/doc/Mesh_2/fig/lloyd.png | Bin 3131485 -> 566712 bytes
|  1 file changed, 0 insertions(+), 0 deletions(-)
* de07dec change the image to make it more understandable
|  Mesh_2/doc/Mesh_2/fig/lloyd-histograms.png | Bin 17685 -> 18732 bytes
|  Mesh_2/doc/Mesh_2/fig/lloyd.png            | Bin 697890 -> 3131485 bytes
|  2 files changed, 0 insertions(+), 0 deletions(-)
* c0c6e8f add figures to the documentation
   Mesh_2/doc/Mesh_2/fig/lloyd-histograms.png | Bin 0 -> 17685 bytes
   Mesh_2/doc/Mesh_2/fig/lloyd.png            | Bin 0 -> 697890 bytes
   2 files changed, 0 insertions(+), 0 deletions(-)
```
What can we trim down to reduce the size of the branch?

**Comment by lrineau** [comment]
There is a new warning:

https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-35/Mesh_2/TestReport_lrineau_x86-64_Linux-Fedora19_g++-4.8.gz

Indeed, one cannot call a constructor from a constructor, unless C++11 is used.

**Comment by lrineau** [comment]
There is also an error in the Doxygen test suite:
https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.7-Ic-35/Mesh_2.log

**Comment by sloriot** [comment]
I've created https://github.com/sloriot/cgal/tree/rebase/Mesh_2-add_optimizers-GF which size is 804K and `git diff rebase/Mesh_2-add_optimizers-GF..cgal-dev/Mesh_2-add_optimizers-GF` indicates that the branch files are identical. If you agree I can overwrite the branch in cgal-dev with that one.

What I did is recreate the branch before Mesh_2-add_optimizers-GF-old was merged into master, squashed the commits doing pictures manipulations before replaying the merge with the same version of master. Then I cherry-picked the missing commits and replay the merge of the QT branch, finally followed by cherry-picking the last missing commits.

**Comment by janetournois** [comment]
This feature was successfully tested in CGAL-4.7-Ic-44

Waiting for @lrineau 's approval to merge in master

**Comment by lrineau** [comment]
CGAL-4.7-Ic-44 was really too broken to conclude anything. I am sorry, because I am pretty sure your branch and pull-request are ready. I have remerged for tonight.

**Comment by janetournois** [comment]
thank you!

**Comment by lrineau** [comment]
For the moment,  the pull-request still use the heavy branch that weights 4.5Mo. Sébastien, Jane, can you discuss so that:
  - the pull-request is rebased onto the filtered branch made by Sébastien,
  - but still use the latest commits made by Jane to fix warnings.
  - And what is more, try to find out why Github says that there are so many changed, compared to `master`. Maybe a rebase of the branch on top of master can help.

That is a blocker for the moment.

**Comment by sloriot** [comment]
The branch is back at 703K and merged into integration

**Comment by lrineau** [comment]
The tests in [CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml) seems good so far. If no new problems occurs in the columns of the testsuite that will arrive later today, I will merge that pull-request in `master`, so that it is in CGAL-4.7.

**Comment by sloriot** [comment]
@janetournois What is the status of the branch gsoc2013-Mesh_2-improvements-rgallegos?
Can we remove it?

**Comment by janetournois** [comment]
yes, we can remove it. Its content has been moved to Mesh_2-add_optimizers-GF. I will do it.

**Pull request merged**
