### PR TITLE
Arrangement: small doc fixes

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Throw in `%` to avoid links.

## Release Management

* Affected package(s): Arrangements

### CODE REVIEW

**Comment by albert-github** [comment]
I think good corrections , though I think there are more places in the CGAL software where these problems occur (probably also the word `Cartesian` a bit earlier in the same file.
I think a `grep` / `grep -v` might be useful here
- check Cartesian (and also cartesian)
- check orientation()
- check Homogeneous (and also homogeneous)

**Comment by afabri** [comment]
No need for the lower case versions.

**Comment by afabri** [comment]
So far I did only fixes in  `Pkg/doc/Pkg`

**Comment by afabri** [comment]
> Regarding lower case conversions I wrote this as a reminder to check whether or not the case of the words is correct or not.

ok.  In fact I changed several "Homogeneous" to "homogeneous".

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-56

**Pull request merged**
