### PR TITLE
Aos 2 construct curve 2 efif

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

All in all the changes below are bug fixes that enable the use of arrangements of geodesic arcs on a sphere in a larger scope (in particular as geodesic segments of a polyline).

1. Removed redundant constructors for `Traits::Point_2` in `Arr_geodesic_arc_on_sphere_traits_2`. These constructors were erroneous and did not compile. The correct way to construct points and curves for this traits is via the traits, that is, by using `Traits::Construct_point_2`,  `Traits::Construct_x_monotone_curve_2`, and `Traits::Construct_curve_2`.
2. Added Construct_curve_2 for several traits that were missing this functor. It is used by the polyline traits. 
3. Changed the code that constructs a segment of a polyline to use the `SegmentTraits::Construct_curve_2` functor  instead of constructing the segment directly (i.e., `Segment_2(p1, p2)`). This was done to enable the construction of polylines that made of  geodesic arcs on a sphere;  Note that a geodesic arc must be constructed via the functor `Arr_geodesic_arc_on_sphere_traits_2::construct_curve_2`.
4. Introduced a new concept called `ArrangementConstructCurveTraits_2`. It requires the provision of the functor Construct_curve_2 (very similar to the concept `ArrangementConstructXMonotoneCurveTraits_2, which requires the provision of Construct_x_monotone_curve_2.)
5. For some reason the section that describes the Polycurve traits class template in the user manual (last subsection of 7.2.2) was commented out in the last submission. (I assume I made this mistake.) Anyhow, I've resurrected it.

## Release Management

* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): no bug was issued
* Feature/Small Feature (if any): none
* Link to compiled documentation [Arrangement_on_surface_2](http://www.cs.tau.ac.il/~efif/doc_output5/Arrangement_on_surface_2/)
* License and copyright ownership: TAU

### CODE REVIEW

**Comment by sloriot** [comment]
The demo is failing on almost all platforms. See for example [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-129/Arrangement_on_surface_2_Demo/TestReport_gimeno_ArchLinux-clang-Release.gz)

```
/mnt/testsuite/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h:186:5: error: no matching constructor for initialization of 'CGAL::_Conic_arc_2<CGAL::Cartesian<CORE::BigRat>, CGAL::Cartesian<CORE::Expr>, CGAL::CORE_algebraic_number_traits>'
    Base(source, target)
    ^    ~~~~~~~~~~~~~~
```

**Comment by efifogel** [comment]
This is fixed now
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
New warnings:
```
/mnt/testsuite/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h:188:17: warning: statement has no effect [-Wunused-value]
  188 |     this->_info != static_cast<int>(DEGREE_1);
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/testsuite/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h:193:41: warning: statement has no effect [-Wunused-value]
  193 |     if (dir_res == SMALLER) this->_info != IS_DIRECTED_RIGHT;
      |                             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/mnt/testsuite/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h:197:19: warning: statement has no effect [-Wunused-value]
  197 |       this->_info != IS_VERTICAL_SEGMENT;
      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/mnt/testsuite/include/CGAL/Arr_geometry_traits/Conic_x_monotone_arc_2.h:200:17: warning: statement has no effect [-Wunused-value]
  200 |     this->_info != IS_SPECIAL_SEGMENT;
```

**Comment by efifogel** [comment]
oh, big mistake.
I fixed it.
Thank you.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-131

**Comment by lrineau** [comment]
Now that I have created the branch for 5.4 (`5.4.x-branch`), I am considering pull-requests for 5.5, to be merged in `master`. This one is one of them.

I see that this PR modifies the documentation. Should not it be a small feature?

**Comment by efifogel** [comment]
It could, but it's really minor.
In general, the Curve_2 and X_monotone_curve_2 types of the segment traits
are the same exact type.
We used to have a function object called Construct_x_monotone_curve_2 that
could be used to construct objects of type X_monotone_curve_2. This PR adds
Construct_curve_2, which is a type def of Construct_x_monotone_curve_2 and
a function called construct_curve_2_object(), which is a duplicate of
construct_x_monotone_curve_2_object().

The reason we need all this is because
(i) We have already all this in the Arr_geodesic_arc_on_sphere_traits_2,
and there is a difference between X_monone_curve_2 and Curve_2 in this
traits
(2) We use all this from the Arr_polyline_curve_2
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel  guess the 3 following warnings are coming from this branch:
```
/Users/sloriot/CGAL/testsuite/CGAL-5.5-Ic-11/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h:1666:49: warning: unused parameter 'p1' [-Wunused-parameter]
    Comparison_result operator()(const Point_2& p1, const Point_2& p2) const
                                                ^
/Users/sloriot/CGAL/testsuite/CGAL-5.5-Ic-11/include/CGAL/Arr_geodesic_arc_on_sphere_traits_2.h:1666:68: warning: unused parameter 'p2' [-Wunused-parameter]
    Comparison_result operator()(const Point_2& p1, const Point_2& p2) const

/Users/sloriot/CGAL/testsuite/CGAL-5.5-Ic-11/include/CGAL/Arr_topology_traits/Arr_spherical_insertion_helper.h:146:32: warning: unused parameter 'event' [-Wunused-parameter]
before_handle_event_imp(Event* event, Arr_all_sides_oblivious_tag)
```

**Comment by efifogel** [comment]
This is fixed now.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Pull request merged**
