### PR TITLE
Ignore internal directories

### PR DESCRIPTION
**Pull request by sloriot**
Following of #4009

### CODE REVIEW

**Comment by lrineau** [comment]
Have you observe if that changes at all the produced documentation? In Mesh_3, I think there is somewhere we "document" internal types, in the official documentation. Could there be other packages with such obscure practices?

**Comment by sloriot** [comment]
I think the PR is useless and internal is excluded anyway (I'll check before testing it). The CI reported an issue on a file in internal and I was afraid it's because of the nesting of internal but after checking it is because the header was included in a documented file.

**Comment by sloriot** [comment]
Be sure that what I said above is true.

**Comment by sloriot** [comment]
@janetournois @lrineau `internal::` is mentioned in those pages but I don't know how to fix them:
- https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_gray_image_8h-example.html
- https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_labeled_image_8h-example.html
- https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/structCGAL_1_1Mesh__vertex__base__3_1_1Rebind__TDS.html

**Comment by lrineau** [comment]
@sloriot:
> `internal::` is mentioned in the following pages but I don't know how to fix them:
>   * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_gray_image_8h-example.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_gray_image_8h-example.html)
>   * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_labeled_image_8h-example.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_labeled_image_8h-example.html)
>   * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/structCGAL_1_1Mesh__vertex__base__3_1_1Rebind__TDS.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/structCGAL_1_1Mesh__vertex__base__3_1_1Rebind__TDS.html)

The first two are headers. Why do they even appear in examples?

**Comment by sloriot** [comment]
You did it: 07b2acdd3c9f and Jane did the same: 032ad19677a1

> @sloriot:
> 
> > `internal::` is mentioned in the following pages but I don't know how to fix them:
> > 
> > * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_gray_image_8h-example.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_gray_image_8h-example.html)
> > * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_labeled_image_8h-example.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/CGAL_2Mesh_3_2initialize_triangulation_from_labeled_image_8h-example.html)
> > * [cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/structCGAL_1_1Mesh__vertex__base__3_1_1Rebind__TDS.html](https://cgal.geometryfactory.com/CGAL/doc/master/Mesh_3/structCGAL_1_1Mesh__vertex__base__3_1_1Rebind__TDS.html)
> 
> The first two are headers. Why do they even appear in examples?

You did it: 07b2acdd3c9f and Jane did the same: 032ad19677a1

**Comment by sloriot** [comment]
Before those are non-documented headers

**Comment by sloriot** [comment]
@lrineau  I remove them from example.txt. Do you agree?

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-145

**Pull request merged**
