### PR TITLE
Point set processing parallelized with TBB

### PR DESCRIPTION
**Pull request by sgiraudot**
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Point_set_processing_parallelize_for

Last testsuite: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-123.shtml
(Errors have been corrected since.)

### CODE REVIEW

**Comment by lrineau** [comment]
Please modify the file `Installation/changes.html`, so that its contains what is announced at https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Point_set_processing_parallelize_for#changes.html

**Comment by lrineau** [comment]
:white_check_mark: For information, that pull-request passes the tests of the script `Scripts/developer_scripts/test_merge_of_branch`.

**Comment by sloriot** [comment]
@sgiraudot the branch requires an update

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-7](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-7.shtml)

**Comment by sloriot** [comment]
@sgiraudot : I think there is a new warning `/home/cgal_tester/build/src/cmake/platforms/CentOS5/test/Point_set_processing_3/wlop_simplify_and_regularize_test.cpp:59: warning: passing ‘double’ for argument 1 to ‘void std::vector<_Tp, _Alloc>::resize(size_t, _Tp) [with _Tp = CGAL::Point_3<CGAL::Simple_cartesian<double> >, _Alloc = std::allocator<CGAL::Point_3<CGAL::Simple_cartesian<double> > >]’`

**Comment by sgiraudot** [comment]
This warning is probably not new (the incriminated line wasn't changed by this pull request). But I'll fix it anyway as it is pretty straightforward.

**Comment by sloriot** [comment]
Would you mind fixing it? The branch is still under a pre-approved status so we have some time before we can merge the branch.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-10](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-13](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-13.shtml)

**Pull request merged**
