### PR TITLE
Getting rid of the remaining dont_submit files

### PR DESCRIPTION
**Pull request by sloriot**
In order to simplify the generation of releases we are trying to get rid of the remaining dont_submit files.
In this branch I either remove non needed files or move them in `archive` at the root of the package. `archive` is ignored by the release creation script

Some of them are remaining. Remaining files:
- [ ] `Installation` : html files related to the changes page
- [ ] `wininst` : some files are ignored. Can the whole directory be ignored?
- [ ] `Three` : Only the documentation,  while waiting for a review.
- [ ] `Operations_on_polyhedra` :  will disappear soon with a merge of a small feature
- [ ] `Polytope_distance_d` : One test file (related to CGAL/cgal-public-dev/Polytope_distance_d-Bernd?)

TODO: open an issue to track the remaining `dont_submit` files.

### CODE REVIEW

**Comment by sloriot** [comment]
@lrineau I think we should merge this branch now to ease the fix of making individual header compilable.

**Comment by lrineau** [comment]
Sébastien, in https://github.com/CGAL/cgal/pull/1446#issuecomment-249119896:
> @lrineau I think we should merge this branch now to ease the fix of making individual header compilable.

After having merged that PR in my local branch, I now have 79 headers that do not compile, instead of 81.

**Comment by sloriot** [comment]
I sent an email at Bernd about `Polytope_distance_d`

**Comment by sloriot** [comment]
@lrineau If I rebase the branch to fix the conflicts, can we turn the remaining TODO into an issue and try integrating this branch (`Installation` and `wininst` can probably be dealt directly in the upcoming cmake script)

**Comment by lrineau** [comment]
I agree.

**Comment by sloriot** [comment]
I'll open the issue when the branch is merged.

**Comment by lrineau** [comment]
```
 delete mode 100644 Polyhedron/demo/Polyhedron/data/bull.off
 delete mode 100644 Polyhedron/demo/Polyhedron/data/fandisk.off
 delete mode 100644 Polyhedron/demo/Polyhedron/data/femur.off
 delete mode 100644 Polyhedron/demo/Polyhedron/data/lion-head.off
 delete mode 100644 Polyhedron/demo/Polyhedron/data/retinal.off
 delete mode 100644 Polyhedron/demo/Polyhedron/data/turbine.off
```
I am pretty sure we would like to keep those, at least the `fandisk.off`.

**Comment by afabri** [comment]
I agree. Unless want to have a central data repository.

**Comment by lrineau** [comment]
I have merged this PR with the other tested in CGAL-4.10-Ic-23.

@sloriot: You have two TODO:
- re-add the data files in `demo/Polyhedron/data/`,
- open an issue to track the remaining `dont_submit` files.

**Pull request merged**
