### PR TITLE
Make postprocessing script working with python3 and python2

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by lrineau** [comment]
Our CMake script searches python with
```cmake
find_package(PythonInterp 2.6.7)
```

If I understand well, that command will found 2.6.x (with x>=7) and `2.y.x` (with y>=7) but no python3 version.

Should it be modified as well?

**Comment by sloriot** [comment]
AFAIK, this is request for the minimal value and python 3 can be found (which is what happen on @janetournois system where only python 3 is available).

**Comment by lrineau** [comment]
Can I merge this PR today?

**Comment by sloriot** [comment]
@janetournois reported another issue but it might be related to her branch. Let's wait for her to test it on the master branch.

**Comment by lrineau** [comment]
Jane, let me know...

**Comment by janetournois** [comment]
I tested on this branch.
The `doc_with_postprocessing` seems to work fine, but it ends with the following error
```
Traceback (most recent call last):
  File "C:/Users/Jane/Documents/CGAL/git-cgal/Documentation/doc/scripts/html_output_post_processing.py", line 379, in <module>
    main()
  File "C:/Users/Jane/Documents/CGAL/git-cgal/Documentation/doc/scripts/html_output_post_processing.py", line 264, in main
    d = pq(filename=fn, parser='html')
  File "C:\dev\Python3.6.3\lib\site-packages\pyquery\pyquery.py", line 229, in __init__
    elements = fromstring(html, self.parser)
  File "C:\dev\Python3.6.3\lib\site-packages\pyquery\pyquery.py", line 118, in fromstring
    result = custom_parser(context)
  File "C:\dev\Python3.6.3\lib\site-packages\lxml\html\__init__.py", line 940, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src\lxml\etree.pyx", line 3444, in lxml.etree.parse (src\lxml\etree.c:83171)
  File "src\lxml\parser.pxi", line 1855, in lxml.etree._parseDocument (src\lxml\etree.c:121011)
  File "src\lxml\parser.pxi", line 1875, in lxml.etree._parseFilelikeDocument (src\lxml\etree.c:121294)
  File "src\lxml\parser.pxi", line 1770, in lxml.etree._parseDocFromFilelike (src\lxml\etree.c:120078)
  File "src\lxml\parser.pxi", line 1185, in lxml.etree._BaseParser._parseDocFromFilelike (src\lxml\etree.c:114806)
  File "src\lxml\parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\etree.c:107724)
  File "src\lxml\parser.pxi", line 705, in lxml.etree._handleParseResult (src\lxml\etree.c:109392)
  File "src\lxml\etree.pyx", line 326, in lxml.etree._ExceptionContext._raise_if_stored (src\lxml\etree.c:13245)
  File "src\lxml\parser.pxi", line 376, in lxml.etree._FileReaderContext.copyToBuffer (src\lxml\etree.c:105059)
  File "C:\dev\Python3.6.3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 956: character maps to <undefined>
NMAKE : fatal error U1077: 'C:\dev\Python3.6.3\python.exe'▒: code retour '0x1'
Stop.
```

It does not depend on my branch, but maybe it depends on something else in my setup...(?)

**Comment by afabri** [comment]
Is python 2.7 completely outdated?  We should only make the effort to make it work on different versions of python, if that is really necessary.

**Comment by lrineau** [comment]
The postprocessing did not work correctly.

The code of `Documentation/doc/scripts/html_output_post_processing.py`, line 264 is:
```python
    class_files=list(package_glob('./*/class*.html'))
    class_files.extend(package_glob('./*/struct*.html'))
    for fn in class_files:
        d = pq(filename=fn, parser='html')  # HERE IS THE THE LINE 264
        ident = d('#CGALConcept')
        if ident.size() == 1:
            conceptify(d);
            # in case of a second pass don't process this again
            d.remove("#CGALConcept")
        # there is a doxygen bug that prevents the correct linkage of the CGAL breadcrumb
        ident = d('#nav-path .navelem').eq(0).children().eq(0)
        if ident and ident.attr('href') == 'namespaceCGAL.html':
            ident.attr('href', '../Manual/namespaceCGAL.html')
        write_out_html(d, fn)
```
And that is one of the first loop of `main()`. That mean the postprocessing did not work.

**Comment by janetournois** [comment]
the error remains

**Comment by janetournois** [comment]
It seems the error is not only due to the post-processing, but to the html code generated by Doxygen, which contains non-utf-8 characters. See issue #2667 for more details.

**Comment by lrineau** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-121.shtml. Merged.

**Pull request merged**
