### PR TITLE
Minkovski_sum_2: reduced conv collision detection

### LINKED ISSUE #2517: Invalid output (missing hole) when performing 2d minkowski sum
## Issue Details

In some cases, 2d Minkowski Sum produces invalid output.
When performing the Minkowski sum on a polygon with one hole with another (simple) polygon, it seems that some weird conditions on the outer boundary of the polygon with hole lead to invalid output, where the output should still contain an "eroded" hole and this hole is actually missing. See attached pictures that illustrates the case.

cgal_bug_input
Input polygons: the polygon with hole (in blue) and the other polygon, the "pattern" (in green).

cgal_bug_output
Ouput of the minkowski sum where a 1x1 hole is missing.

Note that if we reduce the outer boundary of the polygon with hole on which is applied the sum, by replacing each -3 coordinate by -2, we obtain the correct result (the "eroded" hole is present in the output sum).

## Source Code
```
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/basic.h>
#include <CGAL/minkowski_sum_2.h>

  typedef CGAL::Exact_predicates_exact_constructions_kernel     Kernel;
  typedef Kernel::Point_2                                       Point_2;
  typedef CGAL::Polygon_2<Kernel>                               Polygon_2;
  typedef CGAL::Polygon_with_holes_2<Kernel>                    Polygon_with_holes_2;

  Polygon_with_holes_2 polygon_w_holes;
  polygon_w_holes.outer_boundary().push_back(Point_2(-3., -3.));
  polygon_w_holes.outer_boundary().push_back(Point_2(7., -3.));
  polygon_w_holes.outer_boundary().push_back(Point_2(7., 7.));
  polygon_w_holes.outer_boundary().push_back(Point_2(-3., 7.));

  // the hole for the polygon to apply pattern
  Polygon_2 hole;
  hole.push_back(Point_2(5., 2.));
  hole.push_back(Point_2(2., 2.));
  hole.push_back(Point_2(2., 5.));
  hole.push_back(Point_2(5., 5.));
  polygon_w_holes.add_hole(hole);

  Polygon_2 pattern;
  pattern.push_back(Point_2(1., 1.));
  pattern.push_back(Point_2(-1., 1.));
  pattern.push_back(Point_2(-1., -1.));
  pattern.push_back(Point_2(1., -1.));

  Polygon_with_holes_2  sum = CGAL::minkowski_sum_2(polygon_w_holes, pattern);

  std::cout << "outer boundary: " << sum.outer_boundary() << std::endl;
  for(auto it_hole = sum.holes_begin(); it_hole != sum.holes_end(); ++it_hole)
  {
    std::cout << "hole : " << *it_hole << std::endl;
  }
```

Produces output:
```
outer boundary: 8 -5 -5 -3 -5 7 -5 7 -3 7 7 5 7 -5 7 -5 5
 ```

But expected output should look like this:
```
outer boundary: 8 -5 -5 -3 -5 7 -5 7 -3 7 7 5 7 -5 7 -5 5
 hole : 3 3 3 4 4 4 4 3
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Fedora 25 64 bits
* Compiler: g++ 6.3.1
* Release or debug mode: Release
* Specific flags used (if any): -
* CGAL version: 4.9.1 (git hash: 01ce16fd5f6c6f660d39e037faefbb6b3fdabc6c )
* Boost version: 1.60
* Other libraries versions if used (Eigen, TBB, etc.): -

### PR DESCRIPTION
**Pull request by efifogel**
This fixes a bug in the Minkowski_sum_2 package.
In particular, it fixes a bug in the reduced-convolution  computation.
Specifically, given a face of the arrangement induced by the reduced convolution set, we need to test whether the face is in the sum or not. We pick a point x in the face and test whether P and (x \oplus -Q) collide. The changes in this brunch fix the code the implements the testing logic of the collision detection.

## Release Management

* Affected package(s): Minkowski_sum_2
* Issue(s) solved (if any): fix #2517
* Feature/Small Feature (if any): None

### CODE REVIEW

**Comment by lrineau** [comment]
The bug #2517 was reported against CGAL-4.9. Any chance this PR could be rebased onto `releases/CGAL-4.10-branch` or `releases/CGAL-4.11-branch` ?

**Comment by efifogel** [comment]
It can be rebased into both.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
TODO for @lrineau: we will have to rebase the branch and retest it.

**Comment by sloriot** [comment]
@blinry I've added you as a reviewer. Would you have time to review it?

**Comment by lrineau** [comment]
ping @blinry (https://github.com/CGAL/cgal/pull/2571#issuecomment-343859766), ping @sloriot.

This PR is required for 4.10.2.

**Comment by lrineau** [comment]
Beware: I have rebased the branch onto `releases/CGAL-4.10-branch`! You must reset your local branch.

**Comment by lrineau** [comment]
re-ping!

> ping @blinry (https://github.com/CGAL/cgal/pull/2571#issuecomment-343859766), ping @sloriot.
> 
> This PR is required for 4.10.2.

**Comment by lrineau** [comment]
@maxGimeno I do not understand the Travis error, related to Qt5 that is not found. Is not that something that popped up and we fixed?

**Comment by maxGimeno** [comment]
the .travis.yml file is not the one it should be. It does not match the one from master, especially for the qt5 libs.

**Comment by lrineau** [comment]
@maxGimeno The Travis configuration in this PR is exactly the same as in `cgal/releases/CGAL-4.10-branch`, that [passed, just one day ago][1]!

[1]: https://travis-ci.org/CGAL/cgal/builds/311987506

**Comment by maxGimeno** [comment]
4.10? Aren't we in 4.12?

**Comment by lrineau** [comment]
`master` now targets CGAL-4.12, but bug-fixes pull-requests are against release branches, here `releases/CGAL-4.10-branch`.

**Comment by lrineau** [comment]
Let's ignore the Travis error: even if the PR in against **`releases/CGAL-4.10-branch`**, Travis has tested a commit that merged this PR in **`master`**. That is not consistent.

**Comment by sloriot** [comment]
Tested in [CGAL-4.12-Ic-124](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-124), waiting for Travis green light.

**Comment by lrineau** [comment]
I have decided to merge anyway, because the merge commit Travis has tested is strange.

**Pull request merged**
