### PR TITLE
Do not include <CGAL/basic.h>

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

The tests should only include what is needed.  (I cherry picked from PR #3686). Some few are missing to avoid merge conflicts with #3797 

## Release Management

* Affected package(s): all

### CODE REVIEW

**Comment by maxGimeno** [comment]
I remove it for now, to see if the line Installation is still red without this

**Comment by maxGimeno** [comment]
I think this PR is responsible for 
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-10.shtml#STL_Extension

**Comment by maxGimeno** [comment]
Probably responsible for  https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-14.shtml#Algebraic_foundations

**Comment by afabri** [comment]
@lrineau thanks a lot!!!

**Comment by maxGimeno** [comment]
Seems ok in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-39.shtml, appart maybe for the LEDA columns. Not sure it's related.

**Pull request merged**
