### PR TITLE
Fix the link computation for edges on the border

### PR DESCRIPTION
**Pull request by sloriot**
The condition for adding vL and vR was incorrect

## Release Management

* Affected package(s): Surface Mesh Simplification

### CODE REVIEW

**Comment by sloriot** [comment]
I still need to add some tests.

**Comment by sloriot** [comment]
Tests are here now. Ready to be tested!

**Comment by lrineau** [comment]
There are [compilation errors]. Probably this missing include:
```C++
#include "boost/tuple/tuple_comparison.hpp"
```

  [compilation errors]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-24.shtml#Surface_mesh_simplification

**Comment by lrineau** [comment]
There are warnings in Windows:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-I-90.shtml#Surface_mesh_simplification

That will not block CGAL-4.11, because those warnings are only in the testsuite. But please try to fix them.

**Comment by afabri** [comment]
I take care of this.

**Pull request merged**
