### PR TITLE
Polygon: Add move semantics

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Use move semantics for `Polygon_2`  and `Polygon_with_holes_2`.   
The latter gets passed a polygon as outer boundary and an iterator range of polygons for the holes.  

## Release Management

* Affected package(s):  Polygon_2

### CODE REVIEW

**Comment by pentacular** [comment]
I think that you cannot assume that the holes can be std::move'd on the basis of how the boundary was passed, since std::move will destroy the holes in the caller, and these may have different lifetimes.

**Comment by afabri** [comment]
> I think that you cannot assume that the holes can be std::move'd on the basis of how the boundary was passed, since std::move will destroy the holes in the caller, and these may have different lifetimes.

What are the options.
- Document that this is what we do. If you don't want to move holes, simply do not move the outer boundary and everything gets copied.
- Add overloads which move the boundary one but not the others, and even not the boundary but the holes. 
- Move would not work with a  `const`  boundary polygon, We could move the holes in case they are not const.  That could lead to nasty to debug user code as it would be rather implicit.

**Comment by pentacular** [comment]
> > I think that you cannot assume that the holes can be std::move'd on the basis of how the boundary was passed, since std::move will destroy the holes in the caller, and these may have different lifetimes.
> 
> What are the options.
> 
> * Document that this is what we do. If you don't want to move holes, simply do not move the outer boundary and everything gets copied.
> * Add overloads which move the boundary one but not the others, and even not the boundary but the holes.
> * Move would not work with a  `const`  boundary polygon, We could move the holes in case they are not const.  That could lead to nasty to debug user code as it would be rather implicit.

Well, moving the holes requires a move_iterator -- how about only supporting that where the boundary is also moved?

**Comment by sloriot** [comment]
The bug of the doc comes from the post-processing. I'll fix it.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-92

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-1

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-5

**Pull request merged**
