### PR TITLE
Alpha wrapping: re-use and resume functionalities

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

- https://github.com/CGAL/cgal/pull/7629
- Add benchmarking executables and scripts to generate reports on the state of AW3.
- Add functionality + example to interrupt the wrapping process, and resume it.
- Add functionality + example on re-using the 3D triangulation of a previous wrap with new alpha (and offset) values.
- Introduce zombie mechanism to avoid having to clean the queues when facets are destroyed by a new Steiner point.
- Use a consistent value in the sorted queue (circumradius of the *surface* Delaunay ball, and not of the facet).
- Distinguish between inside/outside cells, and cells that are flagged "inside" to get a manifold result.
- Add a function + named parameter to purge pockets of outside cells that are disconnected from the outside.
- Introduce a new queue that is a simple LIFO instead of sorting by circumradius, which speeds things up:
image
- Misc general improvements.
 
TODO:
- Cached oracle queries: https://gist.github.com/MaelRL/ddb3db8a2ddd7ae5319e68655f255bdd. Useful for sorted queues (noticeable speed-up), but pointless (even costly) for FIFO queues.
- [x] check computation of values in the demo. cube-minus-cube alpha = 20 is too large?

## Release Management

* Affected package(s): `Alpha_wrap_3`
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

**Comment by sloriot** [comment]
Compilation issue on windows + warnings in CGAL-6.0-Ic-112 (AW3 test+ex)

**Comment by afabri** [comment]
warning in [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-116/Polyhedron_Demo/TestReport_magritte_arm64-apple_bigsur_clang1200-release-64bits.gz)
```
CGAL-6.0-Ic-116/test/Polyhedron_Demo/Plugins/Alpha_wrap_3/Alpha_wrap_3_plugin.cpp:220:44: warning: unused parameter 'wrapper' [-Wunused-parameter]
  constexpr bool go_further(const Wrapper& wrapper)
  ```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-116

**Comment by lrineau** [comment]
Mael asked me no to merge this PR. I tag it with https://github.com/CGAL/cgal/labels/Not%20yet%20approved.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-122

**Pull request merged**
