### PR TITLE
Replace deprecated binder2nd

### PR DESCRIPTION
**Pull request by bo0ts**
We cannot just use `boost::bind` or similar, since we need to get the type
of the binder (which is not easily possible without decltype).

### CODE REVIEW

**Comment by lrineau** [comment]
I agree with the change. Well, I would have named the function differently. Maybe `Less_than`, instead of `Less_binder2nd`. What do you think @bo0ts?

**Comment by bo0ts** [comment]
@lrineau Sure, my brain was stuck thinking about the `binder2nd`, so that was the only name I could come up with. Fixed and rebassed.

**Comment by afabri** [comment]
Bounding_volumes/include/CGAL/Min_annulus_d.h:  uses this too.

With  grep "std::bind" */include/CGAL -r  there is even more, but I don't know if these matches are deprecated.

**Comment by bo0ts** [comment]
@afabri I also grepped the code base and there even is an example using it. Unless we are going to require C++11 anytime soon we should replace those were possible with `boost::bind`.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-100

**Comment by bo0ts** [comment]
I noticed that there is a syntax mistake in the PR, but it is only triggered when the code is actually instantiated. That means the testsuite is not covering that part.

**Comment by sloriot** [comment]
Could you fix that?

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-101

**Comment by sloriot** [comment]
My guess was that this PR was about fixing the following warning in the testsuite:
`/home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/test/Mesh_3/test_meshing_3D_gray_image.cpp:47:12: warning: 'template<class _Operation> class std::binder1st' is deprecated [-Wdeprecated-declarations]
       std::binder1st< std::less<Image_word_type> > >    Mesh_domain;`
on that [platform](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-101/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz).
Does this fix something in the testsuite?

**Comment by lrineau** [comment]
The example file still use a deprecated class.
@janetournois

**Comment by janetournois** [comment]
I have pushed 2 complementary commits to the branch [cgal-dev/Mesh_3-replace_binder2nd-pmoeller]{https://github.com/CGAL/cgal-dev/tree/Mesh_3-replace_binder2nd-pmoeller}

**Comment by lrineau** [comment]
I have pushed the three commits from Jane in @bo0ts' fork.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-104

**Comment by sloriot** [comment]
Warning is still [here](:https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-104/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz):
`/home/cgal_tester/build/src/cmake/platforms/ArchLinux-CXX14/test/Mesh_3/test_meshing_3D_gray_image.cpp:47:12: warning: 'template<class _Operation> class std::binder1st' is deprecated [-Wdeprecated-declarations]
       std::binder1st< std::less<Image_word_type> > >    Mesh_domain;`

**Comment by janetournois** [comment]
I have pushed 1 commit fixing this warning to the branch [cgal-dev/Mesh_3-replace_binder2nd-pmoeller](https://github.com/CGAL/cgal-dev/tree/Mesh_3-replace_binder2nd-pmoeller)

@lrineau @bo0ts @sloriot

**Comment by sloriot** [comment]
The warning is [gone](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-106/Mesh_3/TestReport_lrineau_ArchLinux-CXX14.gz)

**Pull request merged**
