### PR TITLE
Add index function in Compact container

### PR DESCRIPTION
**Pull request by gdamiand**
This function allows to retreive the index of a given handle. This is particularly usefull to debug code based on compact container. This allows to write index (small numbers) instead of pointers.

This function is undocumented because it is mainly for cgal developers; and thus there is no modification of api, and thus no small feature.

I used this function in CMap test in order to test it.

### CODE REVIEW

**Comment by lrineau** [comment]
Fine for me.

Let's hope we will eventually have the indexed-based `Compact_container`.

**Comment by gdamiand** [comment]
Thanks. I agree for the indexed-based Compact_container...

However now thanks to index, operator[], is_used and the fact that when an element is removed we can continue to use iterator on it, the use of Compact_container is much simpler and its use more similar to a std::vector.

I used these functionalities in personal code and it simplify a lot the code...

**Comment by lrineau** [comment]
There are several errors in the testsuite of CMap, today:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10-Ic-15.shtml#Combinatorial_map

Could it be because of this PR?

**Comment by gdamiand** [comment]
Yes it is.
I will correct this.

**Comment by gdamiand** [comment]
Done in [this] (https://github.com/gdamiand/cgal/commit/f034fe2a928c980e42d842a7ab6304445a7df3ff commit) commit.

I added a test in [this second] (https://github.com/gdamiand/cgal/commit/5626eeae92892a1775e995045899d1137fe30d1a) commit

**Pull request merged**
