### PR TITLE
Mesh_2 suppress an "unused parameter" warning concerning boost

### PR DESCRIPTION
**Pull request by afabri**
This should fix this [testcase](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/Mesh_2/TestReport_lrineau_Fedora-strict-ansi.gz)

### CODE REVIEW

**Comment by sloriot** [comment]
Would you mind adding a check on the boost version? The fix has been included in boost 1.60.

**Comment by lrineau** [comment]
@sloriot Can you point out the reference? I did not know is was fixed for Boost-1.60.

**Comment by sloriot** [comment]
The tag for boost.parameter 1.60 is BOOSTORG/parameter@0461c0a which contains BOOSTORG/parameter@9821c1a5

**Comment by sloriot** [comment]
Tested in CGAL-4.8-Ic-136

**Pull request merged**
