### PR TITLE
Convex hull 3 fix halfspace intersections sloriot

### LINKED ISSUE #76: halfspace_intersection_3.h::is_intersection_dim_3 not smart enough
If you pass the following planes to halfspace_intersection_3 (planes forming a box-thing):

-1 0 0 -11.92
0 -1 0 32.72
0 1 0 -33.28
0 0 -1 0.64
0 0 1 -1.6
1 0 0 11.3599

If I'm not mistaken the intersection is a valid polyhedron cuboid, but the assertion above aggressively (and I would think incorrectly) determines it is not in 3 dimensions.

I think this is because plane1_it = -1 0 0 -11.92 and plane2_it = 1 0 0 11.3599, which are parallel, so they are automatically coplanar with any other vector in the "coplanar" check.

### PR DESCRIPTION
**Pull request by sloriot**
Merged into CGAL-4.7-Ic-30
The branch is based on releases/CGAL-4.6-branch

It fixes #76 and #75

Previously submitted as #81

### CODE REVIEW

**Comment by sloriot** [comment]
Re-merged in 4.7-Ic-32

**Comment by sloriot** [comment]
Is there any blocking point to merge this PR?

**Comment by lrineau** [comment]
Sorry, I had not seen that pull-request, because it was not merged using [`hub`](https://github.com/github/hub),

The tests in CGAL-4.7-Ic-32 were successful.

**Comment by bombax** [comment]
I have a huge set of sample data to test this fix with, which I think could be useful. As of 4.6 there are some instances which do not work. I would gladly test the fix for you. Do I need to recompile CGAL .a and .dll files to test or is the fix completely header-only? What should I replace?

Thanks!

**Comment by sloriot** [comment]
There is no need to recompile the library.

**Pull request merged**
