### PR TITLE
Towards getting rid of dont_submit files

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by sloriot** [comment]
CGAL/LEDA_basic.h was removed while it is used in various files.

**Comment by afabri** [comment]
resurrected.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-93

**Comment by sloriot** [comment]
New warnings were added in `Surface_mesher` because some new tests were ran

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-94

**Pull request merged**
