### PR TITLE
 SMSP: fix border and robustness issues (5.0)

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

5.0 version of #3977.

## Release Management

* Affected package(s): `Surface_mesh_shortest_path`

### CODE REVIEW

**Comment by maxGimeno** [comment]
Runtime error : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-158.shtml#Surface_mesh_shortest_path

**Comment by MaelRL** [comment]
It's a timeout, not an error.

**Comment by maxGimeno** [comment]
It is still a red line :/

**Comment by MaelRL** [comment]
I did notice that Debug runtime was a lot worse while release mode runtime is unaffected, but as it was still sub 40mins on my machine, I did not bother with it.

It does show that almost all platforms are running in Debug mode though, even most of those advertised as Release mode.

**Pull request merged**
