### PR TITLE
Polyhedron_demo : Fix for 773

### PR DESCRIPTION
**Pull request by maxGimeno**
This is a fix for #773 : it makes the color of the facets of a selection_item editable.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-137

**Comment by sloriot** [comment]
@janetournois Does this fix the issue reported?

**Comment by sloriot** [comment]
@janetournois any update?

**Comment by janetournois** [comment]
@sloriot this PR fixes the issue
Thanks @maxGimeno

**Pull request merged**
