### PR TITLE
Circular_kernel_{2,3}: Cleanup of examples and tests

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

The tests and examples included unnecessary files.  A test should include the absolute minimum, and examples must be exemplary.

## Release Management

* Affected package(s): Circular_kernel  2D and 3D

### CODE REVIEW

**Comment by maxGimeno** [comment]
Tests failing in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-125.shtml#Circular_kernel_2

**Comment by lrineau** [comment]
I think I have found the right fix, in https://github.com/CGAL/cgal/pull/3682/commits/c3b8d2c46fe4bb2ca41d14e397495d245907172c. But I cannot test it easily. Let's see tonight in the test suite.

**Comment by maxGimeno** [comment]
Warning here (I think) : https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-127.shtml#Circular_kernel_3

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Feb 19, 2019, 1:21 PM GMT+1](https://github.com/CGAL/cgal/pull/3682#issuecomment-465108116 "2019-02-19T12:21:23Z - Replied by Github Reply Comments"):
> Warning here (I think) : https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-127.shtml#Circular_kernel_3

That warning is related to PR #3580, merged in `master`. We also [see it in `master`][1]. It will be fixed by the new PR #3694.

[1]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-126/Circular_kernel_3/TestReport_gimeno_Fedora-rawhide-Release.gz

**Comment by afabri** [comment]
This is fixed now.  [Before ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-127/Circular_kernel_3/TestReport_lrineau_Fedora-Release.gz)and [after](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-128/Circular_kernel_3/TestReport_lrineau_Fedora-Release.gz)

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-130.shtml

**Pull request merged**
