### PR TITLE
Use to_double to make it work with Epec

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by sloriot** [comment]
Fixes #858

**Comment by lrineau** [comment]
The line `Polygon_mesh_processing_Examples` is fully red, and git logs point to this pull-request:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-1.shtml#Polygon_mesh_processing_Examples
```
------------------------------------------------------------------
- ProgramOutput.isotropic_remeshing_example.x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8
------------------------------------------------------------------
Split border...done.
Start remeshing of data/pig.off (911 faces)...
CGAL error: assertion violation!
Expression : size_t(_idx) < data_.size()
File       : /no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/include/CGAL/Surface_mesh/Surface_mesh.h
Line       : 411
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: size_t(_idx) < data_.size()
File: /no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/include/CGAL/Surface_mesh/Surface_mesh.h
Line: 411
./cgal_test_with_cmake: line 69: 59220 Aborted                 (core dumped) ./isotropic_remeshing_example

------------------------------------------------------------------
```

**Comment by lrineau** [comment]
Cc @janetournois, see last comment 
https://github.com/CGAL/cgal/pull/871#issuecomment-199188625

**Comment by lrineau** [comment]
TODO: There should be something in the documentation that explains which algorithms that cannot be exact, even with an exact number type.

**Comment by lrineau** [comment]
@janetournois @afabri What is the status of this PR? Has the documented been updated, since the last discussion three weeks ago?

**Comment by lrineau** [comment]
@janetournois @afabri Same question as https://github.com/CGAL/cgal/pull/871#issuecomment-208340050. Status update?

**Comment by sloriot** [comment]
Replaced by #957

**Pull request closed without merging**
