### PR TITLE
Handle isolated vertices

### PR DESCRIPTION
**Pull request by sloriot**
`Is_outward_oriented()` results in a segfault if the input mesh has some isolated vertices.

### CODE REVIEW

**Comment by lrineau** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cgal/cgal/2919#-:-L7POIFDYLjaDAlXRzC4:bnfp4nl)*

**Comment by lrineau** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cgal/cgal/2919)*

**Comment by lrineau** [comment]
Travis reports real errors.

**Comment by sloriot** [comment]
Should be fixed, strange ctest did not reported it locally...

**Comment by lrineau** [comment]
Maybe a difference of behavior between clang and gcc.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.12-Ic-207], and then merged.

  [CGAL-4.12-Ic-207]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-207.shtml

**Pull request merged**
