### PR TITLE
Spelling correction

### PR DESCRIPTION
**Pull request by albert-github**
Another batch of spelling corrections in doxygen and normal comments

### CODE REVIEW

**Review by afabri — APPROVED** [review]
I have fully read the _Files changed_ and approve the changes. Thank you Albert.

**Comment by afabri** [comment]
As you are on it, can you please also just change the insure to ensure [here](https://github.com/CGAL/cgal/blob/e90842fd05bbbec3148a45a2a8608f494c2ff075/Triangulation_2/doc/Triangulation_2/Triangulation_2.txt#L1256).   In an open pull request Mael has already fixed another occurrence in the 3D demo.

**Review by afabri — APPROVED** [review]
I have read all changes.

**Comment by albert-github** [comment]
@afabri 
Thanks for gong through the spelling changes I made.
I'm currently working on the next batch and I already found the ensure / insure problem in Triangulation_2/doc/Triangulation_2/Triangulation_2.txt

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-262

**Pull request merged**
