### PR TITLE
Add BGL helper copy_face_graph()

### PR DESCRIPTION
**Pull request by bo0ts**
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/BGL_copy_face_graph#API

This adds a function to copy a `FaceListGraph` to another `FaceListGraph`.

### CODE REVIEW

**Comment by sloriot** [comment]
See also #949 to see if the fix should apply too

**Comment by afabri** [comment]
I applied the fix from  janetournois:BGL-fix_conversion_of_boundary_halfedges-jtournois

**Comment by lrineau** [comment]
TODO: @lrineau or @bo0ts should update this PR.

**Comment by janetournois** [comment]
I just rebased the branch onto master and pushed it to cgal-dev/BGL-document_copy_face_graph-pmoeller.
@lrineau or @bo0ts can you please push it to this PR?

I'm now testing if it works locally

**Comment by janetournois** [comment]
It does work locally. Ready for testing

**Comment by lrineau** [comment]
I have pushed the rebased version to @bo0ts's fork of cgal. This PR is updated.

**Comment by lrineau** [comment]
Merged.

In the merge commit ea1462d6daf55206736f4879c0e5798544d4e659, I have moved the paragraph in `Installation/changes.html` from 4.8 to 4.9.

**Comment by janetournois** [comment]
thanks!

**Comment by sloriot** [comment]
Was the wiki updated?

**Comment by lrineau** [comment]
@sloriot:
> Was the wiki updated?

Done, now.

**Pull request merged**
