### PR TITLE
Fix wrong uses of std::numeric_limits::min() (4.11)

### LINKED ISSUE #2563: bug in Two_vertices_parameterizer_3.h
## Issue Details
runtime error
given a mesh with only one triangle 
-27.9902 8.96537 -36.5647
-27.9902 8.96613 -36.5647
-27.9901 8.96704 -36.5647
parameterize it with Square_border_arc_length_parameterizer_3 and LSCM_parameterizer
-> crash, using null pointer

bug is in:
Two_vertices_parameterizer_3.h:135-137
in 131-149 we suppose to find the bounding box of the mesh.
so  xmax should be initialize as -inf(std::numeric_limit<double>lowest),
but cgal is using numeric_limite<double>::min
which is the minimal positive value of double, epsilon. close to 0
so at the end xmax =0, (it like we extend bbox with 0,0,0)
then cgal chose Z then X as axis
as we all have the same Z, so all vertex will paramterized as u=0

then in line:230,232, again, using min instead of lowest
umax is epsilon now
we never enter if in line:255(u=0<epsilon)
vxmax is empty. crash in line 262

 

* Operating system (Windows/Mac/Linux, 32/64 bits):win64
* Compiler:MSVC
* Release or debug mode: release
* Specific flags used (if any):
* CGAL version:4.10, also in 4.11
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Second part of #2564, because `SMP` was restructured with CGAL-4.11.

## Release Management

* Affected package(s): `SMP`
* Issue(s) solved (if any): fixes  #2563.
* Feature/Small Feature (if any): --

### CODE REVIEW

**Comment by lrineau** [comment]
@mglisse https://github.com/CGAL/cgal/pull/2565#issuecomment-339972470
> Out of curiosity, is it properly documented that this only works if `FT` is float, double or similar (infinity, max and min are likely to return 0 for most types)? Not that anyone is going to try, but you never know... I see a mention in Shape_detection_traits.h, but supposedly one could provide their own class satisfying the `ShapeDetectionTraits` concept.

That is one reason to use `max()` instead of `infinity()`: there is more chance that it is implemented.

**Comment by lrineau** [comment]
Actually... it seems all the use cases are the computation of a `Bbox_3`. And the number type of `CGAL::Bbox_3` is always `double`, for all CGAL kernels.

**Comment by mglisse** [comment]
> That is one reason to use max() instead of infinity(): there is more chance that it is implemented.

Note that I wasn't suggesting changing the code, just making sure the doc was in sync.

> Actually... it seems all the use cases are the computation of a Bbox_3. And the number type of CGAL::Bbox_3 is always double, for all CGAL kernels.

Well the code in Octree.h does use FT directly, which isn't double for Epeck.

**Comment by sgiraudot** [comment]
The `Shape_detection_traits` says that FT should be `float` or `double`, so I think we're good.

**Comment by mglisse** [comment]
@sgiraudot "I see a mention in Shape_detection_traits.h, but supposedly one could provide their own class satisfying the ShapeDetectionTraits concept.", I just wonder if the remark should be copied from Shape_detection_traits to the concept.

**Comment by sgiraudot** [comment]
Most probably… I don't think the package would work with something else than `float` or `double` (it's one of the many).

**Pull request merged**
