### PR TITLE
Fixed unusable error message

### PR DESCRIPTION
**Pull request by rewolff**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Users of cgal, in this case, "openscad" end-users, sometimes get this error message and then have no clue on what's wrong an how to fix it.  One look at the code show what the error is for, so I made the error message more useful. 

## Release Management

I think this should be included ASAP and should be quite innocent. (i.e. not cause regressions). 

I think someone more familiar with the code should look at  my change before approval: I just looked at at most 10 lines around the offending error message.

### CODE REVIEW

**Comment by MaelRL** [comment]
Thank you for the PR.

Could you please rebase this onto the 4.14 branch so that your fix can also be in the bug fix releases for 4.14 and 5.0? This can be achieved simply with:
```
git rebase --onto cgal/releases/CGAL-4.14-branch cgal/master
```
and a force push.

**Comment by rewolff** [comment]
That does not work for me. I managed 
```
abra2:~/tmp/cgal> git rebase --onto cgal/releases/CGAL-4.14-branch cgal/master
fatal: Needed a single revision
invalid upstream cgal/master
abra2:~/tmp/cgal> 
```
I don't have the foggiest idea what you're doing there, so I've tried about 12 variants but not one seems to succeed.

**Comment by lrineau** [comment]
> That does not work for me. I managed
> 
> ```
> abra2:~/tmp/cgal> git rebase --onto cgal/releases/CGAL-4.14-branch cgal/master
> fatal: Needed a single revision
> invalid upstream cgal/master
> abra2:~/tmp/cgal> 
> ```
> 
> I don't have the foggiest idea what you're doing there, so I've tried about 12 variants but not one seems to succeed.

Your remote is probably named `origin`. Try:
```shell-session
> git rebase --onto origin/releases/CGAL-4.14-branch origin/master
> git push -f origin
```

**Comment by rewolff** [comment]
WHat I first did is clone YOUR repository, then forked it on github, added that upstream as "mine" and pushed my changes to "mine". 
I tried substituting mine where you suggested "origin". I already tried that on my own btw as well. No go. 
I now cloned my own repository into a new directory  did the rebase, and pushed as you suggested. That seems to have worked!

**Comment by MaelRL** [comment]
@rewolff Since you have deleted the repo, this pull request is now void and broken, can you please submit a new pull request?

**Comment by rewolff** [comment]
Ehh That was not the intention. 
"Such quick patches that require a pull request" tend to clutter my "list-of-repositories". So to keep things clean, I like to clean up whenever possible. And a note here in this pull request said something to the effect: "Pull request closed, click here to clean up your forked version of this project". So I followed the directions.... 

Will try to reinstate ASAP. 
(Replacing fan in my pc first. )

**Comment by rewolff** [comment]
pull #4667 is the new one.

**Pull request closed without merging**
