### PR TITLE
fix navtree hack

### LINKED ISSUE #3562: Online Documentation: sidebar is mislinked in Mesh_3 Reference Manual
## Issue Details

When clicking a section in the documentation (latest) sidebar, the correct section is loaded but then the sidebar jumps to a different section, making us lose context since the sidebar no longer shows the section we're reading. This is possibly a problem in other documentation chapters as well. 

Going back to CGAL documentation version 4.11.3, this issue is no longer present. The issue starts appearing in doc version 4.12.1 and is also present in 4.13, "latest" and "master".

Steps to reproduce:
* Navigate to: https://doc.cgal.org/latest/Mesh_3/group__PkgMesh__3.html
* Click the `Reference Manual - Mesh Classes` section in the sidebar. (The correct section text is loaded on the right, but the sidebar jumps to `Reference Manual - Main Concepts - MeshComplexWithFeatures_3InTriangulation_3`.)

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Tested in Chrome, Edge, Firefox on Windows 10
* CGAL version: documentation versions master, latest, 4.13, 4.12.1

### PR DESCRIPTION
**Pull request by sloriot**
Fix #3562

### CODE REVIEW

**Comment by sloriot** [comment]
@albert-github I wonder whether I should report the behavior change  (`hash` was an empty string before and now is `#` in case no anchor is given).

**Comment by albert-github** [comment]
Yes, I think you should report it together with an example / the place where we can find the problem.
The problem might be due to the extra processing as done by CGAL.

**Comment by lrineau** [comment]
The bug #3562 is fixed, in the testsuite: see at https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-121/master/Mesh_3/group__PkgMesh3MeshClasses.html.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-122.shtml

**Pull request merged**
