### PR TITLE
Fix demos for qglviewer 2.7.0

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Rework for everything that uses qglviewer so it is not broken by the version 2.7.0.
## Release Management

* Affected package(s): All 3D Demos

### CODE REVIEW

**Comment by lrineau** [comment]
There is a conflict with `master`.

**Comment by maxGimeno** [comment]
Resolved

**Comment by lrineau** [comment]
Maxime, do you think the patch of this branch could be applied easily to CGAL-4.10?

**Comment by maxGimeno** [comment]
It mainly modifies demos we almost never touch, so I guess this should be easy.

**Comment by lrineau** [comment]
I ask because the issue #2223, is reported by a user against CGAL-4.10. Could you prepare a PR for the 4.10 branch?

**Comment by maxGimeno** [comment]
Ok

**Pull request merged**
