### PR TITLE
Mesh_3: add the manifold criterion

### PR DESCRIPTION
**Pull request by lrineau**
For the moment, as of CGAL-4.7, the manifold criterion of Mesh_3 is documented, but it is not implemented.

This pull-request implements it, when the sequential mode of Mesh_3 is used.

Drawbacks:
  - it will crash if it is used with the `Parallel_tag`,
  - it will crash if the protecting balls impose a non-manifold configuration on the c3t3.

<s>Maybe that is a regression, compared to CGAL-4.7. For the moment, when the ` facet_topology` parameter of `Mesh_criteria_3` is set to `CGAL::MANIFOLD`, it is ignored. After this PR, it can crash in certain cases (described above). I do not know if that is best that way, or if I should use a non-documented API, using for example another value of the enum, `CGAL::SECRET_MANIFOLD_CRITERION_THAT_CAN_CRASH`?</s>

### CODE REVIEW

**Comment by lrineau** [comment]
cc @afabri, @janetournois

**Comment by lrineau** [comment]
Update: there is no regression. The `MANIFOLD` value was not documented.

**Comment by lrineau** [comment]
5ca23a105a8eb25529cf500c73490679c4209529 adds the support in the "Polyhedron" demo.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-93

**Comment by sloriot** [comment]
New warnings for `Mesh_3` testsuite were introduced on windows.

**Comment by lrineau** [comment]
Maybe the commit https://github.com/lrineau/cgal/commit/25b2330fb00743f5392eca152407faaca8dd241f will manage to fix those warnings. But, without a way to check on Linux (`-Wconversion` detects too much), I cannot be sure.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-94

**Comment by sloriot** [comment]
`Mesh_3` testsuite is fully red but it might be the issue you already reported

**Comment by janetournois** [comment]
I just checked locally, there is no remaining conversion warnings on msvc2013.

**Comment by lrineau** [comment]
I can reproduce the bug with 2215bb94db9877e6cd10ee3f02d9f403d8c78665  (`cgal-dev/testsuite-Thursday`) but not with this branch. That suggests that the issue is triggered by the PR #549.

**Comment by lrineau** [comment]
On the other hand, #549 was tested in CGAL-4.8-Ic-93 successfully.

**Comment by lrineau** [comment]
I found out. My commit cgal-dev@25b2330fb00743f5392eca152407faaca8dd241f was wrong.

**Comment by lrineau** [comment]
Conflicts are fixed again. Merged in [CGAL-4.8-Ic-95][i].

[i]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-95.shtml

**Comment by lrineau** [comment]
Merged in [CGAL-4.8-Ic-95][i].

[i]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-95.shtml

**Comment by sloriot** [comment]
`Mesh_3` testsuite has new warnings and maybe a memory leak detected with visual

**Comment by lrineau** [comment]
I hope the commit https://github.com/lrineau/cgal/commit/f0ed1101c091dfb901a84fb3199c8035fed735e5 will fix the warnings. At least there was no warnings on my machine, with the flags `-O3 -DCGAL_NDEBUG -Wall -Wextra`, with g++-4.9.

**Comment by lrineau** [comment]
Commit https://github.com/lrineau/cgal/commit/f5cbf206b8788a918051066790649b7804afd71a fixes the merge issues.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-97

**Pull request merged**
