### PR TITLE
Segment_2/Segment_3 midpoint()

### PR DESCRIPTION
**Pull request by Dig-Doug**
## Summary of Changes

Adds a CGAL::midpoint() implementation for segments.

In the documentation:   [function ](https://cgal.github.io/5545/v0/Kernel_23/group__midpoint__grp.html) and [concept](https://cgal.github.io/5545/v0/Kernel_23/classKernel_1_1ConstructMidpoint__3.html)

## Release Management

* Affected package(s): Kernel_23
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): n/a
* License and copyright ownership: CLA signed

### CODE REVIEW

**Comment by afabri** [comment]
Hello @Dig-Doug, I just made the code more complex, or call it more CGAL compliant. The free function has to call the functor which does the real work.    We are in the lucky situation where the functor already existed.

**Comment by Dig-Doug** [comment]
No problem, please let me know if you need anything else from me.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-158.shtml

**Pull request merged**
