### PR TITLE
Qt5 support, GSoC 2014

### PR DESCRIPTION
**Pull request by maxGimeno**
Feature initially added by Aurélien Vialon in 2014, and then modified in 2015 by Maxime Gimeno. The feature impacts all the graphical demos of CGAL in all packages.

> Qt5 is now available for a while and it is maybe time to CGAL to be port to this new version of the API. The aim of this small feature is to replace Qt4 by Qt5 for CGAL and all the demonstrations, and to upgrade the OpenGL related code to a more recent and efficient version. 

See more at : https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Qt5_support

#### Edit: Progression of the integration, by the release management team
TODOs filled by Sébastien in https://github.com/CGAL/cgal/pull/154#issuecomment-119257680 :
  - [x] <s>`Maintenance/infrastructure/*`</s> ( @lrineau ? ) **Edit:** will not be fixed. See https://github.com/CGAL/cgal/pull/154#issuecomment-119952719
  - [x] <s>`Maintenance/deb/*`</s> ( @joachim-reichel ? ) **Edit:** see https://github.com/CGAL/cgal/pull/154#issuecomment-119336421
  - [ ] 
`Linear_cell_complex/benchmark/Linear_cell_complex_3/cmake/ACGCommon.cmake`, `Linear_cell_complex/examples/Linear_cell_complex/CMakeLCCViewerVtk.inc`, `Linear_cell_complex/examples/Linear_cell_complex/CMakeLists.txt` `Linear_cell_complex/examples/Linear_cell_complex/CMakeLCCViewerQt.inc` ( @gdamiand  ?)
  - [x] `CGAL_ImageIO/demo/CGALimageIO/CMakeLists.txt`(shall we simply remove it?) **Edit:** fixed, see https://github.com/CGAL/cgal/pull/154#issuecomment-119897222
  - [ ] Testsuite:  `Maintenance/test_handling/to_zipped_format` `Maintenance/test_handling/create_testresult_page` `Testsuite/test/collect_cgal_testresults_from_cmake`
  - [ ] `Installation/test/Installation/CMakeLists.txt` (**Edit:** could be ignored, see https://github.com/CGAL/cgal/pull/154#issuecomment-121305710)
  - [ ] Scripts: `Installation/dont_submit`, `Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgramQt4.cmake`, `Scripts/scripts/cgal_create_CMakeLists`, `Scripts/scripts/cgal_create_cmake_script`, `Scripts/developer_scripts/check_library_uses_no_gpl_files`, `Scripts/developer_scripts/cgal_generate_cmake_script.cmake` (here I think we can simply drop the generation of QT specific instructions)

Other TODOs:
  - [x] remove files `Polyhedron/demo/Polyhedron/gl3splat.*`, see https://github.com/CGAL/cgal/pull/154#issuecomment-119219731. Fixed by 58c8bfd3283bc51a7e9c8ae814b6b500920cab0d.
  - [x] We must fix the CMake warnings when Qt5 is not there, see https://github.com/CGAL/cgal/pull/154#issuecomment-119890406 . **Edit:** addressed by PR #171 
  - [ ] Install Qt5 on our MacOS X test machine. **Edit:** started. See commit 2bb20ce40c54367e8819f99bba2804c45d5cc5f1.
  - [x] Fix the skeleton plugin in the Polyhedron demo (see https://github.com/CGAL/cgal/pull/154#issuecomment-120064957) **Edit:** Fixed by e36ae96, 62a4255 and 3498e2e
     - [x] One action creates a polyline item, but it is not shown (one has to modify it so that it is displayed)
     - [x] The other action creates an empty dock widget, or even several of them, if the action is used several times.
  -  [x] We must change the minimal version of CMake to 2.8.11 (https://github.com/CGAL/cgal/pull/154#issuecomment-120394354) **Edit:** fixed by f9917c4

### CODE REVIEW

**Comment by lrineau** [comment]
Tested in [CGAL-4.7-Ic-68](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-68.shtml).

**Comment by lrineau** [comment]
Good
----
:white_check_mark: The script `./Scripts/developer_scripts/test_merge_of_branch` does not report any error.
:white_check_mark: The compressed weight of the branch is evaluated to 850KB. Knowing the list of modifications, I think that is fine.

Need announcement in `changes.html`
-----------------------------------
:x: The branch should modify `Installation/changes.html`. What is [written in the small feature page is not sufficient][smallfeature], in my opinion:

[smallfeature]: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Qt5_support#changes.html

> **Qt Version**
>
>    Qt5 is now mandatory to be able to compile CGAL and its demos, instead of Qt4.

The change for users is important, and should be properly announced. We'll discuss that later.

I have merged in `integration` for testing tonight in [CGAL-4.7-Ic-73][Ic-73].

[Ic-73]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-73.shtml

**Comment by lrineau** [comment]
I had to revert the merge into `integration`. Too many conflicts with the other pull-requests, and for some of them we have to test them quickly before the authors go on vacation.

**Comment by sloriot** [comment]
It seems the cmake is not shipping FindQt5.cmake nor config files. We should use a trick similar as the one described [here](http://stackoverflow.com/questions/15706318/check-if-cmake-module-exists).

**Comment by lrineau** [comment]
@sloriot: Qt5 uses the `CONFIG` mode of the CMake `find_package` command (see [the documentation of `find_package`, second block][doc-cmake]).

[doc-cmake]: http://www.cmake.org/cmake/help/v3.0/command/find_package.html

There is no official `FindQt5.cmake` module, on purpose. When Qt5 development files are installed, there is a file `Qt5Config.cmake` somewhere on the system, and CMake searches for it.

Not that CGAL is also using the config mode, with its file `CGALConfig.cmake`.

**Comment by lrineau** [comment]
Todo before a merge in `master`:
  - :x: scan the documentation and change all occurrences of Qt4 to Qt5 (and adapt the text of the documentation if needed).

**Comment by lrineau** [comment]
TODO:
  - :x: remove files `Polyhedron/demo/Polyhedron/gl3splat.*`

**Comment by sloriot** [comment]
I've done a cleaning pass to remove mentions of Qt4.
What remains to be done:
- :x: `Maintenance/infrastructure/*` ( @lrineau ? )
- :x: `Maintenance/deb/*` ( @joachim-reichel ? )
- :x: 
`Linear_cell_complex/benchmark/Linear_cell_complex_3/cmake/ACGCommon.cmake`, `Linear_cell_complex/examples/Linear_cell_complex/CMakeLCCViewerVtk.inc`, `Linear_cell_complex/examples/Linear_cell_complex/CMakeLists.txt` `Linear_cell_complex/examples/Linear_cell_complex/CMakeLCCViewerQt.inc` ( @gdamiand  ?)
- :x: `CGAL_ImageIO/demo/CGALimageIO/CMakeLists.txt`(shall we simply remove it?)
- :x: Testsuite:  `Maintenance/test_handling/to_zipped_format` `Maintenance/test_handling/create_testresult_page` `Testsuite/test/collect_cgal_testresults_from_cmake`
- :x: `Installation/test/Installation/CMakeLists.txt`
- :x: Scripts: `Installation/dont_submit`, `Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgramQt4.cmake`, `Scripts/scripts/cgal_create_CMakeLists`, `Scripts/scripts/cgal_create_cmake_script`, `Scripts/developer_scripts/check_library_uses_no_gpl_files`, `Scripts/developer_scripts/cgal_generate_cmake_script.cmake` (here I think we can simply drop the generation of QT specific instructions)

**Comment by joachim-reichel** [comment]
Hi,

On 07/07/2015 06:17 PM, Sebastien Loriot wrote:
> I've done a cleaning pass to remove mentions of Qt4.
> What remains to be done:
> 
>   * :x: |Maintenance/deb/*| ( @joachim-reichel
>     <https://github.com/joachim-reichel> ? )

this should not block the use of Qt5. These file are just a backup of the meta
data of the Debian packages. Usually, I update this copy after the release (but
haven't done that for quite a while).

Joachim

**Comment by lrineau** [comment]
:x: We must fix the CMake warnings when Qt5 is not there: add `QUIET`. I think that we should also display a message (not a warning) when Qt5 is not found, quite similar to the message displayed by CMake itself:
```
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
 ```

**Comment by sloriot** [comment]
@joachim-reichel OK let's keep them as is until the release is out.

**Comment by lrineau** [comment]
As for the CGAL/VTK/Qt demo in `CGAL_ImageIO/demo/CGALimageIO/`, that code does not use `CGAL_Qt4` but only a plain Qt4 and VTK configured with the Qt support. Actually, I think that maybe we can write the `CMakeLists.txt` so that Qt4 is not mentioned at all, but only QVTK.

**Comment by lrineau** [comment]
@sloriot: for `Maintenance/infrastructure/*`, the support of Qt4 will remain, at least for a while. We want to be able to test former CGAL releases, that have only the support for Qt4.

**Comment by lrineau** [comment]
:x: Fix the skeleton plugin in the Polyhedron demo

**Comment by lrineau** [comment]
Please all, have a look [the list of TODOs, in the first comment](https://github.com/CGAL/cgal/pull/154#issue-92400578).

**Comment by lrineau** [comment]
:x: We must change the minimal version of CMake to 2.8.11. I'll do it...

[To go back to the list of TODOs, click here.](https://github.com/CGAL/cgal/pull/154#issue-92400578)

**Comment by lrineau** [comment]
In my opinion `Installation/test/Installation/CMakeLists.txt` could stay with its reference to `CGAL_Qt4`. It is here to check that the `WITH_CGAL_<lib>` options are consistent with the reality.

[To go back to the list of TODOs, click here.](https://github.com/CGAL/cgal/pull/154#issue-92400578)

**Comment by lrineau** [comment]
Today is the day of the `alpha1` release. For that reason I will merge that pull-request in `master` *today* even if there are still items in the TODO list. The branch `cgal-public-dev/CGAL-Qt5_support-GF` will go on, and fix the issues.

**Pull request merged**
