### PR TITLE
Header-only: consider CGAL as an imported target (if CMake>=3.11)

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Fix the issue https://github.com/cdcseacave/openMVS/issues/425.

When CGAL is used header-only, from another project, the `CGALConfig.cmake` creates an interface library. With this change, it will be an *imported* interface library.

Unfortunately, that feature required CMake version 3.11 or later (available only since March 28, 2018).

## Release Management

* Affected package(s): Installation
* Issue(s) solved (if any): fix cdcseacave/openMVS/issues/425
* License and copyright ownership: na

* This PR is based on CGAL-4.13.1.

### CODE REVIEW

**Comment by cdcseacave** [comment]
I can confirm that this fixes OpenMVS

**Comment by cdcseacave** [comment]
@lrineau can u pls merge this and update the vcpkg port? many libraries depend on this patch to pass compilation tests

**Comment by lrineau** [comment]
[**@cdcseacave**](https://github.com/cdcseacave) commented on [May 15, 2019, 2:42 PM GMT+2](https://github.com/CGAL/cgal/pull/3922#issuecomment-492638009 "2019-05-15T12:42:14Z - Replied by Github Reply Comments"):
> @lrineau can u pls merge this and update the vcpkg port? many libraries depend on this patch to pass compilation tests

I cannot before it is tested successfully by our testsuite process, on all our supported platforms. At best it could be tomorrow afternoon (Paris time).

@maxGimeno can you please merge this in `integration`?

**Comment by cenit** [comment]
wonderful. I was working on a vcpkg port of openmvs and got stuck on this CGAL problem. I am also waiting for this PR to succeed :)

**Comment by maxGimeno** [comment]
Seems ok in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-39.shtml

**Pull request merged**
