### PR TITLE
Fix for compilation conflict on macOS.

### PR DESCRIPTION
**Pull request by sakrist**
## Summary of Changes

Error was appearing in case Surface_mesh.h was included in *.mm file.

OS: MacOS

### CODE REVIEW

**Comment by sloriot** [comment]
Note that it might be better to apply the patch over the branch `releases/CGAL-4.10-branch` and change the PR base if you want it to be included in a potentiel 4.10.2 release.

**Comment by lrineau** [comment]
> Note that it might be better to apply the patch over the branch `releases/CGAL-4.10-branch` and change the PR base if you want it to be included in a potentiel 4.10.2 release.

If you apply the patch to `releases/CGAL-4.10-branch`, it will also be published with CGAL-4.11.1, in a few months.

**Comment by sakrist** [comment]
I made changes to my local build, so I'm ok for now. But if you want/need it I can make separate PR to `releases/CGAL-4.10-branch`.

**Comment by lrineau** [comment]
I have merged the PR in `master`, and cherry-picked it in release branches as well.

**Pull request merged**
