### PR TITLE
Optimal Transport Reconstruction: Fix memory leak

### LINKED ISSUE #7132: Optimal Transport: memory leak
## Issue Details

Reported by the address sanitizer in this [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-139/Optimal_transportation_reconstruction_2_Examples/TestReport_lrineau_Fedora-Release.gz).

I can reproduce the "Premature ending"  by adding `CGAL::get_default_random() = CGAL::Random(1671586136);` in `main()`.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Keep the samples in a `std::vector<Sample>`  to avoid a memory leak. I guess that one can still have an inconsistent data structure after a failed `run()` that led to the leak.

## Release Management

* Affected package(s): Optimal_transport_reconstruction
* Issue(s) solved (if any): fix #0000, fix #7132

### CODE REVIEW

**Comment by sloriot** [comment]
Demo has some compilation issues (CGAL-5.6-Ic-144). See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-144/Optimal_transportation_reconstruction_2_Demo/TestReport_lrineau_ArchLinux.gz) for example.

There is also a warning:
```
/Users/magritte/cgal_root/CGAL-5.6-Ic-144/include/CGAL/Optimal_transportation_reconstruction_2.h:381:22: warning: comparison of integers of different signs: 'int' and 'std::__1::vector<int>::size_type' (aka 'unsigned long') [-Wsign-compare] 
```

**Comment by sloriot** [comment]
Could this PR be responsible for this [error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-153/Optimal_transportation_reconstruction_2/TestReport_lrineau_Fedora-32-Release.gz)

**Comment by afabri** [comment]
> Could this PR be responsible for this [error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-153/Optimal_transportation_reconstruction_2/TestReport_lrineau_Fedora-32-Release.gz)

The error is an assertion about a difference in one edge in the output:
```
- ProgramOutput.test_reconstruction_until.Fedora-32-Release
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1673365778
STATS
# vertices : 9
# isolated vertices : 0
# triangles: 20
# edges: 36
# solid: 9
# ghost: 23
Isolated_points: 0
Edges: 9
test_reconstruction_until: /home/cgal_tester/build/src/cmake/platforms/Fedora-32-Release/test/Optimal_transportation_reconstruction_2/test_reconstruction_until.cpp:43: int main(): Assertion `edges.size() == 8' failed.
```
It would probably make sense to run it locally on the architecture where we have a problem and have a look at the result visually, as I could well imagine that both outputs are valid. The algorithm does vertex relocations, so it might well depend on numerics.  What do you think @palliez

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-156

**Pull request merged**
