### PR TITLE
Fixed Eigen3 3.4.90 deprecation warnings

### PR DESCRIPTION
**Pull request by soesau**
## Summary of Changes

Moved parameters from compute method to class template.

## Release Management

* Affected package(s): Surface_mesh_deformation

### CODE REVIEW

**Comment by sloriot** [comment]
Did you check that the change works with the first supported version of Eigen? 
See [here](https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyEigen). If needed the minimal version could be updated but then cmake scripts will need an update too.

I guess this branch should be based on cgal/5.4-x-branch. See [here](https://github.com/CGAL/cgal/wiki/Source-Code-Management-with-Git#rebase-an-existing-bug-fix-branch) for how to do it.

**Comment by soesau** [comment]
I compiled the examples and tests with both versions, i.e., 3.4.0 and 3.4.90.

**Comment by sloriot** [comment]
Actually 3.3.4 is the minimal version that we are testing. We should update the requirements but then the PR can only target 5.5. @lrineau do you agree?

**Comment by soesau** [comment]
I made a mistake. I compiled the tests, but I did not execute them.
The options for solving the SVD were moved into the template parameter with version 3.4.90. This only works for 3.4.90, but not for 3.4.0 and before. Thus, we can suppress the warnings by using
#ifdef EIGEN_VERSION_AT_LEAST(3,4,90)...

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-90

**Pull request merged**
