### PR TITLE
When opening a binary ply file  we have to use std::ios_base::binary

### PR DESCRIPTION
**Pull request by afabri**
@sgiraudot  We have to check that with an Ascii file

### CODE REVIEW

**Comment by sgiraudot** [comment]
I tested with an ASCII file and it works (although everything used to work on GNU/Linux - binary included - without this fix).

I find it weird that this error did not arise in the testsuite: we _do_ test the reading of a binary PLY file (in `test/Point_set_processing_3/read_test.cpp` with file `data/read_test/simple.ply`) and it apparently works on every platform...
Should we add the same tag to the file opening of `read_test.cpp`?

**Comment by lrineau** [comment]
On Linux the binary mode has no effect. That is different on Windows, where the end-of-line is composed of several characters. You must test the ascii file on Windows. @afabri

**Comment by afabri** [comment]
tested on Windows. It works.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-111

**Comment by sgiraudot** [comment]
There is no error and no warning related to this PR in the [testsuite](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-111.shtml) (the only warnings are the usual boost ones).

**Pull request merged**
