### PR TITLE
CDT2: Throw on constraint intersections that do not require constructions

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

CDT2 with the no intersection tag says it throws on intersecting constraints, except for common extremities. In practice, it did not throw if there was an intersection that did not require a construction (overlapping segments, segment with an extremity on the interior of another segment).

This PR changes the behavior so it also throws in these cases.

Two new tags introduced, see small feature.

## Release Management

* Affected package(s): `Triangulation_2`
* Issue(s) solved (if any): -
* Small feature: [Replace_CGAL::No_intersection_tag](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Replace_CGAL::No_intersection_tag) -- **pre-approval date:** 2019/10/01

### CODE REVIEW

**Comment by sloriot** [comment]
I think we should also introduce the new tag `No_construction_needed_blabla_tag`. Simply making it inheriting from `No_intersection_tag` should be enough to have everything working directly. That way the previous behaviour is still available.

**Comment by MaelRL** [comment]
Sounds good, but it should probably be done in another PR since it will be a small feature.

**Comment by maxGimeno** [comment]
Tests are now failing all over PMP : 
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-117.shtml#Polygon_mesh_processing

**Comment by MaelRL** [comment]
This is more like an existing problem with `PMP`. Corefinement adds constraints multiple times:
- Example of border-border constraint being added multiple times: `data_coref/elephant.off` and `data_coref/sphere.off`. We loop over the border and add from one side and from another. Should https://github.com/CGAL/cgal/commit/f68a2a4dff7e10a72a3d40b681b6c371e742d099 be reverted?
- Example of the same constraint being inserted multiple (case of coplanar faces and internal nodes): `data_coref/P7.off` and `data_coref/Q7.off`.

**Comment by MaelRL** [comment]
I have added the "intersection without constructions" tag directly in that PR, but left it undocumented.

**Comment by lrineau** [comment]
What is the status of this PR? Does it still fail with PMP?

I am trying to prepare CGAL-4.13.2, and other releases. That is why I have a look at pull-requests.

**Comment by MaelRL** [comment]
Awaiting a change in PMP by @sloriot (either removing duplicates or changing the CDT tag).

**Comment by sloriot** [comment]
I'm still puzzled about what this PR implies to our users. This is a breaking change IMO.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-1.shtml#Triangulation_2

IIUC the new checks trigger warnings on many platforms.

**Comment by maxGimeno** [comment]
It is still here : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-10.shtml#Triangulation_2

**Comment by maxGimeno** [comment]
Warnings on some platforms : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-12.shtml#Triangulation_2

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-18.shtml

**Comment by lrineau** [comment]
This PR is ready to be merged, once the `CHANGES.md` is updated.

**Comment by afabri** [comment]
Didn't we say at one point to put the text for changes into the discussion for the PR, so that it can be added by you right before the merge without conflicts ?

**Comment by lrineau** [comment]
> Didn't we say at one point to put the text for changes into the discussion for the PR, so that it can be added by you right before the merge without conflicts ?

We did discussed about that, but nobody has yet proposed any implementation. So we stay with the current process, until we have a better one.

**Comment by MaelRL** [comment]
The text that will go into CHANGES.md is already on the small feature page so it should be already available. But it's probably faster to resolve conflicts than copy-pasting, commiting, etc. I was just waiting on these PRs to reduce conflicts, but maybe it wasn't such a good idea, sorry.

Anyway, done in 020aa0a.

**Pull request merged**
