### PR TITLE
Installation - fix `CGAL_ITK_support`

### LINKED ISSUE #7855: Issue with CGAL ITK_Support
### Discussed in https://github.com/CGAL/cgal/discussions/7854

<div type='discussions-op-text'>

<sup>Originally posted by **oarcelus** November 10, 2023</sup>
I am trying to build a CGAL program that uses ITK.

I downloaded and setup everything with vcpkg for x64. When trying to configure my Cmake folder the following error appears.

```
CMake Error at C:/dev/vcpkg/installed/x64-windows/share/cgal/CGAL_ITK_support.cmake:4 (set_target_properties):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  CMakeLists.txt:52 (include)
```

Does this mean that I need to install ITK in ´debug´ or ´general´ mode?</div>

----

That is a bug from about file `CGAL_ITK_support.cmake`. That file should use the imported targets created by `ITKConfig.cmake`.

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR modifies `CGAL_ITK_support.cmake`, so that it uses imported targets from `ITKConfig.cmake`.

Note that for now
- the line `include(${ITK_USE_FILE})` is still needed
- the module `ITKThresholding` does not have a lib, so we do not link the libraries and only include the files

## Release Management

* Affected package(s): Installation, and the CMakeLists of Mesh_3
* Issue(s) solved (if any): fix #7855
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
The error in the CI is the following
```
/usr/bin/ld: cannot find -lITKSmoothing: No such file or directory
/usr/bin/ld: cannot find -lITKImageIntensity: No such file or directory
```

@SaillantNicolas can you please check how ITK is installed on the CI machine, and if these libs are really not available?
It is working with my windows setup.

cc @lrineau

**Comment by lrineau** [comment]
> The error in the CI is the following
> 
> ```
> /usr/bin/ld: cannot find -lITKSmoothing: No such file or directory
> /usr/bin/ld: cannot find -lITKImageIntensity: No such file or directory
> ```
> 
> @SaillantNicolas can you please check how ITK is installed on the CI machine, and if these libs are really not available? It is working with my windows setup.
> 
> cc @lrineau

I think I fixed that with the three commits https://github.com/CGAL/cgal/pull/7858/files/0b73361226b11e06520c32970178e016cc0d200d..0a9392c778ab7e485603ed0658e1f679b0be44bb.

I used https://github.com/nektos/act to first verify locally (using act's Docker images), to create cb5bd56ef0dd9161096346f185b2c696a5b30bd2. Then there was an issue with Github's version of Ubuntu. Fixed in 0a9392c778ab7e485603ed0658e1f679b0be44bb.

@SaillantNicolas You should install https://github.com/nektos/act on your machine. That is a very useful tool to test Github workflows on your local machine.

**Comment by lrineau** [comment]
... Actually it was fixed by commit 74896b99c08a79ab6721675c504c9f45e6612c2e: install ITK 5 instead of ITK 4.

**Review by lrineau — APPROVED** [review]

**Comment by janetournois** [comment]
In the testsuite, 2 platforms are failing because of this PR (Ubuntu-Latest-NO_DEPRECATED_CODE and Ubuntu-GCC_master_CXX20-Release), complaining about
```
/usr/bin/ld: cannot find -lITKSmoothing: No such file or directory
/usr/bin/ld: cannot find -lITKImageIntensity: No such file or directory
```
and with lots of warnings from ITK-4.13.

Is it possible to update those 2 platforms to ITK-5, and add the needed libraries please? @sloriot

**Comment by lrineau** [comment]
> In the testsuite [CGAL-6.0-Ic-112](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-112/Mesh_3_Examples/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz), 2 platforms are failing because of this PR (Ubuntu-Latest-NO_DEPRECATED_CODE and Ubuntu-GCC_master_CXX20-Release), complaining about
> 
> ```
> /usr/bin/ld: cannot find -lITKSmoothing: No such file or directory
> /usr/bin/ld: cannot find -lITKImageIntensity: No such file or directory
> ```
> 
> and with lots of warnings from ITK-4.13.
> 
> Is it possible to update those 2 platforms to ITK-5, and add the needed libraries please? @sloriot

Actually, there are Linux distributions (including the one I use: Fedora 39) that are currently stuck with ITK version 4.13, and I would like to stay compatible with that version of ITK. I will modify this PR accordingly.

**Comment by lrineau** [comment]
In commit 9262c6a8b681d35903e1eb9e5126012542eb91b7 I have re-add a file `CGAL_ITK_support.cmake` and an imported target `CGAL::ITK_support`. That imported target uses imported targets from ITK, and should be compatible with both ITK versions 4.13 and 5.x.

**Comment by afabri** [comment]
Errors in the [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-114/Mesh_3_Examples/TestReport_gimeno_Ubuntu-Latest-NO_DEPRECATED_CODE.gz)

**Comment by lrineau** [comment]
> Errors in the [testsuite ](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-114/Mesh_3_Examples/TestReport_gimeno_Ubuntu-Latest-NO_DEPRECATED_CODE.gz)

The last merged commit for that testsuite was not the last one (9262c6a9) but the one before (74896b99). Probably my push arrived too late yesterday.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-116

**Pull request merged**
