### PR TITLE
Pmp psp fixes for release

### PR DESCRIPTION
**Pull request by sloriot**
Three fixes in PMP and PSP for issues introduced between 4.11 and 4.12-beta2.

### CODE REVIEW

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-222/logs_master/Point_set_processing_3.log
> /home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-222/include/CGAL/structure_point_set.h:1646: warning: More #endif's than #if's found.

I think the `#if #endif`s are right, but there is something strange about the `\cond \endcond`s, in that file.

**Comment by sgiraudot** [comment]
Yes, Sebastien added `\cond SKIP_IN_MANUEL` /  `\endcond` around a function that is in a section that's already surrounded by these tags (which apparently Doxygen doesn't like).

(Apart from that, the PR looks good to me.)

**Comment by lrineau** [comment]
Plus a Travis error:
```
  /home/travis/build/CGAL/cgal/Installation/../Point_set_processing_3/include/CGAL/structure_point_set.h:1597:22:
  error: use of undeclared identifier 'Shape_detection_3'

                       Shape_detection_3::Efficient_RANSAC<Traits>&
                       ^
```
https://travis-ci.org/CGAL/cgal/jobs/364672140

**Comment by lrineau** [comment]
@sloriot @sgiraudot If you handle that issue, please re-merged into `integration`.

**Comment by sloriot** [comment]
Travis is happy now.

**Pull request merged**
