### PR TITLE
Bounding Volumes:  Fix and improve the documentation

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

* [x] `OptimisationTraitsD`  and its models had not been replaced everywhere.
* [x] Improve the User Manual. If `Min_sphere_d`  is only faster for homogeneous coordinates the example should reflect that. And we should have an example for `Min_sphere_of_spheres_d`  if that is faster and even works for floating point arithmetic.

## Release Management

* Affected package(s): Bounding Volumes
* Issue(s) solved (if any):  cgal-discuss
* License and copyright ownership:  unchanged ETHZ

### CODE REVIEW

**Comment by lrineau** [comment]
This PR has doxygen errors:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.2-Ic-5/logs1/Bounding_volumes.log
```
/home/cgal-testsuite/cgal_doc_build/CGAL-5.2-Ic-5/doc/Bounding_volumes/examples.txt:17: Warning: included file Min_sphere_d/min_sphere_homogeneous_d.cpp is not found. Check your EXAMPLE_PATH
citelist:79: Warning: Unexpected new line character
/home/cgal-testsuite/cgal_doc_build/CGAL-5.2-Ic-5/doc/Bounding_volumes/CGAL/Min_sphere_d.h:66: Warning: included file Min_sphere_d/min_sphere_homogeneous_d.cpp is not found. Check your EXAMPLE_PATH
```

**Comment by lrineau** [comment]
And warnings on all platforms:
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-5.shtml#Min_sphere_d_Examples

**Comment by maxGimeno** [comment]
Warnings: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-15.shtml#Min_sphere_d_Examples

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-18.shtml

**Pull request merged**
