### PR TITLE
Fix implementation of AABB_traits::Closest_point

### LINKED ISSUE #260: Wrong functor required/used
The AABBGeomTraits require the functor [Compute_closest_point_3](http://doc.cgal.org/latest/AABB_tree/classAABBGeomTraits.html#a97e587bad84dcd1e90d00fb18a134762), but this signature is never used in `AABB_tree` code.

The class `AABB_traits`  provides a functor `Closest_point` which calls the free function `internal::nearest_point_3` which seems to be used instead. Note that even if this functor is renamed it is still in the wrong class (should be in the geomtraits).

### LINKED ISSUE #1341: Move Functors to the Kernel
The `AABB_traits.h` file contains implementations of the functors
- ~~Compute_closest_point_3~~ `Construct_closest_point_3`
- `Compare_distance`

They should both be moved to the Kernel

This issue is related to #260

### PR DESCRIPTION
**Pull request by sloriot**
The problem reported by #260 was the requirement of having `Compute_closest_point_3` in `AABBGeomTraits` while it was not used. In this PR, we turn this requirement into having `Construct_projected_point_3` with operators for triangles and segments, and `Compare_squared_distance_3`. These two functors are now used it in the implementation of `Closest_point` in `AABB_traits`. Note that the current implementation might be slower as we no longer take advantage of the `bound` parameter to quit earlier the computation of the closest point.

The Kernel functor `Construct_projected_point_3` has been updated so that it provides two additional operators (one for segments and one for triangles).

Replaces #1350 
Fixes #260
Fixes #1341

### CODE REVIEW

**Comment by sloriot** [comment]
@afabri, @janetournois  do you agree this PR fixes the aforementioned issues?

**Comment by lrineau** [comment]
I have not had a look for a while, but if I remember well the changes are good.

**Comment by afabri** [comment]
I do not agree with adding two files to `Kernel_23/include/CGAL/Kernel`.  The functions in the files should be dispatched  to global_functions_3.h and global_functions_internal_3.h, and there might be code that goes into functors.

**Comment by sloriot** [comment]
The code is used in Kernel functors so I don't see it going  in `global_functions_internal_3.h` that contains only wrapping code. The code is used by both Cartesian and Homogeneous kernels so it cannot be put in these packages like it is done with other projection code. I can move the file into `internal` instead of Kernel or even merge the file if you want.

**Comment by afabri** [comment]
Shouldn't we at least move it into global_functions_3.h ?

**Comment by sloriot** [comment]
Moved into `Kernel/function_objects.h`

**Pull request merged**
