### PR TITLE
Installation - matching bug is fixed in MSVC >= 2015 (target - CGAL-5.0)

### LINKED ISSUE #5021: CGAL_CFG_MATCHING_BUG is not needed by MSVC >= 2015
## Issue Details

I commented all the `#define` of `Installation\include\CGAL\MSVC_compiler_config.h` and compiled the tests and examples of Mesh_3. It turns out that the macros defined to avoid the "matching bug" are not needed anymore with MSVC 2019 (version 16).
I tried a few examples with the compilers of MSVC 2015, 2017 and 2019 and they behave similarly (no error).

Should we start thinking of removing them?

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows
* Compiler: MSVC >= 2015
* Release or debug mode: both
* CGAL version:  releases/CGAL-5.0-branch

### PR DESCRIPTION
**Pull request by janetournois**
This PR is a duplicate from #5024 that should have targeted the 5.0-branch.

## Summary of Changes

MSVC 2015 and later versions do not have the "matching bug" worked around by CGAL macros `CGAL_CFG_MATCHING_BUG_n`.

This PR removes the code that was necessary with previous versions of MSVC.

Note that since CGAL supports C++14, it does not support MSVC 2013 and earlier anymore.

## Release Management

* Affected package(s): Installation, Arrangement_on_surface_2, Circular_kernel_2, Circular_kernel_3, Filtered_kernel, Kernel_23, Periodic_2_triangulation_2, Periodic_3_triangulation_3, Periodic_4_hyperbolic_triangulation_2, STL_Extension, Triangulation_3

* Issue(s) solved (if any): fix #5021
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by lrineau** [comment]
Are we sure we want to take the risk to disrupt CGAL-5.0.x and CGAL-5.1.x? That PR is only a sort of "cleaning": it does not solve actual bugs for users.. but may introduce new bugs we do not see.

**Comment by janetournois** [comment]
I understand your point
I created this PR because there was a conflict with #5022...

**Comment by janetournois** [comment]
> Are we sure we want to take the risk to disrupt CGAL-5.0.x and CGAL-5.1.x? That PR is only a sort of "cleaning": it does not solve actual bugs for users.. but may introduce new bugs we do not see.

We should make a decision about that.
The way #5022 (fix compilation of `intersection(Plane_3, Plane_3, Plane_3)` for MSVC) is implemented and tested depends on it.

3 options :
1. leave as is, and introduce the risk of introducing bugs in 5.0 and 5.1
2. base #5022 on `master`, and target 5.2 for both PRs. Imho it's a pity because it is a real bug fix.
3. revert my latest changes, i.e. base this branch on `master`, the bug fix of #5022 on 5.0, and fix merge conflicts manually in `integration` and the release branche(s)

**Comment by lrineau** [comment]
> 3 options :
> 
>     1. leave as is, and introduce the risk of introducing bugs in 5.0 and 5.1
> 
>     2. base #5022 on `master`, and target 5.2 for both PRs. Imho it's a pity because it is a real bug fix.
> 
>     3. revert my latest changes, i.e. base this branch on `master`, the bug fix of #5022 on 5.0, and fix merge conflicts manually in `integration` and the release branche(s)

I think the third option is the best. But maybe others disagree. Let's see if someone else has an opinion.

**Comment by maxGimeno** [comment]
I didn't think it would impact so many files to rebase the cleaning on 5.0. Tt would probably be easier to just fix conflicts in integration...

**Comment by janetournois** [comment]
Ok, so I am closing this PR and reverting the other one

**Pull request closed without merging**
