### PR TITLE
Polyhedron demo: Automatically decide between selection_io_plugin or selection_io_sm_plugin

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

With this PR, static functions to access the scene and the mainwindow are added.
It is used to automatically decide if the selection_io_plugin or the selection_io_sm_plugin should be used.

### CODE REVIEW

**Comment by lrineau** [comment]
That patch seems really ugly, because it breaks the separation between the application and the plugin: with this patch, there would be a piece of code in the `MainWindow` that is specific to two plugins. Could not it be fixed in the `canSave` function of the two plugins?!

**Comment by maxGimeno** [comment]
You mean the canLoad() function. Maybe.

**Comment by maxGimeno** [comment]
You need access to the scene for that, which you don't have in an IO plugin, as they don't have an init() function. So the plugin must be turned into a Polyhedron_demo_plugin_interface, which I know you don't like. What's the better option ?

**Comment by lrineau** [comment]
I think it is time to merge into `master` the static accessor to the scene...

**Comment by maxGimeno** [comment]
That's fine by me.

**Comment by lrineau** [comment]
There is still a license issue in Three:
https://travis-ci.org/CGAL/cgal/jobs/388148748
```
.. Test merging of the branch "HEAD"...
Already up to date.
HEAD detached at FETCH_HEAD
nothing to commit, working tree clean
.. Testing permissions...
.. Testing licenses...
=> There are modifications in licenses:
 M Three/package_info/Three/license.txt
(aborting the merge now)
fatal: There is no merge to abort (MERGE_HEAD missing).
```

You can run `./Scripts/developer_scripts/detect_packages_licenses` locally. It should not modify the license files. If you have doubts on the real reason, you can run `./Scripts/developer_scripts/licensecheck` on all the header files of Three.

**Comment by lrineau** [comment]
Does not compile. See https://github.com/CGAL/cgal/pull/3165#issuecomment-396651537.

**Pull request merged**
