### PR TITLE
Doc: Add a menu for version selection in the doc header.

### LINKED ISSUE #3018: doc.cgal.org: add Javascript code to allow changing the version of CGAL
## Issue Details

In all CMake documentation pages, like [this one](https://cmake.org/cmake/help/latest/command/string.html), there is a small menu that allows to change the version of CMake:

screenshot_20180412_172555

screenshot_20180412_172627

That would be really nice to have something similar for CGAL.

For CMake, the Javascript code is https://cmake.org/cmake/help/version_switch.js

Maxime, could you have a look at it and try to implement something similar, and easy to maintain?

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This adds a span menu that allows to select the version of the doc.

## Release Management

* Affected package(s):Documentation
* Issue(s) solved (if any): fix #3018
* Feature/Small Feature (if any):

### CODE REVIEW

**Comment by lrineau** [comment]
@CGAL/developers This PR has already been integrated in all the Doxygen versions of the documentation. It is easy to modify and maintain, because only one Javascript file has to be modified, for all CGAL versions of the documentation.

Have a look for example at https://doc.cgal.org/

screenshot_20180413_185247

screenshot_20180413_185317

Please comment.

**Comment by sloriot** [comment]
The menu is not here (yet?) for master.

**Comment by MoniqueTeillaud** [comment]
When you choose "master" in the menu, then the menu box disappears, and you cannot reach other versions, you are blocked in master. 
Is this a bug or a feature...?

**Comment by sloriot** [comment]
It will be updated next Monday when the doc of master will be rebuilt.

**Comment by lrineau** [comment]
[**@MoniqueTeillaud**](https://github.com/MoniqueTeillaud) commented on [Apr 25, 2018, 10:23 AM GMT+2](https://github.com/CGAL/cgal/pull/3023#issuecomment-384202619 "2018-04-25T08:23:06Z - Replied by Github Reply Comments"):
> indeed, this is solved. 
> There is one aspect that I find confusing: there are several versions in the menu, but it is not clear for a user which one is the "official" release. The term "latest" in the url is fine as long as there are no other choices, otherwise I don't find it so intuitive to guess what it actually means.

They are all official releases. What do you mean?

**Comment by sloriot** [comment]
What I think is confusing is latest vs master. Maybe having latest does not make sense as the latest release is obviously the one with a release number that is on the top of the list. So we can simply remove latest IMO. Would that solve the issue for you @MoniqueTeillaud ?

**Comment by sgiraudot** [comment]
I agree the naming is confusing. Also, `master` does not really mean anything to someone not involved in the project. Why not:

- `latest` -> `latest release`
- `master` -> `upcoming release (in development)`

It might be too verbose, but I think we should make it clear that `master` is a regularly evolving branch and that `latest` is the current stable release.

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Apr 25, 2018, 10:28 AM GMT+2](https://github.com/CGAL/cgal/pull/3023#issuecomment-384204502 "2018-04-25T08:28:57Z - Replied by Github Reply Comments"):
> What I think is confusing is latest vs master. Maybe having latest does not make sense as the latest release is obviously the one with a release number that is on the top of the list. So we can simply remove latest IMO. Would that solve the issue for you @MoniqueTeillaud ?

Well... currently 
  - `latest` is the same as `4.11.1`,
  - `4.12` is the documentation of the CGAL-4.12-beta2 release
  - `master` is even more recent.

So `latest` is far from being the latest version of the documentation. It is the latest non-beta release.

So now I understand what you mean.

**Comment by lrineau** [comment]
[**@sgiraudot**](https://github.com/sgiraudot) commented on [Apr 25, 2018, 10:31 AM GMT+2](https://github.com/CGAL/cgal/pull/3023#issuecomment-384205386 "2018-04-25T08:31:47Z - Replied by Github Reply Comments"):
> I agree the naming is confusing. Also, `master` does not really mean anything to someone not involved in the project. Why not:
> 
> - `latest` -> `latest release`
> - `master` -> `upcoming release (in development)`
> 
> It might be too verbose, but I think we should make it clear that `master` is a regularly evolving branch and that `latest` is the current stable release.

I agree. But what about the documentation of CGAL-4.12-beta2? How does it fit between "latest release" and "upcoming release"?

Note that we only have added something to navigate between the different versions of the documentation, without changing the names. Now there is probably rooms for improvements. What is nice is that we have put the definition of that menu at only one place², in one single Javascript file, so that it relatively easy to change it, and experiment.

²) Actually two places, because the `master` version has a different copy of it.

**Comment by sgiraudot** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [25 avr. 2018 à 10:41 UTC+2](https://github.com/CGAL/cgal/pull/3023#issuecomment-384208421 "2018-04-25T08:41:06Z - Replied by Github Reply Comments"):
> [**@sgiraudot**](https://github.com/sgiraudot) commented on [Apr 25, 2018, 10:31 AM GMT+2](https://github.com/CGAL/cgal/pull/3023#issuecomment-384205386 "2018-04-25T08:31:47Z - Replied by Github Reply Comments"):
> > I agree the naming is confusing. Also, `master` does not really mean anything to someone not involved in the project. Why not:
> > 
> > - `latest` -> `latest release`
> > - `master` -> `upcoming release (in development)`
> > 
> > It might be too verbose, but I think we should make it clear that `master` is a regularly evolving branch and that `latest` is the current stable release.
> 
> I agree. But what about the documentation of CGAL-4.12-beta2? How does it fit between "latest release" and "upcoming release"?

I would put it between latest and master? Something like:

* CGAL development branch
* CGAL 4.12 beta 2
* __CGAL 4.11 (latest stable branch)__
* CGAL 4.10
* (etc.)

(Default being always the latest stable branch.)

**Comment by lrineau** [comment]
Maxime, how difficult would it be to have something that way? I imagine that the Javascript array of strings would be turned into an array of pairs of strings (one for the URL component, and one for the string to display).

(Anyway, @maxGimeno, that topic is less urgent that the new flood of warnings we have in our [Doxygen testsuite].)

[Doxygen testsuite]: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/

**Comment by MoniqueTeillaud** [comment]
@lrineau I meant that master is not an "official release". It is the preliminary state of the future official release (= 4.12 as for today). And when you see the list 4.12, 4.11.1, you don't know which one is supposed to be stable (today it is 4.11.1, isn't it?). 
What I consider an official release is a release that you announce on the cgal-announce mailing list. 
@sloriot  Actually no, latest is not the one on the top. latest links to 4.11.1 whereas the one on the top is 4.12. You see, confusing... 

Other examples of the confusing numbering:
* When you choose latest, you reach a page entitled CGAL 4.12-Ic-219, which looks quite cryptic
* When you choose 4.12, you reach the same 4.12-Ic-219
* And when you choose master, you reach a page entitled CGAL 4.12, which you had not reached when you had chosen 4.12. argh... 
* When you start from cgal.org -> news and follow links -> CGAL 4.12 beta2, you see "Link to the CGAL-4.12 documentation". So there 4.12 beta2 suddenly becomes 4.12, which is confusing (this should be fixed on the website). And when you click you reach 4.12-Ic-219. 

The tags in this new menu on doc.cgal should be consistent with the naming on the CGAL website and in the announcement emails. I guess that
- master
- 4.12 beta
- 4.11.1
- 4.11, etc
would already be less confusing.

**Pull request merged**
