### PR TITLE
Remove support for BLAS, LAPACK, and TAUCS

### LINKED ISSUE #3905: Point Set Processing: cleanup
## Issue Details

For 5.0 we should remove functionality that was deprecated long ago, such as [this](https://doc.cgal.org/latest/Point_set_processing_3/index.html#title4).

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

This PR is a consequence of bug #3317. It removes our support for BLAS, LAPACK, and TAUCS.

## Release Management

* Affected package(s):
   - Installation,
   - Jet_fitting_3,
   - Point_set_processing_3,
   - Ridges_3,
   - Solver_interface,
   - Surface_mesh_parameterization.
* Fix #3905

### CODE REVIEW

**Comment by lrineau** [comment]
@sgiraudot In this branch, for the moment, I have removed the support of BLAS,  LAPACK, and TAUCS from our CMake scripts in Installation/.

There are still mentions in:
```
../Jet_fitting_3/include/CGAL/Monge_via_jet_fitting.h
../Jet_fitting_3/test/Jet_fitting_3/CMakeLists.txt
../Jet_fitting_3/examples/Jet_fitting_3/CMakeLists.txt
../Point_set_processing_3/include/CGAL/jet_smooth_point_set.h
../Point_set_processing_3/include/CGAL/jet_estimate_normals.h
../Point_set_processing_3/test/Point_set_processing_3/CMakeLists.txt
../Point_set_processing_3/examples/Point_set_processing_3/CMakeLists.txt
../Ridges_3/test/Ridges_3/CMakeLists.txt
../Ridges_3/examples/Ridges_3/CMakeLists.txt
../Solver_interface/include/CGAL/Lapack_svd.h
../Solver_interface/doc/Solver_interface/Concepts/SvdTraits.h
../Surface_mesh_parameterization/examples/Surface_mesh_parameterization/CMakeLists.txt
```

**Comment by sgiraudot** [comment]
I've taken care of it, except for `Surface_mesh_parameterization`, I'm not quite sure what to do with it, the only mention of Lapack is:

```cmake
    set(SuiteSparse_USE_LAPACK_BLAS ON)
```
But the rest of the scripts depends on that, and I'm not sure what the status of SuiteSparse in CGAL is.

**Comment by afabri** [comment]
@MaelRL should have a look at this.

**Comment by lrineau** [comment]
Ping @MaelRL.

And please somebody fix the conflicts.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Mar 8, 2019, 10:20 AM GMT+1](https://github.com/CGAL/cgal/pull/3739#issuecomment-470861041 "2019-03-08T09:20:23Z - Replied by Github Reply Comments"):
> @MaelRL should have a look at this.

@MaelRL Please review the changes.

@sgiraudot Is there still something to implement?

I think this pull-request should be completed and integrated in `master` as soon as possible, early enough in the release cycle of CGAL-5.0.

**Comment by MaelRL** [comment]
I haven't replied yet on SMP because I don't know: the `CMakeLists.txt` as well as the `FindSuiteSparse.cmake` were just mindlessly copied from somewhere else.

I'll look into it...

**Comment by sgiraudot** [comment]
I just pushed a change in the documentation of PSP (as @afabri noted that it was mentioned there). Apart from that (and from SMP which Mael is looking into), I did not have anything else to do.

**Comment by lrineau** [comment]
Great. I have removed the "TODO" tag, and pinged @maxGimeno to test the PR in `integration`. @MaelRL, if you find a bug in this PR, let us know.

**Comment by lrineau** [comment]
[**@sgiraudot**](https://github.com/sgiraudot) commented on [Mar 8, 2019, 9:54 AM GMT+1](https://github.com/CGAL/cgal/pull/3739#issuecomment-470853866 "2019-03-08T08:54:42Z - Replied by Github Reply Comments"):
> I've taken care of it, except for `Surface_mesh_parameterization`, I'm not quite sure what to do with it, the only mention of Lapack is:
> 
> ```cmake
>     set(SuiteSparse_USE_LAPACK_BLAS ON)
> ```
> But the rest of the script depends on that, and I'm not sure what the status of SuiteSparse in CGAL is.

The `FindSuiteSparse` can use the `FindBLAS` and `FindLAPACK` from the CMake distribution.

**Comment by maxGimeno** [comment]
There is a conflict here.

**Comment by maxGimeno** [comment]
Seems ok in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-39.shtml

**Pull request merged**
