### PR TITLE
Polyhedron demo: unify OFF io plugins

### PR DESCRIPTION
**Pull request by sgiraudot**
Merge `OFF_to_xyz plugin` in `OFF_plugin`:
* The OFF reader of point sets is used if the OFF file does not contain faces
* A new plugin is created to generate an oriented point set from a Polyhedron item (similarly to what was done when loading a Polyhedron OFF file with the `OFF_to_xyz` plugin)

### CODE REVIEW

**Comment by sloriot** [comment]
This is not sufficient, there is also off_to_nef plugin. Moreover this is not a good idea IMO because if the OFF is not a polyhedron (that is a polygon soup) you will not be able to access the points. The off_to_nef plugin is also using a different function (`CGAL::OFF_to_nef()`) while the action Polyhedron->Nef is using the constructor of Nef.

**Comment by lrineau** [comment]
What is the status of this pull-request? Is it stalled?

**Comment by sgiraudot** [comment]
I still have to add a function to convert a polygon soup in point set (so that all the current functionalities are still available) as Sebastien pointed it out.

For the `off_to_nef`, my intention was never to merge it (although it is true that their will still be 2 off plugins if this PR is accepted, but I don't see any easy solution to integrate `off_to_nef` because the input is the same as for the current `off_plugin` - a polyhedral surface).

(I had other things to do these last few days but I haven't given up on this, just did not have time to work on it :-) )

**Comment by lrineau** [comment]
Ping.

**Comment by sgiraudot** [comment]
I added the feature to create a point set item from the vertices of a polygon soup item. The PR is ready to be tested.

**Comment by lrineau** [comment]
Will be tested tonight.

**Comment by lrineau** [comment]
@sloriot, you set the label "not yet approved". It is done, now?

**Comment by sloriot** [comment]
OK

**Comment by lrineau** [comment]
This PR is merged in `master`, now.

**Pull request merged**
