### PR TITLE
Referencing non existing file

### PR DESCRIPTION
**Pull request by albert-github**
For a better quality also the close image was converted to an svg image, so the png does not exists anymore. This has to be reflected in this file as well.

### CODE REVIEW

**Comment by lrineau** [comment]
The modification of this PR must be replicated in the four versions of the `resources/` directory.

**Comment by albert-github** [comment]
@lrineau I don't think this is the case the close.svg only is a problem for the newer version i.e as of 1.8.19.

**Comment by albert-github** [comment]
@MaelRL This is not an enhancement but an error (bug)

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-11.shtml

**Pull request merged**
