### PR TITLE
Polyhedron_demo: Join_and_split_polyhedra_plugins uses Surface_mesh

### LINKED ISSUE #1932: Polyhedron_demo: Use Scene_surface_mesh_item instead of Scene_polyhedron_item
## Issue Details

We should use the Scene_surface_mesh_item where it is possible, as it is more efficient in terms of memory consumption. We should integrate the plugins by package, to dispatch tests and to avoid a too important difference with the current master branch.

Packages:

- [x] AABB_tree
- [x] Convex_decomposition
- [x] Convex_hull
- [x] IO
- [x] Mesh_2
- [ ] Mesh_3
- [x] Operations_on_polyhedra
- [x] PCA
- [ ] PMP
- [ ] Point_set
- Subdivision_methods
- [ ] Surface_mesh
- [x] Surface_mesh_deformation

Plugins: 

- [x] Plugins/AABB_tree/Cut_plugin.cpp
- [x]  Plugins/PCA/Create_bbox_mesh_plugin.cpp
- [x]  Plugins/PCA/Pca_plugin.cpp
- [x]  Plugins/PCA/Scene_polyhedron_transform_item.h
- [x]  Plugins/PCA/Edit_box_plugin.cpp
- [x]  Plugins/Mesh_3/Detect_sharp_edges_plugin.cpp
- [ ]  Plugins/Mesh_3/Optimization_plugin_cgal_code.cpp
- [x]  Plugins/Mesh_3/Mesh_3_plugin.cpp
- [x]  Plugins/IO/GOCAD_io_plugin.cpp
- [x]  Plugins/IO/Surf_io_plugin.cpp
- [x]  Plugins/IO/STL_io_plugin.cpp
- [x]  Plugins/IO/VTK_io_plugin.cpp
- [x]  Plugins/Convex_decomposition/Nef_plugin.cpp
- [x]  Plugins/Surface_mesh_deformation/Edit_polyhedron_plugin.cpp
- [x]  Plugins/Surface_mesh_deformation/Scene_edit_polyhedron_item.h
- [ ]  Plugins/Point_set/Surface_reconstruction_plugin.cpp #Uses a Polyhedron_incremental_builder_3
- [x]  Plugins/Point_set/Point_set_shape_detection_plugin.cpp
- Plugins/Surface_mesh/Remeshing_plugin.cpp # Must enhance Mesh_3 and then remove this plugin
- [x]  Plugins/Surface_mesh/Mesh_simplification_plugin.cpp
- [ ]  Plugins/Surface_mesh/Mesh_segmentation_plugin.cpp 
- [x]  Plugins/Surface_mesh/Shortest_path_plugin.cpp
-  Plugins/Surface_mesh/Remeshing_plugin_cgal_code.cpp # Must enhance Mesh_3 and then remove this plugin
-  Plugins/Surface_mesh/Parameterization_plugin.cpp#There is an on going SF concerning this plugin
- [x]  Plugins/Convex_hull/Convex_hull_plugin.cpp
- [x]  Plugins/Convex_hull/Kernel_plugin.cpp
- [x]  Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp
- [x]  Plugins/Operations_on_polyhedra/Point_set_from_vertices_plugin.cpp
- [x]  Plugins/PMP/Inside_out_plugin.cpp
- [x]  Plugins/PMP/Point_inside_polyhedron_plugin.cpp
- [x]  Plugins/PMP/Polyhedron_slicer_plugin.cpp
- [x]  Plugins/PMP/Corefinement_plugin.cpp
- [x]  Plugins/PMP/Polyhedron_stitching_plugin.cpp
- [x]  Plugins/PMP/Repair_polyhedron_plugin.cpp
- [x]  Plugins/PMP/Surface_intersection_plugin.cpp
- [x]  Plugins/PMP/Distance_plugin.cpp
- [x]  Plugins/PMP/Selection_plugin.cpp
- [x]  Plugins/PMP/Join_and_split_polyhedra_plugin.cpp
- [x]  Plugins/PMP/Hole_filling_polyline_plugin.cpp
- [x]  Plugins/PMP/Hole_filling_plugin.cpp # TODO check normalize_borders
- [x]  Plugins/PMP/Jet_fitting_plugin.cpp
- [x]  Plugins/PMP/Isotropic_remeshing_plugin.cpp
- [ ]  Plugins/PMP/Mean_curvature_flow_skeleton_plugin.cpp
- [x]  Plugins/PMP/Triangulate_facets_plugin.cpp
- [x]  Plugins/Mesh_2/Mesh_2_plugin.cpp
-  Plugins/Subdivision_methods/Subdivision_methods_plugin.cpp #There is an on going SF concerning this plugin

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Join_and_split_polyhedra_plugin works with both Polyhedron and Surface_mesh.
Needs #2201 to compile correctly.
## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #1932

### CODE REVIEW

**Comment by lrineau** [comment]
There is a [build error in Travis](https://travis-ci.org/CGAL/cgal/jobs/246131190#L5605) and a conflict with `master`.

**Comment by maxGimeno** [comment]
It is explained in the description.

**Comment by lrineau** [comment]
I have cherry-picked the sole commit of #2201 in this PR, so that Travis can test it.

The conflict with `master` is still there.

**Comment by lrineau** [comment]
...but #2201 will be tested and merged on its own. Please do not close it.

**Comment by lrineau** [comment]
There is a compilation error on Windows:
```
[ 90%] Building CXX object Plugins/PMP/CMakeFiles/join_and_split_polyhedra_plugin.dir/Join_and_split_polyhedra_plugin.cpp.obj
	cd C:\CGAL\test\CGAL-4.11-Ic-54\cmake\platforms\x64_Cygwin-Windows8_MSVC2013-Release-32bits\test\Polyhedron_Demo\Plugins\PMP
	C:\PROGRA~2\MICROS~4.0\VC\bin\cl.exe  @C:\cygwin\tmp\nm4558.tmp
Join_and_split_polyhedra_plugin.cpp
C:\CGAL\test\CGAL-4.11-Ic-54\cmake\platforms\x64_Cygwin-Windows8_MSVC2013-Release-32bits\test\Polyhedron_Demo\Plugins\PMP\Join_and_split_polyhedra_plugin.cpp(152) : error C2899: typename cannot be used outside a template declaration
C:\CGAL\test\CGAL-4.11-Ic-54\cmake\platforms\x64_Cygwin-Windows8_MSVC2013-Release-32bits\test\Polyhedron_Demo\Plugins\PMP\Join_and_split_polyhedra_plugin.cpp(228) : error C2899: typename cannot be used outside a template declaration
```
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-54.shtml#Polyhedron_Demo

**Pull request merged**
