### PR TITLE
PMP : add measure functions

### PR DESCRIPTION
**Pull request by janetournois**
This PR adds measure functions such as edge_length() and face_area() to the PMP package.
These measure functions are also available for ranges of simplices, or the full polygon mesh.

It implements the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_PMP_measure_functions), which has been pre-approved on Nov. 9th

### CODE REVIEW

**Comment by janetournois** [comment]
Merged in [CGAL-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-55.shtml)

**Comment by sloriot** [comment]
Testsuite is red

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-56](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-56.shtml)

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-56](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-56.shtml)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-57

**Pull request merged**
