### PR TITLE
Update AABB_halfedge_graph_segment_primitive.h

### PR DESCRIPTION
**Pull request by afabri**
Fix typos

### CODE REVIEW

**Comment by afabri** [comment]
It looks so trivial  to me that I find  it overkill to run that in a testsuite.

**Comment by lrineau** [comment]
Tests are better than me to count the number of backquotes in a line, and I cannot trust that you have even compiled locally. I see that you committed using the Github web interface.

**Comment by afabri** [comment]
Apparently the backticks do NOT get counted by the testsuite.   And the `const ... *`  is an obvious error, as the whole mesh won't get copied into each primitive.  It needs that someone reads and confirms the obvious, even with a testsuite.

**Comment by lrineau** [comment]
That PR introduced an error in our Doxygen testsuite:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1-Ic-193/logs2/AABB_tree.log
> include/CGAL/AABB_halfedge_graph_segment_primitive.h:127: warning: explicit link request to 'edge_descriptor' could not be resolved

(Fixed in 62c15ff47ac.. and f24f9b2c03f)

So that would have been useful to test this before merging.

**Comment by sloriot** [comment]
`AABB_face_graph_triangle_primitive` has the exact same issues fixed by this PR.

**Comment by sloriot** [comment]
`AABB_face_graph_triangle_primitive` is fixed by #4835

**Pull request merged**
