### PR TITLE
Add an option to toggle between 2D and 3D mode for the basic viewer.

### PR DESCRIPTION
**Pull request by gdamiand**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Add an option to toggle between 2D and 3D mode for the basic viewer; feature asked by an user.

## Release Management

* Affected package(s): GraphicsView
* Fix: #4966

### CODE REVIEW

**Comment by sloriot** [comment]
It is somehow strange that it is not fixed by the `draw()` function itself. If I have a `Surface_mesh<Point_3>` I know that I want to display 3D and if I have a `Polygon_2` I know that it is 2D. I probably miss something...

**Comment by afabri** [comment]
The viewer detects if all points live in a plane.

**Comment by afabri** [comment]
@gdamiand just in case you use emacs, somebody once told me to put  `(add-hook 'before-save-hook 'delete-trailing-whitespace)`  in my .emacs.

**Comment by gdamiand** [comment]
Thanks @afabri.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-12.shtml

**Pull request merged**
