### PR TITLE
Replace  __    with   _   in function names

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by lrineau** [comment]
That was already reviewed more than one year ago.

@palliez , @MoniqueTeillaud, what do you think of this modification? It seems more in agreement with the usual naming in CGAL, but there might be a reason that was discussed during the review.

**Comment by sloriot** [comment]
Ah you are right `__` stands for parenthesis.

**Comment by mglisse** [comment]
Clément pointed this pull request to me.
@sloriot Could you add a link to whatever conversation decided that? `__` is illegal in C++... (though I agree that it can be convenient)

**Comment by lrineau** [comment]
Only identifiers beginning by `__` are illegal (actually reserved for the compiler and STL) in C++. And also those beginning by a single `_` and a capital letter.

**Comment by mglisse** [comment]
You are confusing with C. In C++:
[lex.name]
> Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

**Comment by sloriot** [comment]
I never say it was illegal. I just forget we used them on purpose. Fortunately we only use lowercase letter.

**Comment by mglisse** [comment]
@sloriot You probably read my comment too fast... I am the one saying it is illegal, and I was asking where it was decided to use that notation on purpose (there is a "?" in the middle splitting the comment into 2 sentences).
(I don't insist on changing the names, I just think it worth reminding people of the fact that it is illegal)

**Pull request closed without merging**
