### PR TITLE
PMP : new features for isotropic_remeshing

### PR DESCRIPTION
**Pull request by janetournois**
With this PR, <code>PMP::isotropic_remeshing</code> is now able to :
* preserve some prescribed vertices `vertex_is_constrained_map` (given by a property map, mapping vertices to booleans)
* preserve patch id's, given by a property map `face_patch_map`, mapping faces to a "patch id", e.g. a color

These functionalities have been added via BGL named parameters, so they have no impact on the API and backward compatibility issues.

As a side effect of this PR, the `connected_components_plugin` of the Polyhedron demo is now able to color the connected components of a polyhedral surface that are separated by constrained polylines (using `edge_is_constrained_map`). The polylines are selected using the selection tool.

edit : I rebased my branch on master right before creating the PR

~~TODO : I need to make some local tests before testing in the testsuite~~
~~TODO : check the documentation is ok~~

The associated [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/PMP::isotropic_remeshing_new_features)

### CODE REVIEW

**Comment by lrineau** [comment]
No documented API? No small feature? No modification of `changes.html`?

Is that wanted?

**Comment by janetournois** [comment]
* the API is coming, 
* there is no small feature because it's "only" an improvement, but I can write one if you prefer
* changes.html is coming too

I have several local commits coming soon...

**Comment by janetournois** [comment]
TODO's done. Shall I write a small feature @lrineau ?

**Comment by afabri** [comment]
I would suggest NO. The PR says it all.

**Comment by lrineau** [comment]
Like for another PR, I still think that there should be a form of peer-review of modifications that are visible to users, and especially the modifications to the documentation. That is why we have the small features.

I do trust Jane as for the quality of the documentation she write, but if we start avoiding [the rules][sf], where is the limit? There is one rule that I would like to modify: if the "maintainer" of a package cannot review a small feature quickly enough, then there should be a way for other CGAL editors to review and accept the small feature.

[sf]: http://www.cgal.org/review_process_rules.html#small_submissions

**Comment by janetournois** [comment]
[small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/PMP::isotropic_remeshing_new_features) submitted

**Comment by sloriot** [comment]
Tests looks good but there are other errors in other package. To be sure let's retest it.

**Pull request merged**
