### PR TITLE
Polyhedron demo: New widget for color computation

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Adds a widget that allows to colorize a surface_mesh according to the smallest angle of each of its faces, or according to their scaled jacobian.
## Release Management

### CODE REVIEW

**Comment by lrineau** [comment]
A Travis check, about `override`, has failed:
https://travis-ci.org/CGAL/cgal/jobs/275923790#L4127

**Comment by janetournois** [comment]
Nice feature, thank you!

It works fine, but there is something strange in the behavior :
- load a polyhedral surface
- click "Display properties" : the scaled jacobian is chosen by default (maybe having the smallest angle as the default would be more intuitive btw)
- click "Colorize" : the values for min and max of the ramp change in the spin boxes, but not on the colored ramp. That's a bit weird. But then clicking on "replace ramp" changes the min and max of the ramp so it's ok.
- change the property to "smallest angle", and click "colorize": the ramp extrema change in the spinboxes, but the ramp does not change at all (not the color, nor the extrema). And this time, it looks more like a bug.

Imho, it is acceptable that the ramp does not change on-the-fly when the spinboxes values are changed, but that the same criterion is taken into account, until one clicks "Replace ramp".
However, when the criterion iss changed, the ramp should be updated when "Colorize" is clicked.

**Comment by maxGimeno** [comment]
* click "Colorize" : the values for min and max of the ramp change in the spin boxes, but not on the colored ramp. That's a bit weird. But then clicking on "replace ramp" changes the min and max of the ramp so it's ok.
-> It is wanted : having the values in the min and max boxes scaled on the extrema of the surface allows to get its values, which gives an idea for the values we want for the ramp, but we don't want the ramp to change everytime we colorize a mesh. The upside is that it makes the economy of a button, but if you think it is disturbing, I guess it is better to add a button anyway.

**Comment by janetournois** [comment]
Thank you for the changes.

About the smallest angle scale :
I agree that, when loading a triangle mesh, the initial angle bounds should be `[0;60]`, but when the mesh is not triangular, the smallest angle has different bounds, and `[0;180]` would be a reasonable choice in case of non-convex polygons.
 
Note that the mesh can be hybrid (for example triangles and quads), so I would suggest that 
- if `CGAL::is_triangle_mesh()` returns true, the initial bounds are set to `[0;60]`
- if `CGAL::is_quad_mesh()` returns true, the initial bounds are set to `[0,90]` (even with non-convex polygons, it should be correct 
- otherwise, the inital bounds are set to `[0; 180]`

**Comment by janetournois** [comment]
When "Replace Ramp" is clicked, is it on purpose that the faces are not re-colorized automatically?

**Comment by maxGimeno** [comment]
Yes, you might just want to check if your new ramp looks like you want before re-colorizing all the faces. I guess.

**Comment by lrineau** [comment]
[Warnings in the testsuite]:
```
test\Polyhedron_Demo\Plugins\Display\Display_property_plugin.cpp(172): warning C4305: 'initializing': truncation from 'double' to 'float'
test\Polyhedron_Demo\Plugins\Display\Display_property_plugin.cpp(173): warning C4305: 'initializing': truncation from 'double' to 'float'
```

[Warnings in the testsuite]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-45.shtml#Polyhedron_Demo

**Pull request merged**
