### PR TITLE
Adjusting zNear with wheel and shift

### PR DESCRIPTION
**Pull request by maxGimeno**
Using Shift+wheel adjusts the zNear plane in the Frustum

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-63

**Comment by lrineau** [comment]
I have merged that PR in my branc, and tried it. It works, at least on my machine under Linux Fedora 21.

(TODO) I have a remark: you should call `QGLViewer::setMouseBindingDescription` so that the action of `Shift+Wheel` is self-documented in the help popup of QGLViewer, like the other bindings.

**Comment by maxGimeno** [comment]
Sadly, it doesn't seem to be possible to add a bindingDescription to a wheel event. There is a setKeyBindingDescription, that takes a Qt::Key, a setMouseBindingDescription, that takes a Qt::MouseButton (which does not contain any Wheel) but no setWheelBindingDescription, despite the existance of setWheelBinding, which only works with the qglviewer's enum "MouseAction". 
 Plus I cannot use the "MiddleButton" instead of the wheel, as it is already taken by another action. 
 The only way I can think of to add this description line is to override the function that displays the help page and manually add the line about Shift + Wheel, but it seems especially complex and unclean.

**Comment by maxGimeno** [comment]
Completely randomly, I found out that for setting a WheelEvent description, you have to specify Qt::NoButton as argument for setMouseBindingDescription, so I will PR soon.

**Pull request merged**
