### PR TITLE
Polyhedron demo: Addition of a preset of  camera positions

### PR DESCRIPTION
**Pull request by maxGimeno**
- In the camera positions list dock widget, six buttons have been added, that allow the user to move the camera in the following positions : front, back, left, right, top, bottom, but always looking at the center of the scene.

### CODE REVIEW

**Comment by sgiraudot** [comment]
Some remarks:

* There's a bug if we try to move the saved camera positions up or down in the list: if we move it up when it's the first (or down if it's the last), it disappears.

* I did not find how to _use_ a saved camera position (double-clicking on it just allows to rename it but doesn't actually go to this position).

* I understand that it is much more standard and consistent to always look at the center of the scene on the default positions, but it sometimes makes it useless: some objects may be centered on a far away point and they go out of view when using default camera positions. Maybe another solution would be to allow the user to "recenter" the object? (= translating it so that its centroid is on the origin) But that might be out of scope for this particular feature, I don't know.

Otherwise this is an interesting feature to have on the Polyhedron demo.

**Comment by lrineau** [comment]
I am the one how wrote the "camera position plugin". The patch from Maxime only adds the six buttons.

- I do not know about the bug you are talking about (first item in your message). I would have to check.
- To use a save position, just click *once* on it.
-  In my opinion the six pre-defined positions should be computed from the center of rotation (the look-around-point), and not the center of the scene.

**Comment by sgiraudot** [comment]
Single click doesn't work either for me to use a saved position.

**Comment by maxGimeno** [comment]
It is probably a bug that comes from when I changed the preloaded list of
positions to buttons. I will fix it tomorrow.

2015-09-29 14:09 GMT+02:00 Simon Giraudot <notifications@github.com>:

**Comment by sgiraudot** [comment]
Okay, so Maxime and I actually found out that the way to activate the QListView depends on the platform ( http://doc.qt.io/qt-4.8/qabstractitemview.html#activated ).

On my computer, in order to _use_ a saved position, I have to click on it _and_ press Enter afterwards. It is a bit weird that this behavior is different (considering we are both on GNU/Linux) but at least we know it's not a bug...

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-10](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-13](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-13.shtml)

**Comment by sloriot** [comment]
Tests look good

**Comment by lrineau** [comment]
As I said earlier:
> In my opinion the six pre-defined positions should be computed from the center of rotation (the look-around-point), and not the center of the scene.

In my opinion, this feature is buggy. If I load a scene that is not centered on the origin, then the buttons are useless.

**Pull request merged**
