### PR TITLE
Add join operation to Surface_mesh

### PR DESCRIPTION
**Pull request by afabri**
This adds `operator+= ()` for a `Surface_mesh`.

### CODE REVIEW

**Comment by lrineau** [comment]
@afabri, please use correct titles for the pull-requests. "Surface mesh join gf" is meaningless.

**Comment by lrineau** [comment]
@afabri: I had a quick look and I cannot see any documentation. Is that a fix of code because the functions were already documented? Otherwise it should be a documented small feature.

**Comment by afabri** [comment]
It is a small feature   https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_operator%2B%3DSM

and it has additional documentation see:
ec19e1ca12fa5670aacfd8927fd36b8e1c8e1d6f

**Comment by lrineau** [comment]
I have merged the pr in integration, before leaving the office. It will be tested tonight.

**Comment by lrineau** [comment]
The tests in CGAL-4.7-Ic-33 were successful.

**Pull request merged**
