### PR TITLE
Gsoc2014 vcm 3 jmeyron

### PR DESCRIPTION
**Pull request by sloriot**
[Small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/vcm_computation_and_applications)

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.6-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml)

**Comment by lrineau** [comment]
The pull request adds an example [`examples/Convex_hull_3/lloyd_algorithm.cpp`](https://github.com/sloriot/cgal/blob/a2b0267891c3b6ef099fb78523d65c8e9d5034b9/Convex_hull_3/examples/Convex_hull_3/lloyd_algorithm.cpp). That does not seem to be in the small feature. That must be an error.

What is more, the branch weights 890Ko, without any addition of images. That must be an error too.

**Comment by sloriot** [comment]
The branch history contains indeed contains a binary (that is only 81K) but most importantly it uses a version of fandisk.off in the testsuite that is ~600K compressed and that is responsible for most of the weight of the branch. This file is used in the testsuite to check precomputed values and redoing the test is not that easy.

I'll see if I can do it again with the lighter version already in the repo.

**Comment by lrineau** [comment]
The results from [CGAL-4.7-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-55.shtml) were good.

**Pull request merged**
