### PR TITLE
Address warning Wself-assign-overloaded

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

In the testsuite we assign sometimes variables to themselves: `f = f`. 
This triggers a [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-49/Mesh_2/TestReport_lrineau_ArchLinux-clang-CXX14.gz) and it can be avoided by writing `void(f = f)`.

## Release Management

* Affected package(s): Mesh_2  (more to follow if it works)

### CODE REVIEW

**Comment by afabri** [comment]
@lrineau This did not help

> /home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-Release/test/Mesh_2/test_double_map.cpp:74:11: warning: explicitly assigning value of variable of type 'Map' (aka 'Double_map<int, int>') to itself [-Wself-assign-overloaded]
  void(f2 = f2); // check the auto-assignment 
       ~~ ^ ~~
1 warning generated.

**Comment by afabri** [comment]
@lrineau can you point out occurrences of this warning?.

**Comment by lrineau** [comment]
In the results of [CGAL-4.14-Ic-56](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-56.shtml), here they are:
```
Modular_arithmetic/TestReport_lrineau_ArchLinux-clang.gz:.../test/Modular_arithmetic/Residue.cpp:105:15: warning: explicitly assigning value of variable of type 'CGAL::Residue' to itself [-Wself-assign-overloaded]
Number_types/TestReport_lrineau_ArchLinux-clang.gz:.../test/Number_types/Interval_nt.cpp:214:5: warning: explicitly assigning value of variable of type 'IA_nt' to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_Linf_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_Linf_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_Linf_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_Linf_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_Linf_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_Linf_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
Segment_Delaunay_graph_Linf_2/TestReport_lrineau_ArchLinux-clang.gz:.../test/Segment_Delaunay_graph_Linf_2/include/test_types.h:170:7: warning: explicitly assigning value of variable of type 'Segment_Delaunay_graph_2' (aka 'SDG') to itself [-Wself-assign-overloaded]
STL_Extension/TestReport_lrineau_ArchLinux-clang.gz:.../test/STL_Extension/test_dispatch_output.cpp:26:6: warning: explicitly assigning value of variable of type 'T1' (aka 'typename output::Iterator_tuple') to itself [-Wself-assign-overloaded]
STL_Extension/TestReport_lrineau_ArchLinux-clang.gz:.../test/STL_Extension/test_dispatch_output.cpp:72:8: warning: explicitly assigning value of variable of type 'Dispatcher' (aka 'Dispatch_output_iterator<CGAL::cpp11::tuple<T1, T2>, CGAL::cpp11::tuple<T1 *, std::back_insert_iterator<std::vector<T2> > > >') to itself [-Wself-assign-overloaded]
STL_Extension/TestReport_lrineau_ArchLinux-clang.gz:.../test/STL_Extension/test_dispatch_output.cpp:73:8: warning: explicitly assigning value of variable of type 'Dropper' (aka 'Dispatch_or_drop_output_iterator<CGAL::cpp11::tuple<T1, T2>, CGAL::cpp11::tuple<T1 *, std::back_insert_iterator<std::vector<T2> > > >') to itself [-Wself-assign-overloaded]
```

**Comment by afabri** [comment]
@lrineau can you update the list above.

**Comment by lrineau** [comment]
Only one remains:
```
test/Modular_arithmetic/Residue.cpp:105:15: warning: explicitly assigning value of variable of type 'CGAL::Residue' to itself [-Wself-assign-overloaded]
```

**Comment by afabri** [comment]
@lrineau it seems we are through

**Comment by lrineau** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-64/.

OK for `master`.

**Pull request merged**
