### PR TITLE
Rename parameters

### LINKED ISSUE #8176: The width of documentation of CGAL::Polygon_mesh_processing::corefine_and_compute_boolean_operations is too large
https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gaaeb559e2f901b418ddd563e8aace83eb

That documentation does not fit in the width of any of my screens.

That seems to be because of `const std::tuple< NamedParametersOut0, NamedParametersOut1, NamedParametersOut2, NamedParametersOut3 > &  	nps_out = std::tuple<NamedParametersOut0,NamedParametersOut1,NamedParametersOut2,NamedParametersOut3>() 
` that is too wide, and not wrapped by Doxygen CSS.

Same issue with CGAK-5.5.x (and even previous versions). I am surprised it was not pointed out by the review of the documentation... :smiling_imp:

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #8176

### CODE REVIEW

**Comment by albert-github** [comment]
Wouldn't it be more consistent to replace all `NamedParametersOut...` by `NPOut...` in this package?
Analogous for `NamedParametersIn...` rename to `NPIn...` and `NamedParameters...` to `NP...`.

**Comment by lrineau** [comment]
That is better. Now it fits just in the width of my screen:
https://cgal.github.io/8178/fix/Polygon_mesh_processing/group__PMP__corefinement__grp.html#gae3553532387bd3ecfbcb72f4f092c7bc

**Comment by afabri** [comment]
It should also be changed for the input parameters.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-237

**Pull request merged**
