### PR TITLE
Redirect and readability

### PR DESCRIPTION
**Pull request by albert-github**
- correcting permanent redirect
- improve readability

### CODE REVIEW

**Comment by lrineau** [comment]
The `<TT>` should be turned into a `<blockquote>`, in my opinion.

**Comment by albert-github** [comment]
@lrineau 
Do you mean the doxygen `<blockquote>`? 
The resulting output would look like;

image

**Comment by lrineau** [comment]
> @lrineau Do you mean the doxygen `<blockquote>`? The resulting output would look like;
> 
> image

Yes, exactly. I think you can remove the `, ` before `the namespace`, just after the blockquote.

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-90

**Pull request merged**
