### PR TITLE
Make Ridge_3 work for any FaceGraph

### PR DESCRIPTION
**Pull request by afabri**
This package introduced a subset of the types and functions of CGAL::Polyhedron as a concept. We replaced that concept with FaceGraph.   Users who have other models than Polyhedron will suffer from breaking backward compatibility.

The package is merged in integration, and had already several times a green row in testsuites. 

The merge conflict concerns changes.html

### CODE REVIEW

**Comment by lrineau** [comment]
Is there a small feature about that set of changes? Or is it considered as a bug-fix?

What about the backward compatibility?

**Comment by afabri** [comment]
Polyhedron_3 is a model of FaceGraph, so for most users it will work.
There is an item in changes.html

**Comment by lrineau** [comment]
That is a small feature:
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Ridges_BGL

Already preapproved for several months.

**Comment by lrineau** [comment]
I suggest you fix the conflict in `changes.html`, so that it is easier to merge the branch in `integration`.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml): the lines about `Ridges_3` and `Jet_fitting_3` are exemplary green, and I have verified that the errors in `Polyhedron_Demo` are not due to this PR.

**Pull request merged**
