### PR TITLE
New point set processing algorithm: Hierarchical clustering

### PR DESCRIPTION
**Pull request by sgiraudot**
Small feature: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Point_set_processing_hierarchical_clustering

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-7](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-7.shtml)

**Comment by sloriot** [comment]
@sgiraudot See errors in the testsuite

**Comment by sloriot** [comment]
@sgiraudot: `/Users/cgaltester/cgal_test/CGAL-4.8-Ic-7/cmake/platforms/x86-64_Darwin-13.0_Apple-clang-5.1_Release-LEDA-without-GMP/test/Point_set_processing_3/hierarchy_simplification_test.cpp:21:3: warning: 'typename' occurs outside of a template [-Wc++11-extensions]`

**Comment by sgiraudot** [comment]
That is already fixed by commit 47e415e (in some other platforms, it was just a warning).

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-15](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-15.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-16](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-16.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-17](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-17.shtml)

**Comment by sloriot** [comment]
Testsuite is missing the windows platforms

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by sgiraudot** [comment]
Everything went fine on the testsuite. The only errors in _Point_set_processing_3_ come from _vcm_all_tests_ which is not affected by this branch. Same for _Point_set_processing_3_examples_ (error in _normals_example_). The _hierarchy_simplification_test_ file was compiled and executed with no issue.

**Comment by lrineau** [comment]
I have merged this pull-request.

Could somebody investigate on the bug of `vcm_all_tests.cpp`. It seems to be only on 32 bits, Release:

https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Pull request merged**
