### PR TITLE
PMP::Polyhedral_envelope:  Fix memory leak

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

In case `update_exact()` is called the rep stores a non null pointer in `et` which must be deleted before a re-assignment.

## Release Management

* Affected package(s): PMP

### CODE REVIEW

**Review by maxGimeno — APPROVED** [review]
I approve these changes, and so does my sanitizer :+1:

**Comment by lrineau** [comment]
The *real* bug is that `CGAL::Lazy_rep` does not follow the rule-of-five: it has:
  - a copy-constructor (deleted)
  - a destructor,

and thus it should also define the other three special member functions:
  - a move-constructor,
  - a copy-assignment operator (probably as deleted),
  - and a move-assignment operator.

Here the bug comes from the lack of the move-assignment.

**Comment by maxGimeno** [comment]
So the real bug would be to add a move-assignment operator that deletes the current `et` and then replace it by the target's `et`, right ?

**Comment by lrineau** [comment]
> So the real bug would be to add a move-assignment operator that deletes the current `et` and then replace it by the target's `et`, right ?

Yes, the fix would be:
  - define a deleted copy-assignment,
  - define a move-assignment, that: delete the current `et`, replace it by the new one, *and* set `et` to `nullptr` in the other rep
  - define a move-constructor that does about the same as the move-assignment.

**Review by lrineau — APPROVED** [review]

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-158.shtml

**Pull request merged**
