### PR TITLE
Polyhedron demo - remesh a non-triangle mesh

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

When a user wants to remesh a non-triangle mesh, the remeshing menu is available, but remeshing freezes the demo.
With this PR, a pop-up asks whether the demo should first triangulate faces, or cancel remeshing.

Actually, it is not needed that the input mesh is fully triangulated. Only the faces to be remeshed should be triangulated.

TODO :
- [x] add something similar in `isotropic_remeshing_of_several_polyhedra()`
- [x] add in `triangulate_facets_plugin` the possibility to triangulate a selection of facets (given by a `scene_selection_item`)

## Release Management

* **Depends on: #3268** 
* Affected package(s): Polyhedron demo, PMP
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
When we apply "triangulate faces" on a selection of faces, the selection is lost by triangulation.
@sloriot do you think it is an issue?

**Comment by sloriot** [comment]
See #3268 :)

**Comment by janetournois** [comment]
thank you!

**Comment by janetournois** [comment]
This PR needs #3268 to be integrated first.

**Comment by lrineau** [comment]
Conflicts with #4994.

**Comment by maxGimeno** [comment]
There is a conflict here

**Comment by maxGimeno** [comment]
errors : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-31/Polyhedron_Demo/TestReport_lrineau_Fedora-Release.gz

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-41.shtml

**Pull request merged**
