### PR TITLE
Flag to prevent blanking linking flags from being applied

### LINKED ISSUE #1352: UseCGAL.cmake causes build spam due to deprecated CMake features.
```
find_package(CGAL COMPONENTS Core)
include(${CGAL_USE_FILE})
```

 results in `Directory not found` spam when compiling on platforms that support multiple build profiles (Debug, Release, etc). This is because of it's outdated use of link_directories.

### PR DESCRIPTION
**Pull request by elfprince13**
Fix #1352

### CODE REVIEW

**Comment by lrineau** [comment]
Hi @elfprince13, I see (in #1352) that you are following that issue since August 2016. Last summer, I told you that the CMake scripts would be completely renewed during Sept 2016, at the CGAL Developers Meeting. I did most of the work in the PR #1436. But I lack time to properly make it tested broadly and documented.

Anyway, I propose to integrate your fix quickly, and I hope to rework on #1436 soon or later.

**Comment by elfprince13** [comment]
Thanks both for the update on your work on #1436, and for the quick integration of this patch.

**Comment by lrineau** [comment]
Hi @elfprince13. I have merged this pull-request.

**Comment by elfprince13** [comment]
Great, thanks!

**Pull request merged**
