### PR TITLE
Polyhedron demo: Fixes for Mesh_3 plugin

### PR DESCRIPTION
**Pull request by maxGimeno**
- When loading an image, a dialog opens to let the user select the desired precision. In this dialog, the cursor was a WaitCursor. With this PR, the WaitCursor only appears when the selection is validated.
- The plugin's directory has been renamed.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-147

**Comment by sloriot** [comment]
@janetournois or @lrineau  could you give it a try and let me know if this implements what you wanted?

**Comment by janetournois** [comment]
this PR fixes the wait cursor issue

@afabri @maxGimeno was there a github issue about that? I can't find it in the list

**Comment by afabri** [comment]
In the bibliography of a paper we would have written "Personal communication".

**Comment by janetournois** [comment]
ok perfect :)

**Comment by lrineau** [comment]
That seems a big change, for CGAL-4.8. Should not we delay it to 4.9?

**Comment by lrineau** [comment]
Forget what I said. It is big because of the renamings.

**Pull request merged**
