### PR TITLE
fix halfspace intersection for a kernel with exact constructions

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.7-Ic-95

**Comment by sloriot** [comment]
The testsuite looks good but some errors that randomly shows up (see for example [this testsuite](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-93.shtml)) that are not related to this branch.
I'll merge the release branch into master too.

**Comment by lrineau** [comment]
The pull request was tagged for the milestone 4.7-beta, but it was forked from and merged into `releases/CGAL-4.6-branch`. Do we have a customer wanting a CGAL-4.6.2?

**Comment by afabri** [comment]
On 27/07/2015 11:09, Laurent Rineau wrote:
> The pull request was tagged for the milestone 4.7-beta, but it was
> forked from and merged into |releases/CGAL-4.6-branch|. Do we have a
> customer wanting a CGAL-4.6.2?

no

**Pull request merged**
