### PR TITLE
Document internal function for computing interior point

### LINKED ISSUE #268: Request: CGAL::find_interior_point(PlaneIterator begin, PlaneIterator end)
In my program I use the halfspace_intersection_3.h code a lot. I found myself at one point needing to find an interior point of the polyhedron enclosed by a set of planes.

Now of course I could just call CGAL::halfspace_intersection_3(...), then use the polyhedron to figure out an interior point (like averaging the points). But I don't need to compute the whole polyhedron in this case so this is slow.

What I've done now is add the code

``` cpp
#include <CGAL/Convex_hull_3/dual/interior_polyhedron_3.h>
#include <CGAL/internal/Exact_type_selector.h>
...
        Interior_polyhedron_3<CGALKernel, CGAL::internal::Exact_field_selector<void*>::Type> poly;
        CGAL_assertion_code(bool interior_point_found = )
        poly.find(planes.begin(), planes.end());
        CGAL_assertion_msg(interior_point_found, "finalizeTree: problem when determing a point inside the intersection");
        Point inside = poly.inside_point();
```

But it would be much nicer with a convenience function for this as documented here: http://doc.cgal.org/latest/Convex_hull_3/group__PkgConvexHull3Functions.html#ga6118d2c46934c541669ab871f8e1fd24

Thanks!

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes

document function `halfspace_intersection_interior_point_3()` that is using `QP_solver` to compute a point inside the interior of the intersection of a set of halfspaces. It is an implementaiton detail of `halfspace_intersection_3()`.

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #268 
* Feature/Small Feature (if any): [`Features/Small_Features/HSI_interior_point_3`](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/HSI_interior_point_3) -- pre-approved by Andreas Fabri 09:22, 27 July 2020 (CEST)
* Link to compiled documentation (obligatory for small feature) [doc](https://cgal.geometryfactory.com/~sloriot/doc/CH3_hsiip_v1/Convex_hull_3/group__PkgConvexHull3Functions.html#ga9a1ead3126e42fbf46ef269466cddc8f)
* License and copyright ownership: GF forwarding

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot can you add this in an example.     Is it not problematic to depend on the QP solver?

**Comment by sloriot** [comment]
@afabri It's not a new dependency as it is only documenting an internal function. I don't think an example is needed, you provide a range of plane and get a point as output, there is no added value IMO.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-228.shtml

**Comment by lrineau** [comment]
I cannot merge this PR because it fails on Travis.

**Comment by maxGimeno** [comment]
https://travis-ci.com/github/CGAL/cgal/jobs/371271834#L7477

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-3.shtml

**Comment by lrineau** [comment]
I will merge this PR once the `CHANGES.md` file is modified. Note that the text of the `CHANGES.md` should be part of the review of the small feature.

**Pull request merged**
