### PR TITLE
Mesh_3: Add back missing consts

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by lrineau** [comment]
We should be careful. That change may break user-code, with domain or criteria classes with non-const call operators.

**Comment by sloriot** [comment]
The constness was removed from 5.5. The impl functions uses `const&`

**Comment by sloriot** [comment]
So I somehow restore something that was mistakenly removed

**Comment by lrineau** [comment]
> The constness was removed from 5.5. The impl functions uses `const&`

According to git blame, the culprit PR was https://github.com/CGAL/cgal/pull/6642, merged in `master` for 5.6, not 5.5.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-184

**Pull request merged**
