### PR TITLE
Use CGAL_USE to avoid g++6.0 warning

### PR DESCRIPTION
**Pull request by afabri**
Warning issued on platform  Ubuntu-latest-GCC6-Release_?

### CODE REVIEW

**Comment by afabri** [comment]
Similar warnings were in the packages Circulator, Triangulation, Voronoi_diagram_2, and Visibility_2

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-105

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-106

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-107

**Pull request merged**
