### PR TITLE
Add the maximal perimeter as an argument to the executable

### PR DESCRIPTION
**Pull request by afabri**
I merged it into integration.

### CODE REVIEW

**Comment by sloriot** [comment]
Do you want to target 4.7 or 4.8 is OK?

**Comment by afabri** [comment]
whatever is easier for the release management

**Comment by sloriot** [comment]
Merged in Merged into [4.8-Ic-4](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-4.shtml)

**Comment by sloriot** [comment]
Previous testsuite was incomplete.
Merged in [CGAL-4.8-Ic-5](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-5.shtml)

**Pull request merged**
