### PR TITLE
Provide a better dependency check in GraphicsView

### PR DESCRIPTION
**Pull request by bo0ts**
Numerous alpha testers have complained about not knowing what Qt5 components are required. Improve the message and up the code quality a little.

### CODE REVIEW

**Comment by lrineau** [comment]
Do you trust the patch enough that we can expect it in CGAL-4.7-beta1?

**Comment by bo0ts** [comment]
Yes, IMO good for 4.7. The logic change is quite minimal. The large diff is the unfortunate result of fixing the indent after inverting the if branches.

**Comment by bo0ts** [comment]
I just moved this branch to integration and it merged cleanly, but it has merge conflicts with https://github.com/CGAL/cgal/commit/21e6e8bcc1396cd3344a329b437d2a6ba13dc27a#diff-b33b08fac51a9e0f9e83c5678be72681L17

will resolve them by rebasing.

**Comment by lrineau** [comment]
I have reverted the merge of this branch in `integration`, because there was a conflict.

**Comment by lrineau** [comment]
I have eventually reverted the revert, and remerged.

**Comment by bo0ts** [comment]
Ic-107 looks good to me.

**Comment by lrineau** [comment]
Philipp, I let you clean-up your branch.

**Pull request merged**
