### PR TITLE
Aos_2: non symetrical observer

### LINKED ISSUE #1956: Arrangement_2: Non-symetrical observer notification of insert/remove edge
## Issue Details

As initially reported on the [cgal-discuss mailing list](https://sympa.inria.fr/sympa/arc/cgal-discuss/2017-03/msg00004.html). The notification order when calling the free-function insert/remove edge is not symetrical:

### When inserting a (isolated) segment:
- Before create vertex
- After create vertex
- Before create vertex
- After create vertex
- Before create Edge
- After create edge

### When removing a (isolated) segment:
- Before remove edge
- Before remove vertex
- After remove vertex
- Before remove vertex
- After remove vertex
- After remove edge

Please note the 'remove vertex' surrounded by 'begin remove edge' and 'after remove edge', this is not the case when inserting a segment.

### Expected
I think it is important to have a consistent notification ordering, and i think the 'insert' case is the correct behaviour, as per documentation: ```before_foo_bar()``` is called **just** before foo-ing a bar. and ```after_foo_bar()``` is called **just** after foo-ing a bar.

## Source Code

The early call to ```_notify_before_remove_edge``` is at L4425 of Arrangement_on_surface_2_impl.h, function:
```C++
template <typename GeomTraits, typename TopTraits> 
typename Arrangement_on_surface_2<GeomTraits, TopTraits>::DFace*
Arrangement_on_surface_2<GeomTraits, TopTraits>::
_remove_edge(DHalfedge* e, bool remove_source, bool remove_target)
```

## Environment

KUbuntu 64 bits, with distro provided CGAL and boost, no other dependencies or 'weird' flag/macros. ...

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

When removing an edge from an arrangement and the user has requested to remove the end-vertices in case they become redundant (either isolated or approach infinity), defer the removal of the such end-vertices to occur after the observer is notified that the edge has been removed. This is symmetric (opposite) to the order of notification when an edge is inserted.

This fix does not completely resolve the issue. The notifications occur when inserting an edge and removing and edge are still not completely symmetric, because of notifications related to ccb's (connected component of the boundaries):

**Insert:**
```
before_create_vertex
after_create_vertex
before_create_vertex
after_create_vertex
before_create_edge
after_create_edge
before_add_inner_ccb
after_add_inner_ccb
```

**Remove:**
```
before_remove_edge
before_remove_inner_ccb
after_remove_inner_ccb
after_remove_edge
before_remove_vertex
after_remove_vertex
before_remove_vertex
after_remove_vertex
```

I've decided to fix the issue in two steps (over 2 succeeding releases) because:
1. This change breaks somehow backward compatibility.
2. Notifications related to ccbs are less important.
3. I'm not sure which of the current orders (either of the insertion or of the removal) is desired. I lean towards following the order of the removal; that is:

**Insert:**
```
before_create_vertex
after_create_vertex
before_create_vertex
after_create_vertex
before_create_edge
before_add_inner_ccb
after_add_inner_ccb
after_create_edge

```
**Remove:**
```
before_remove_edge
before_remove_inner_ccb
after_remove_inner_ccb
after_remove_edge
before_remove_vertex
after_remove_vertex
before_remove_vertex
after_remove_vertex
```

BW, the user can restore old (non-symmetric) behaviour by defining the macro:

  `CGAL_NON_SYMETRICAL_OBSERVER_EDGE_REMOVAL_BACKWARD_COMPATIBILITY`

## Release Management

* Affected package(s): 2D_arrangement_on_surface
* Issue(s) solved (if any): fix #1956 (partially)
* Feature/Small Feature (if any):

### CODE REVIEW

**Comment by lrineau** [comment]
This PR was tested last night, and the Arrangement testsuite is fully red:
```
   ERROR:    execution of test_observer
```
Do you reproduce that error locally?

**Comment by efifogel** [comment]
Yes, this was my fault.
I'm using the new ctest, which is great, by the way, but I have to get use
to it...
Anyhow, fixed & pushed.
Thanks.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Thanks Efi. It will be tested again tonight...

**Comment by lrineau** [comment]
The test for Aos_2 are not good.
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-121.shtml#Arrangement_on_surface_2

At least the columns:
- `Windows10_MSVC2013-Debug-64bits`, and 
- `Windows10_MSVC2017-Release-64bits
show new runtime errors. I do not know if the issue is with this PR #2671 or the other one #2617 that was also tested last night.

@afabri @janetournois, could you try the local testsuite of Aos_2 with one or the other?

**Comment by efifogel** [comment]
I've fixed a real problem, committed, and pushed.
You can try it again.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Tested in [CGAL-4.12-Ic-124](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-124)

**Comment by sloriot** [comment]
@efifogel Issue #1956 was automatically closed when I merged this PR. You might want to either reopen the issue or create a new one to indicate what remains to be done.

**Pull request merged**
