### PR TITLE
Polyhedron_3 and TDS_3 compare handle nullptr

### PR DESCRIPTION
**Pull request by GilesBathgate**
## Summary of Changes

This uses the nullptr comparison operators of Compact_container to check for an empty handle instead of using an instance of an empty handle.  I think this is clearer semantically, and possibly slightly more performant.

The same operators are then added to In_place_list, and vector_iterator. Comparisons to nullptr utilised in the same way.

The change also suppresses some static analysis warnings about usage after explicit null.

## Release Management

* Affected package(s): Polyhedron_3 and TDS_3
* Issue(s) solved (if any): cleaning
* License and copyright ownership: Returned to CGAL authors.

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by afabri** [comment]
@maxGimeno I guess that this PR is responsible for the red line, of the package `Polyhedron`, in [today's testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-119.shtml). Can you  try to fix it.

**Comment by afabri** [comment]
@maxGimeno what are the warnings?

**Comment by GilesBathgate** [comment]
@afabri Was this not the warnings in the test suite (that I think I've already fixed?)

**Comment by maxGimeno** [comment]
@GilesBathgate yes it was. Thnaks for that

**Comment by maxGimeno** [comment]
I guess what @afabri wants to know is why I added a flag, and the answer is in the description of the PR : 

> The change also suppresses some static analysis warnings about usage after explicit null.

**Comment by GilesBathgate** [comment]
@afabri @maxGimeno I wonder if the CGAL developers have ever looked at using clang-analyser https://clang-analyzer.llvm.org/ it could provide some of these kinds of warnings in your testsuite...

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-128.shtml

**Pull request merged**
