### PR TITLE
Tetrahedral remeshing - fix edge split step

### LINKED ISSUE #5235: Tetrahedral remeshing: bug with custom selection of cells
## Issue Details

Take `Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp` from either `5.1.x-branch` or `master`, apply the following patch:
```patch
diff --git a/Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp b/Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp
index 6f108c48789..9dd7e959c77 100644
--- a/Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp
+++ b/Tetrahedral_remeshing/examples/Tetrahedral_remeshing/tetrahedral_remeshing_of_one_subdomain.cpp
@@ -22,7 +22,9 @@ public:
 
   bool operator()(Remeshing_triangulation::Cell_handle c) const
   {
-    return m_subdomain == c->subdomain_index();
+    return m_subdomain == c->subdomain_index() &&
+      CGAL::centroid(c->vertex(0)->point(), c->vertex(1)->point(),
+                     c->vertex(2)->point(), c->vertex(3)->point()).x() <= -0.3;
   }
 };
 
@@ -39,4 +41,3 @@ int main(int argc, char* argv[])
 
   return EXIT_SUCCESS;
 }
-
```

The idea from @xiaoXiaoCam was to experiment with a custom selection of sub-part of a sub-domain.

Then that code crashes with both 5.1.x and `master`:

```
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: si != Surface_patch_index()
File: /home/lrineau/Git/cgal-5.1.x/Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/smooth_vertices.h
Line: 616
```

It seems the issue seems to be that a vertex is on the border of the selection but not on the border of a sub-domain.

The bug is quite urgent because Xiao's work on that topic is stuck. As a workaround, he will experiment with the isotromic remeshing of the boundary of the mesh, instead of the full mesh.

## Source Code

You can also get the files from https://gist.github.com/lrineau/c598fbc2cccbfaa3e05e758fe4b178ad.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux, but probably cross-platform
* Compiler: GNU c++ 10.2
* Release or debug mode: Debug
* CGAL version: 5.1.x, 5.2.x, `master`
* Boost version: n/a

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

During the splitting edges step, some vertices could get a wrong value for their `dimension` (the smallest dimension of the geometric components they belong to), because an edge can have its 2 end vertices on some surface patches/feature polylines, and still be in the interior of the domain.

## Release Management

* Affected package(s): Tetrahedral_remeshing
* Issue(s) solved (if any): fix #5235 
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
@xiaoXiaoCam @lrineau this patch should fix your issue with tetrahedral remeshing.
It should work now :-)

**Comment by lrineau** [comment]
@maxGimeno This pull-request is important for us. It should be tested.

**Comment by maxGimeno** [comment]
Warnings: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-16/Tetrahedral_remeshing/TestReport_lrineau_Fedora-with-LEDA.gz

**Comment by maxGimeno** [comment]
Error: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-16/STL_Extension/TestReport_lrineau_Debian-stable-Release.gz

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-19.shtml

**Pull request merged**
