### PR TITLE
Fix CC selection in selection item

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary

And remove CC selection from the deformation item, where it had limited use.

## Release Management

* Affected package(s): `Lab`
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): - 
* License and copyright ownership: no change

### CODE REVIEW

**Comment by sloriot** [comment]
Works as expected, thanks! One remark: Components is now the default tab, it should be Simplices IMO

**Comment by afabri** [comment]
> Works as expected, thanks! One remark: Components is now the default tab, it should be Simplices IMO

And in Simplices it should be faces    (statistically for me).

**Comment by MaelRL** [comment]
> > Works as expected, thanks! One remark: Components is now the default tab, it should be Simplices IMO
> 
> And in Simplices it should be faces (statistically for me).

There are a lot of instances of "facet(s)", so I leave it out of scope of this PR.

**Comment by sloriot** [comment]
> > > Works as expected, thanks! One remark: Components is now the default tab, it should be Simplices IMO
> > 
> > 
> > And in Simplices it should be faces (statistically for me).
> 
> There are a lot of instances of "facet(s)", so I leave it out of scope of this PR.

I guess Andreas meant putting face(t)s as default selected simplex instead of vertex

**Comment by MaelRL** [comment]
The plugin uses everywhere the combo box ID (aka the position of "Facet" or "Vertex" in the list of options) so it's a lot more work than just changing the order in the UI. Not worth it right now.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-257

**Comment by afabri** [comment]
> Successfully tested in CGAL-6.0-Ic-257

Do we have to test it in the GUI on a Windows machine?

**Comment by MaelRL** [comment]
> > Successfully tested in CGAL-6.0-Ic-257
> 
> Do we have to test it in the GUI on a Windows machine?

Can't hurt, both for the buttons that i have reorganized and so you can check the behavior of the CC buttons since you had the issue.

Note that I left a behavior that a bit is surprising at first but makes sense : when you click "select CCs with simplices count under threshold", it updates the threshold to a new value. That new value is the number of simplices for the next smallest, unselected CC. Thus, you keep clicking and it adds one CC at the time.

**Comment by lrineau** [comment]
> > Successfully tested in CGAL-6.0-Ic-257
> 
> Do we have to test it in the GUI on a Windows machine?

I have actually merged the pull-request. Now the GUI can be tester from a build of CGAL Lab from `master`.

**Pull request merged**
