### PR TITLE
Surface Mesh Topology: Test Whether a Closed Curve is Homotopic to a Simple Cycle

### PR DESCRIPTION
**Pull request by gdamiand**
## Summary of Changes

 This PR adds a function `CGAL::Surface_mesh_topology::Curves_on_surface_topology::is_homotopic_to_simple_cycle()` which can be used to determine whether there exists a continuous deformation of the input curve that makes it a cycle without self-intersection. This feature is part of GSOC 2020.

This PR replace #4898 to simplify the integration.
 
## Release Management
* Affected package(s): `Surface_mesh_topology`
* Feature/Small Feature: [Small feature page on CGAL wiki](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Test_simplicity_of_closed_curve_up_to_homotopy), Pre-approved. Gdamiand 17:08, 4 February 2021 (CET)
* Link to compiled documentation: [Documentation](http://www.cs.umd.edu/~shuhao/CGAL/Surface_mesh_topology/index.html)
* License and copyright ownership: signed CLA to CNRS
* **TODO:**
  
  * [x]  check branch size (@sloriot)

### CODE REVIEW

**Comment by gdamiand** [comment]
Pre-approved 4 February 2021; thus approved since 18 February.

**Comment by sloriot** [comment]
@gdamiand ready to be tested?

**Comment by gdamiand** [comment]
> @gdamiand ready to be tested?

Yes.

**Comment by sloriot** [comment]
FYI, no warning no runtime error for tests and examples of the package on my linux (nor doxygen warning).

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-74.shtml

**Pull request merged**
