### PR TITLE
Mesh_3::Add handling of *.nii files in one example

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

While the Polyhedron demo can read `*.nii` files there is no example in `examples/Mesh_3/`.
This PR adds the functionality to the example that uses vtk to read DICOM data.

This is triggered by [this question](https://stackoverflow.com/questions/77331075/is-there-an-easy-way-to-convert-from-nifti-nii-image-format-to-inr) on stackoverflow.

- [ ] Support of `*.nrrd` format
- [ ] example for segmented images
- [ ] Add example data for the file formats.

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-96

**Comment by lrineau** [comment]
@afabri This PR still have several TODO items. Should I wait or merge it?

**Comment by afabri** [comment]
> @afabri This PR still have several TODO items. Should I wait or merge it?

Wait.

**Comment by sloriot** [comment]
Successfully tested in 6.0-Ic-251

**Pull request merged**
