### PR TITLE
CGAL CTest support: rename the test names

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Now that CTest test names can contain whitespace, we can have better looking names. That is also more practicle because we can now copy-paste the target name in `compilation of  <target_name>`.

## Release Management

* Affected package(s): All CGAL

### CODE REVIEW

**Comment by albert-github** [comment]
Interesting and reasonably new (I think around version 3.19 (so November 2020).
Is the `cmake_minimum_required` as seen in the `CMakeLists.txt` files still correct?

**Comment by albert-github** [comment]
I don't see anywhere in the repository `cmake_minimum_required(VERSION 3.11...3.23)`, on most places it is:
- `cmake_minimum_required(VERSION3.1...3.23)`
- and on a few `cmake_minimum_required(VERSION3.1...3.20)`:
  - `SMDS_3/examples/SMDS_3/CMakeLists.txt`
  - `SMDS_3/test/SMDS_3/CMakeLists.txt`

**Comment by lrineau** [comment]
As I said, that is in `cmake/modules/CGAL_SetupCGALDependencies.cmake`, here in the current version of `master` as of today:

https://github.com/CGAL/cgal/blob/d979e070bee8f49344125f58e298be51eba84838/Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake#L26-L26

That file is included by anything that uses the CMake API of CGAL (using `CGALConfig.cmake`), because it defines the properties of the imported target `CGAL::CGAL`.

**Comment by lrineau** [comment]
> and on a few `cmake_minimum_required(VERSION3.1...3.20)`:
>     * `SMDS_3/examples/SMDS_3/CMakeLists.txt`
>     * `SMDS_3/test/SMDS_3/CMakeLists.txt`

Before the release of CGAL-5.6, we will unify everything to `3.11...3.26`.

**Comment by lrineau** [comment]
`Documentation/doc/CMakeLists.txt` probably works with older versions of CMake.

Anyway, we should probably install easier version of CMake in our CI actions, to check our claims.

**Comment by lrineau** [comment]
I have refreshed this PR to remove the conflict with `master` (that came from #6835).

**Comment by sloriot** [comment]
Tests failing in CGAL-5.6-Ic-222 (at least on all windows platform)

**Comment by lrineau** [comment]
> Tests failing in CGAL-5.6-Ic-222 (at least on all windows platform)

My bad. The commit 12c8e60e6eef2c3ced0145aac6bb1c18df0021ac is a fix attempt.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-229

**Pull request merged**
