### PR TITLE
2D reconstruction: rename package

### PR DESCRIPTION
**Pull request by sgiraudot**
This PR addresses the following issue: https://github.com/CGAL/cgal/issues/795

I compiled and ran:
* The documentation
* The demo
* The examples
* The tests

No error and no warning on my computer.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-140

**Comment by sloriot** [comment]
Some warnings were generated on windows because the name is now too long for the demo path

**Comment by sgiraudot** [comment]
I shortened the names of the files of the demo. I think that should be enough without renaming the folder (the examples and test have the same folder name and do not raise any warning).

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-145

**Comment by lrineau** [comment]
This PR forgot to rename the package title in `changes.html`. @sgiraudot, can you please handle the renaming in that file as well?

**Comment by sgiraudot** [comment]
Oh yes, sorry! I'll take care of this right away.

**Comment by afabri** [comment]
Looks like noise to me, if it was in changes.html

**Comment by lrineau** [comment]
> Optimal Transportation Curve Reconstruction (new package)

That is the only new package in CGAL-4.8. It cannot be considered as a noise!

**Comment by afabri** [comment]
I misunderstood: I thought you meant that the last minute renaming of the package should be mentioned.

**Pull request merged**
