### PR TITLE
Triangulation_3: Accelerate point insertion

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Filling the cavity of a conflict zone used `next_around_edge()` on the outside of the boundary to identify neighboring new cells.  This got replaced with a small custom hash map, inspired by geogram.  
Additionally, replaced some `std::vector` by `boost::small_vector`.

## Release Management

* Affected package(s): Triangulation_3
* License and copyright ownership: maintenance so IP remains at inria sophia

### CODE REVIEW

**Comment by lrineau** [comment]
I have rebased the PR on 4.14.x, effortless. The CTest testsuite of `Triangulation*` passes on my machine.

**Comment by MaelRL** [comment]
Travis is now unhappy because I changed the license to the newer format in e4cbed0 when the branch targeted master.

**Comment by maxGimeno** [comment]
It will have to be dealt with branch by branch at the merge I guess

**Comment by maxGimeno** [comment]
Warning : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-27.shtml. 
Choose any yellow square :)

**Comment by lrineau** [comment]
I am looking at the Mesh_3 issue, currently...

**Comment by lrineau** [comment]
[**@MaelRL**](https://github.com/MaelRL) commented on [Dec 10, 2019, 8:07 AM GMT+1](https://github.com/CGAL/cgal/pull/4397#issuecomment-563897097 "2019-12-10T07:07:34Z - Replied by Github Reply Comments"):
> Travis is now unhappy because I changed the license to the newer format in e4cbed0 when the branch targeted master.

Actually, this branch cannot apply to 4.14.x, because of the use of `constexpr`. It will be only for 5.0.x.

**Comment by MaelRL** [comment]
I noticed that the function `construct_point()` (https://github.com/CGAL/cgal/blob/master/Triangulation_3/include/CGAL/Triangulation_3.h#L566) ought to return a const& for basic triangulations.

with
```
- Point_3
+ typename boost::result_of<const typename Geom_traits::Construct_point_3(const P&)>::type
```
I seem to be gaining a handful of % on a rough benchmark. I fixed it in another branch, but it might be worth putting it here too?

**Comment by lrineau** [comment]
[**@MaelRL**](https://github.com/MaelRL) commented on [Dec 12, 2019, 1:16 PM GMT+1](https://github.com/CGAL/cgal/pull/4397#issuecomment-564983137 "2019-12-12T12:16:54Z - Replied by Github Reply Comments"):
> I noticed that the function `construct_point(): https://github.com/CGAL/cgal/blob/254d60f642a5e6f95803fec7ab2189a5c95e1d3f/Triangulation_3/include/CGAL/Triangulation_3.h#L566
> ought to return a const& for basic triangulations. With
> ```
> - Point_3
> + typename boost::result_of<const typename Geom_traits::Construct_point_3(const P&)>::type
> ```
> I seem to be gaining a handful of % on a rough benchmark. I fixed it in another branch, but it might be worth putting it here too?

As the branch is for 5.0.1 (with C++14), we can even use `decltype(auto)` instead of the complicated type with `result_of`.

**Comment by afabri** [comment]
Maybe I do something wrong, but with VC2019 just using `Point_3`  it is faster than using  `result_of`, `decltype` or `const Point_3&`.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-31.shtml

**Pull request merged**
