### PR TITLE
Fix CMake warnings about CMP for Visual 2017

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Fixes the cmake warnings about cmp0071 and CMP0074 .

### CODE REVIEW

**Comment by afabri** [comment]
@maxGimeno there remain some to fix

**Comment by maxGimeno** [comment]
@lrineau if you look at Peridoic_2_triangulation_2, you'll see I have set the policy for CMP0071, and yet the testsuite results keep warning about it not being set. Do you know why and how to fix this ?

**Comment by lrineau** [comment]
I think this PR was not merged in 'integration'.

**Comment by maxGimeno** [comment]
well why are there like 16 warnings less and this line:

e9cb358 Merge pull request #3470 from maxGimeno/CMake-Fix_warnings_for_CMP0071-GF
  parents: 6c4b020 d6cfa1a

 at the beginning of the report then ?

**Comment by lrineau** [comment]
There was another line
```cmake
 cmake_minimum_required(VERSION 3.1)
```
later in the file. And that resets the policies. I have pushed the removal of several lines, in https://github.com/CGAL/cgal/pull/3470/commits/6c72c9fa06f01f5022d29b485b98193a6c5892d3.

**Comment by maxGimeno** [comment]
No more warnings.

**Pull request merged**
