### PR TITLE
Doc improvements for TDS-related classes

### LINKED ISSUE #4621: SDG2: Missing storage classes in documentation
The doc says:
```
CGAL::Segment_Delaunay_graph_2< Gt, DS >
```
but the actual code is:
```
template<class Gt,
         class ST = Segment_Delaunay_graph_storage_traits_2<Gt>,
         class D_S = Triangulation_data_structure_2 <
		                Segment_Delaunay_graph_vertex_base_2<ST>,
		                Segment_Delaunay_graph_face_base_2<Gt> >,
         class LTag = Tag_false >
class Segment_Delaunay_graph_2;
```

The template parameter corresponding to the second template parameter is missing, the class `Segment_Delaunay_graph_storage_traits_2` (and its concept?) are undocumented.

This seems to be the case across the whole package (maybe in SDG2_inf too?).

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

The base goal of this branch was to properly document the requirements of the base vertex / face / cell classes in the data structure template parameter.

On the way I noticed some other issues (missing concepts, etc.) and mainly that the documentation of the package `Segment_Delaunay_graph_2` had a lot of issues. Those issues come from the fact that a large update was added to SDG2 and only partially reverted, a long time ago.

Not fixed in SDG2 in this PR:
- all undocumented "simple" classes
- all classes related to sites with `info()` are not documented but they appear in examples
- In_place_edge_list abuses

TODO:
- [x] Announce the removal of deprecated classes.

## Release Management

* Affected package(s): `Many`
* Issue(s) solved (if any): fix #4621
* Feature/Small Feature (if any): -
* License and copyright ownership: No change

### CODE REVIEW

**Comment by MaelRL** [comment]
/build:v0.1

**Comment by maxGimeno** [comment]
Errors on MSVC <2019 : 
```
C:\CGAL\test\CGAL-5.3-Ic-63\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Release-64bits\test\Voronoi_diagram_2\vda_sdg.cpp(115): fatal error C1060: compiler is out of heap space
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'
```

**Comment by MaelRL** [comment]
> Errors on MSVC <2019 :
> 
> ```
> C:\CGAL\test\CGAL-5.3-Ic-63\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Release-64bits\test\Voronoi_diagram_2\vda_sdg.cpp(115): fatal error C1060: compiler is out of heap space
> NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'
> ```

Seems like an issue with the compiler since the code was correct, but anyway the commit was just aligning the code with the concept (SDG2 Vb needing a T2 Vb as template parameter), but that requirement is wrong (SDG2 Vb only needs a TDS2 Vb since the point geometry brought by T2 Vb is meaningless), so I have changed the concept and reverted the code change.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-65.shtml

**Comment by lrineau** [comment]
This PR is tested, but it still have a TODO in its first message, and the file `CHANGES.md` was not modified.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-74.shtml

**Pull request merged**
