### PR TITLE
LCC demo

### PR DESCRIPTION
**Pull request by gdamiand**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Update the LCC demo, and the LCC basic viewer, in order to factorize the code.

There is no modification of documented api.

Plus one bug fix in Buffer_for_vao.h, in the method is_facet_convex (which is used by the polyhedron demo).

## Release Management

* Affected package(s): LCC

### CODE REVIEW

**Comment by maxGimeno** [comment]
Well, I tried with several more or less challenging meshes and nothing crashed, so I'd say it works.

**Comment by gdamiand** [comment]
Should be ok after https://github.com/CGAL/cgal/pull/3488/commits/c2665415cd37264c37202682d435b449dea3c720

**Comment by maxGimeno** [comment]
Thanks !

**Comment by maxGimeno** [comment]
warnings of unused variables :https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-58.shtml#Linear_cell_complex_Demo

**Comment by gdamiand** [comment]
Corrected in https://github.com/CGAL/cgal/pull/3488/commits/12ae925f317cf92a471ad5d9b37ebc31addff5c7

**Comment by maxGimeno** [comment]
Thank you !

**Pull request merged**
