### PR TITLE
Fix linking issue with VTK for Mesh_3 Polyhedron demo

### PR DESCRIPTION
**Pull request by alefy**
Fix following linking issue (with macOS big-sur / llvm-clang12) when linking Polyhedron demo to VTK (libio_image_plugin.so)
```
Undefined symbols for architecture x86_64:
  "vtkImageGaussianSmooth::New()", referenced from:
      Io_image_plugin::createDCMImage(QString) in Io_image_plugin.cpp.o
ld: symbol(s) not found for architecture x86_64
```

## Summary of Changes
Found working fix : add `VTK::ImagingGeneral` to `VTK_LIBRARIES` alongside `VTK::IOImage` in `Polyhedron/demo/Polyhedron/Plugins/Mesh_3/CMakeLists.txt`

## Release Management

* Affected package(s): Polyhedron (demo/Plugins/Mesh_3)
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): NA
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by lrineau** [comment]
@maxGimeno This pull-request should be rebased for CGAL-5.1.x, because the bug is already there.

**Review by lrineau — APPROVED** [review]

**Comment by maxGimeno** [comment]
@alefy can you please add me as a collaborator so I can rebase your PR before we start testing it ?

**Comment by alefy** [comment]
@maxGimeno collaborator invite should have been sent.
Let me know if you did not received it.
Thank you

**Comment by maxGimeno** [comment]
done

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-128.shtml

**Pull request merged**
