### PR TITLE
Polygon Mesh Processing: fix stitching

### PR DESCRIPTION
**Pull request by sloriot**
doc and code bug-fixes

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.7-Ic-103](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-103.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.7-Ic-103](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-103.shtml)

**Comment by lrineau** [comment]
Should it be in CGAL-4.7?

**Comment by lrineau** [comment]
I prefer that we try to fix everything before the release of CGAL-4.7-beta1.

**Comment by sloriot** [comment]
Successfully tested in CGAL-4.7-Ic-104

**Pull request merged**
