### PR TITLE
Avoid a construction in segment traits

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by efifogel** [comment]
Just to make sure that I understand: we actually save the comparison of the
2 representative points on the line.
(Cause we already have a left and right points)
Right?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
The old code construct the equation of the line + evaluate the equation at a given while here we do a direct computation on the input (which are segment endpoints).

**Comment by efifogel** [comment]
Ah, even better!
I approved, of course.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-35.shtml

**Pull request merged**
