### PR TITLE
Number_types: doc fix for leda_integer

### LINKED ISSUE #6894: Number_types: inconsistent representation of Q, R, Z
In the package Number_types we see:

image

image

and even

image

It is a bit strange that the `Z` is in a different type than the `R` and the mix of the `Q` especially seen the logo with the package:

image

Is there any explanation for this? or is it just an inconsistency or a bug.

### PR DESCRIPTION
**Pull request by afabri**
## Release Management

* Affected package(s): Number_types
* Issue(s) solved (if any): fix #6894

### CODE REVIEW

**Comment by albert-github** [comment]
I think there are a few more places in the Numbert_types that need checking (a bit unfiltered:
```
Number_types/doc/Number_types/CGAL/CORE_BigInt.h:The class `CORE::BigInt` provides exact computation in \f$ \Z\f$.
Number_types/doc/Number_types/CGAL/CORE_BigRat.h:The class `CORE::BigRat` provides exact computation in \f$ \Q\f$.
Number_types/doc/Number_types/CGAL/double.h:Determines whether the argument represents a value in \f$ \mathbb{R}\f$.
Number_types/doc/Number_types/CGAL/float.h:Determines whether the argument represents a value in \f$ \mathbb{R}\f$.
Number_types/doc/Number_types/CGAL/leda_integer.h:The class `leda_integer` provides exact computation in \f$ \Z\f$.
Number_types/doc/Number_types/CGAL/leda_rational.h:The class `leda_rational` provides exact computation in \f$ \mathbb{Q}\f$.
Number_types/doc/Number_types/CGAL/long_double.h:Determines whether the argument represents a value in \f$ \mathbb{R}\f$.
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:For example, let `Integer` be some type representing \f$ \Z\f$, then
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:`Sqrt_extension<Integer,Integer>` is able to represent \f$ \Z[\sqrt{\mathrm{root}}]\f$
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:for some arbitrary Integer \f$\mathrm{root}\f$. \cgalFootnote{\f$ R[a]\f$ denotes the extension of a ring \f$ R\f$ by an element \f$ a\f$. See also: <A HREF="http://mathworld.wolfram.com/ExtensionRing.html">\cgalFootnoteCode{http://mathworld.wolfram.com/ExtensionRing.html}</A>}
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:Arithmetic operations among different extensions, say \f$ \Z[\sqrt{a}]\f$
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:and \f$ \Z[\sqrt{b}]\f$, are not supported.
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:The result would be in \f$ \Z[\sqrt{a},\sqrt{b}]\f$, which is not
Number_types/doc/Number_types/CGAL/Sqrt_extension.h:`EuclideanRing` is just an `IntegralDomain`, since the extension in general destroys the unique factorization property. For instance consider \f$ \Z[\sqrt{10}]\f$, the extension of \f$ \Z\f$ by \f$ \sqrt{10}\f$: in \f$ \Z[\sqrt{10}]\f$ the element 10 has two different factorizations \f$ \sqrt{10} \cdot \sqrt{10}\f$ and \f$ 2 \cdot 5\f$. In particular, the factorization is not unique.
```

**Comment by albert-github** [comment]
I think setting it to `under testing` is a bit too early especially seen my comment: https://github.com/CGAL/cgal/pull/6895#issuecomment-1259618932  e.g.: Number_types/classCGAL_1_1Sqrt__extension.html


image

**Comment by MaelRL** [comment]
The "Under testing" flag doesn't mean that the PR is in its final iteration. The idea here was likely that it does not hurt to test even an intermediate version.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-79

**Comment by lrineau** [comment]
> Successfully tested in CGAL-5.6-Ic-79

But there is still a TODO label, that seems related to that message https://github.com/CGAL/cgal/pull/6895#issuecomment-1259709258.

**Comment by afabri** [comment]
@lrineau Shall we replace this PR by     https://github.com/afabri/cgal/tree/Number_types-doc_leda_integer-GF

**Comment by albert-github** [comment]
I'm getting a bit confused by git in this case (my problem),  I think that the commit by @afabri is a bit more extensive, though I'm missing the original change from this PR #6895.
The commit by @afabri also changes some true / false / RT / FT so that they are seen as code and not running text (is a good idea (later on we can do a full search to find other occurrences of this in the repository ....).

**Comment by lrineau** [comment]
Replaced by https://github.com/CGAL/cgal/pull/6929. @albert-github Please review the new pull-request.

**Pull request closed without merging**
