### PR TITLE
Fix Euler::add_vertex_and_face_to_border()

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Bug fix

## Release Management

* Affected package(s): BGL, Polyhedron Demo

### CODE REVIEW

**Comment by sloriot** [comment]
The PR should be over the 4.11 branch.

**Comment by sloriot** [comment]
Nope, you need to rebase your branch onto the 4.11.1 or you'll bring all the changes from master.

**Comment by lrineau** [comment]
I think there should be a test. That code was wrong previously only because it was not tested correctly.

**Comment by afabri** [comment]
@lrineau  this must go in 4.12.

**Pull request merged**
