### PR TITLE
Deal with an empty range as input

### PR DESCRIPTION
**Pull request by afabri**
See #1577

### CODE REVIEW

**Comment by sloriot** [comment]
Why did you open another pull request for the same fix?

**Comment by afabri** [comment]
Because it is for 4.9

**Comment by sloriot** [comment]
Then just push force into the other PR and we can edit the base onto which the PR applies (a relatively new feature of github, that Laurent annonced on cgal-develop some time ago).

**Comment by sloriot** [comment]
I just did it.

**Comment by lrineau** [comment]
Replaced by #1577.

**Pull request closed without merging**
