### PR TITLE
Add a hook CGAL_hook_fix_ctest_dependencies

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Add a hook `CGAL_hook_fix_ctest_dependencies`.

This hook function detects dependencies between targets tests, and add proper dependencies between compilation tests of those targets.

## Release Management

* Affected package(s): Installation, Polyhedron/demo

### CODE REVIEW

**Comment by lrineau** [comment]
Actually, this could be a bug fix for release branches as well, but the patch is quite heavy.

@sloriot Do you want to fix the CMake issues in the testsuite for release branches as well?

**Comment by sloriot** [comment]
> Actually, this could be a bug fix for release branches as well, but the patch is quite heavy.
> 
> @sloriot Do you want to fix the CMake issues in the testsuite for release branches as well?

It does not seem necessary to me.

**Comment by sloriot** [comment]
Windows does not seem to like this change. See 6.0-Ic-168

**Comment by lrineau** [comment]
> Windows does not seem to like this change. See 6.0-Ic-168

Should be fixed by 3664fc8fdb24b99918a256b74c458f0465453121. I have not tested on Windows. I have only test on Linux that there was no regression.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-169

**Pull request merged**
