### PR TITLE
Mesh_3 - `Mesh_criteria_3` cleaning

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

As spotted in PR #7532, there were named parameters available in the constructor of `Mesh_criteria_3` that had never been documented or used.

[This commit](https://github.com/CGAL/cgal-attic/commit/1614a89e32693a9f33394083d75ed11f06209947), written before the publication of Mesh_3 with features in CGAL-3.8, removed the documentation of these criteria before their publication.

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
@lrineau I also added the use of `get_parameter_reference()` for all the parameters that may be a `MeshDomainField_3` (distance and size)

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
Most probably responsible for errors in Mesh_3 test/ex in CGAL-6.0-Ic-112

**Comment by sloriot** [comment]
+ periodic mesh

**Comment by janetournois** [comment]
My last commit 7fdc36d highlights the fact that it was possible to use `facet_size` together with `facet_sizing_field` and `sizing_field`, which was imho confusing, but could still be considered as a feature.
@lrineau do you still agree that we should keep only `facet_size` (and other dimensions counterparts)?

**Comment by lrineau** [comment]
> My last commit [7fdc36d](https://github.com/CGAL/cgal/commit/7fdc36dbbef57506c9431f248c16ee3eeb1d1c58) highlights the fact that it was possible to use `facet_size` together with `facet_sizing_field` and `sizing_field`, which was imho confusing, but could still be considered as a feature. @lrineau do you still agree that we should keep only `facet_size` (and other dimensions counterparts)?

Yes I agree.

**Comment by afabri** [comment]
Maybe this PR is responsible for this [warning](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-118/Mesh_3/TestReport_cgaltester_x86-64_Darwin-18.5_Apple-clang-default_Release.gz):
```
/Users/sloriot/CGAL/testsuite/CGAL-6.0-Ic-118/cmake/platforms/x86-64_Darwin-18.5_Apple-clang-default_Release/test/Mesh_3/test_mesh_criteria_creation.cpp:96:6: warning: unused variable 'facet_size_nok' [-Wunused-variable]
  FT facet_size_nok = radius_facet/FT(10);
     ^
/Users/sloriot/CGAL/testsuite/CGAL-6.0-Ic-118/cmake/platforms/x86-64_Darwin-18.5_Apple-clang-default_Release/test/Mesh_3/test_mesh_criteria_creation.cpp:137:6: warning: unused variable 'cell_size_nok' [-Wunused-variable]
  FT cell_size_nok = radius_cell/FT(10);
     ^
`````

**Pull request merged**
