### PR TITLE
Replace NULL and Nullptr_t with nullptr and nullptr_t

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Replace NULL and Nullptr_t with nullptr and nullptr_t

## Release Management

* Affected package(s): all
* Issue(s) solved (if any): fix #0000

### CODE REVIEW

**Comment by lrineau** [comment]
Please try to compile the packages you modify, before pushing.

**Comment by afabri** [comment]
@maxGimeno ready for testing

**Comment by maxGimeno** [comment]
[warnings](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-57.shtml#Skin_surface_3)

**Comment by maxGimeno** [comment]
/usr/local/include/CGAL/marching_tetrahedra_3.h:56:57: error: redefinition of
      'T_Vertex'
  typedef typename T_Vertex_iterator::value_type        T_Vertex;
                                                        ^
/usr/local/include/CGAL/marching_tetrahedra_3.h:52:57: note: previous definition
      is here
  typedef typename T_Vertex_iterator::value_type        T_Vertex;

**Comment by lrineau** [comment]
The header file `Skin_surface_3/include/CGAL/marching_tetrahedra_3.h` still does not compile:
```
In file included from /home/travis/build/CGAL/cgal/Skin_surface_3/include/CGAL/mesh_skin_surface_3.h:28:
/home/travis/build/CGAL/cgal/Skin_surface_3/include/CGAL/marching_tetrahedra_3.h:144:26: error: use of undeclared identifier 'Cell_handle'
    CGAL_assertion(ch != Cell_handle());
                         ^
/home/travis/build/CGAL/cgal/Skin_surface_3/include/CGAL/marching_tetrahedra_3.h:152:28: error: use of undeclared identifier 'Cell_handle'
      CGAL_assertion(ch != Cell_handle());
                           ^
2 errors generated.
```
https://travis-ci.org/CGAL/cgal/jobs/544716145#L6488

**Comment by lrineau** [comment]
I have fixed the compilation issues in https://github.com/CGAL/cgal/pull/3979/commits/67e73c2324bf99b7fdb0e1943594290706c4364a.

**Comment by maxGimeno** [comment]
Seems all good in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-59.shtml

**Pull request merged**
