### PR TITLE
Fix boost warning (unused typedef)

### PR DESCRIPTION
**Pull request by sgiraudot**
Using `BOOST_STATIC_ASSERT` and `BOOST_CONCEPT_ASSERT` generates warning about unused typedef in many packages and platforms in the testsuite (example on [Point set processing](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-I-114/Point_set_processing_3/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release-cpp11.gz)).

One way to remove this warning is to append `__attribute__((unused))` after the assertion (as described [here](https://svn.boost.org/trac/boost/ticket/7242)). That was actually already included in CGAL with the macro `CGAL_UNUSED` (which is called when using `CGAL_static_assertion` instead of `BOOST_STATIC_ASSERT`). `BOOST_STATIC_ASSERT` shouldn't be used directly in CGAL code.

This PR replaces `BOOST_STATIC_ASSERT` by `CGAL_static_assertion` everywhere and adds `CGAL_UNUSED` after `BOOST_CONCEPT_ASSERT` everywhere it is used.

_(Note: if this macro is to be used more frequently, it might be a good idea to similarly create a `CGAL_concept_assertion` macro that encapsulates the Boost assertion with correct preprocessing tests, `CGAL_UNUSED`, etc.)_

### CODE REVIEW

**Comment by sgiraudot** [comment]
Merged in [4.8-I-116](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-I-116.shtml).

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-117

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-118

**Comment by sloriot** [comment]
The warning is gone

**Pull request merged**
