### PR TITLE
[Small Feature] BGL: Regularize Face Selection Borders

### PR DESCRIPTION
**Pull request by sgiraudot**
## Rationale

Manually selecting faces on a triangle mesh may create irregular borders (sawtooth) because of the shape of the triangles. Such borders can be regularized using `CGAL::alpha_expansion_graphcut()`. This small feature offers an API to easily apply the Alpha Expansion to the borders of a selection on a `FaceGraph`.

## Summary of API changes

A new function `CGAL::regularize_face_selection_borders()` is provided by the BGL package.

## License and copyright ownership

GeometryFactory

## CHANGES.md

After the section about the new alpha expansion function:

```markdown
 -   Added function `regularize_face_selection_borders()` which uses
     this alpha expansion graphcut to regularize the borders of a
     selected faces on a triangle mesh.
```

## Submission

* [__User Manual__](https://cgal.geometryfactory.com/~sgiraudot/BGL-Regularize_face_selection_borders/BGL/index.html#title35)
* [__Reference Manual__](https://cgal.geometryfactory.com/~sgiraudot/BGL-Regularize_face_selection_borders/BGL/group__PkgBGLSelectionFct.html#ga80ba96c028b017aea3e85f0e2031c1e3)

## Status

- Depends on https://github.com/CGAL/cgal/pull/4104
- Developed and locally tested (GNU/Linux)
- [Small Feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Regularize_Face_Selection_Borders) Pre-approved Andreas Fabri 2 April 2020 (CEST)

### CODE REVIEW

**Comment by afabri** [comment]
Typo: Epansion

**Comment by sgiraudot** [comment]
Feature updated accordingly.

**Comment by afabri** [comment]
@sloriot is that really for BGL or should it go to PMP?

**Comment by sloriot** [comment]
There is already a selection section in BGL so it fits pretty well in it.

**Comment by sgiraudot** [comment]
After further discussion with Sébastien, I decided to keep the `vertex_point_map` because it is also internally used to compute areas for normalization of the costs computed on faces (it becomes overly complicated if users have both to give a map for the edges and a map for the faces, they might as well use directly the raw alpha expansion function). I thus added a `geom_traits` parameter to make sure lengths/areas can be computed.

Doc is updated.

**Comment by afabri** [comment]
Do not repeat the parameter name in `is_selected` `is_selected` indicates ...
@sloriot is it a `FaceGraph` or a `TriangleMesh`?

**Comment by sloriot** [comment]
I guess TriangleMesh model of FaceGraph

**Comment by maxGimeno** [comment]
The following files have trailing whitespaces:
BGL/include/CGAL/boost/graph/selection.h

**Comment by maxGimeno** [comment]
Errors in travis
:+1:  /home/travis/build/CGAL/cgal/BGL/include/CGAL/boost/graph/selection.h:175:44: error: no member named 'squared_distance' in namespace 'CGAL'
      double edge_length = std::sqrt(CGAL::squared_distance (get (pmap.rg->vertex_point_map, esource),
                                     ~~~~~~^
/home/travis/build/CGAL/cgal/BGL/include/CGAL/boost/graph/selection.h:581:32: error: no member named 'squared_distance' in namespace 'CGAL'
        out += std::sqrt(CGAL::squared_distance (get (vertex_point_map, esource),
                         ~~~~~~^
2 errors generated.
CMake Error at /home/travis/build/CGAL/cgal/Installation/cmake/modules/run_cmd_redirection_cerr.cmake:32 (message):

**Comment by maxGimeno** [comment]
success in https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-121

**Pull request merged**
