### PR TITLE
bug fix:  set_next() was not called for the opposite edges

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by sloriot** [comment]
If there is no test file, it is useless to test it. Could you add one?

**Comment by lrineau** [comment]
In `BGL/test/BGL/test_helpers.cpp` there is a test of `make_triangle`:
```C++
  Mesh m;
  halfedge_descriptor hd;
  hd = CGAL::make_triangle(a,b,c,m);
  assert(CGAL::is_triangle(hd,m));
  m.clear();
```

There should be also a call to `is_valid(m)`, and also for the other tested functions in the same file.

**Comment by afabri** [comment]
done

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by afabri** [comment]
needs a new round of integration

**Comment by afabri** [comment]
Note that this ideally goes to 4.7

**Comment by lrineau** [comment]
The pull-request is against `master`, and the branch was created from `master`, and not from the bug-fix branch `releases/CGAL-4.7-branch`. I will have to rebase the branch onto `releases/CGAL-4.7-branch`...

**Comment by lrineau** [comment]
I have rebased the branch onto `releases/CGAL-4.7-branch`, and pushed (with `--force`) to your fork to update this pull-request.

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-21][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-21.shtml

**Comment by afabri** [comment]
passes the testsuite. and could go into 4.7

**Comment by lrineau** [comment]
I have merged the branch into `CGAL-4.7-branch`, and then in `master`.

**Pull request merged**
