### PR TITLE
Polygon: Add a function to filter consecutive collinear points in range

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

This PR adds a free undocumented function to the package `Polygon` to filter a range of points and simplify sequences of collinear (or almost collinear) points. A point is removed if the two segments, formed using its previous and next points in the range are collinear segments, up to a given tolerance.

## Release Management

* Affected package(s): `Polygon`
* Issue(s) solved (if any): --
* Feature/Small Feature (if any): --

### CODE REVIEW

**Comment by lrineau** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cgal/cgal/2920)

**Comment by sloriot** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h, line 29 at r1](https://reviewable.io:443/reviews/cgal/cgal/2920#-L7TZqgU2mzHyV4b47iY:-L7TZqgVzO1lwDL9YJNj:bd9kn36) ([raw file](https://github.com/cgal/cgal/blob/b26422705d79bc0a6937c0aec96b7763c3b42209/Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h#L29)):*
> ```objc
> #include <CGAL/Polygon_2/Polygon_2_simplicity.h>
> 
> #include <boost/next_prior.hpp>
> ```

In `CGAL/algorithm.h` there is `cpp11::prev()` and `cpp11::next()`

---

*[Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h, line 62 at r1](https://reviewable.io:443/reviews/cgal/cgal/2920#-L7T_Cq-8jVjD_YU1zvq:-L7T_Cq0kZlF0_qL8zYg:b-c37lco) ([raw file](https://github.com/cgal/cgal/blob/b26422705d79bc0a6937c0aec96b7763c3b42209/Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h#L62)):*
> ```objc
> //
> template<typename K, typename InputForwardIterator, typename OutputForwardIterator>
> void filter_collinear_points(InputForwardIterator first,
> ```

the output iterator should be returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cgal/cgal/2920)*

**Comment by MaelRL** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h, line 29 at r1](https://reviewable.io:443/reviews/cgal/cgal/2920#-L7TZqgU2mzHyV4b47iY:-L7TcXufg0Y9j8Aou-VW:b-896fix) ([raw file](https://github.com/cgal/cgal/blob/b26422705d79bc0a6937c0aec96b7763c3b42209/Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h#L29)):*
<details><summary><i>Previously, sloriot (Sebastien Loriot) wrote…</i></summary><blockquote>

In `CGAL/algorithm.h` there is `cpp11::prev()` and `cpp11::next()`
</blockquote></details>

Done.

---

*[Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h, line 62 at r1](https://reviewable.io:443/reviews/cgal/cgal/2920#-L7T_Cq-8jVjD_YU1zvq:-L7TcaALcNSJuRA32LB6:b-896fix) ([raw file](https://github.com/cgal/cgal/blob/b26422705d79bc0a6937c0aec96b7763c3b42209/Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h#L62)):*
<details><summary><i>Previously, sloriot (Sebastien Loriot) wrote…</i></summary><blockquote>

the output iterator should be returned.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cgal/cgal/2920)*

**Comment by lrineau** [comment]
In Travis CHECK job:
```
  /home/travis/build/CGAL/cgal/Polygon/include/CGAL/Polygon_2/Polygon_2_algorithms_impl.h:97:8:
  error: no member named 'abs' in namespace 'CGAL'; did you mean simply
  'abs'?

      if(CGAL::abs(det) <= tolerance)
         ^~~~~~~~~
         abs

```

**Comment by lrineau** [comment]
In the testsuite `Polygon/test/Polygon/AlgorithmTest.cpp` does not work:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-200.shtml#Polygon

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.12-Ic-207], and then merged.

  [CGAL-4.12-Ic-207]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-207.shtml

**Pull request merged**
