### PR TITLE
Forgot to set the halfedge of the face

### PR DESCRIPTION
**Pull request by afabri**
This should fix Issue #925

### CODE REVIEW

**Comment by maxGimeno** [comment]
Indeed, it seems to work.

**Comment by lrineau** [comment]
This PR should be against `release/CGAL-4.8-branch`.

TODO: I will rebase/cherry-pick the PR, if needed, to include it in CGAL-4.8. @afabri, you will not have anything to do.

**Comment by lrineau** [comment]
The test suite of CGAL-4.9-Ic-1 has its BGL line fully read! For example:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-1/BGL/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz
```
------------------------------------------------------------------
- ProgramOutput.test_Euler_operations.x64_Cygwin-Windows8_MSVC2012-Release-32bits
------------------------------------------------------------------
Program recieved signal SIGSEGV: Segmentation Fault.
```
or: 
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-1/BGL/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz
```
------------------------------------------------------------------
- ProgramOutput.test_Euler_operations.x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8
------------------------------------------------------------------
ASAN:SIGSEGV
=================================================================
==26779==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004f68c1 sp 0x7ffc6a39d220 bp 0x7ffc6a39d250 T0)
    #0 0x4f68c0 in boost::graph_traits<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >::halfedge_descriptor CGAL::Euler::join_vertex<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >(boost::graph_traits<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >::halfedge_descriptor, CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> >&) (/no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/BGL/test_Euler_operations+0x4f68c0)
    #1 0x4e51d6 in void join_vertex_exterior_test<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >() (/no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/BGL/test_Euler_operations+0x4e51d6)
    #2 0x4af18c in void test_Euler_operations<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >() (/no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/BGL/test_Euler_operations+0x4af18c)
    #3 0x4ac928 in main (/no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/BGL/test_Euler_operations+0x4ac928)
    #4 0x7f8a5aa7357f in __libc_start_main (/lib64/libc.so.6+0x2057f)
    #5 0x4ac1d8 in _start (/no-raid/home/lrineau/CGAL/CGAL-4.9-Ic-1/cmake/platforms/x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8/test/BGL/test_Euler_operations+0x4ac1d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 boost::graph_traits<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >::halfedge_descriptor CGAL::Euler::join_vertex<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >(boost::graph_traits<CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> > >::halfedge_descriptor, CGAL::Polyhedron_3<CGAL::Simple_cartesian<double>, CGAL::Polyhedron_items_with_id_3, CGAL::HalfedgeDS_default, std::allocator<int> >&)
==26779==ABORTING
```

The last one shows that the segfault is in `CGAL::Euler::join_vertex`.

**Comment by lrineau** [comment]
Please also check if the failures in `Surface_mesh_simplification` may be related: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-1/Surface_mesh_simplification/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz

**Comment by afabri** [comment]
Both are fixed now.

**Comment by lrineau** [comment]
@afabri I have rebased the branch with:
```shell
git rebase master --onto releases/CGAL-4.8-branch
```
and pushed `--force` to your fork https://github.com/afabri/cgal. Andreas. You should remove your *local* branch, with:
```
git branch -D BGL-fix_join_vertex-GF
```

**Comment by lrineau** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-3.shtml

**Pull request merged**
