### PR TITLE
Fix a miscompilation by clang-3.6.x

### PR DESCRIPTION
**Pull request by lrineau**
Fix issue #139

### CODE REVIEW

**Comment by lrineau** [comment]
Replaced by #161.

**Comment by gdamiand** [comment]
Laurent, why 

return rhs == CC_iterator<DSC, Const>();

instead of

return rsh.operator->()==NULL; 

?

I suppose the second is faster since it avoids default construction of a CC_iterator. Am i wrong ?

**Comment by cjamin** [comment]
We're doing this everywhere in the code, so I hope you're wrong ;)

**Comment by lrineau** [comment]
Clément said it was easier to understand. And I hope the compiler is able to optimise out the creation of the null object.

**Comment by gdamiand** [comment]
For me the simple code is 

rhs.m_ptr.p==NULL

And this is probably the faster code, we don't need to suppose compiler will optimise...

For the same reason, operator==(rhs, lhs) could be

rhs.m_ptr.p==lhs.m_ptr.p

I see no interest of the current form (&*rhs == &*lhs).

**Comment by cjamin** [comment]
Actually, I agree with Guillaume. Why call the overloads since we are inside the iterator class? Of course, it would make it a bit easier if we changed the internal structure, but is it worth making the code more difficult to understand? It's very unlikely the internal structure will change anyway.

**Pull request closed without merging**
