### PR TITLE
Correction of hyperlinks

### LINKED ISSUE #5755: Security risk regarding link to uni-bielefeld in package Surface_mesh
## Issue Details

Not 100% a CGAL problem, but the link to:
```
https://graphics.uni-bielefeld.de/publications/imr11/
```
in the package Surface_mesh (file: Surface_mesh/doc/Surface_mesh/Surface_mesh.txt) gives a security risk:
```
Warning: Potential Security Risk Ahead
```
this is not that good and might be best to contact uni-bielefeld about this issue (better from an institute than from a private person).

### PR DESCRIPTION
**Pull request by albert-github**
The link checker gave a number of redirects and incorrect links.
- the redirects have been solved as far as possible
- the incorrect links have been checked and corrected where possible, others  have been reported through issues;

Fixes #5755

### CODE REVIEW

**Comment by afabri** [comment]
Thanks a lot @albert-github  !!!   I thought you "only" pointed out errors which I already considered as a contribution.

**Comment by albert-github** [comment]
I don't like double work and as I already knew where the problem was it is easy to fix (and afterwards I can also easily check it by rerunning the checker ...).

**Comment by lrineau** [comment]
@albert-github Do you know a link checker that can also verify fragments part of the URL (after the `#`)? Such a checker would verify that the URL points to an HTML page defining that ID.

**Comment by albert-github** [comment]
I think that the link checker (W3C-LinkChecker-4.81) I use does also the fragment checking  as I have:
```
Checking ./doc_output/Triangulation_on_sphere_2/index.html
==============================================

Processing      file:///.../doc_output/Triangulation_on_sphere_2/index.html

List of broken links and other issues:
file:///...doc_output/Triangulation_on_sphere_2/index.html
 Lines: 179, 191
  Code: 200 (no message)
 To do: Some of the links to this resource point to broken URI fragments
        (such as index.html#fragment).
The following fragments need to be fixed:
        Section_2D_Triangulations_Regular       Line: 191
        Section_2D_Triangulations_Definitions   Line: 179
```

I'm right now working on these 2.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-148.shtml

**Pull request merged**
