### PR TITLE
Classification Plug-In: Better Widget & Cluster Classification

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

This PR adds some features to the classification plug-in:
- much better reworked widget
- possibility to compute classification on clusters (from RANSAC or region growing)

Some undocumented code is added to the package (some might be completed and documented later on with a small feature).

## Release Management

* Affected package(s): Classification, Polyhedron demo
* Tested locally on GNU/Linux using both `clang` and `gcc`

### CODE REVIEW

**Comment by sgiraudot** [comment]
Still some errors/warnings. I'm correcting them.

**Comment by lrineau** [comment]
A small warning remains.
```
[100%] Building CXX object Plugins/Classification/CMakeFiles/classification_plugin.dir/Cluster_classification.cpp.obj
	cd C:\CGAL\test\CGAL-4.12-Ic-207\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Debug-64bits\test\Polyhedron_Demo\Plugins\Classification
	C:\PROGRA~2\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\cl.exe @C:\Users\afabri\AppData\Local\Temp\nm9163.tmp
Cluster_classification.cpp
Unknown compiler version - please run the configure tests and report the results
[...]\test\Polyhedron_Demo\Plugins\Classification\Cluster_classification.cpp(748): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-207/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

**Comment by sgiraudot** [comment]
I don't understand, this warning should already be fixed, line 748 was fixed by commit https://github.com/CGAL/cgal/pull/2940/commits/5cbf1e1abd75333e3c75a978c41d7937c3e72036, using an explicit conversion:

```c++
                                         int(num_trees));
```

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.12-Ic-210], and then merged.

  [CGAL-4.12-Ic-210]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-210.shtml

**Pull request merged**
