### PR TITLE
Documentation overview: enhancement

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Specifies in the result page that Doxygen 1.8.13 is the one used for the CGAL documentation and adds a header to the result table to regroup the columns by version in a cleaner way.
## Release Management

* Affected package(s):Documentation

### CODE REVIEW

**Comment by sloriot** [comment]
@lrineau mentionned in a private email that we can stop tested 1.8.4, shall we use this PR to make this change too?

**Comment by lrineau** [comment]
There is actually one thing that could prevent us to upgrade. So far, only the documentation of CGAL-4.12 and `master` (future 4.13) was using Doxygen 1.8.13. If we drop 1.8.4, that means that 4.11.2 will have to be documented with 1.8.13 as well. That means backporting the script to that release branch. As far as I know, that should be fine.

By the way, the PR should be rebased on the branch for 4.12.1.

**Comment by maxGimeno** [comment]
> By the way, the PR should be rebased on the branch for 4.12.1.

Why ? What difference does it make?

**Comment by lrineau** [comment]
If you don't, then the branch `releases/4.12-branch` will not get the PR, and every week-end when 4.12 is tested instead of 4.13 it will use the old script.

**Comment by lrineau** [comment]
Then could you please rebase the PR on 4.12?

**Comment by lrineau** [comment]
This PR is now merged, but I do not see the changes in the result page:
  https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/

Do you know why?!

**Comment by maxGimeno** [comment]
I do ! Compare Ic12 and 14 it should strike you enough :)

**Comment by lrineau** [comment]
Sorry I did not look the right page. All is fine. Thanks.

**Pull request merged**
