### PR TITLE
Demo isotropic_remeshing_plugin - keep selection valid

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

In the demo, the `isotropic_remeshing_plugin` was invalidating the set of selected edges (resp. vertices, facets) given as input via the selection plugin, because of the modifications made to the mesh associated with the call to `surface_mesh->collect_garbage()`.

This PR uses the visitor in `surface_mesh->collect_garbage(visitor)` to keep selection valid after remeshing and garbage collection.

This PR follows PR #4978 in the case we have a selection_item with selected edges

## Release Management

* Affected package(s): Polyhedron demo
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
There is still an issue though : `selection_item->polyhedron_item()->invalidateOpenGLBuffers();` empties the selection, though it is still valid.

**Comment by maxGimeno** [comment]
The problem is that modifications to the poly_item made by other operations will still mess up the selection. 
But I think you can trick it by updating num_faces/edge/etc. in the Scene_polyhedron_selection_item's `d`.
You will need to add a function tu update them, and call it before calling invalidateOpenGLBuffers(). This way, the function will consider that no significant change has been performed, and won't clear the selection.

**Comment by janetournois** [comment]
Selection is now valid after remeshing.

Note that using the visitor in `collect_garbage()` as done in this PR could probably be generalized in the demo to avoid clearing the selection when it's possible.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-36.shtml

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-41.shtml

**Pull request merged**
