### PR TITLE
PMP:: Use operator<  instead of operator> as OM only implements the former

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Change the comparison operator for descriptors in the corefinement code so that it works with OpenMesh.

## Release Management

* Affected package(s): PMP

### CODE REVIEW

**Comment by maxGimeno** [comment]
There is an error here : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-70/Polygon_mesh_processing_Examples/TestReport_lrineau_Fedora-with-LEDA.gz

But it might be due to a problem of merging. Anyway, a part of this PR changes code that disappeared from master, so I'll juste postpone this test as I don't know how to do yet.

**Comment by afabri** [comment]
@maxGimeno can you please check that my latest commit fixes the error in the [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-76/Polygon_mesh_processing_Examples/TestReport_lrineau_Fedora-rawhide.gz).

**Comment by maxGimeno** [comment]
It works

**Comment by afabri** [comment]
Thank you.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-78.shtml

**Pull request merged**
