### PR TITLE
SLS: Fix warnings

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix warnings in [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-12/Straight_skeleton_2/TestReport_Christo_MSVC-2019-Community-Release.gz) 

## Release Management

* Affected package(s): Straight_line_skeleton

### CODE REVIEW

**Review by MaelRL — COMMENTED** [review]
I think it should rather be a change in the definition of `weights` (value type is an integral type, and it should be double)

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-22.
Warning is gone: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-22/Straight_skeleton_2/TestReport_Christo_MSVC-2019-Community-Release.gz

**Comment by lrineau** [comment]
> I think it should rather be a change in the definition of `weights` (value type is an integral type, and it should be double)

@MaelRL @AndreasHaas  You should discuss that topic today.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-56

**Pull request merged**
