### PR TITLE
Compatibility issue with Alpha_shape_2

### PR DESCRIPTION
**Pull request by grzjab**
This pull request is directly connected with the issue https://github.com/CGAL/cgal/issues/1258

### CODE REVIEW

**Comment by lrineau** [comment]
Hi @grzjab

This PR has caused a lot of new warnings in the 2D periodic triangulation. Could you check locally on your machine and try to fix the warnings?

I think we just need to add some cases in the switch:
```C++
case OUTSIDE_CONVEX_HULL: CGAL_error();
case OUTSIDE_AFFINE_HULL: CGAL_error();
```
`CGAL_error()` is a macro that evaluates to a function that is tagged with the attribute `noreturn`. At compile time, the optimizers of compilers will remove the branches of those cases.

CC @afabri. See also #1547.

**Comment by afabri** [comment]
And please put a comment, that this cannot happen in a periodic triangulation,  but that otherwise we get a warning.
And where the enum  is add also a comment that although they make sense, they are added for periodic alpha shapes.

**Comment by lrineau** [comment]
I have pushed a fix myself.

**Comment by grzjab** [comment]
@lrineau I just realized that there is actually much more to do, if one wants to use it. I wasn't aware of the branch by nkruithof.

**Comment by lrineau** [comment]
Do you want to cancel the pull-request?

**Comment by grzjab** [comment]
I think it makes much more sense. Sorry for that.

**Comment by MaelRL** [comment]
Closing this PR in favor of PR https://github.com/CGAL/cgal/pull/2369.

**Pull request closed without merging**
