### PR TITLE
STL writer under LGPL

### PR DESCRIPTION
**Pull request by sloriot**
The reader is LGPL

### CODE REVIEW

**Comment by lrineau** [comment]
`master` only?

**Comment by sloriot** [comment]
My guess was that you'd not like to backport just changes but we can go up to 4.13 if you (as release manager) says it is acceptable.

**Comment by lrineau** [comment]
At least CGAL-4.14.1. Due to the special role of CGAL-5.0, the CGAL-4.14-branch will have to be a bit more than just bug fixes.

**Comment by lrineau** [comment]
I have reset the milestone to 4.14 because the base branch of the PR is 4.14.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-10.shtml

**Pull request merged**
