### PR TITLE
Replace tabs with spaces and remove trailing whitespaces

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
[in this testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-27.shtml),
there are some warnings due to indentation issues that are due to patches using spaces in files using tabs most probably, I'll fix them. 
I'm a bit worried about the red line in the arrangement testsuite and the red column about missing boost headers (probably not related to this branch).

**Comment by efifogel** [comment]
I see that these errors, in the arrangement package, did not show up
yesterday.
What has changed?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel only tabs -> 2spaces and removing trailing whitespaces.

**Comment by efifogel** [comment]
On most platforms I see that 2 tests failed, namely, test_overlay and
test_overlay geodesic_arcs_on_sphere. (the former tests overlay of
arrangements induced by segments).
It seems that they failed because the execution exceeded the time limit.
I cannot reproduce on Ubuntu 16.04.6 LTS, gcc 5.4.0.
Can someone reproduce it?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Too many conflicts approximately everywhere. I won't test it in integration tonight. Probably not before most of the PRs are integrated, to limit conflicts as much as possible.

**Comment by lrineau** [comment]
With the git-merge options `-s recursive -X ignore-all-space`, all conflicts but one disappear, instead of 36 conflicts. The remaining conflict is about a file that has been removed.

**Comment by sloriot** [comment]
@lrineau I fixed the inconstant indentation issues in flies that were mixing spaces and tabs while restricting the changes to whitespace only.

**Comment by sloriot** [comment]
@lrineau new version

**Comment by maxGimeno** [comment]
Lots of conflicts

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-108.shtml

**Comment by sloriot** [comment]
Includes updates of releases branches, diff with the branch before the push is empty

**Pull request merged**
