### PR TITLE
Polyhedron demo : Addition of a small axis system in a corner 

### PR DESCRIPTION
**Pull request by maxGimeno**
A small axis system is displayed in the top right corner of the viewer, allowing to quickly know the orientation of the camera at any time. It is displayed by default but can be hidden with the A key. The colors are :
X in red
Y in green
Z in blue
so that x,y,z is r,g,b.

### CODE REVIEW

**Comment by sgiraudot** [comment]
I tested it and it looks good.

Just one small bug: the axis goes too far up when the window is thin (that is to say, when the height of the viewer is bigger than the width).

**Comment by maxGimeno** [comment]
I corrected this.

**Comment by sgiraudot** [comment]
Okay, everything seems fine for me now!

**Comment by maxGimeno** [comment]
You are absolutely right !

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-10](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-13](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-13.shtml)

**Comment by sloriot** [comment]
Tests look good

**Pull request merged**
