### PR TITLE
PMP::Orient polylines of Polgon Mesh Slicer ccw.

### LINKED ISSUE #3883: Orientation of Polylines in Slicer Pkg:PMP
# Issue Details

It is cool to find slicing for meshes in Polygon Mesh Processing package. I tested the example and other 3D objects for slicing. However, I found that the sliced polylines maybe randomly oriented (Do I miss some input parameters? I am new to CGAL). As you know, many users like me want to have the exterior polylines **CCW** oriented and the hole ones to be **CW**, so that we can build the tree of polylines (e.g. by ClipperLib) very conveniently.

## Environment

* Operating system:Windows64 bits
* Compiler:MSVC2015
* Release or debug mode:Release 
* Specific flags used (if any):
* CGAL version:4.14
* Boost version:1.70.0
* Other libraries versions if used (Eigen, TBB, etc.):Eigen

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Insure that the polylines produced by the slicer are ccw when seen from the positive side of the slicing plane.

## Release Management

* Affected package(s):PMP
* Issue(s) solved (if any): fix #3883

### CODE REVIEW

**Comment by afabri** [comment]
I am not sure that users want all polylines CCW.   Usually one wants the domain "to the left" of the boundary, that is an outer boundary CCW, the boundary of a hole CW (as in WKT, btw).  We should ask the people who asked for this feature.

**Comment by maxGimeno** [comment]
> I am not sure that users want all polylines CCW. Usually one wants the domain "to the left" of the boundary, that is an outer boundary CCW, the boundary of a hole CW (as in WKT, btw). We should ask the people who asked for this feature.

No, we don't need to ask. This is only the first step, while we are thinking about how to do the nesting.

**Comment by sloriot** [comment]
> I am not sure that users want all polylines CCW. Usually one wants the domain "to the left" of the boundary, that is an outer boundary CCW, the boundary of a hole CW (as in WKT, btw). We should ask the people who asked for this feature.

Fixed, the orientation of the polylines depends on the orientation of the supporting mesh.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-36.shtml.

**Comment by lrineau** [comment]
The corresponding PR #3918 was tested in `integration`.

**Pull request merged**
