### PR TITLE
Scale space reconstruction: Improve API

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

Separation of meshing and smoothing algorithm, addition of two new (better) algorithms. This is a pre-approved small feature.

## Release Management

* Affected package(s): Scale Space Reconstruction (and Polyhedron demo for the plugin)
* [Small Features/Improve API of Scale Space Reconstruction](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Improve_API_of_Scale_Space_Reconstruction)

### CODE REVIEW

**Comment by lrineau** [comment]
Testsuite fully red:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-52.shtml#Scale_space_reconstruction_3_Examples

because of a runtime error:
```
------------------------------------------------------------------
- ProgramOutput.scale_space_advancing_front.ArchLinux
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1498624762
Error, no input file provided
```

You should add a data file, and a `.cmd` file.

**Comment by lrineau** [comment]
@sgiraudot TODO: have a look at, and review, the comment of commit e57aeb554e0e74d6be46353b7da524d69013fd2d by Andreas.

**Comment by lrineau** [comment]
@sgiraudot I merged this PR in `master` by error.

Try to have a look anyway at that comment https://github.com/CGAL/cgal/pull/2159#issuecomment-311901091:
> TODO: have a look at, and review, the comment of commit e57aeb5 by Andreas.

**Comment by lrineau** [comment]
@sgiraudot, another TODO: add something in the `changes.html`.

**Comment by sgiraudot** [comment]
I've created another PR for the remaining TODOs: https://github.com/CGAL/cgal/pull/2226

**Pull request merged**
