### PR TITLE
Use std::set instead of boost::flat_set in case of VC++ and boost 1.55

### PR DESCRIPTION
**Pull request by afabri**
known bug in boost 1.55

### CODE REVIEW

**Comment by sloriot** [comment]
Is the bug gone in boost 1.56? Was it introduced in 1.55?

**Comment by afabri** [comment]
I had checked that it is gone with 1.56. 
I interpreted [this](https://svn.boost.org/trac/boost/ticket/9267) as that it had been introduced in 1.55

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-103

**Comment by lrineau** [comment]
Note that the milestone is 4.7.1 but the PR is merged in `master`. Which is wrong?

**Comment by sloriot** [comment]
I have rebased the branch and merged it first in 4.7 and then merged 4.7 in master.

**Pull request merged**
