### PR TITLE
Linear_cell_complex: Replace call to rand() in one testcase

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Make the testsuite reproducible by replacing the call to `rand()`.

## Release Management

* Affected package(s): Linear_cell_complex
* Issue(s) solved (if any): related to #6579

### CODE REVIEW

**Review by gdamiand — COMMENTED** [review]
Thanks @afabri, sorry for the delay to solve this issue.
My plan is to solve this problem with the new branch cmap with index since there are many modifications.

**Comment by lrineau** [comment]
How does this PR fixes the issue? I do not see why `CGAL::get_default_random().get_int(0,RAND_MAX)` is better than `rand()`.

**Comment by afabri** [comment]
It is to make it seedable so the next time we see when it crashes we can reproduce.

**Comment by gdamiand** [comment]
I plan to solve the issue later, with the branch cmap index.

**Comment by sloriot** [comment]
I think you can see the error in [CGAL-5.6-Ic-1](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-5.6-Ic-1/Linear_cell_complex/TestReport_Christo_MSVC2015-Release-64bits.gz)

**Comment by sloriot** [comment]
Replaced by #6688. @gdamiand please confirm that you have handled this issue.

**Comment by gdamiand** [comment]
> Replaced by #6688. @gdamiand please confirm that you have handled this issue.

I think so, but we will see the results of the test suite.

**Pull request closed without merging**
