### PR TITLE
Optimal Transportation Reconstruction: Run with tolerance

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

[Pre-approved small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/OT_Reconstruction_with_Wasserstein_tolerance) that introduces a new way to run reconstruction based on a Wasserstein tolerance (instead of a number of output edges).

## Release Management

* Affected package(s): Optimal Transportation Curve Reconstruction
* Feature/Small Feature (if any): [Features/Small_Features/OT_Reconstruction_with_Wasserstein_tolerance](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/OT_Reconstruction_with_Wasserstein_tolerance)
* Pre-approved: Pierre Alliez 09:50, 21 December 2017 (CET)

### CODE REVIEW

**Comment by sloriot** [comment]
I have this error when locally running the testsuite:
```
/home/sloriot/CGAL/git/integration/Optimal_transportation_reconstruction_2/test/Optimal_transportation_reconstruction_2/../../include/CGAL/Optimal_transportation_reconstruction_2.h:674:29: error: no matching function for call to ‘sqrt(CGAL::Lazy_exact_nt<CGAL::Gmpq>)’
     double cost = std::sqrt (pedge.after() / pedge.total_weight());
                   ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sloriot** [comment]
New warnings in the demo. See [here](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-125.shtml)

**Comment by sgiraudot** [comment]
Travis failed for an `apt-get` failure (note: I don't know if it's possible, but it would be nice that this kind of error is detected or showed differently, it happens not that rarely and it's not related to the PR).

**Comment by lrineau** [comment]
Every day I check for suspicious Travis failures, and I restart the job that failed because of a network problem (usually `apt-get` cannot reach servers, or the connection is broken, as you said).

**Comment by lrineau** [comment]
There is a line of warnings:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-133.shtml#Optimal_transportation_reconstruction_2_Demo

**Comment by sgiraudot** [comment]
This warning is due to the fusion of this PR and of PR https://github.com/CGAL/cgal/pull/2694. Depending on which one will be merged first, I'll have to fix them afterwards.

**Comment by sgiraudot** [comment]
This PR was rebased on #2694 and the related deprecated warning was fixed.

**Comment by sgiraudot** [comment]
(Travis failed because of `apt-get`.)

**Comment by lrineau** [comment]
1. Somebody has restarted the failed Travis job.
2. There is a tiny conflict with `master` because of commit 8fc5756cc3f5b10db61ed06805bdde023a41b6a4.

**Comment by lrineau** [comment]
(same message but different PR.)

**Comment by sgiraudot** [comment]
Rebased.

**Comment by lrineau** [comment]
TODO: verify that commits are not duplicated with ... the other PR (which number?)

**Comment by sgiraudot** [comment]
Ok, I managed to perform a clean rebase, all should be okay now.

**Comment by sgiraudot** [comment]
(Travis has reached time limit, I restarted it.)

**Comment by lrineau** [comment]
About the TODO: I have verified that #2697 and #2694 share a lot of their commits: no duplication.

**Comment by lrineau** [comment]
Tested in [CGAL-4.12-Ic-142].

  [CGAL-4.12-Ic-142]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-142.shtml

**Comment by lrineau** [comment]
Nothing in `changes.md`?!

**Comment by sgiraudot** [comment]
Oops, yes, I even did not put anything in the small feature. Sorry about that, I'll make another PR…

**Pull request merged**
