### PR TITLE
PMP : fix isotropic_remeshing plugin

### PR DESCRIPTION
**Pull request by janetournois**
when remeshing a selection_item, use it instead of poly_item
it avoids using a NULL poly_item

@sloriot can you please confirm it has the behaviour you expect?

### CODE REVIEW

**Comment by lrineau** [comment]
TODO: please rebase the branch into `release/CGAL-4.8-branch`

**Comment by janetournois** [comment]
ok, sure

**Comment by janetournois** [comment]
rebase is done

**Comment by lrineau** [comment]
TODO for @lrineau: Merge this PR in `releases/CGAL-4.8-branch` instead of `master`.

**Comment by janetournois** [comment]
@lrineau is it possible to change this aspect of the PR after it's created? I tried but did not manage to do it

**Comment by lrineau** [comment]
@janetournois : it seems that is not possible. See [StackOverflow][a]. The [current best answer is][b]:
> You can't. Just make a new pull request.
>  _answered Apr 9 '12 at 23:18 Amber._

[a]: http://stackoverflow.com/q/10081053/1728537
[b]: http://stackoverflow.com/a/10081072/1728537

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-13.shtml#Polygon_mesh_processing

**Pull request merged**
