### PR TITLE
Ridges 3 bug fix doc pougetma

### PR DESCRIPTION
**Pull request by pougetma**
## Summary of Changes

Add a rep example/data with 2 off files

## Release Management

Solves issue 8327 
https://github.com/CGAL/cgal/issues/8327

### CODE REVIEW

**Comment by sloriot** [comment]
@pougetma Thanks for the PR. Do you agree that shipping the data is actually not needed and only the text should be updated?

**Comment by pougetma** [comment]
Do you mean I need to store the data outside of CGAL? I’m not aware of the practice of data management within cgal.
The 2 examples are light weight, so  it seemed reasonable to have them in cgal.
M.

**Comment by sloriot** [comment]
Well, it does increase the history size of 0.5MB and I don't see any added value: None of them are used in tests, rocker-arm.off is a plain copy of aim@shape data and the ellipsoid could be regenerated using an implicit function with `Mesh_3`. Even worse for rocker-arm, it's not the data used to generate the figure. Do you see what I mean? (I can call you if I'm not clear :) )

**Comment by pougetma** [comment]
Ok, agree, I removed the data files

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-318

**Pull request merged**
