### PR TITLE
Travis: Clean-up script.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Stop installing QGLViewer for demos.

### CODE REVIEW

**Comment by lrineau** [comment]
I think we should delay this PR until all supported release branches have QGLViewer shipped with CGAL. Otherwise, pull-requests against release branches may fail.

**Comment by maxGimeno** [comment]
Oh, ok.

**Comment by sloriot** [comment]
Looks like the PR contains not diff. @maxGimeno  Shall we close it?

**Comment by maxGimeno** [comment]
Yep, I think it has already been done in another PR.

**Pull request closed without merging**
