### PR TITLE
Polyhedron demo : Menu operation is accessible with a context menu

### PR DESCRIPTION
**Pull request by maxGimeno**
- Pressing ctrl and shift while performing a right click on the viewer opens a contextual menu for operations.

### CODE REVIEW

**Comment by sgiraudot** [comment]
The code looks good and the feature works fine from what I have tested.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-8](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-8.shtml)

**Comment by lrineau** [comment]
In the polyhedron demo, the <kbd>Shift</kbd> key is used for "picking", and the <kbd>Ctrl</kbd> is used to manipulate the manipulated frame (such as the cutting plane). Using <kbd>Ctrl+Shift</kbd> seems a bad idea to me.

There is already a context menu accessible directly from the 3D view, with <kbd>Shift</kbd>+right click. Could you add the operation menu as a sub-menu in that context menu?

**Comment by maxGimeno** [comment]
I did as you said.

2015-09-29 14:11 GMT+02:00 Laurent Rineau <notifications@github.com>:

**Comment by sgiraudot** [comment]
Tested, it works fine.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-10](Merged in [CGAL-4.8-Ic-10](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-13](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-13.shtml)

**Comment by sloriot** [comment]
Tests look good

**Pull request merged**
