### PR TITLE
Replace #ifdef CGAL_USE_BOOST_PROGRAM_OPTIONS 

### PR DESCRIPTION
**Pull request by afabri**
with `#ifndef DONT_USE_BOOST_PROGRAM_OPTIONS` 

This allows us to not use boost even if it is available in a testsuite (but broken as boost was not compiled as expected)

### CODE REVIEW

**Comment by lrineau** [comment]
With this patch, the program will have compilation error as soon as Boost.Program_options is not found by CMake (in that case, in master, `CGAL_USE_BOOST_PROGRAM_OPTIONS` would not have been defined).

A better patch could use:
```C++
#if defined(CGAL_USE_BOOST_PROGRAM_OPTIONS) && !DONT_USE_BOOST_PROGRAM_OPTIONS
```
then if the macro `DONT_USE_BOOST_PROGRAM_OPTIONS` is defined to `1`, Boost.Program_option would not be used.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-110

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-111

**Comment by sloriot** [comment]
Shall we set the flag on test platforms having issues?

**Comment by afabri** [comment]
Laurent had planned that @bo0ts   adds the -D...    on the Docker platforms concerned.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-112

**Comment by lrineau** [comment]
Merged in CGAL-4.8-Ic-113.

I have added the config flag to the gcc6 docker images¹. They are building now. I hope it will be in tonight's testsuite.

¹) See https://github.com/CGAL/cgal-testsuite-dockerfiles/commit/033a0f69fa8a5c05acc120525dc5949d664bb56d

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-115

**Comment by lrineau** [comment]
All the Docker images "gcc6" will have `-DDONT_USE_BOOST_PROGRAM_OPTIONS` in the compiler flags tonight.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-116

**Comment by sloriot** [comment]
Errors are now gone.

**Pull request merged**
