### PR TITLE
Polyhedron demo: Enhance RANSAC display

### PR DESCRIPTION
**Pull request by sgiraudot**
Additional option for the _point_set_shape_detection plugin_: for a plane, construct alpha shape of the points projected on the detected plane (stored in the form of a _Scene_polyhedron_item_). This is how RANSAC plane detection results are commonly displayed in literature.

This has not been tested yet (merged on _integration_ today).

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-38

**Comment by sgiraudot** [comment]
ransac_compare
* __Left__: current display after shape detection (still available with this PR)
* __Center__: proposed display (polyhedron with flat rendering by default -> what is interesting is mostly the plane and its boundaries)
* __Right__: same display after setting flat+edges rendering

**Comment by sgiraudot** [comment]
I see no error/warning in the testsuite related to this plugin.

**Comment by sloriot** [comment]
Unfortunately the testsuite is not complete and failing on windows. If you want to test it tomorrow you need to update to the new framework from #430

**Comment by sgiraudot** [comment]
Merged in CGAL-4.8-Ic-39

**Comment by sgiraudot** [comment]
Everything seems to be okay on the testsuite (warnings and errors not related to this plugin).

**Comment by sloriot** [comment]
@sgiraudot There is a runtime error in `Point_set_shape_detection`. Could it be related?

**Comment by sgiraudot** [comment]
Not likely. I haven't altered any file from the package <code>Point_set_shape_detection</code>, only the Polyhedron demo plugin.

**Comment by sloriot** [comment]
I reverted the merge that depends on #430 that is not yet ready.

**Pull request merged**
