### PR TITLE
Regular_triangulation_3: Add Regular_triangulation_cell_base_3::hidden_points()

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

The [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-117/Periodic_3_triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz) for 3D periodic regular triangulations calls `std::distance(b,e)` where the iterators are from a list. The function that returns a range (something we want later anyways) permits to call `.size()`. 

## Release Management

* Affected package(s): Triangulation_3 and Periodic_3_triangulation_3

### CODE REVIEW

**Comment by afabri** [comment]
@MoniqueTeillaud do you think we can reduce the size the point set of the 3D periodic regular triangulation test?

**Comment by mglisse** [comment]
> `std::distance(b,e)` where the iterators are from a list

Too bad other implementations did not copy gcc, where std::distance(list.begin(),list.end()) has constant complexity (it is optimized to a call to `size()`).

**Comment by afabri** [comment]
Successfully tested in [CGAL-4.14-Ic-119](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-119/Periodic_3_triangulation_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2013-Debug-64bits.gz)

**Comment by afabri** [comment]
The conclusion of a discussion with @MoniqueTeillaud was that we better do  tests with random point sets and not with two stored point sets.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-122.shtml

**Pull request merged**
