### PR TITLE
Polyhedron_demo: Make the demo customizable at build time

### LINKED ISSUE #2040: Polyhedron_demo: Make the demo configurable at build time
## Issue Details
Find a way to chose which plugins should be compiled and added at the build time to make portable versions of the demo.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Add options to the CMakeLists.txt that allow to chose easily what will or will not be built in the default target thanks to  cmake-gui.
This is done using checkboxes : one per plugin and one per "category", which regroup related plugins.

Also and add four targets that emulate the categories.

To use this : you can either call cmake-gui for the demo, and clic on configure to apply your changes, then generate and call make in the console;
or you can call make category-[ visualizer | mesh_processing | point_set_processing | meshing ].

@afabri @sgiraudot can you try it and give me some feedback ?

## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #2040

### CODE REVIEW

**Comment by sgiraudot** [comment]
I have some errors when calling cmake:

```
-- Configuring done
CMake Error at polyhedron_demo_macros.cmake:71 (add_library):
  Cannot find source file:

    PLUGINS_meshing

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  Plugins/IO/CMakeLists.txt:46 (polyhedron_demo_plugin)


CMake Error: CMake can not determine linker language for target: vtk_plugin
CMake Error: Cannot determine link language for target "vtk_plugin".
CMake Error: CMake can not determine linker language for target: surf_to_sm_io_plugin
CMake Error: Cannot determine link language for target "surf_to_sm_io_plugin".
CMake Error: CMake can not determine linker language for target: off_plugin
CMake Error: Cannot determine link language for target "off_plugin".
CMake Error: CMake can not determine linker language for target: nef_io_plugin
CMake Error: Cannot determine link language for target "nef_io_plugin".
CMake Error: CMake can not determine linker language for target: off_to_nef_plugin
CMake Error: Cannot determine link language for target "off_to_nef_plugin".
CMake Error: CMake can not determine linker language for target: surf_io_plugin
CMake Error: Cannot determine link language for target "surf_io_plugin".
CMake Error: CMake can not determine linker language for target: gocad_plugin
CMake Error: Cannot determine link language for target "gocad_plugin".
CMake Error: CMake can not determine linker language for target: surface_mesh_io_plugin
CMake Error: Cannot determine link language for target "surface_mesh_io_plugin".
CMake Error: CMake can not determine linker language for target: selection_io_plugin
CMake Error: Cannot determine link language for target "selection_io_plugin".
CMake Error: CMake can not determine linker language for target: stl_plugin
CMake Error: Cannot determine link language for target "stl_plugin".
-- Generating done
```

**Comment by maxGimeno** [comment]
I push forced the fix

**Comment by sgiraudot** [comment]
Looks good to me (again, I did not check the plugins in the mesh categories, but IO and point sets look good). Nice work!

**Comment by afabri** [comment]
It could be visualization instead of visualizer.

**Comment by lrineau** [comment]
The Travis build failed: https://travis-ci.org/CGAL/cgal/jobs/231130629#L5218

**Comment by lrineau** [comment]
Sorry for the closed/reopened: wrong button...

**Comment by sloriot** [comment]
@afabri @sgiraudot do you agree with the latest modifications?

**Comment by lrineau** [comment]
I object against this PR.

**Comment by sgiraudot** [comment]
It looks good to me (but needs rebasing).

@lrineau there's no rush, but can you elaborate on why you object against the PR? If there is a debate, we should have it before Maxime spends any more time on this, as it would be a waste of time.

**Comment by lrineau** [comment]
I object against this PR because it is an important change to the CMake scripts of the polyhedron demo, and I had not had any time to review it.

Today, I did not look into the details but:
  - it seems the patch is rather small considering what it does,
  - some of you have reported that it works correctly.

Before it is merged, I would like a sort of documentation explaining the role of the various cache variable, and the expected behavior, without copy-pasting the documentation line of the variable. Because Philip and Eric modified the CMake scripts heavily, they did not document the behavior correctly, and now we cannot know if the current behavior is buggy or working as expected. At least with a documentation we can compare the documented behavior and the actual behavior of the code.

**Comment by maxGimeno** [comment]
@lrineau We need to talk about this, as I am waiting for the system to be validated before I update the branch.

**Comment by lrineau** [comment]
Replaced by #3412 with a better implementation.

**Pull request closed without merging**
