### PR TITLE
Surface_mesh: normals in OBJ Writer

### LINKED ISSUE #4071: SMS::edge_collapse exported data lacking vertex normal
hi~
I simplified the OBJ file after SMS::edge_collapse. The obj exported by the normal has no vertex normals. Only vertices and faces. I want to get the vertex  normal corresponding to the face. What should I do?
A correct obj file should have vertex normals
image
I am very eager to know about this problem.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Add vertex nomals in write_OBJ for Surface_mesh

## Release Management

* Affected package(s):Surface_mesh
* Issue(s) solved (if any): fix #4071
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by simonasdmd** [comment]
Hello there. I saw that this problem should have been completed. I want to ask how to get it?

**Comment by maxGimeno** [comment]
You can get my cgal clone on git and checkout the branch :
in your cgal git directory:
```
git remote add maxGimeno https://github.com/maxGimeno/cgal.git
git fetch maxGimeno
git checkout maxGimeno/CGAL_IO-OBJ_writes_normals-maxGimeno
```

If you don't have a cgal directory, directly clone my repo with 
```
git clone  https://github.com/maxGimeno/cgal.git <directory>
git checkout maxGimeno/CGAL_IO-OBJ_writes_normals-maxGimeno
```
After that tou can go in <directory>/Polyhedron/demo/Polyhedron and build it. The plugin that reads and write the OBJ is the `off_plugin`

**Comment by simonasdmd** [comment]
hi~ @maxGimeno 
I used this method before. Export the obj file. But there is no normal. Is this method still used after the update? Can I get the normal using this? 

write_mesh(modelPath, *mesh)

**Comment by simonasdmd** [comment]
image
I tried it twice and failed. Is there any other way to get it?

**Comment by lrineau** [comment]
At the URL https://github.com/maxGimeno/cgal you can find a big green button in the top-rigth corner: `Clone or download ▼`. Clock on it and then on `Download ZIP`.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jul 31, 2019, 10:05 AM GMT+2](https://github.com/CGAL/cgal/pull/4122#issuecomment-516743691 "2019-07-31T08:05:25Z - Replied by Github Reply Comments"):
> At the URL https://github.com/maxGimeno/cgal you can find a big green button in the top-rigth corner: `Clone or download ▼`. Click on it and then on `Download ZIP`.

Actually, you need to download the right branch, from here: https://github.com/maxGimeno/cgal/tree/CGAL_IO-OBJ_writes_normals-maxGimeno

**Comment by simonasdmd** [comment]
hi~ @lrineau 
I want to use the export obj file in my code. How can I use it? thank you for telling me.

**Comment by maxGimeno** [comment]
Use `CGAL::generic_print_surface_mesh()` with `CGAL::File_writer_wavefront ` as writer. Its header is #include <CGAL/IO/File_writer_wavefront.h>.

**Comment by simonasdmd** [comment]
@maxGimeno  
hi~
I want to ask. The first one was downloaded from the main cgal line. The second one is downloaded from the place you told me. The two structures are not the same. How to use the second one?

**Comment by simonasdmd** [comment]
hi~
@lrineau 
image

I want to ask. The first one was downloaded from the main cgal line. The second one is downloaded from the place you told me. The two structures are not the same. How to use the second one?
image

**Comment by lrineau** [comment]
I suggest you read the file `README.md` in that directory. You can also [read it on Github](https://github.com/maxGimeno/cgal/blob/CGAL_IO-OBJ_writes_normals-maxGimeno/README.md) with a nice formatting.

Also read the file [`INSTALL.md`](https://github.com/maxGimeno/cgal/blob/CGAL_IO-OBJ_writes_normals-maxGimeno/INSTALL.md).

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-100.shtml

**Comment by simonasdmd** [comment]
Hello, may I ask if this has been merged into the main line? Can I download it now on the main line?
Can you provide a usage example? I don't know how to use this to export obj files. Previously I used "WriteMesh" to export obj files.
I am stupid....  I really need an example
Really please you

**Comment by simonasdmd** [comment]
I simplified the obj file with ''SMS::edge_collapse'. Then I exported the simplified obj file. Can this update recalculate the normal and export the obj file?
I hope to provide examples.

**Comment by maxGimeno** [comment]
See [this example](https://gist.github.com/maxGimeno/877a961f9d4f99c3372d88887ad89f2b)

**Comment by simonasdmd** [comment]
@maxGimeno Hello there. I can't access this address. Maybe it is because I am in China. There are restrictions on the firewall. Can you help me with screenshots or attachments?

**Comment by maxGimeno** [comment]
```cpp
//to create the mesh
#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
//only used to generate the tetrahedron
#include <CGAL/boost/graph/helpers.h>
//to compute the normals
#include <CGAL/Polygon_mesh_processing/compute_normal.h>
//to export
#include <fstream>
#include <CGAL/IO/File_writer_wavefront.h>
#include <CGAL/IO/generic_copy_OFF.h>
#include <CGAL/Surface_mesh/IO.h>



int main()
{

  //Conveniency typedefs
  typedef CGAL::Exact_predicates_inexact_constructions_kernel Epick;
  typedef Epick::Point_3 Point_3;
  typedef CGAL::Surface_mesh<Point_3> Mesh;
  typedef boost::graph_traits<Mesh>::vertex_descriptor vertex_descriptor;
  //Create a dummy mesh for the example
  Mesh m;
  CGAL::make_tetrahedron(Point_3(0,0,0), Point_3(0,1,0),
                         Point_3(1,0,0), Point_3(0,0,1), m);

  //compute its vertex normals
  Mesh::Property_map<vertex_descriptor, Epick::Vector_3 > vnormals =
      m.add_property_map<vertex_descriptor, Epick::Vector_3 >("v:normal").first;
  CGAL::Polygon_mesh_processing::compute_vertex_normals(m, vnormals);
  //export it
  std::ofstream out("mesh.obj");
  CGAL::File_writer_wavefront  writer;
  CGAL::generic_print_surface_mesh(out, m, writer);

}
```

**Comment by simonasdmd** [comment]
@maxGimeno 
Hello there. I really don't understand this conversion.
How does this example change to read an obj. Then call "SMS::edge_collapse" to simplify the obj file. Finally calculate the normal and export the obj file?
Really please you

**Comment by maxGimeno** [comment]
It shows how to compute the normals and export as an obj file. 
I updated it to show you how to read an OBJ file, but I am not willing to show you how to use documented functions. Just look at the examples, it is not complicated.

**Comment by simonasdmd** [comment]
@maxGimeno 
Can the updated example be sent out? I can't access the address.
thank you

**Comment by simonasdmd** [comment]
In which file is the example you provided?
hi @maxGimeno

**Comment by maxGimeno** [comment]
In my earlier comment:

```
//to create the mesh
#include <CGAL/Surface_mesh.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
//to ocnvert from soup to mesh
#include <CGAL/Polygon_mesh_processing/orient_polygon_soup.h>
#include <CGAL/Polygon_mesh_processing/polygon_soup_to_polygon_mesh.h>
//to compute the normals
#include <CGAL/Polygon_mesh_processing/compute_normal.h>
//to import
#include <CGAL/IO/OBJ_reader.h>
//to export
#include <fstream>
#include <CGAL/IO/File_writer_wavefront.h>
#include <CGAL/IO/generic_copy_OFF.h>
#include <CGAL/Surface_mesh/IO.h>



int main(int argc, char**argv)
{
  if (argc != 2)
    return 1;

  //Conveniency typedefs;
  typedef CGAL::Exact_predicates_inexact_constructions_kernel Epick;
  typedef Epick::Point_3 Point_3;
  typedef CGAL::Surface_mesh<Point_3> Mesh;
  typedef boost::graph_traits<Mesh>::vertex_descriptor vertex_descriptor;
  //Create a dummy mesh for the example

  std::vector<Point_3> points;
  std::vector<std::vector<std::size_t> > faces;

  Mesh m;
  std::ifstream in(argv[1]);
  bool failed = !CGAL::read_OBJ(in,points,faces);
  if(failed)
    return 1;
  CGAL::Polygon_mesh_processing::orient_polygon_soup(points,faces);
  CGAL::Polygon_mesh_processing::polygon_soup_to_polygon_mesh(points,faces,m);

  //compute its face normals
  Mesh::Property_map<vertex_descriptor, Epick::Vector_3 > vnormals =
      m.add_property_map<vertex_descriptor, Epick::Vector_3 >("v:normal").first;
  CGAL::Polygon_mesh_processing::compute_vertex_normals(m, vnormals);

  std::ofstream out("mesh.obj");
  CGAL::File_writer_wavefront  writer;
  CGAL::generic_print_surface_mesh(out, m, writer);

}
```

**Comment by simonasdmd** [comment]
hi~
I want to use "Microsoft Visual Studio" to use cgal. But I can't get the current master installer.
Can you provide it?
urgent need
Thank you very much
@maxGimeno 
I follow this and build under windows. This error has occurred. If you can. Can you provide a current master installer?
image
image

**Comment by afabri** [comment]
Hi @simonasdmd, if you have firewall problems with github, please do not expect workarounds and extra services for you.  Stick to the public release and locally patch the two files you can find in the **Files Changed **  tab. Best, Andreas

**Comment by sgiraudot** [comment]
It seems to me that the error is pretty explicit: **Could NOT find GMP (missing: GMP_INCLUDE_DIR)**

You need to install GMP as stated in [the installation manual](https://doc.cgal.org/latest/Manual/installation.html#secessential3rdpartysoftware). If you already did and have this error anyway, you need to specify to CMake where your installation of GMP is located.

**Comment by simonasdmd** [comment]
I see that the installation manual does not say that GMP is a must.
image

**Comment by afabri** [comment]
The CGAL installer installs GMP, so we only document what you have to install yourself

**Comment by simonasdmd** [comment]
Where should I get the right GMP？
~

**Comment by simonasdmd** [comment]
I have installed CGAL before. There is gmp inside. Can I use it?
image

**Comment by simonasdmd** [comment]
The GMP download is complete. Is the GMP path specified in cmake. Or compile GMP first and then compile cgal?

**Comment by simonasdmd** [comment]
@maxGimeno 
hi
Hello. I followed the code you gave me. But the normals are not calculated. I found that the "normals" attribute was not added to this place. Why is this.
code is：
image

image

**Comment by maxGimeno** [comment]
Did you check what is inside the vprops_ array ? You should look what is inside vnormals using cout.
You can use 
```cpp
for(auto v : vertices(m))
{
  std::cout<<get(vnormals, v)<<std::endl;
}
```

I'm quite sure the normals are computed with your code.
What version of CGAL are you using now ?

**Comment by simonasdmd** [comment]
thanks~
my cgal version is 4.14
I did print a lot of things in your way. But how do you use these normals?
The obj exported by CGAL still has only vertex and face indexes and no normals. These normals don't work.
Is the problem in the process of exporting obj？

**Comment by maxGimeno** [comment]
The feature is not in 4.14. It has been integrated in 5.0. Either upgrade your CGAL version.

**Comment by simonasdmd** [comment]
Well. I'll upgrade my CGAL version first
Will "generic_print_surface_mesh" export normals synchronously in version 5.0?

**Comment by maxGimeno** [comment]
Using your current code, it should yes.

**Comment by simonasdmd** [comment]
I'll try. Thanks to your help, otherwise I still don't know this.

**Pull request merged**
