### PR TITLE
Fix some Boost includes

### PR DESCRIPTION
**Pull request by bo0ts**
While going through the list of [Boost libraries used](https://gist.github.com/bo0ts/dacb1a3100c49ea050d8) by CGAL I did a quick check of some suspicious includes and cleaned them up.

The most notable is the removal of Boost.Lambda code from Mesh_3.

### CODE REVIEW

**Comment by lrineau** [comment]
I have merged the PR into `integration`. As `integration` is now freely open for CGAL-4.7, please merge it yourself next time.

**Comment by bo0ts** [comment]
@lrineau I don't understand what you are trying to say. I already merged it into integration on Monday and this was part of 4.7-Ic-5 : https://github.com/CGAL/cgal-dev/commits/testsuite-Monday

**Comment by lrineau** [comment]
Sorry, I did not know. Please mention those facts next time. Your branch seems fine. But CGAL-4.7-Ic-5 was not completely clean. Let's see how it will be in CGAL-4.7-Ic-6...

**Comment by lrineau** [comment]
[CGAL-4.7-Ic-6][Ic-6] was not clean. Would you patch modify only a few packages, such as Mesh_3, I would have merged it, after seeing the results of that internal release, but the patch modifies files from packages that have new red cells in the testsuite (due to other branches probably). I have remerged it in `integration` for tonight [CGAL-4.7-Ic-7][Ic-7].

`integration` was just reopen a few days ago, and there is a lot of traffic on it. Let's hope that will calm down soon...

[Ic-6]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-6.shtml
[Ic-7]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-7.shtml

**Comment by lrineau** [comment]
[CGAL-4.7-Ic-7][7] was a bad internal release. I have remerged for testing in [CGAL-4.7-Ic-8][8] tonight.

[7]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-7.shtml
[8]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-8.shtml

**Comment by bo0ts** [comment]
What is you conclusion for `Ic-8`? The branches I've touched look alright, except Surface_mesh_examples which seem to have VS bugs.

**Comment by lrineau** [comment]
Le Sunday 19 April 2015 23:50:03 Philipp Moeller a écrit :
> What is you conclusion for `Ic-8`? The branches I've touched look alright,
> except Surface_mesh_examples which seem to have VS bugs.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/CGAL/cgal/pull/54#issuecomment-94372798

CGAL-4.7-Ic-8 have had new issues with:
  Surface_mesh
  Polyhedron_demo
  Spatial_sorting
  BGL
  Surface_modeling

I have remerged the PR for tonight. I hope Andreas and Sébastien will 
eventually stop breaking the internal releases.

-- 
Laurent Rineau, PhD
R&D Engineer at GeometryFactory           http://www.geometryfactory.com/
Release Manager of the CGAL Project       http://www.cgal.org/

**Pull request merged**
