### PR TITLE
Incorrect definition of ccProd

### PR DESCRIPTION
**Pull request by albert-github**
The ccProd macro for formulas is defined as `\sum_{#1}^{#2}{#3}` but this should be `\prod_{#1}^{#2}{#3}`, probably a cut and paste error from ccSum.
Only place where ccProd is used in the (code) documentation is: Polynomial/doc/Polynomial/Concepts/PolynomialTraits_d--Resultant.h

### CODE REVIEW

**Comment by albert-github** [comment]
**Note**
 The proposed pull request #4644 also contains this change, but I think this proposed pull request has its value as it clearly signals the ccProd problem and otherwise it goes under  in the major change of #4644.

**Comment by lrineau** [comment]
This PR is flagged for 4.14.x, but the branch is based on `master`.

**Comment by sloriot** [comment]
@albert-github  I guess we can close this one if the fix is included in the PR updating the location of the macro definitions?

**Comment by albert-github** [comment]
@sloriot  In principle yes, but for the clarity, see my argumentation in my previous comment, I think it would be better to incorporate this proposed pull request before incorporating the proposed pull #4644

**Comment by albert-github** [comment]
As #4644 has been merged into master, so this pull request became obsolete unless it will be  used for older versions.

@sloriot, @lrineau up to you to decide.

**Comment by sloriot** [comment]
Let's close it.

**Pull request closed without merging**
