### PR TITLE
Polyhedron demo : fix deformation plugin

### PR DESCRIPTION
**Pull request by janetournois**
This PR fixes the list of roi_border edges collected before deformation.

The result is that the ROI area does not get wrong after isotropic remeshing

and adds a default constructor to ROI_border_pmap (will be needed by isotropic remeshing soon)

### CODE REVIEW

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-160][t].

[t]:https://cgal.geometryfactory.com/CGAL/testsuite/results-4.8-Ic-160.shtml

**Comment by janetournois** [comment]
isotropic remeshing has been introduced for 4.8, so this PR targets 4.8

**Comment by sloriot** [comment]
I tested it locally and it seems that the problematic behavior is still there.

**Comment by lrineau** [comment]
This bug is currently the last one blocking CGAL-4.8-beta2.

**Comment by sloriot** [comment]
working on it

**Comment by sloriot** [comment]
The branch should be ready now. It also contains 2 bug fixes in the Surface mesh deformation package and polygon mesh processing package.

**Comment by lrineau** [comment]
Will be in [CGAL-4.8-Ic-162][i].

[i]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.8-Ic-162.shtml

**Comment by lrineau** [comment]
@janetournois @sloriot I imaging that you both tested the modifications locally on your machine?

**Comment by sloriot** [comment]
I did

**Comment by janetournois** [comment]
I did too! Thanks

**Pull request merged**
