### PR TITLE
Add CGAL::Euler::add_faces()

### PR DESCRIPTION
**Pull request by sloriot**
Add an alternative to iterative calls to `add_face()`

Using a 700K faces mesh with `Surface_mesh` I have:
```
Reading from stream
  is_valid? 1
Total time: 0.822106

Reading from soup + iterative add_face
  Read soup: 0.469716
  is_valid? 1
  time for iterative add_face: 0.170593
Total time: 0.646068

Reading from soup + add_faces
  Read soup: 0.468396
  is_valid? 1
  time for add_faces: 0.116195
Total time: 0.588976
```
@MaelRL there is a hack in `read_OFF` that you might want to consider and generalize for #4255

**TODO:**
- <s>[ ] code TODOs</s>
- <s>[ ] use the function for IO</s>
- <s>[ ] doc</s>
- <s>[ ] SF</s>
- <s>[ ] generalize the function to also handle face given as a range of id + map id->vertex?</s>
- [x] reallocation of patches around a non-manifold patch
- <s>[ ] factorize the check of valid face in `add_face()` and use it? What about the impact on the runtime?</s>

### CODE REVIEW

**Comment by sloriot** [comment]
@afabri that's here I'd like to see if we can benefit from using `Small_unordered_map`.

**Comment by sloriot** [comment]
We decided to integrate the function as is without documentation for now as API changes might be introduced when integrating with the I/O package.

**Comment by sloriot** [comment]
With d59100d I now have:
```
Reading from stream
  is_valid? 1
Total time: 0.85878

Reading from soup + iterative add_face
  Read soup: 0.500825
  is_valid? 1
  time for iterative add_face: 0.178803
Total time: 0.685666

Reading from soup + add_faces
  Read soup: 0.497131
  is_valid? 1
  time for add_faces: 0.091022
Total time: 0.59261
```

**Comment by maxGimeno** [comment]
Warnings : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-119.shtml#BGL

**Comment by maxGimeno** [comment]
Conversion warnings remaining: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-120/BGL/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-126.shtml

**Pull request merged**
