### PR TITLE
corefine with non manifold edges

### PR DESCRIPTION
**Pull request by sloriot**
Add a non-documented options to corefine meshes with non-manifold (duplicated) edges.

**TODO**:
- [x] benchmark there is no regression in regular cases
- [x] fix autorefine testsuite
- [x] move new example to tests

### CODE REVIEW

**Comment by maxGimeno** [comment]
Conflicts and TOTO

**Comment by maxGimeno** [comment]
@sloriot at this rate this PR will get postponed

**Comment by sloriot** [comment]
I'm waiting for #5047 to be merged in master.

**Comment by lrineau** [comment]
> I'm waiting for #5047 to be merged in master.

I just merge it.

**Comment by sloriot** [comment]
I did not notice any significant slow down between 5.1 and this branch using 2 meshes of 351K vertices.

**Comment by lrineau** [comment]
@sloriot 

> I did not notice any significant slow down between 5.1 and this branch using 2 meshes of 351K vertices.

Have you found out the cause of the slowdown?

**Comment by maxGimeno** [comment]
> @sloriot
> 
> > I did not notice any significant slow down between 5.1 and this branch using 2 meshes of 351K vertices.
> 
> Have you found out the cause of the slowdown?

@lrineau I think you misread @sloriot 's message

**Comment by maxGimeno** [comment]
Travis errors : 
The following tests FAILED:
```
	608 - compilation_of__corefinement_SM (Failed)
	609 - compilation_of__corefinement_consecutive_bool_op (Failed)
	610 - compilation_of__corefinement_difference_remeshed (Failed)
	611 - compilation_of__corefinement_mesh_union (Failed)
	612 - compilation_of__corefinement_mesh_union_and_intersection (Failed)
	613 - compilation_of__corefinement_mesh_union_with_attributes (Failed)
	614 - compilation_of__corefinement_polyhedron_union (Failed)
	615 - compilation_of__corefine_non_manifold (Failed)
	617 - compilation_of__corefinement_LCC (Failed)
	2216 - compilation_of__test_corefinement_and_constraints (Failed)
	2217 - compilation_of__test_corefinement_bool_op (Failed)
	2218 - compilation_of__test_corefine (Failed)
	2219 - compilation_of__test_coref_epic_points_identity (Failed)
	2220 - compilation_of__test_does_bound_a_volume (Failed)
	2221 - compilation_of__test_pmp_clip (Failed)
	2222 - compilation_of__test_autorefinement (Failed)
	2223 - compilation_of__autorefinement_sm (Failed)
	2226 - compilation_of__test_orient_cc (Failed)
```
and 
```
In file included from /home/travis/build/CGAL/cgal/Installation/../Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/clip.h:18:
In file included from /home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/corefinement.h:23:
In file included from /home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/Visitor.h:21:
/home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h:226:26: error: unknown type name 'halfedge_descriptor'; did you mean 'face_descriptor'?
  void before_edge_split(halfedge_descriptor /* h */, const TriangleMesh& /* tm */){}
                         ^~~~~~~~~~~~~~~~~~~
                         face_descriptor
/home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h:217:40: note: 'face_descriptor' declared here
  typedef typename GT::face_descriptor face_descriptor;
                                       ^
/home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h:227:19: error: unknown type name 'halfedge_descriptor'; did you mean 'face_descriptor'?
  void edge_split(halfedge_descriptor /* hnew */, const TriangleMesh& /* tm */){}
                  ^~~~~~~~~~~~~~~~~~~
                  face_descriptor
/home/travis/build/CGAL/cgal/Polygon_mesh_processing/include/CGAL/Polygon_mesh_processing/internal/Corefinement/face_graph_utils.h:217:40: note: 'face_descriptor' declared here
  typedef typename GT::face_descriptor face_descriptor;
                                       ^
[ 60%] [34m[1mCheck header Mesh_3/include/CGAL/Mesh_cell_criteria_3.h[0m
2 errors generated.
CMake Error at /home/travis/build/CGAL/cgal/Installation/cmake/modules/run_cmd_redirection_cerr.cmake:32 (message):
```

**Comment by lrineau** [comment]
> > @sloriot
> > > I did not notice any significant slow down between 5.1 and this branch using 2 meshes of 351K vertices.
> > 
> > 
> > Have you found out the cause of the slowdown?
> 
> @lrineau I think you misread @sloriot 's message

Indeed. :slightly_frowning_face:

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-5.shtml

**Comment by lrineau** [comment]
> Successfully tested in [cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-5.shtml](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-5.shtml)

@sloriot What about the TODO list at https://github.com/CGAL/cgal/pull/5049#issue-496761822?

**Comment by sloriot** [comment]
I have an improvement of the algorithm coming very soon (currently working in the general case and need to fix it for autorefinement now)

**Comment by lrineau** [comment]
> I have an improvement of the algorithm coming very soon (currently working in the general case and need to fix it for autorefinement now)

OK, I will block this PR and prevent its merge for now.

**Comment by sloriot** [comment]
I'm done with this branch.

**Comment by maxGimeno** [comment]
There are conflicts with master

**Comment by maxGimeno** [comment]
warning : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-60/Polygon_mesh_processing/TestReport_lrineau_Fedora-with-LEDA.gz

**Comment by sloriot** [comment]
The warning is not present in my branch:
```
  typedef typename Kernel::Point_3 Point_3;
  typedef typename cpp11::result_of<
    typename Kernel::Orientation_3(Point_3, Point_3, Point_3, Point_3)>::type
      Orientation;

  Orientation s0 = orientation(o_prime, o, p1, p2);
```
I guess it comes from Dmitry's.

**Comment by maxGimeno** [comment]
Yep, I found it ! Sorry

**Comment by maxGimeno** [comment]
warning :https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-61/Polygon_mesh_processing/TestReport_lrineau_Fedora-rawhide.gz

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-65.shtml

**Pull request merged**
