### PR TITLE
Add boost::hash and std::hash

### PR DESCRIPTION
**Pull request by afabri**
Add hash functors for the iterators and circulators of classes based on In_place_list, Compact_container, Surface_mesh.

https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/hash

### CODE REVIEW

**Comment by lrineau** [comment]
- :x: The small feature page [declares a modification of `changes.html`][c] but the branch does not modify that file.
  - :white_check_mark: The script `./Scripts/developer_scripts/test_merge_of_branch` does not detect any issue.
  - :warning: The branch was tested rather successfully in [CGAL-4.7-Ic-67][Ic-67], but there is a warning in a test file `test/Hash_map/Hash.cpp`:
```
test/Hash_map/Hash.cpp:40:34: warning: unused parameter 'lcc' [-Wunused-parameter]
void fct2(Linear_cell_complex_3& lcc)
                                 ^
1 warning generated.
```
[c]: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/hash#changes.html
[Ic-67]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-67.shtml#Hash

**Comment by lrineau** [comment]
This feature has a serious issue with recent clang++ and libc++. The forward declaration of `std::hash` is not permitted by the norm, and it does break!

**Comment by afabri** [comment]
Do we have to introduce a CGAL_CFG_....  for which we test whether std::hash<int> can be  instantiated?

**Comment by lrineau** [comment]
`BOOST_NO_CXX11_HDR_FUNCTIONAL` from Boost.Config could be used to detect if `<functional>` from the STL has all the C++ features.

**Comment by afabri** [comment]
Do you suggest to use this macro directly, or do we define a CGAL_NO_HASH based on BOOST_NO_CXX11_HDR_FUNCTIONAL ?

**Comment by lrineau** [comment]
We will have to create a macro `CGAL_CFG_NO_STD_HASH` because `BOOST_NO_CXX11_HDR_FUNCTIONAL` was introduced in Boost 1.50, and it seems that we still support version 1.48 and later.

In `<CGAL/config.h>`, one can see constructions like:
```c++
#if defined(BOOST_NO_LAMBDAS) || BOOST_VERSION < 104000
#define CGAL_CFG_NO_CPP0X_LAMBDAS 1
#endif
```

For `std::hash`, it could be:
```c++
#if defined(BOOST_NO_CXX11_HDR_FUNCTIONAL) || BOOST_VERSION < 105000
#define CGAL_CFG_NO_STD_HASH 1
#endif
```

**Comment by afabri** [comment]
Isn't it then an easier solution to  have a test file that does #include <functional> and tries to instantiate std::hash<int> ???

**Comment by lrineau** [comment]
No. The definition of the macro is three lines, and it does not have any know issue. With the test files, we have several problems:
  - that slows down each CMake run,
  - it is not robust: when compiler flags are changed for a CGAL program, we need to re-configure the CGAL libraries, so that `<CGAL/compiler_config.h>` is updated,
  - incompatible with the idea that CGAL is headers-only,
  - and that does not work for cross-compilation.

If all those test files could be entirely removed, that would be a good gain.

**Comment by lrineau** [comment]
I have created the issue #287 to track that task.

**Comment by afabri** [comment]
and what about boost < 50 then ???

**Comment by lrineau** [comment]
If such an old version of Boost is used, I think it is safe to assume that C++11 is not used, and thus `std::hash` does not exist. The only use-case that would be problematic is a user expecting CGAL handles and iterators to be usable with `std::hash`, but using an old version of Boost. And even for that use case, the user could still pass a user-defined hash function as a template argument. I suggest we ignore such a use case, until somebody complains.

**Pull request merged**
