### PR TITLE
CMap make null_handle const

### PR DESCRIPTION
**Pull request by gdamiand**
Make the (internal and undocumented) variable null_handle const.

It is a bug fix (because the fact that this variable was non cost was a bug).

Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-113.shtml.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-115

**Comment by lrineau** [comment]
Please try to find a better title for the pull-request! :smile:

**Comment by gdamiand** [comment]
I thinks it was an automatic title taken from the name of the branch...

**Comment by gdamiand** [comment]
@sloriot I don't understand why you do another test since I already tested this branch in CGAL-4.8-Ic-113 ?

**Comment by lrineau** [comment]
@gdamiand the title can still be changed afterward, no?

**Pull request merged**
