### PR TITLE
Stream_support: Fix reading WKT POLYGON

### LINKED ISSUE #4379: WKT  Is the data set buggy?
## Issue Details

Why is the first point repeated [here](https://github.com/CGAL/cgal/blob/master/Stream_support/examples/Stream_support/data/polygons.wkt#L3)?  When I read it into a Polygon with holes it is not simple because there is a zero length segment.

@maxGimeno please check.

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

As a file with a  `POLYGON` repeats the first point of the sequence we ended up with a zero length segment inside a `CGAL::Polygon_2`, so we have to remove the last point (or write our own WKT parser).

I fixed at the same time that we set the `failbit` of the `istream&`  in case the boost reading function throws an exception.

TODO: 
  - [x] @maxGimeno  please do the same fixes for the `MULTIPOLYGON`. 

## Release Management

* Affected package(s): Stream_support
* Issue(s) solved (if any): fix #4379

### CODE REVIEW

**Comment by maxGimeno** [comment]
You forgot `typename`s

**Comment by afabri** [comment]
> 
> 
> You forgot `typename`s

Please fix it at the same time as you fix the other issuer.

**Comment by lrineau** [comment]
Travis error: https://travis-ci.org/CGAL/cgal/jobs/632220960#L5707

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-53.shtml

**Pull request merged**
