### PR TITLE
Fix general_polygon_example.png

### PR DESCRIPTION
**Pull request by lbartoletti**
## Summary of Changes

The visibility zone is slightly offset on the original image. This version displays the correct zone.

Before:

image

After:

image

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by lbartoletti** [comment]
> @lbartoletti There is an issue with your commit: it is empty.

Ooops. Fixed.

**Comment by afabri** [comment]
In case you use a vector graphics tool for producing the image it would be preferable that you commit a svg version.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-106

**Comment by sloriot** [comment]
cf https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-6.0-Ic-106/output2/Visibility_2/index.html#fig__general_polygon

**Pull request merged**
