### PR TITLE
New class of MeshDomainWithFeatures_3, from a polyhedral complex

### PR DESCRIPTION
**Pull request by lrineau**
Small feature: [Add `Polyhedral_complex_mesh_domain_3`](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_Polyhedral_complex_mesh_domain_3)

### CODE REVIEW

**Comment by janetournois** [comment]
To allow not to protect borders and sharp features in a polyhedral complex, we decided to overload `construct_initial_points_object()` in this new mesh domain.
To be able to do so, I had to make quite a few modifications about constness of functions and make internal data structures `mutable`. This is done in commit 087c6ab.
cc @lrineau

**Comment by janetournois** [comment]
I agree!

**Comment by afabri** [comment]
LR: needs a small feature...

**Comment by lrineau** [comment]
TODO: This PR will require a small feature.

**Comment by lrineau** [comment]
TODO; this PR will require a small feature.

**Comment by lrineau** [comment]
And: Travis detected a build failure.

https://travis-ci.org/CGAL/cgal/jobs/237183028#L4184

**Comment by janetournois** [comment]
The [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_Polyhedral_complex_mesh_domain_3) is submitted.

**Comment by lrineau** [comment]
This PR have a conflict with `master`.

**Comment by janetournois** [comment]
I am doing the `rebase`, but it now has compilation errors

**Comment by janetournois** [comment]
rebase done. It should be ok now

**Comment by lrineau** [comment]
I have solved a conflict in `changes.html`, using the Github UI. That merged `master` in the PR.

This PR was tested last night and the line is fully red, probably because of the merge of PR #2102 about weighted points.

https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-60.shtml#Mesh_3

**Comment by lrineau** [comment]
There are also warnings:
```
/mnt/testsuite/include/CGAL/Mesh_domain_with_polyline_features_3.h:875:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Mesh_domain_with_polyline_features_3.h:875: warning: comparison between signed and unsigned integer expressions
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:530:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:530: warning: comparison between signed and unsigned integer expressions
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:805:17: warning: unused variable 'poly_id' [-Wunused-variable]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:805: warning: unused variable ‘poly_id’
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:905:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:905: warning: comparison between signed and unsigned integer expressions
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:930:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:930: warning: comparison between signed and unsigned integer expressions
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:935:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:935: warning: comparison between signed and unsigned integer expressions
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:943:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/testsuite/include/CGAL/Polyhedral_complex_mesh_domain_3.h:943: warning: comparison between signed and unsigned integer expressions
```

**Comment by janetournois** [comment]
I am taking care of it

**Comment by janetournois** [comment]
I rebased the branch with `master`, and the warnings and errors seen in the testsuite should be fixed now

**Pull request merged**
