### PR TITLE
Nef_3: Avoid a filter failure

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Avoid a geometric test that will lead to a filter failure

## Release Management

* Affected package(s): Nef_3
* License and copyright ownership: maintenance

### CODE REVIEW

**Review by sloriot — APPROVED** [review]

**Comment by afabri** [comment]
@GilesBathgate in case you give this a try let me know if it also makes things faster for you. I sometimes have the impression that depending on what exactly we test, we discover other aspects that can improve on.  For example I never did an affine transformation in my benchmarks.

**Comment by GilesBathgate** [comment]
@afabri There does seem to be a performance increase in my tests but not as significant. Certainly in the profiler, this is a hotspot that your changes improve.

I still get overall better performance with my changes in #5486

**Comment by GilesBathgate** [comment]
> Remove unused local variable (why did no compiler warn?)

Because the variable removed has a constructor that could have a side-effect
http://cpp.sh/4slyj

**Comment by maxGimeno** [comment]
Error : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-105/Convex_decomposition_3/TestReport_lrineau_Debian-stable-Release.gz

**Comment by afabri** [comment]
Fixed and checked locally with the testsuite.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-106.shtml

**Pull request merged**
