### PR TITLE
LCC: fix examples with Qt5

### PR DESCRIPTION
**Pull request by gdamiand**
Update the basic viewer to use qt5 instead of qt4.

(plus some improvement in the drawing function).

Tested in https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-41.shtml

### CODE REVIEW

**Comment by sloriot** [comment]
It seems there are new warnings on one platform:
+++ CGAL-4.8-Ic-41/results_lrineau_CentOS7-Release.txt	2015-11-07 00:56:37.000000000 +0100
+Combinatorial_map w
+Combinatorial_map_Examples w
+Linear_cell_complex w
+Linear_cell_complex_Demo w
+Linear_cell_complex_Examples w
+Polyhedron_Demo w

**Comment by gdamiand** [comment]
This is once again the warning "array subscript is above array bounds".

Another bug introduced in gcc 5.1 ? (which is a new test platform)

Indeed if we compare gcc 5.1 (test 26), gcc 4.8.3 (test 21) and gcc 4.9.2 (test 5) they have all the same flags (-frounding-math -Wall -O3 -DCGAL_NDEBUG) but three different behaviour :
* gcc 5.1 warning in are_cc_isomorphic (and not in Is_sewable_functor)
* gcc 4.8.3 warning in Is_sewable_functor (and not in are_cc_isomorphic)
* gcc 4.9.2 no warning

Moreover note that this PR does not modify anything regarding these warnings; they are still there in master.

**Comment by sloriot** [comment]
If relevant here, have you tried using the macro `CGAL_ASSUME`?

**Comment by gdamiand** [comment]
I didn't try; I don't want to lose time on these bogus warning...

**Comment by sloriot** [comment]
It was the first time the branch was merged and some windows platform were missing.
I also added a CGAL_ASSUME to try if it solved the warning in `CGAL/Combinatorial_map.h:913`
on CentOS7-Release

Merged in 4.8-Ic-43

**Comment by sloriot** [comment]
Windows testsuite is still missing.
Merged in 4.8-Ic-44

**Pull request merged**
