### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by maxGimeno**
- fix for the indentation warnings
- removes the gluErrorString from Volume_planes.h in the Polyhedron_demo Mesh_3 plugin

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-112

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-113

**Comment by maxGimeno** [comment]
Added more fixes. Should be ready to merge

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-115

**Comment by maxGimeno** [comment]
I added a license to a file.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-116

**Pull request merged**
