### PR TITLE
Bug fix in doc

### PR DESCRIPTION
**Pull request by gdamiand**
## Summary of Changes

Remove duplicated lines in doc import_from_polyhedron_3

## Release Management

* Affected package(s): Linear_cell_complex

### CODE REVIEW

**Comment by lrineau** [comment]
If the bug was already present in CGAL-4.9 or CGAL-4.10, I think the PR should be against the corresponding branch.

**Comment by lrineau** [comment]
Same for this PR, Guillaume. Let me know if you want to apply the same patch to CGAL-4.9.1 and CGAL-4.10.

**Comment by gdamiand** [comment]
@lrineau Thanks ! Yes you can apply this to CGAL-4.9.1 and CGAL-4.10.

**Comment by lrineau** [comment]
I could not apply the patch to CGAL-4.9, but only to CGAL-4.10.

**Pull request merged**
