### PR TITLE
WIP: Throw Away Branch to see if Windows swaps

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

The Mesh_3 testsuite on Windows with TBB activated (2013,2015, but not 2017) hits the timeout.
I can't reproduce it locally on my machine by just compiling `test_meshing_3D_image .cpp`.   The files in a test directory are compiled sequentially, while the directories  test and examples may be compiled simultaneously.  This PR moves `Mesh_3/examples/Mesh_3` into `XMesh/examples/XMesh`.

@lrineau can you confirm that @maxGimeno can put it into integration.
## Release Management

* Affected package(s): Mesh_3

### CODE REVIEW

**Comment by lrineau** [comment]
I think Maxime @maxGimeno can merge it into `integration`.

**Comment by afabri** [comment]
The VC2013 Mesh_3 test passes when there are no examples. Maybe it is enough to buy more memory.

**Comment by afabri** [comment]
@maxGimeno how to add a new package that makes it into the testsuite?

**Comment by lrineau** [comment]
This PR will never go into `master`. It is only an attempt.

**Comment by maxGimeno** [comment]
I know, I mean if the attempt is successful and we decide to do it for real.

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Feb 4, 2019, 9:56 AM GMT+1](https://github.com/CGAL/cgal/pull/3634#issuecomment-460172128 "2019-02-04T08:56:35Z - Replied by Github Reply Comments"):
> I know, I mean if the attempt is successful and we decide to do it for real.

Even if we are convinced by the test, we will not do it this way. The best way would be to generate the order ourselves, instead of relying on the files globbing.

**Comment by maxGimeno** [comment]
Ah ok.

**Comment by lrineau** [comment]
That does not seem related to swapping at all. Today, I was watching the resource monitor of the Windows machine (gauguin), while the testsuite was running. And, during the test of the platform `x64_Cygwin-Windows10_MSVC2013-Debug-64bits`, the test `test_meshing_3D_gray_image.exe` ran for more than 50 minutes, and the memory usage was very low (about 4GB out of 32GB).

The compilation flags were:
```
$ cat CMakeFiles/test_meshing_3D_gray_image.dir/flags.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.12

# compile CXX with C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /wd4503 /bigobj /D_DEBUG /MDd /Ob0 /Od /RTC1   -DNOMINMAX -DCGAL_LINKED_WITH_TBB -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /wd4503 /bigobj

CXX_DEFINES = -DBOOST_ALL_DYN_LINK -DBOOST_ALL_DYN_LINK=1 -DCGAL_EIGEN3_ENABLED -DCGAL_TEST_SUITE=1 -DCGAL_USE_GMP -DCGAL_USE_MPFR -DCGAL_USE_ZLIB=1

CXX_INCLUDES = -IC:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\test\Mesh_3\..\..\..\AABB_tree\include -IC:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\test\Mesh_3 -IC:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\include -IC:\CGAL\test\CGAL-4.14-Ic-115\include -IC:\3rdPartyLibs\zlib-1.2.11\build_msvc2013\include -IC:\3rdPartyLibs\boost\boost_1_57_0 -IC:\3rdPartyLibs\VC-64\gmp-5.0.1_and_mpfr-3.0.0\include -IC:\3rdPartyLibs\eigen-3.3.4 -IC:\3rdPartyLibs\tbb2018_20170919oss\include
```

The link flags were:
```
test_meshing_3D_gray_image.exe: CMakeFiles\test_meshing_3D_gray_image.dir\objects1.rsp
        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=C:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\test\Mesh_3\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable test_meshing_3D_gray_image.exe"
        C:\dev\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\test_meshing_3D_gray_image.dir --manifests  -- C:\PROGRA~2\MICROS~2.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\test_meshing_3D_gray_image.dir\objects1.rsp @<<
 /out:test_meshing_3D_gray_image.exe /implib:test_meshing_3D_gray_image.lib /pdb:C:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\test\Mesh_3\test_meshing_3D_gray_image.pdb /version:0.0  /machine:x64 /DEBUG:NONE /INCREMENTAL:NO /subsystem:console  -LIBPATH:C:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\lib C:\3rdPartyLibs\VC-64\gmp-5.0.1_and_mpfr-3.0.0\lib\libmpfr-4.lib C:\3rdPartyLibs\VC-64\gmp-5.0.1_and_mpfr-3.0.0\lib\libgmp-10.lib C:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\lib\CGAL_ImageIO-vc120-mt-gd-4.14-Ic-115.lib C:\CGAL\test\CGAL-4.14-Ic-115\cmake\platforms\x64_Cygwin-Windows10_MSVC2013-Debug-64bits\lib\CGAL-vc120-mt-gd-4.14-Ic-115.lib C:\3rdPartyLibs\tbb2018_20170919oss\lib\intel64\vc12\tbb_debug.lib C:\3rdPartyLibs\tbb2018_20170919oss\lib\intel64\vc12\tbbmalloc_debug.lib C:\3rdPartyLibs\VC-64\gmp-5.0.1_and_mpfr-3.0.0\lib\libmpfr-4.lib C:\3rdPartyLibs\VC-64\gmp-5.0.1_and_mpfr-3.0.0\lib\libgmp-10.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_thread-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_system-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_chrono-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_date_time-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_atomic-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_thread-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_chrono-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_system-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_date_time-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\boost\boost_1_57_0\lib64_msvc12\boost_atomic-vc120-mt-gd-1_57.lib C:\3rdPartyLibs\zlib-1.2.11\build_msvc2013\lib\zlib.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
```
(from `build.cmake` in the same directory.)

**Comment by lrineau** [comment]
Replaced by #3674. This throw-away PR can be closed without merge.

**Pull request closed without merging**
