### PR TITLE
Mesh 3 - fix initialization

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

PR #7280 highlighted the fact that the mesh refinement `one_step()` loop may crash if the C3T3 had been corrupted during the initialization step.
Now both `refine_mesh()` and the `one_step()` loop have the exact same behaviour.

This crash was first met in the demo :
- open cube.off
- "Tetrahedral mesh generation -> Generate surface mesh"
- keep all default parameters
- OK

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by sloriot** [comment]
Error [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-228/Mesh_3/TestReport_Christo_MSVC2017-Debug-64bits.gz)

**Comment by janetournois** [comment]
I can't reproduce the error, even with the seed

**Comment by janetournois** [comment]
I gave it another try with the same options as in the testsuite but still cannot reproduce the error...

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-241

**Pull request merged**
