### PR TITLE
Installation - update `FindOpenMesh.cmake`

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR updates CGAL's `FindOpenMesh.cmake`, accordingly with the one provided by OpenMesh 11.0, and introducing the target `OpenMesh::OpenMesh` 

## Release Management

* Affected package(s): Installation
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by sloriot** [comment]
Since the target is from CGAL, shouldn't be prefixed with CGAL? Or even  CGAL_OpenMesh_support to be consistent?

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-300

**Comment by janetournois** [comment]
I have unpushed temporary code to add the CGAL prefix as you suggested @sloriot 
Do not merge this PR yet

**Comment by janetournois** [comment]
Christo is up-to-date to test CGAL examples with OpenMesh-11.0

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-321

**Pull request merged**
