### PR TITLE
CGAL_ENABLE_CHECK_HEADERS implies CGAL_PROFILE

### LINKED ISSUE #1622: Add -DCGAL_PROFILE to check_headers

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Set CGAL_PROFILE to ON  if CGAL_ENEABLE_CHECK_HEADERS is ON.
## Release Management

* Affected package(s):Installation
* Issue(s) solved (if any): fix #1622

### CODE REVIEW

**Comment by lrineau** [comment]
I do not understand the patch. As far as I know the CMake variable `CGAL_PROFILE` is not used anywhere.

The issue #1622 is about defining the C++ macro `CGAL_PROFILE` to `1` (with the compilation flag`-DCGAL_PROFILE`). Probably here:
https://github.com/maxGimeno/cgal/blob/cb5bf32f09651f6bc0c998bba2114ad36f5f7ea0/Installation/CMakeLists.txt#L1069-L1077
To be tested. As I said, that may trigger new failures in the "check headers" process. I think the idea is to test the header files of `Profiling_tools/include` that rely on processor conditionals on `CGAL_PROFILE`:
``` shellsession
$ ack '\bCGAL_PROFILE\b' Git/cgal/Profiling_tools/include/CGAL
Git/cgal/Profiling_tools/include/CGAL/Profile_timer.h
24:// triggered by CGAL_PROFILE to enable it:
70:#ifdef CGAL_PROFILE

Git/cgal/Profiling_tools/include/CGAL/Profile_counter.h
25:// triggered by CGAL_PROFILE to enable them:
231:#ifdef CGAL_PROFILE
```

**Comment by lrineau** [comment]
I was right. That `-DCGAL_PROFILE` triggered new compilation errors in the `CHECK` lines of our Travis tests:
https://travis-ci.org/CGAL/cgal/jobs/341359443

**Comment by maxGimeno** [comment]
How do we fix that ?

**Comment by lrineau** [comment]
The error is rather simple to understand, once you manage to extract it from the verbose compilation log:
```
/home/travis/build/CGAL/cgal/Segment_Delaunay_graph_Linf_2/include/CGAL/Segment_Delaunay_graph_Linf_2/Voronoi_vertex_sqrt_field_new_C2.h:1052:10:
  error: invalid use of incomplete type ‘std::ofstream {aka class
  std::basic_ofstream<char>}’
         ofs.precision(16);
            ^
```
The fix is `#include <fstream>` to that the class template `std::ofstream` is defined.

I suggest you run the "check_headers" locally, because there might be other failures. I think the Travis test stops at the first error.

**Comment by lrineau** [comment]
The Travis CHECK line is now fixed. The PR is selected for tonight `integration` test.

**Comment by lrineau** [comment]
Tested successfully in [CGAL-4.12-Ic-182], and then merged.

[CGAL-4.12-Ic-182]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-182.shtml

**Pull request merged**
