### PR TITLE
Use get_filename_component to manipulate paths

### PR DESCRIPTION
**Pull request by lrineau**
Replaces #131 from Philipp:

> This caused a bug in CMake>=3.3.0 when file(GLOB) is not adding multiple
> slashes. The lack of trailing slashes is guaranteed and documented in
> `get_filename_component`.

> Verified against a build of Kitware/CMake@f4144af

The initial patch from #131 was not right, for CMake<=2.8.11. I have:
  - rebased the branch onto `releases/CGAL-4.6-branch`,
  - added a commit to use `PATH` instead of `DIRECTORY`.

### CODE REVIEW

**Comment by lrineau** [comment]
Tested on CentOS 5 with CMake version 2.6.4.

**Comment by lrineau** [comment]
Also tested on Fedora Rawhide (Fedora 23 to be), with CMake version 3.3.0-rc1.

**Comment by bo0ts** [comment]
:+1: 
Thanks for fixing this.

**Comment by lrineau** [comment]
See also https://github.com/CGAL/cgal-testsuite-dockerfiles/commit/5a4143a6f5e4dd8cf42438a265a6501b358dcd01 ("Add Dockerfile for Fedora Rawhide").

**Pull request merged**
