### PR TITLE
Document exactness of constructions in Epick

### LINKED ISSUE #1433: Documenting and checking exactness of geometric primitives
_Section [Documenting and checking exactness of geometric primitives](https://cgal.geometryfactory.com/CGAL/Members/wiki/Meetings/Zurich16#Documenting_and_checking_exactness_of_geometric_primitives) of CGAL developers meeting a Zurich'16._
- Shall we document for `CGAL::Epick` the list of constructions that are known to be exact?
- Or document the representation of CGAL geometrical objects, in CGAL kernels?
- Or can we add a machinery so that the compiler can warn about non-exact constructions?

### PR DESCRIPTION
**Pull request by HoffmannMichael**
## Summary of Changes

Document which constructions are always guaranteed to be exact for `Epick`.  These are mostly access functions and/or sign changes. But as the representation of geometric objects is not specified, the user has no way to know. Documenting which constructions are exact allows to reason about the correctness of user code using epic and some of these "trivial" constructions. 

It is implemented by putting a list on the doc page of `Epick` itself and also add an "Exactness" comment on the page of the corresponding member or global function. 

## Release Management

* Affected package(s): Kernel_23, Documentation
* Issue(s) solved (if any): fix #1433
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature): https://cgal.github.io/7412/v2/Kernel_23/classCGAL_1_1Exact__predicates__inexact__constructions__kernel.html
* License and copyright ownership: n/a

### CODE REVIEW

**Comment by albert-github** [comment]
Looks like you have to add the `\cgalEpicExact`  to the `ALIASES` of the, relatively new, file `Documentation/doc/resources/1.9.6/BaseDoxyfile.in` as well

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-116

**Comment by lrineau** [comment]
Hi @HoffmannMichael, this work you did during last CGAL developers meeting is eventually merged in the documentation.

**Comment by afabri** [comment]
Luckily you had come to the previous developer meeting. Hope to see you in Lyon :>

**Pull request merged**
