### PR TITLE
fixed three documentation typos

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by lrineau** [comment]
That was merged in `master`. Should we backport the patch to the branch `releases/CGAL-4.7-branch`?

**Comment by sloriot** [comment]
it would be useless

**Comment by lrineau** [comment]
There is only one commit. It could be cherry-picked. We know it was already tested.

**Comment by afabri** [comment]
If it takes less time than this discussion just do it.
If it takes longer lets not do it as it is not deep.

**Comment by lrineau** [comment]
Done in 5655fec14972a832d78f896a720be2e4aaf10ebf

**Pull request merged**
