### PR TITLE
New package Point_set_3

### PR DESCRIPTION
**Pull request by sgiraudot**
[Full feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Point_set_3) reviewed as API ready.

### CODE REVIEW

**Comment by sloriot** [comment]
No error reported by `test_merge_of_branch`, weight is 212K

**Comment by lrineau** [comment]
@sloriot I see that only the API of the feature has been accepted so far. Until the manual is fully accepted, we cannot mark the feature as accepted, in my opinion.

**Comment by lrineau** [comment]
@sloriot For CGAL-4.10?

@sgiraudot Can you describe the impact of this PR on CGAL? I see that the PR mostly adds new files (in a new package). What about the modifications to existing files? How risky are they?

**Comment by sgiraudot** [comment]
It's a new package that has pretty much no impact on any other package.

There is no modification to existing files (most of the change of code in `Surface_mesh` have already been included since this PR https://github.com/CGAL/cgal/pull/1527), except for the addition of a missing `const` in a Point Set Processing file and a new method in the Properties of Surface Mesh. The risk of breaking something is very close to 0.

**Comment by sloriot** [comment]
@palliez and I are the reviewer. Pierre did have a look at the user manual, I didn't. I was waiting for the result of the testsuite to have a look.

**Comment by sgiraudot** [comment]
There were warnings in the testsuite, they should now be fixed.

**Comment by sloriot** [comment]
There is an issue with `PackageDescriptions.txt`. See https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.10-Ic-93/output/Manual/packages.html

**Comment by sgiraudot** [comment]
Arghh, still one warning... Fixed.

**Comment by sgiraudot** [comment]
Testsuite looks good at last.

**Pull request merged**
