### PR TITLE
Fix the merge of PR #2478 into releases/CGAL-4.11-branch

### PR DESCRIPTION
**Pull request by lrineau**
Fix bug #2708.

### CODE REVIEW

**Comment by lrineau** [comment]
@sgiraudot This PR is now the only one blocking the release of CGAL-4.11.1. Can you have a look at the branch, and see how the PR #2590/#2568  could be reapplied to the branch?

**Comment by sgiraudot** [comment]
The problem came from https://github.com/CGAL/cgal/pull/2666/files, integrated on 4.11 but which depended on https://github.com/CGAL/cgal/pull/2358, integrated in 4.12.

I cherry-picked the commits of https://github.com/CGAL/cgal/pull/2358 in this PR: I tested locally and it seems to solve the issue.

**Comment by lrineau** [comment]
This PR will be tested tonight in a special version of `integration` composed from `releases/CGAL-4.11-branch` (instead of `master`), plus this PR.

**Comment by lrineau** [comment]
The testsuite is not pretty (a lot of warnings, some fixed in `master`, and a strange system error on gauguin)... but I merge this PR anyway. There is no visible regression.

**Pull request merged**
