### PR TITLE
Remove Qt3 based demos

### PR DESCRIPTION
**Pull request by afabri**

### CODE REVIEW

**Comment by sloriot** [comment]
I created a release from the branch and I got many errors while trying to compile all examples, demos and tests. Probably a problem in the scripts modified...

-- Configuring test in test/AABB_tree_Demo
-- Requested component: Qt5
-- Requested component: MPFR
-- Requested component: GMP
-- Found QGLViewer: /home/sloriot/install/libQGLViewer-2.6.2/QGLViewer/libQGLViewer.so
CMake Error at test/AABB_tree_Demo/CMakeLists.txt:54 (add_executable):
  add_executable cannot create target "AABB_demo" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory "/tmp/CGAL-release/CGAL-new/demo/AABB_tree".  See
  documentation for policy CMP0002 for more details.

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by lrineau** [comment]
Sorry. I have reverted my merge in integration. It seems more work is needed (see https://github.com/CGAL/cgal/pull/389#issuecomment-146228572).

**Comment by lrineau** [comment]
TODO: fix the permission issue: `mode change 100644 => 100755 Documentation/dont_submit`

**Comment by lrineau** [comment]
I fixed the permission.

**Comment by lrineau** [comment]
Merged in [CGAL-4.8-Ic-21](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-21.shtml).

**Comment by afabri** [comment]
needs another test as there were warnings in the User Manuals

**Comment by lrineau** [comment]
Merged in [CGAL-4.8-Ic-22](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-22.shtml).

**Comment by lrineau** [comment]
There are still [warnings in the Doxygen compilation][1]:
```
Warning: source /home/cgal-testsuite/integration/Nef_3/demo is not a readable file or directory... skipping.
citelist:10: Warning: Unexpected new line character
/home/cgal-testsuite/integration/Nef_3/doc/Nef_3/CGAL/IO/Qt_widget_Nef_3.h:24: Warning: unable to resolve reference to `Nef_3/visualization_SNC.cpp' for \ref command
/home/cgal-testsuite/integration/Nef_3/doc/Nef_3/CGAL/IO/Qt_widget_Nef_3.h:24: Warning: included file Nef_3/visualization_SNC.cpp is not found. Check your EXAMPLE_PATH
```

[1]: https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.8-Ic-22/Nef_3.log

**Comment by sloriot** [comment]
Merged in [4.8-Ic-23](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-23.shtml)

**Comment by sloriot** [comment]
Merged in [4.8-Ic-28](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-28.shtml)

**Comment by sloriot** [comment]
The testsuite was good. I'm still doing some manual tests before merging the branch

**Comment by sloriot** [comment]
The error reports on the flat layout is not related to the branch as it happen with other internal releases as well. Basically `-DWITH_tests=ON` cannot be combined with `-DWITH_examples=ON` or `-DWITH_demos=ON` as the tests also create examples and demos.

**Pull request merged**
