### PR TITLE
Some Documentation Fixes for Issue #3457

### LINKED ISSUE #3457: Problematic external links in documentation (non literature)
Ran a link check over the resulting documentation, from master, regarding inconsistencies / errors.
There are different categories of problems. 
This issue is regarding external link problems (non literature  as for this issue #3455 has been submitted). It is possible that a number of issues (like boost, wikipedia) are present a number of times as the source is used on multiple places.

Other problems(like doxygen problems) I'm investigating.

Find attached an overview of the non literature problematic links.

[links_non_literature.txt](https://github.com/CGAL/cgal/files/2585846/links_non_literature.txt)

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Mainly http -> https
Not clear what to do with boost. 
More to do after @albert-github 's next run.

## Release Management

* Issue(s) solved (if any): fix #3457

### CODE REVIEW

**Comment by afabri** [comment]
I would suggest to target 4.14 as there are also some real fixes (Intel MKL, Ipe, ....)

**Comment by afabri** [comment]
@albert-github can you do me the favor and update the list of wrong links.

**Comment by albert-github** [comment]
I'll have (during the weekend  ?) a go at it.

**Comment by lrineau** [comment]
I have reviewed the changes. I agree for CGAL-4.14, but only if you do not push any new commit to the pull-request. Any new modifications will have to be in another pull-request targeting CGAL-5.0.

**Comment by lrineau** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-159.shtml.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Mar 26, 2019, 1:00 PM GMT+1](https://github.com/CGAL/cgal/pull/3780#issuecomment-476594709 "2019-03-26T12:00:08Z - Replied by Github Reply Comments"):
> @albert-github can you do me the favor and update the list of wrong links.


[**@albert-github**](https://github.com/albert-github) commented on [Mar 26, 2019, 1:10 PM GMT+1](https://github.com/CGAL/cgal/pull/3780#issuecomment-476597898 "2019-03-26T12:10:46Z - Replied by Github Reply Comments"):
> I'll have (during the weekend  ?) a go at it (in the master version)

Please fill a new issue, or reopen #3457.

**Comment by lrineau** [comment]
This PR was tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-159.shtml, then merged.

**Pull request merged**
