### PR TITLE
Polygon mesh processing, new package

### PR DESCRIPTION
**Pull request by lrineau**
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Polygon_mesh_processing

Feature developed by Jane Tournois (@janetournois), Ilker O.Yaz, Sébastien Loriot (@sloriot),   and Andreas Fabri (@afabri).

### CODE REVIEW

**Comment by lrineau** [comment]
To be fixed before the integration in `master`:
 - :x: the script `./Scripts/developer_scripts/test_merge_of_branch` detects that there are license issues in the directory `Polygon_mesh_processing/`. It seems some files have no licenses/copyright notices.

**Comment by lrineau** [comment]
- :x: The target "dual" in `examples/BGL_surface_mesh` must be renamed (for example to `sm_dual`), to avoid a conflict with an existing target in `examples/BGL_arrangement_2` (that one should be renamed too).
 - :x: Same with target "normals" in `test/Polygon_mesh_processing`.
 - :x: There are difficult conflicts in `Polyhedron/demo`. While merging that pull-request in `integration`, I had to try resolve them, and it was not strait-forward (conflicts in UI files, the no-keyword branch, issues with methods from PMP that are not found). I was not able to solve everything, so tonight's testsuite will be pretty red at the `Polyhedron_Demo` line.

**Comment by lrineau** [comment]
Andreas, Sébastien, Jane, I added you as collaborators in my fork https://github.com/lrineau/cgal .
To update that pull-request, use that command once:
```
git remote add lrineau git@github.com:lrineau/cgal.git
```
then you can update the pull-request with a modified version of ["Update a pull-request" from thw wiki](https://cgal.geometryfactory.com/CGAL/Members/wiki/Guidelines/Source_Code_Management_GIT#Update_a_pull-request):
```
git fetch lrineau
git status
# if there is a deviation, maybe you need to merge/pull with:
#  git merge lrineau/Polygon_mesh_processing-GF
git push lrineau Polygon_mesh_processing-GF
```

**Comment by lrineau** [comment]
Great job!
 - :white_check_mark: The script `./Scripts/developer_scripts/test_merge_of_branch` no longer detects any license issue.
 - :white_check_mark: The script `./Scripts/developer_scripts/test_merge_of_branch` no longer detects any issue with the naming of targets.
 - :white_check_mark: Conflicts were solved.

One remaining issue, that Sébastien @sloriot will help you deal with:
 - :x: The script `./Scripts/developer_scripts/test_merge_of_branch` detects that the weight of the branch, compressed, is 11.7MB!

**Comment by lrineau** [comment]
:x: You must also modify `Installation/changes.html` to announce the new package.

**Comment by lrineau** [comment]
Is Sébastien working with you on the "weight of branch" issue, or should I do something?

**Comment by sloriot** [comment]
I'll take care of it but it might be more complicated than other branches (because another branch has this one merged into it)

**Comment by lrineau** [comment]
:white_check_mark: The script ./Scripts/developer_scripts/test_merge_of_branch no longer detects any issue. but:
 - :x: the weight of the branch, compressed, is 11.7MB!

**Comment by sloriot** [comment]
After filtering the branch size its size is now 1.9M

**Comment by sloriot** [comment]
The branch is now compatible with Qt5.

**Comment by sloriot** [comment]
Today is the day of the alpha1 release. For that reason I will merge that pull-request in master today. Up to minor warnings, test results of CGAL-4.7-Ic-87 are good. The warnings will be fixed before the beta.

**Pull request merged**
