### PR TITLE
SMSP: fix border and robustness issues

### PR DESCRIPTION
**Pull request by sloriot**
## Summary

Fixes issues in `SMSP` with open meshes and excessive pruning of the window tree.

TODO:
- [x] PR for 5.0 once this one is stable

## Release Management
Package: `Surface_mesh_shortest_path`
Fixes: #3993 (initially an issue on [SO](https://stackoverflow.com/questions/56439971/cgal-triangulated-surface-mesh-shortest-paths-assertion-errors))

## Misc
Some code that was useful to debug it but that I don't want to commit: https://gist.github.com/MaelRL/c9cbb326195673b65cdb70c4cb51a597

### CODE REVIEW

**Comment by maxGimeno** [comment]
[warnings](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-57.shtml#Surface_mesh_shortest_path)

**Comment by lrineau** [comment]
@maxGimeno I think @sloriot does not have the time to maintain this pull-request. Please fix the warnings.

**Comment by maxGimeno** [comment]
[warnings](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-)71.shtml#Surface_mesh_shortest_path

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-73.shtml

**Comment by lrineau** [comment]
@sloriot What about the "work in progress" label. Is this PP ready for integration?

**Comment by sloriot** [comment]
#3993 contains an additional issue that this PR should fix so the status is correct.

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Jul 3, 2019, 12:52 PM GMT+2](https://github.com/CGAL/cgal/pull/3977#issuecomment-508043892 "2019-07-03T10:52:06Z - Replied by Github Reply Comments"):
> #3993 contains an additional issue that this PR should fix so the status is correct.

So, I do not merge it, for the moment.

**Comment by lrineau** [comment]
Should I still delay the merge of this PR? I hope to release bug-fix releases pretty soon, and this PR may delayed too long.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jul 10, 2019, 2:29 PM GMT+2](https://github.com/CGAL/cgal/pull/3977#issuecomment-510040260 "2019-07-10T12:29:30Z - Replied by Github Reply Comments"):
> Should I still delay the merge of this PR? I hope to release bug-fix releases pretty soon, and this PR may delayed too long.

Well, "pretty soon" was optimistic. But the question remains. @sloriot?

**Comment by sloriot** [comment]
I did not have time to look at it. @MaelRL did. But I guess we can delay the milestone of this PR.

**Comment by MaelRL** [comment]
I don't have any ETA for #3993, I have only a very vague knowledge of the algorithm and I don't understand what's going wrong right now let alone a fix, only that it is related to numerical errors in almost-flat configurations.

Probably should integrate this PR and deal with #3993 later.

**Comment by lrineau** [comment]
If @sloriot agrees, then the commit https://github.com/CGAL/cgal/pull/3977/commits/fdfa7fc75b1e4f2061b38cc33450b474676990df should be reverted, and a new PR created.

**Comment by sloriot** [comment]
Let's only mark it as not for the next release. We'll see if we manage to fix it during the meeting.

**Comment by lrineau** [comment]
This PR will have to be recreated, based on 4.14-branch.

**Comment by lrineau** [comment]
Is this PR ready to be tested and eventually integrated in 4.14.2 and 5.0?

**Comment by MaelRL** [comment]
Should be ready now, pending travis.

**Comment by lrineau** [comment]
Travis seems OK. Please create the PR for `master`, so that we can test it in `integration`.

**Pull request merged**
