### PR TITLE
Fix selection issue with boundary vertices

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes

An extra test was needed when a vertex is on the boundary

## Release Management

* Affected package(s): BGL

### CODE REVIEW

**Comment by lrineau** [comment]
This PR has a conflict with `master`. Can you please merge it in `integration`?

**Comment by sloriot** [comment]
Done.

**Comment by lrineau** [comment]
Thanks. I have registered the conflict resolution in git-rerere, so that I can redo it on demand.

**Comment by lrineau** [comment]
There are runtime errors about `test_Manifold_face_removal.cpp` in the BGL line of the [test results of CGAL-4.14-Ic-20](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-20.shtml#BGL) in a few platforms.

**Comment by sloriot** [comment]
This has to do with iteration order and another connected component of faces is removed thus changing the final number of faces. I'll change the test to avoid counting the number of faces but rather verify the invariant.

**Comment by lrineau** [comment]
Plead merge in integration. I am no longer at the office.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.14-Ic-27][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-27.shtml

**Pull request merged**
