### PR TITLE
Solver_interface: Move documentation to  include/CGAL/*.h

### LINKED ISSUE #2470: Solver Interface: documentation is split between /doc/CGAL and /include/CGAL
The documentation of the package `Solver_interface` is rendering incompletely (see https://doc.cgal.org/latest/Solver_interface/classCGAL_1_1Eigen__sparse__matrix.html) because it is split between `/doc/CGAL/XXX.h` and `/include/CGAL/XXX.h`. All the documentation of the latter is then ignored.

They should be merged.

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

@MaelRL can you please check the manual once it is in the manual testsuite.

## Release Management

* Affected package(s): Solver_interface
* Issue(s) solved (if any): fix #2470

### CODE REVIEW

**Comment by afabri** [comment]
@lrineau can you please put it into a testsuite so that Mael can check the resulting manual

**Comment by lrineau** [comment]
There are Doxygen errors:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-59/Solver_interface.log
```
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:91: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:115: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:176: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:203: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:143: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_matrix.h:313: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_solver_traits.h:162: Warning: Found unknown command `\commentheading'
/home/cgal-testsuite/cgal_doc_build/CGAL-4.12-Ic-59/include/CGAL/Eigen_solver_traits.h:252: Warning: Found unknown command `\commentheading'
```

**Comment by MaelRL** [comment]
I have removed `Eigen_sparse_matrix`'s `assemble_matrix` from the doc (and its useless call in one of the example) in 7e3ed29. It strikes me more as an implementation detail.

**Comment by lrineau** [comment]
This PR conflicts with #2469. It will be tested later.

**Pull request merged**
