### PR TITLE
Fix call with EPECK

### LINKED ISSUE #7577: Compilation errors when using PMP::remove_almost_degenerate_faces with Exact_predicates_inexact_constructions_kernel
## Issue Details

Attempting to use the `CGAL::Polygon_mesh_processing::remove_almost_degenerate_faces` function from 5.6-beta1 with a `CGAL::Exact_predicates_inexact_constructions_kernel` kernel results in the following error while compiling with Visual Studio 17.6.1:
```
error C2664: 'int CGAL::Polygon_mesh_processing::internal::Is_cap_angle_over_threshold_impl<CGAL::Simple_cartesian<boost::multiprecision::number<boost::multiprecision::backends::gmp_int,boost::multiprecision::et_on>>>::operator ()(const CGAL::Point_3<Kernel_> &,const CGAL::Point_3<Kernel_> &,const CGAL::Point_3<Kernel_> &,const boost::multiprecision::number<boost::multiprecision::backends::gmp_int,boost::multiprecision::et_on>) const': cannot convert argument 4 from 'T' to 'const boost::multiprecision::number<boost::multiprecision::backends::gmp_int,boost::multiprecision::et_on>'
 with
[         
 Kernel_=CGAL::Simple_cartesian<boost::multiprecision::number<boost::multiprecision::backends::gmp_int,boost::multiprecision::et_on>>
]
and
[
  T=double
]
```

The `CGAL::Polygon_mesh_processing::experimental::remove_almost_degenerate_faces` function from previous versions didn't display this behavior.

## Source Code

Simple example which reproduces the issue:
```cpp
#include <CGAL/Surface_mesh.h>
#include <CGAL/Polygon_mesh_processing/repair_degeneracies.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

using Kernel = CGAL::Exact_predicates_exact_constructions_kernel;
using Point_3 = Kernel::Point_3;
using Mesh = CGAL::Surface_mesh<Point_3>;

int main()
{
  Mesh mesh;
  CGAL::Polygon_mesh_processing::remove_almost_degenerate_faces(mesh);
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Windows 11
* Compiler: Visual Studio 17.6.1
* Release or debug mode: both
* Specific flags used (if any):
* CGAL version: 5.6-beta1
* Boost version: 1.75 and 1.80
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by sloriot**
FIxes #7577

### CODE REVIEW

**Comment by mglisse** [comment]
Just to check: in the error message, the kernel seemed to be `Simple_cartesian<mpz_int>`. `square(threshold)` converted to an integer type is 0 or 1 (for mpz_class it may even be always 0). Is that the desired result? (I know nothing of this package, maybe it is what should happen)

**Comment by sloriot** [comment]
The error message was mentioning conversion from double to boost mp with gmp backend. All other exact nt backend was fine. Do you me to double check?

**Comment by mglisse** [comment]
> conversion from double to boost mp with gmp backend

Note: conversion to the **integer** type of boost mp, not the *rational* type. That was the strange part for me.

Without GMP and with an old Boost, before your patch, I see
`/home/glisse/repos/cgal/Number_types/include/CGAL/NT_converter.h:37:16: error: no matching function for call to ‘CGAL::MP_Float::MP_Float(const CGAL::Quotient<CGAL::MP_Float>&)’`

**Comment by sloriot** [comment]
Replaced by #7588

**Comment by sloriot** [comment]
Thanks a lot @mglisse, that was definitely a big issue that you spotted!

**Pull request closed without merging**
