### PR TITLE
Fix changes.html

### PR DESCRIPTION
**Pull request by aympelle**
3D periodic triangulations changes were badly located.

### CODE REVIEW

**Comment by lrineau** [comment]
I do not understand the change. Why do you want to split the entry *3D Periodic Triangulations* in two separate entries?

**Comment by lrineau** [comment]
OK, I got it: something was announced in 4.4, but some of it was actually in 4.5, and the rest will be in 4.7. I merge.

Note that it will not change what was announced on the web site.

**Comment by lrineau** [comment]
You can remove your branch `Fix_3D_PT_in_changes_html-APelle` from your fork.

**Comment by MoniqueTeillaud** [comment]
I can correct the entries in the website (I already fixed a bunch of layout bugs that I mentioned on cgal-develop)

**Pull request merged**
