### PR TITLE
Polygon mesh processing - add isotropic remeshing

### PR DESCRIPTION
**Pull request by janetournois**
This PR introduces the incremental triangle based isotropic remeshing algorithm of M.Botsch et al.

It is associated with the following small feature,
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_PMP_isotropic_remeshing
accepted on October 21st, 2015.

Code is ready for testing.
The user manual is the only thing that is not completely ready, it should be ready today.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-37

**Comment by janetournois** [comment]
I remerged into CGAL-4.8-Ic-37 after these 3 commits

**Comment by sloriot** [comment]
Full red line :)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-40

**Comment by sloriot** [comment]
The tests, examples and demos have warnings.

**Comment by janetournois** [comment]
The warning on msvc2015 is a warning about boost code. How should we process about it? Ignore until it's fixed?

**Comment by janetournois** [comment]
Merged in CGAL-4.8-I-42

**Comment by janetournois** [comment]
Merged in CGAL-4.8-Ic-44

**Comment by janetournois** [comment]
Merged in CGAL-4.8-Ic-45

**Comment by janetournois** [comment]
Merged in CGAL-4.8-Ic-47

**Comment by sloriot** [comment]
@afabri: please fix the issue in the BGL testsuite with OpenMesh

**Comment by sloriot** [comment]
@janetournois + @maxGimeno: please work together to update the scene_edit_polyhedron_item conflicts (use enum instead of hard coded values)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-49

**Comment by janetournois** [comment]
the PMP testsuite looks good, apart from some boost warnings

**Comment by afabri** [comment]
In Number_types/include/CGAL/Mpzf.h we can find 
```C++
    // If Clang has the warning -Wunused-local-typedef, then disable it temporarily.
    #if BOOST_WORKAROUND(BOOST_VERSION, BOOST_TESTED_AT(105800)) &&     BOOST_CLANG && __has_warning("-Wunused-local-typedef")
    #  define CGAL_CLANG_PUSH_AND_IGNORE_UNUSED_LOCAL_TYPEDEF \
        _Pragma("clang diagnostic push") \
        _Pragma("clang diagnostic ignored \"-Wunused-local-typedef\"")
    #  define CGAL_CLANG_POP_DIAGNOSTIC _Pragma("clang diagnostic pop")
    #else
    #  define CGAL_CLANG_PUSH_AND_IGNORE_UNUSED_LOCAL_TYPEDEF
    #  define CGAL_CLANG_POP_DIAGNOSTIC
    #endif
```
Would it make sense to factorize that so that it can be used elsewhere.  @mglisse

**Comment by sloriot** [comment]
`test_merge_of_branch` reported no error with this branch.

**Comment by mglisse** [comment]
> Would it make sense to factorize that so that it can be used elsewhere.

Pretty sure I didn't write that. Which typedef is this about, and can't it be removed?

**Comment by afabri** [comment]
The [testsuite](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-49/Polygon_mesh_processing/TestReport_lrineau_ArchLinux-clang-Release.gz)

Polygon_mesh_processing/fairing_test.cpp
In file included from /home/cgal_tester/build/src/cmake/platforms/ArchLinux-clang-Release/test/Polygon_mesh_processing/fairing_test.cpp:6:
/mnt/testsuite/include/CGAL/Polygon_mesh_processing/fair.h:129:5: warning: unused typedef 'boost_static_assert_typedef_131' [-Wunused-local-typedef]

**Pull request merged**
