### PR TITLE
Intersections_2: Fix bugs and populate tests (4.14)

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

This PR is a continuation of PR #3938. it contains bug fixes in some 2D intersection combinations that were introduced in 4.14.

The intersections_2 tests are enhanced by testing, for each combination of types, cases that yield all different types of intersection (e.g. `Iso_rectangle_2` vs `Line_2` can be nothing, `Point_2`, or `Segment_2`). Doesn't meant that all branches of the code have been tested, though.

## Release Management

Integrate #3938 first.

* Affected package(s): `Intersections_2`

### CODE REVIEW

**Comment by lrineau** [comment]
It seems CGAL in non-header-only is broken:

https://travis-ci.org/CGAL/cgal/jobs/533792214#L7754
```
[  2%] Building CXX object Installation/src/CGAL/CMakeFiles/CGAL.dir/all_files.cpp.o
In file included from /home/travis/build/CGAL/cgal/build_test/Installation/src/CGAL/all_files.cpp:2:
/home/travis/build/CGAL/cgal/Intersections_2/src/CGAL/Bbox_2_intersections.cpp:29:10: fatal error: 
      'CGAL/Intersections_2/internal/Bbox_2_Line_2_intersection_impl.h' file not
      found
#include <CGAL/Intersections_2/internal/Bbox_2_Line_2_intersection_impl.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MaelRL** [comment]
Does the plateform Fedora-32 (might need to be renamed with Fedora version 32 on the corner) require the `CGAL::Set_ieee_...` shenanigans? (One error, in https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-49/Intersections_2/TestReport_lrineau_Fedora-32-Release.gz.)

**Comment by lrineau** [comment]
[**@MaelRL**](https://github.com/MaelRL) commented on [Jun 3, 2019, 8:15 AM GMT+2](https://github.com/CGAL/cgal/pull/3940#issuecomment-498126310 "2019-06-03T06:15:10Z - Replied by Github Reply Comments"):
> Does the plateform Fedora-32 (might need to be renamed with Fedora version 32 around the corner) require the `CGAL::Set_ieee_...` shenanigans? (One error, in https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-49/Intersections_2/TestReport_lrineau_Fedora-32-Release.gz.)

Yes, with an x86 processor in 32 bits, the FPU is the venerable x87 co-processor. The line `force_ieee_double_precision();` restricts it from using 80 bits register for floating points, instead of the standard 64 bits for the precision of `double`.

**Comment by maxGimeno** [comment]
Seems all good in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-59.shtml

**Comment by lrineau** [comment]
@maxGimeno The first message of this PR says that PR #3938 should be integrated first. I cannot merge this PR until #3938 is correctly tested and merged.

And then your other PR #3999 is stuck as well.

**Comment by MaelRL** [comment]
Note that this PR is based on #3938, but the other one is based on 4.13 so this being tested doesn't guarantee everything for the other one.

**Comment by MaelRL** [comment]
Note that this PR is based on #3938, but the other one is based on 4.13 so this being tested doesn't guarantee everything for the other one.

**Comment by maxGimeno** [comment]
Oh ok, so the other one is not the 4.14 based version of this PR, and I need to test both at the same time.

**Comment by MaelRL** [comment]
No, the other PR just needs to be tested on CGAL-4.13. 

Although it's probably not very interesting, the changes of the other PR are just forwarded into this PR.

**Comment by maxGimeno** [comment]
So we should consider both tested, integrate them in there respective bases, and check that #3938 did not break 4.13 afterwards.

**Comment by lrineau** [comment]
If you eventually agree, let me know which PR I should merge now.

**Comment by MaelRL** [comment]
I'm just stating what is tested and what isn't. Usually PRs for 4.13 seem to be tested on master. If you follow that road, then it's ready to be merged.

**Comment by maxGimeno** [comment]
It's just that half the files affected by #3938 have disappeared from 4.14 so it is a little hard to test in master...

**Comment by lrineau** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-62.shtml

I have merged #3938 as well.

**Pull request merged**
