### PR TITLE
Rename get() to get_pointee_or_identity()

### PR DESCRIPTION
**Pull request by afabri**
An example that used a built-in array revealed that the compiler (VC++) didn't find the right function <code>get()</code>.  One solution was to add <code>using ::get;</code>.  The cleaner solution is to rename the function which is only an implementation detail.

### CODE REVIEW

**Comment by lrineau** [comment]
Is that a bug fix of a small feature?

**Comment by afabri** [comment]
a bug fix

On 11/05/2015 17:33, Laurent Rineau wrote:
> Is that a bug fix of a small feature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/pull/78#issuecomment-100947667>.
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by lrineau** [comment]
What you call a bug fix adds an example:
https://github.com/CGAL/cgal/pull/78/files#diff-990e5d5ea820d31bd2b384c421d1f21b
Is that intended?

In my opinion, examples are supposed to be documented in the user manual of the package, and that one is not. I have the impression that the branch that was used to create the pull-request had another goal, at the beginning. Am I wrong?

**Comment by afabri** [comment]
This example lead to the bug.

I can move it to another branch and mention
it into the user manual.  After all it corresponds
to what Nicolas Douillet wanted to achieve.

andreas

**Comment by lrineau** [comment]
It seems that this pull-request would fix the bug #83. Maybe the branch should be rebased onto CGAL-4.6.

**Comment by lrineau** [comment]
I have pushed a branch named [`afabri-CGAL-array_as_property_map-GF-rebased-on-CGAL-4.6`](https://github.com/CGAL/cgal-dev/tree/afabri-CGAL-array_as_property_map-GF-rebased-on-CGAL-4.6) to cgal-dev. How can we update that pull-request?

**Comment by lrineau** [comment]
Replaced by #85.

**Pull request closed without merging**
