### PR TITLE
Remove Z offset.

### LINKED ISSUE #3661: Polyline display is broken
When displaying a mesh + polylines, I can see the polylines from both sides.
screenshot from 2019-02-06 14-38-40
screenshot from 2019-02-06 14-38-51

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Remove the Z offset in the shaders for the wide edges, so it is not visible through faces anymore. Selected edges are impacted, as original edges will be seen on top of them. Not very aesthetic but much clearer.
## Release Management
* Issue(s) solved (if any): fix #3661

### CODE REVIEW

**Comment by lrineau** [comment]
There is now a conflict with `master`.

**Comment by maxGimeno** [comment]
Fixed

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-122.shtml

**Comment by lrineau** [comment]
@sloriot, have you checked if this PR fixes the drawing issues you reported in #3661?

**Comment by sloriot** [comment]
No but since I provided the input files, @maxGimeno has already checked it was fine.

**Pull request merged**
