### PR TITLE
Use regular font

### LINKED ISSUE #4634: Strange typesetting of words "GPL" and "LGPL" in license text
## Issue Details

When looking at the file https://doc.cgal.org/latest/Manual/license.html we see here that the words "GPL" and "LGPL" are set in a, in my opinion, a bit a strange way.
CGAL_lic

## Source Code

The origin of this problem is the fact that the wordds "GPL" and "LGPL" are set in so called "small-caps" and that in the code they are written as: `\sc{Gpl}` and `\{Lgpl}`:
```
Documentation/doc/Documentation/License.txt:6:\sc{Gpl}/\sc{Lgpl} open source license, as well as under commercial licenses.
Documentation/doc/Documentation/License.txt:19:The \sc{Gpl} is an Open Source license that, if you distribute your software
Documentation/doc/Documentation/License.txt:20:based on \sc{Gpl}ed \cgal data structures, obliges you to distribute the
Documentation/doc/Documentation/License.txt:21:source code of your software under the \sc{Gpl}.
Documentation/doc/Documentation/License.txt:28:The \sc{Lgpl} is an Open Source license that obliges you to distribute
Documentation/doc/Documentation/License.txt:30:In contrast to the \sc{Gpl}, there is no obligation to make the source
Documentation/doc/Documentation/License.txt:31:code of software you build on top of \sc{Lgpl}ed \cgal data structures.
Documentation/doc/Documentation/License.txt:38:We have chosen the \sc{Gpl} and the \sc{Lgpl} as they are well-known
Documentation/doc/Documentation/License.txt:44:the \sc{Lgpl}, and the higher level packages under the \sc{Gpl}.
Documentation/doc/Documentation/License.txt:60:use packages of \cgal released under the \sc{Lgpl}.
```

I think that it probably is better to use `\sc{GPL}` and `\sc{LGPL}`.

I haven't, yet, made a pull request of it as I think it is a a bit an opinion problem.

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #4634

Only for 5.0 branch as the file has been moved and it isn't worth the trouble to backport onto 4.14

### CODE REVIEW

**Comment by sloriot** [comment]
@maxGimeno Any idea why travis think that Surface_mesh_topology has disappeared?

**Comment by gdamiand** [comment]
> @maxGimeno Any idea why travis thinks that Surface_mesh_topology has disappeared?

Surface_mesh_topology does not exist in 5.0; it was integrated in 5.1.

**Comment by maxGimeno** [comment]
@sloriot : 
`@MaelRL MaelRL changed the base branch from master to releases/CGAL-5.0-branch 22 hours ago`

That's the reason why. This operation alwayus break Travis.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-126.shtml

**Pull request merged**
