### PR TITLE
Periodic_3: Use static filters also for Epeck and make  it faster

### PR DESCRIPTION
**Pull request by afabri**
The class `Periodic_3_Delaunay_triangulation_traits_3` had a partial specialisation for `Epick` but not for `Epeck`.  I added that.   I added at the same time the usage of the functor that takes `x()` of the approximated point instead of the approximation of the exact x value. That saves the constructions of lazy numbers in case of the exact constructions kernel.

@lrineau Is it possible to avoid the include of Epick and Epeck for the partial specialization

@MoniqueTeillaud Is there a need for the filtered traits class header files (publicly)

### CODE REVIEW

**Comment by sloriot** [comment]
Why not using the nested `static const bool` `Has_static_filters` and `Has_filtered_predicates` instead ?

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-140

**Comment by sloriot** [comment]
I used the aforementioned flags and remove the include directives to predefined kernels.
However, note that the full performance boost will be on only when #853 is merged.

**Comment by afabri** [comment]
- [ ]   Cleanup examples which use filtered traits class
- [ ]   Work around imposing Boolean tags.
- [ ] Remove deprecated traits class

**Comment by MoniqueTeillaud** [comment]
please also take care of the same change for periodic regular triangulations in the branch - thanks

**Comment by sloriot** [comment]
Done in CGAL/cgal-dev@5a95ab3. However, I did not do the part checking whether the flag exists in the traits as it requires a file from this branch.

**Comment by lrineau** [comment]
@sloriot The commit GAL/cgal-dev@5a95ab3 does not seem to be part of this pull-request. Is that intentional?

**Comment by sloriot** [comment]
Yes, it is in a branch about another feature (periodic regular) that is not yet ready to be integrated (see this [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_Periodic_3_regular_triangulation_3))

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-6][6].

[6]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-6.shtml

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-6/Periodic_3_triangulation_3/TestReport_lrineau_Debian-stable-Release.gz
```
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:190:57: warning: 'px' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqx = qx - px + domx * ( o_q.x() - opx );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:188:28: warning: 'domzmin' may be used uninitialized in this function [-Wmaybe-uninitialized]
    double domz = domzmax - domzmin;
                            ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:188:28: warning: 'domzmax' may be used uninitialized in this function [-Wmaybe-uninitialized]
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:187:28: warning: 'domymin' may be used uninitialized in this function [-Wmaybe-uninitialized]
    double domy = domymax - domymin;
                            ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:187:28: warning: 'domymax' may be used uninitialized in this function [-Wmaybe-uninitialized]
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:186:28: warning: 'domxmin' may be used uninitialized in this function [-Wmaybe-uninitialized]
    double domx = domxmax - domxmin;
                            ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:186:28: warning: 'domxmax' may be used uninitialized in this function [-Wmaybe-uninitialized]
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:198:57: warning: 'sz' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double psz = sz - pz + domz * ( o_s.z() - opz );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:197:57: warning: 'sy' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double psy = sy - py + domy * ( o_s.y() - opy );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:196:57: warning: 'sx' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double psx = sx - px + domx * ( o_s.x() - opx );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:195:57: warning: 'rz' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double prz = rz - pz + domz * ( o_r.z() - opz );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:194:57: warning: 'ry' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pry = ry - py + domy * ( o_r.y() - opy );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:193:57: warning: 'rx' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double prx = rx - px + domx * ( o_r.x() - opx );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:192:57: warning: 'qz' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqz = qz - pz + domz * ( o_q.z() - opz );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:191:57: warning: 'qy' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqy = qy - py + domy * ( o_q.y() - opy );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:190:57: warning: 'qx' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqx = qx - px + domx * ( o_q.x() - opx );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:192:57: warning: 'pz' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqz = qz - pz + domz * ( o_q.z() - opz );
                                                         ^
../CGAL/internal/Static_filters/Periodic_3_orientation_3.h:191:57: warning: 'py' may be used uninitialized in this function [-Wmaybe-uninitialized]
           double pqy = qy - py + domy * ( o_q.y() - opy );
                                                         ^
```

**Comment by lrineau** [comment]
There is a warning:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-22/Periodic_3_triangulation_3/TestReport_lrineau_Debian-stable-Release.gz

Can it be triggered by this PR?

**Comment by lrineau** [comment]
TODO: I think this PR needs some kind of review.

In particular, do we want to keep backward compatibility with code, like all examples, that are using `#include <CGAL/Periodic_3_Delaunay_triangulation_filtered_traits_3.h>`?

Cc: @MoniqueTeillaud

**Comment by afabri** [comment]
I would like to break it.

**Comment by lrineau** [comment]
@afabri:
> I would like to break it.

That would be a new policy in CGAL.

What is the plan, to inform users? At the very least there should be a "breaking change" warning in the changes log.

**Comment by afabri** [comment]
Definitely the breaking change warning. But it is a question of resource management: the periodic triangulations are not yet central, and all the users have to do is to change a line with a typedef.

**Comment by lrineau** [comment]
Well, I disagree.

You are lucky: I will  on vacation next week.

**Comment by sloriot** [comment]
@MoniqueTeillaud As the maintainer of this package please decide what needs to be done (that is merge the PR as is or do something more).

**Comment by MoniqueTeillaud** [comment]
Sébastien just informed me that there is a question for me... It is hard to get a clear overview from the  long sequence of small messages on this page. At least what I can easily understand is that there is no general agreement, and that Laurent proposes to have a review. Is there a small feature submitted? It would make the discussion more open within the CGAL crowd.

**Comment by sloriot** [comment]
The only thing that changed is that before you have to pick `Periodic_3_Delaunay_triangulation_filtered_traits_3<kernel>` if you know that you kernel is filtered while now you can always pick `Periodic_3_Delaunay_triangulation_traits_3<kernel>` (like it is done for regular_triangulation_3, Alpha_shape_3, ....). I guess we can add a compatibility header so that the example of the previous release works but display a deprecation warning (but that file wiil need to be removed in a later release by the maintainer of the package).

cc @MoniqueTeillaud

**Comment by afabri** [comment]
Could the class `Periodic_3_Delaunay_triangulation_filtered_traits_3<kernel>`  have exactly the same code as the class `Periodic_3_Delaunay_triangulation_filtered_traits_3<kernel>` ?

**Comment by sloriot** [comment]
With EPIC and EPECK yes.

**Comment by sloriot** [comment]
OK, I've added a backward compatibility header and examples of CGAL 4.8 now compiles but with the following warning:
`Warning: The header <CGAL/Periodic_3_Delaunay_triangulation_filtered_traits_3.h> is deprecated. Please use <CGAL/Periodic_3_Delaunay_triangulation_traits_3.h> instead.`
This settle the point of discussion. No need to go one more time in the testsuite (according to the former test results and the last modification).

**Comment by MoniqueTeillaud** [comment]
mmm… “could X have the same code as X?” 
I am afraid that there is a bug in the question…

--
Monique Teillaud 
http://www.loria.fr/~teillaud/ 
INRIA Nancy - Grand Est, LORIA 
Institut National de Recherche en Informatique et Automatique

**Comment by MoniqueTeillaud** [comment]
So there is no need for the maintainer to approve? 

What are our submission rules for?

--
Monique Teillaud 
http://www.loria.fr/~teillaud/ 
INRIA Nancy - Grand Est, LORIA 
Institut National de Recherche en Informatique et Automatique

**Comment by afabri** [comment]
It is not a small feature but just some corrective maintenance brought to you by GeometryFactory, and validated by someone different from the author.

**Pull request merged**
