### PR TITLE
Proposal to fix issue #3375

### LINKED ISSUE #3375: Surface_mesh::join does not seem to link free elements correcly
## Issue Details

When chaining free elements (vertices, faces and edges) in Surface_mesh::join method the role of self and other seem to be inverted.

## Environment
* CGAL version: latest

### PR DESCRIPTION
**Pull request by Simon-Lopez**
## Release Management

* Affected package(s): Surface_mesh
* Issue(s) solved (if any): fix #3375

### CODE REVIEW

**Comment by lrineau** [comment]
*As a remark, about the copyright issues: I think this pull-request is not significant enough to require paperwork about the contributor license agreement.*

**Comment by afabri** [comment]
@Simon-Lopez I confirm the bug and your fix. Can you please make me collaborator so that I can push a commit with a testcase in your repo. 
@lrineau this should be rebased to 4.12

**Comment by lrineau** [comment]
Let me know once the branch is finished. If I rewrite the history while you are working on it, we will have troubles.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Oct 9, 2018, 12:43 PM GMT+2](https://github.com/CGAL/cgal/pull/3377#issuecomment-428145442 "2018-10-09T10:43:03Z - Replied by Github Reply Comments"):
> @lrineau this should be rebased to 4.12

That's done, now.

**Warning:** you must now re-fetch the Simon's repo, and then:
```shellsession
> git reset --hard 'Simon-Lopez/simon_cgal_#3375'
```

**Comment by lrineau** [comment]
There is a CMake error detected by Travis:
```
-- Configuring test in test/Surface_mesh
-- Build type: 
-- USING CXXFLAGS = '-std=c++11 '
-- USING LDFLAGS = ' '
-- Code taken from Git branch: HEAD
CMake Error at Installation/cmake/modules/CGAL_CreateSingleSourceCGALProgram.cmake:49 (add_executable):
  add_executable cannot create target "sm_join" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory
  "/home/travis/build/CGAL/cgal/Surface_mesh/examples/Surface_mesh".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  Surface_mesh/test/Surface_mesh/CMakeLists.txt:22 (create_single_source_cgal_program)
```

The `sm_join.cpp` of this PR must be renamed.

**Comment by lrineau** [comment]
Travis says:
```
[ 50%] Building CXX object CMakeFiles/sm_join_test.dir/sm_join_test.cpp.o
/home/travis/build/CGAL/cgal/Surface_mesh/test/Surface_mesh/sm_join_test.cpp:22:29: error: 
      no member named 'vertex_freelist' in
      'CGAL::Surface_mesh<CGAL::Point_3<CGAL::Simple_cartesian<double> > >'
  vertex_descriptor vd = sm.vertex_freelist();
                         ~~ ^
/home/travis/build/CGAL/cgal/Surface_mesh/test/Surface_mesh/sm_join_test.cpp:32:27: error: 
      no member named 'face_freelist' in
      'CGAL::Surface_mesh<CGAL::Point_3<CGAL::Simple_cartesian<double> > >'
  face_descriptor fd = sm.face_freelist();
                       ~~ ^
/home/travis/build/CGAL/cgal/Surface_mesh/test/Surface_mesh/sm_join_test.cpp:42:27: error: 
      no member named 'edge_freelist' in
      'CGAL::Surface_mesh<CGAL::Point_3<CGAL::Simple_cartesian<double> > >'
  edge_descriptor ed = sm.edge_freelist();
                       ~~ ^
3 errors generated.
```
https://travis-ci.org/CGAL/cgal/jobs/439638443#L2100

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.14-Ic-27][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-27.shtml

**Pull request merged**
