### PR TITLE
Parameterization:  Scope name of a #define

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Change to `CGAL_DEBUG_IA` as requested by @lrineau  in a previous PR that got already merged.

### CODE REVIEW

**Comment by afabri** [comment]
As we are on it, what about this `@fixme`?   Do we have that in the kernel?   Shall we add it?  @sloriot

**Comment by afabri** [comment]
In fact we have [`approximate_angle()`](https://doc.cgal.org/latest/Kernel_23/group__approximate__angle__grp.html)

**Comment by sloriot** [comment]
What fixme?

**Comment by afabri** [comment]
> What fixme?

[link](https://github.com/CGAL/cgal/blob/decab153bb9fa9051f3c074b28d35ef72a7d28a9/Surface_mesh_parameterization/include/CGAL/Surface_mesh_parameterization/Iterative_authalic_parameterizer_3.h#L479)

**Review by lrineau — APPROVED** [review]

**Comment by MaelRL** [comment]
Please use something like CGAL_SMP_IA_DEBUG_L0, it's not the general debug macro for the iterative authalic method

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-44

**Pull request merged**
