### PR TITLE
Handle edges with undefined cost

### PR DESCRIPTION
**Pull request by sloriot**
@afabri do you agree with the fix?

### CODE REVIEW

**Comment by lrineau** [comment]
Sébastien, if the PR is for CGAL-4.8.2, can you please rebase the branch and change the base of the PR?

**Comment by sloriot** [comment]
Done, I did it on purpose to test the new edit feature :)

**Comment by lrineau** [comment]
"undefined cost not handled yet" was never displayed in the test suite. That indicates that that code path was never tested. I suggest a new test case be added, to test cases when the cost is undefined.
(TODO)

**Comment by sloriot** [comment]
Done (`simplify_polygon_test data/rectangle.poly`)

**Pull request merged**
