### PR TITLE
Misc fixes for Intersections_3 + related

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Intersections_3 had some issues with missing overloads, redundant files, etc. This PR fixes that, and:
- add missing overloads (e.g. Iso_cuboid & Bbox)
- remove extra overloads in dead files (e.g. Bbox3 Bbox3)
- fix inaccurate usages of K::Object vs Object<K>
- properly use kernel functors rather than member functions of kernel objects, when possible
- Fix a lot of default constructed kernels instead of using parameters
- Misc cleaning + more extensive testing (+ dozen or so bug fixes in actual do_intersect/intersection code)

## Fix in AABB tree

The call to a global function creates a lot of friction when calling `AABB_tree::do_intersect(Query)` with a query type that is not a usual kernel object: the user has to create the overload`do_intersect(Query, Bbox)` and make it visible in the AABB headers. Calling the base traits (model of `AABBGeomTraits`) makes it much simpler to use.

Ideally, the geom traits would not be default constructed, but that is how it is done in the whole `CGAL::AABB_traits` model and it would be some work to change it across the whole `CGAL::AABB_traits` + there are multiple base classes.

TODO:
- [x] Fix bugs, see https://github.com/CGAL/cgal/pull/5777#issuecomment-866968238

Tentative TODO:
- [ ] Orientation of the result in Triangle_3 results: would be nice to have an orientation consistent with the triangle's

## Release Management

* Affected package(s): `AABB_tree`, `Intersections_3`
* Issue(s) solved (if any): -
* License and copyright ownership: No change

### CODE REVIEW

**Comment by MaelRL** [comment]
Here is a list of issues that showed up in the tests I have added:

- [ ] `Epeck::Iso_cuboid_3 P3(55 75 81) P3(62 76 85)` and `Epeck::Sphere_3 = P3(-9 75 83) sqr=64 1`
- [ ] `Epeck::Iso_cuboid_3 P3(0 36 24) P3(5 86 61)` and `Epeck::Line_3 P3(-85 60 26) P3(73 85 43)`
- [ ] `Homogeneous<Epeck_ft>::Plane_3 P3(184 116 70 2) P3(1150 1173 92 23) P3(2759 2790 372 31)` `Homogeneous<Epeck_ft>::Plane_3 P3(195 18 153 3)`
- [ ] `Homogeneous<Epeck_ft>::Plane_3 coeff 0 110 0 0` and `Homogeneous<Epeck_ft>::Sphere_3 148 -74 37 37 4/1 1`
- [ ] illegal Plane_3(FT, FT, FT) constructor in Cartesian_kernel::Construct_radical_plane_3 (only RT is given by the concept and Homogeneous wants Plane_3(RT, RT, RT))
- [ ] `Simple_cartesian<double>::Ray_3 P3(2 0 0) Dir3(-5 0 0)` and `Simple_cartesian<double>::Ray_3 P3(0 0 0) Dir3(1,0,0)`
- [ ] `EPICK::Segment_3 P3(-2,3,4) P3(1,2,-1)` and `EPICK::Sphere_3 P3(9,2,4) sqr = 10000`
- [ ] `Anykernel::Tet3(p(0,0,0), p(0,1,0), p(1,0,0), p(0,0,1))` and `Tr(p(2,0,0), p(2,1,0), p(2,0,1))`
- [ ] `EPICK::Tet3( 42 51 66, 98 85 30, 79 61 61, 31 45 30)` and `EPICK::Triangle_3(67 18 24, 51 79 23, 82 85 18)`

**Comment by maxGimeno** [comment]
Not compatible with #5527
(https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-10.shtml is all red because of that)

**Comment by maxGimeno** [comment]
Errors : 
 - https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-17.shtml#AABB_tree
 - https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-17.shtml#Intersections_3

**Comment by maxGimeno** [comment]
errors:
 - https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-25/Intersections_3/TestReport_lrineau_Fedora-rawhide.gz
 - https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-25/Intersections_3/TestReport_cgaltester_x86-64_Darwin-18.5_Apple-clang-default_Release.gz

warnings:
 - https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-25/Intersections_3/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz
 - https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-25/Intersections_3/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz
 - https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.4-Ic-25/Intersections_3/TestReport_Sosno_MSVC-2022-Preview-Release.gz

**Comment by sloriot** [comment]
@CGAL/geometryfactory it would be nice if someone can look at the errors/warnings and fix them so that we can test it again (2 PRs depend on this one).

**Comment by MaelRL** [comment]
There are a lot of random tests so any run is beneficial regardless of the errors being fixed.

**Comment by sloriot** [comment]
One warning  left:
`C:\cgal_root\CGAL-5.4-Ic-36\include\CGAL/Intersections_3/internal/Tetrahedron_3_Triangle_3_intersection.h(127,8): warning C4834: discarding return value of function with 'nodiscard' attribute [C:\cgal_root\CGAL-5.4-Ic-36\cmake\platforms\MSVC-2022-Preview-Release\test\Intersections_3\test_intersections_Tetrahedron_3.vcxproj]
   C:\cgal_root\CGAL-5.4-Ic-36\include\CGAL/Intersections_3/internal/Tetrahedron_3_Triangle_3_intersection.h(381): message : see reference to function template instantiation 'boost::optional<boost::variant<CGAL::Point_3<K>,CGAL::Segment_3<K>,CGAL::Triangle_3<K>,std::vector<CGAL::Point_3<K>,std::allocator<CGAL::Point_3<K>>>>> CGAL::Intersections::internal::build_intersection<K,std::list<Segment_3,std::allocator<Segment_3>>,std::vector<CGAL::Point_3<K>,std::allocator<CGAL::Point_3<K>>>>(const CGAL::Tetrahedron_3<K> &,const CGAL::Triangle_3<K> &,PointContainer &,SegmentContainer &,const K &)' being compiled [C:\cgal_root\CGAL-5.4-Ic-36\cmake\platforms\MSVC-2022-Preview-Release\test\Intersections_3\test_intersections_Tetrahedron_3.vcxproj]
             with`

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.4-Ic-42.shtml

**Pull request merged**
