### PR TITLE
Make advanced concept documentation analogous to advanced class.

### PR DESCRIPTION
**Pull request by albert-github**
For the advanced class there is a special ALIAS in the documentation but this is not the case for an advanced concept, the result is that in the brief description a big block appears.
- define ALIAS for advanced concept
- used the `cgalAdvancedConcept` where the block appears in the brief description.

Examples of situation beforehand:
adv_concept_inscr_area
adv_concept_splitter

Afterwards (just one example):
new_adv_concept_inscr_area

### CODE REVIEW

**Comment by sloriot** [comment]
I think this will probably break the post-processing. I guess having a concept marked as advanced does not really make sense anyway. You read a concept only if it is required by a function/class you want to use. @afabri  what do you think?

**Comment by maxGimeno** [comment]
ping @afabri

**Comment by afabri** [comment]
I would also tend to simplify and remove the advancd tag from concepts.

**Comment by sloriot** [comment]
@albert-github could you add me as a collaborator so that I can update the branch accordingly?

**Comment by albert-github** [comment]
@sloriot  I hope I succeeded in adding you to the repository as collaborator.

**Comment by sloriot** [comment]
Yep! Thanks :)

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-124.shtml

**Pull request merged**
