### PR TITLE
Introduce CGAL::Default for the geometric traits of Mesh_triangulation_3

### PR DESCRIPTION
**Pull request by afabri**
[Small feature "Use Default"](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Use_Default)

This is related to #829 

I modified one example so that we can look at before/after.

@lrineau : What do you think?

### CODE REVIEW

**Comment by janetournois** [comment]
It looks nicer indeed
@cjamin do you have an opinion?

**Comment by cjamin** [comment]
I like it.

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-4][4]

[4]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-4.shtml

**Comment by lrineau** [comment]
I like that feature too.

TODO: documentation

**Comment by afabri** [comment]
Private discussion with Laurent:  It is a bad idea to put the type in the `#define`, as one then has to read the CMakLists.txt to see what the possibilities are.

**Comment by lrineau** [comment]
I have a compilation error with that patch:
```
In file included from /home/lrineau/Git/cgal/Mesh_3/examples/Mesh_3/mesh_implicit_domains_2.cpp:3:0:
/home/lrineau/Git/cgal/Mesh_3/include/CGAL/Mesh_triangulation_3.h:71:78: error: declaration of ‘typedef typename CGAL::Default::Get<K, typename CGAL::Kernel_traits<T1>::Kernel>::type CGAL::Mesh_triangulation_3<MD, K, Concurrency_tag, Vertex_base_, Cell_base_>::K’
   typedef typename Default::Get<K, typename Kernel_traits<MD>::Kernel>::type K;
                                                                              ^
/home/lrineau/Git/cgal/Mesh_3/include/CGAL/Mesh_triangulation_3.h:66:20: error:  shadows template parm ‘class K’
 template<class MD, class K, class Concurrency_tag,
                    ^
```

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-5][5].

[5]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-5.shtml

**Comment by lrineau** [comment]
Will be tested in CGAL-4.9-Ic-6.

**Pull request merged**
