### PR TITLE
Add function Kd_tree::find_any_point(Query)

### PR DESCRIPTION
**Pull request by afabri**
tested, documented, small feature.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-7](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-7.shtml)

**Comment by lrineau** [comment]
« tested, documented, small feature. »

How much time would it took to copy-paste the URL to the small feature? How much time do *we* use to retrieve which small feature it is?

**Comment by sloriot** [comment]
@afabri : please update `changes.html`

**Comment by afabri** [comment]
done

**Pull request merged**
