### PR TITLE
Named function parameters (5.0)

### PR DESCRIPTION
**Pull request by sloriot**
Version of #4083 for master branch

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-100.shtml

**Comment by maxGimeno** [comment]
This PR did not break anything so I marked it as Tested and it got integrated, but the state of the Polyhedron_Demo seems to indicate that everything was not done : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-110/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Aug 14, 2019, 4:45 PM GMT+2](https://github.com/CGAL/cgal/pull/4119#issuecomment-521276853 "2019-08-14T14:45:16Z - Replied by Github Reply Comments"):
> This PR did not break anything so I marked it as Tested and it got integrated, but the state of the Polyhedron_Demo seems to indicate that everything was not done : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-110/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz

@sloriot will have a look at that issue once he came back.

**Comment by sloriot** [comment]
I can't reproduce the issue with boost 1.71 on Linux. Looks like a bug in boost on windows. Looking at the following error:
```
C:\3rdPartyLibs\boost_master\install_dir\include\boost-1_71\boost/accumulators/accumulators_fwd.hpp(228): warning C4005: 'BOOST_PARAMETER_NESTED_KEYWORD': macro redefinition
C:\3rdPartyLibs\boost_master\install_dir\include\boost-1_71\boost/parameter/nested_keyword.hpp(107): note: see previous definition of 'BOOST_PARAMETER_NESTED_KEYWORD'
```
does not really make sense. The macro is defined in `nested_keyword.hpp` which is protected for multiple inclusion and `accumululators_fwd.hpp` includes that file.

Maybe you should check locally on the machine if you have the same thing I have.

**Comment by maxGimeno** [comment]
You were right, it was a local bug on the test machine. All fixed now.

**Pull request merged**
