### PR TITLE
Triangulation_2: Add a figure and an example for dimension < 2

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add a figure that illustrates how a low dimensional triangulation is represented.

image

## Release Management

* Affected package(s): Triiangulation_2   only documentation.
* License and copyright ownership:  maintenancy by GeometryFactory

### CODE REVIEW

**Comment by sloriot** [comment]
It seems that you are not using the figure in the doc, is it on purpose?

**Comment by lrineau** [comment]
There is a message from Doxygen:
> CGAL-5.1-Ic-162/doc/Triangulation_2/Triangulation_2.txt:185: warning: image file lowdimensional.svg is not found in IMAGE_PATH: assuming external image.

https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1-Ic-162/logs_master/Triangulation_2.log

**Comment by sloriot** [comment]
The warning is only present in integration not in the branch. Investigating...

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-167.shtml

**Pull request merged**
