### PR TITLE
3D Point-Set Shape Detection, new package

### PR DESCRIPTION
**Pull request by cjamin**
Feature page: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Point_set_shape_detection_3

Tested in CGAL-4.7-Ic-71

### CODE REVIEW

**Comment by sloriot** [comment]
Branch weight is now 1.7M, 624K are due to cube.pwn used in tests and examples

**Comment by sloriot** [comment]
@soesau & @cjamin & @palliez  : What are the remaining tasks to complete before the branch is ready?
I remind you that in the review, it was asked to fill the concept `EfficientRANSACTraits` when the code is ready. Let me know if you need some help to get started with this.

**Comment by soesau** [comment]
On the code side one bugfix (should be done today or tomorrow) and the traits concept remains to be done. 
Afterwards, we would like to do a final pass on the user manual and documentation. 

-- 
Sven Oesau, PhD Student 

TITANE 
INRIA Sophia Antipolis Méditerranée 
https://team.inria.fr/titane/ 

----- Original Message -----

**Comment by sloriot** [comment]
@soesau : Please work on cgal-dev/Point_set_processing-cjamin now. You need to hard reset the branch:
`git checkout Point_set_processing-cjamin`
`git reset --hard cgal-dev/Point_set_processing-cjamin`

**Comment by sloriot** [comment]
I just removed cgal-dev/Point_set_shape_detection_3-soesau to avoid any mistake.

**Comment by sloriot** [comment]
@cjamin @soesau test_sphere_connected_component and test_sphere_parameters crashes with the following output:
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert
test_sphere_connected_component<CGAL::Simple_cartesian<float>> Aborted

**Comment by sloriot** [comment]
@cjamin  @soesau 
gdb says:
0x0000000000564a83 in CGAL::Shape_detection_3::Shape_base<CGAL::Shape_detection_3::Efficient_RANSAC_traits<CGAL::Simple_cartesian<float>, std::vector<CGAL::Point_with_normal_3<CGAL::Simple_cartesian<float> >, std::allocator<CGAL::Point_with_normal_3<CGAL::Simple_cartesian<float> > > >, CGAL::Identity_property_map<CGAL::Point_with_normal_3<CGAL::Simple_cartesian<float> > >, CGAL::Normal_of_point_with_normal_pmap<CGAL::Simple_cartesian<float> > > >::connected_component (this=0x886fe0, 
    indices=std::vector of length 3487, capacity 4096 = {...}, cluster_epsilon=0.215777904)
    at /home/sloriot/CGAL/git/integration/Point_set_shape_detection_3/test/Point_set_shape_detection_3/../../include/CGAL/Shape_detection_3/Shape_base.h:165
165	        bitmap[v * int(u_extent) + u] = true;

**Comment by lrineau** [comment]
Who is working on this pull-request?

**Comment by cjamin** [comment]
Me and @soesau. And trust me, we're working hard :)
We're almost there. I discussed with Sebastien about this bug. It's a bit hard to reproduce because it occurs quite rarely. We tried to fix it but it seems it's still occuring on a few platforms (see today testsuite).
Actually, that's the only remaining problem and I hope to fix it tomorrow.

**Comment by sloriot** [comment]
3ccb377f14c09778cd000af165a8060c46b14bad fixes the bug with spheres

**Comment by sloriot** [comment]
Today is the day of the alpha1 release. For that reason I will merge that pull-request in master today without the aforementioned fix that was not tested through integration.

**Pull request merged**
