### PR TITLE
Maintenance - add new testsuite platforms to Gauguin

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

this PR updates the scripts and caches of Gauguin for testsuites on msvc2017 (64 bits) and msvc2013 (64 and 32 bits).

## Release Management

* Affected package(s): Maintenance

Some changes are still requested to these files to test the demos with Qt5 with msvc2013, and to include OpenMesh for msvc 2013, 32 bits.
cc @maxGimeno

### CODE REVIEW

**Comment by lrineau** [comment]
This PR has the label `TODO`. Should I wait before merging it in `master`?

**Comment by janetournois** [comment]
Yes. As soon as the testsuites of Gauguin are fully satisfactory, we ( @maxGimeno and I) should complete this PR before it is merged.
Hopefully tomorrow!

**Comment by lrineau** [comment]
@janetournois @maxGimeno 
Today the results of `gauguin` [are completely blank][see testsuite]. I need at least the test results for MSVC 2017, to prepare the releases CGAL-4.10.1 and CGAL-4.11.

[see testsuite]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-36.shtml#testresults

**Comment by janetournois** [comment]
this PR is ready now

**Pull request merged**
