### PR TITLE
CGAL_ImageIO: Add a new tool extract_a_sub_image.cpp to extract a sub-image

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Add a new tool extract_a_sub_image.cpp to extract a sub-image.

## Release Management

* Affected package(s): CGAL_ImageIO
* License and copyright ownership: maintenance by GeometryFactory 

This PR can go to any beta of CGAL-5.0 or CGAL-5.1. I do not really care.

### CODE REVIEW

**Comment by afabri** [comment]
Warning with VC++:

> extract_a_sub_image.cpp
C:\CGAL\test\CGAL-5.0-Ic-122\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Debug-64bits\test\CGALimageIO_Examples\extract_a_sub_image.cpp(31): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
C:\CGAL\test\CGAL-5.0-Ic-122\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Debug-64bits\test\CGALimageIO_Examples\extract_a_sub_image.cpp(30): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Aug 28, 2019, 12:44 PM GMT+2](https://github.com/CGAL/cgal/pull/4109#issuecomment-525688708 "2019-08-28T10:44:17Z - Replied by Github Reply Comments"):
> Warning with VC++:
> 
> > extract_a_sub_image.cpp
> C:\CGAL\test\CGAL-5.0-Ic-122\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Debug-64bits\test\CGALimageIO_Examples\extract_a_sub_image.cpp(31): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
> C:\CGAL\test\CGAL-5.0-Ic-122\cmake\platforms\x64_Cygwin-Windows10_MSVC2017-Debug-64bits\test\CGALimageIO_Examples\extract_a_sub_image.cpp(30): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data

I can reproduce those warnings on gcc with `-Wfloat-conversion`. They actually are the symptom of a severe bug in the set of parameters I passed.

**Comment by lrineau** [comment]
I have fixed the bug, and all conversion warnings in both CGAL_ImageIO and Surface_mesher (and verified that Mesh_3 was still working and without warnings).

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-129.shtml

**Pull request merged**
