### PR TITLE
cmake_minimum_required(VERSION 3.12...3.29)

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

Change all `cmake_minimum_required` to 

```cmake
cmake_minimum_required(VERSION 3.12...3.29)
```

## Release Management

* Affected package(s): all

### CODE REVIEW

**Comment by lrineau** [comment]
This PR is a blocker for CGAL-6.0-beta1, because it impacts downstream packages.

**Comment by lrineau** [comment]
I have checked with cmake versions 3.12, 3.18, 3.19, and 3.29 (thanks to Fedora `toolbox` and a setup script).

**Comment by lrineau** [comment]
That does not work with cmake-3.11, and I do not really understand why.

With `cmake -DWITH_tests=ON`, the error is:

```
-- Configuring test in test/Installation
CMake Warning (dev) at Installation/cmake/modules/CGAL_add_test.cmake:176 (if):
  Policy CMP0064 is not set: Support new TEST if() operator.  Run "cmake
  --help-policy CMP0064" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  TEST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  Installation/cmake/modules/CGAL_add_test.cmake:357 (cgal_setup_test_properties)
  Installation/test/Installation/CMakeLists.txt:13 (CGAL_add_test)
  Installation/test/Installation/CMakeLists.txt:39 (create_link_to_program)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at Installation/cmake/modules/CGAL_add_test.cmake:176 (if):
  if given arguments:

    "NOT" "TEST" "copy source_dir of Installation_Tests"

  Unknown arguments specified
Call Stack (most recent call first):
  Installation/cmake/modules/CGAL_add_test.cmake:357 (cgal_setup_test_properties)
  Installation/test/Installation/CMakeLists.txt:13 (CGAL_add_test)
  Installation/test/Installation/CMakeLists.txt:39 (create_link_to_program)


-- Configuring incomplete, errors occurred!
```

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-264

**Pull request merged**
