### PR TITLE
Gsoc2014 polyhedron shortest path skiazyk

### PR DESCRIPTION
**Pull request by sloriot**
Successfully tested in [4.7-Ic-45](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-45.shtml).

I remerged it into 4.7-Ic-47 since there were issues with another branch.

See [Feature page](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Polyhedron_shortest_path)

### CODE REVIEW

**Comment by lrineau** [comment]
When I am in `master`, the script `./Scripts/developer_scripts/test_merge_of_branch` reports errors about the branch, and stops:
  - the merge of the branch is not clean: maybe those conflicts should be be resolved now in the branch (but that is not a blocker),
  - there are two files with "executable" permissions that must not have that permission:
```
Polyhedron/demo/Polyhedron/Shortest_path_widget.ui
Surface_mesh_shortest_path/doc/Surface_mesh_shortest_path/fig/saddleVertexExpand.png
```

**Comment by sloriot** [comment]
FYI, the weight of the branch is 1.3M

**Comment by lrineau** [comment]
The results from [CGAL-4.7-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-55.shtml) were good.

**Comment by lrineau** [comment]
The branch is rather heavy (1.3MB), but removing the intermediate files will only gain half that space: 668KB. I have proposed not to modify the history of the branch. I merge...

**Pull request merged**
