### PR TITLE
Make test correctly report errors

### LINKED ISSUE #953: Orthogonal_k_neighbor_search.cpp prints errors
Looking at a random run of the testsuite: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-6/Spatial_searching/TestReport_lrineau_CentOS6-CXX11-Boost157.gz the test Orthogonal_k_neighbor_search prints many lines of the form

> Error: Point -0.999521 -0.662093 at distance 1.43741  >  0.442363

The test still returns 0 and the testsuite shows up green. Is this output expected? If so, it would be nice to reformulate it so it doesn't look so much like there is a bug... And if it isn't expected, then you know...

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #953 

Highlight a regression introduced in CGAL 4.6 about  further neighbor search

### CODE REVIEW

**Comment by lrineau** [comment]
If I understand well, this PR does not fix #953 fully: it only fixes the fact that test results reports are wrongly reported. But even with this PR, the test results are wrong.

**Comment by sloriot** [comment]
Indeed, testsuite will be fully red

**Comment by sloriot** [comment]
The last commit I pushed fixes the orthogonal furthest neighbor search but breaks the improvement done by @MiesA. If we keep tight bounding box we need 3 more doubles per node (we can save one by removing the cutting value in the seperator). Otherwise we need to go back to using the cutting value and kd-tree nodes bounds (+canceling the concept changes introduced that are no longer needed).
@afabri Let's have a skype meeting next week to decide what to do.

**Comment by sloriot** [comment]
After doing some benchmarks, it turns out that the extra 2 double per node does not have a noticeable impact on the performance.

**Pull request merged**
