### PR TITLE
Polyhedron demo : new "statistics" context menu

### PR DESCRIPTION
**Pull request by janetournois**
This is a framework for displaying statistics on as many types of items as needed

in this PR, I propose a first implementation for Scene_polyhedron_item

### CODE REVIEW

**Comment by sloriot** [comment]
The statistics could simply goes into the item info. Now that we have functions to only invalidate buffers there should not be a performance issue (the area and volume are already computed and displayed in the info section).

**Comment by sloriot** [comment]
`Polyhedron_Demo/Polyhedron_demo_statistics_plugin.cpp:130:7: warning: unused variable 'x'`

**Comment by janetournois** [comment]
I can move the "statistics" to the item info

The "statistics" I added so far are simple (number of vertices, even nb of connected components), but my intention is to incrementally add more costly stuff such as 
* manifoldness
* histogram of angles
* ...

For polyhedral surfaces, these should be ok, but I'm afraid that for bigger data or things that are more compilated to compute, the display of statistics slows down the demo.

Examples
* histogram of dihedral angles in a C3T3
* average spacing on point sets (this is already a plugin by itself but could be integrated to the statistics QDialog)
* ...

**Comment by sloriot** [comment]
Having one more plugin does not hurt. Maybe I would have plugged it in the item context menu, something like "About".

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-17](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-17.shtml)

**Comment by janetournois** [comment]
I agree, the item context menu is a better option
I will change that. 
Thanks

**Comment by janetournois** [comment]
remerged into integration

**Comment by sloriot** [comment]
Testsuite is red

**Comment by janetournois** [comment]
remerged into [CGAL-4.8-Ic-26](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-26.shtml)

**Pull request merged**
