### PR TITLE
Surface mesher - Improve support of vtk files as input

### PR DESCRIPTION
**Pull request by janetournois**
This PR updates the CMakeLists to handle recent (>= 6.0) versions of vtk, and update Surface_mesher/demo/Surface_mesher/VTK examples to Qt5 and VTK6.

Also add a menu to the Surface_mesher demo to open a directory (previously one could only open a directory with drag-and-drop)

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-17](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-17.shtml)

**Comment by sloriot** [comment]
Testsuite is missing the windows platforms

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by janetournois** [comment]
This PR concerns only the Surface_mesher demo code, and the testsuite CGAL-4.8-Ic-19 seems Ok.
I think it could be merged.

**Pull request merged**
