### PR TITLE
Point Set Processing:  cleanup 

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

- Move `<CGAL/trace.h>`  to `Stream_support/include/CGAL/IO/trace.h>
- This file was also called by Poisson, skeletonization, and segmentation.
- Move internal files to `CGAL/Point_set_processing_3/internal/

## Release Management

* Affected package(s): PSP, Poisson, Skeletonization, Segmentation

### CODE REVIEW

**Comment by maxGimeno** [comment]
> /usr/local/include/CGAL/Point_set_processing_3/internal/Search_traits_vertex_handle_3.h:238:61: error: 
      no viable conversion from returned value of type
      'CGAL::internal::Static_filter_error' to function return type 'double'

>/home/travis/build/CGAL/cgal/Poisson_surface_reconstruction_3/examples/Poisson_surface_reconstruction_3/poisson_reconstruction_example.cpp:1:10: fatal error: 
      'CGAL/trace.h' file not found
#include <CGAL/trace.h>

**Comment by afabri** [comment]
@maxGimeno I fixed the problem with the inclusion, but have no clue about the first error. Which cpp fails ?

**Comment by maxGimeno** [comment]
@afabri :
it seems to be /Point_set_processing_3/examples/Point_set_processing_3/normals_example.cpp
for the hierarchy_simplification_example

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Apr 5, 2019, 9:34 AM GMT+2](https://github.com/CGAL/cgal/pull/3831#issuecomment-480177616 "2019-04-05T07:34:00Z - Replied by Github Reply Comments"):
> @afabri :
> it seems to be /Point_set_processing_3/examples/Point_set_processing_3/normals_example.cpp
> for the hierarchy_simplification_example

Pleaae give the link to the exact line in the Travis log. That way everybody can see the context.

**Comment by afabri** [comment]
I can't reproduce it with VC++.

**Comment by maxGimeno** [comment]
@lrineau https://travis-ci.org/CGAL/cgal/jobs/515189547#L2893

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Apr 5, 2019, 9:41 AM GMT+2](https://github.com/CGAL/cgal/pull/3831#issuecomment-480179442 "2019-04-05T07:41:06Z - Replied by Github Reply Comments"):
> @lrineau https://travis-ci.org/CGAL/cgal/jobs/515189547#L2893

OK then the full error message is:
```
In file included from /home/travis/build/CGAL/cgal/Point_set_processing_3/examples/Point_set_processing_3/normals_example.cpp:3:
In file included from /usr/local/include/CGAL/mst_orient_normals.h:31:
/usr/local/include/CGAL/Point_set_processing_3/internal/Search_traits_vertex_handle_3.h:238:61: error: 
      no viable conversion from returned value of type
      'CGAL::internal::Static_filter_error' to function return type 'double'
  double inverse_of_transformed_distance(double d) { return sqrt(d); }
                                                            ^~~~~~~
```
so that is during the build of `Point_set_processing_3/examples/Point_set_processing_3/normals_example.cpp`.

**Comment by maxGimeno** [comment]
Can't reproduce it on Ubuntu either.

**Comment by lrineau** [comment]
Remember that Travis test the result of the merge of the branch of the PR and master. Maybe that can explain why you do not reproduce it in the branch of the PR>

**Comment by afabri** [comment]
Shall I rebase to test again locally?

**Comment by maxGimeno** [comment]
even after merging master in the branch I don't reproduce :/ .

**Comment by maxGimeno** [comment]
It was actually a clang error. Adding CGAL:: before sqrt() fixes the error, probably the namespace management is different in clang.

**Comment by maxGimeno** [comment]
https://travis-ci.org/CGAL/cgal/jobs/516143095#L7277

**Comment by lrineau** [comment]
There is a conflict.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-10.shtml

**Pull request merged**
