### PR TITLE
Use reserve(size+1) before to copy attribute

### PR DESCRIPTION
**Pull request by gdamiand**
This solves a bug in one of my prog, which occurs only for CMap with index.
The problem comes from the copy of existing attributes. The new attribute is allocated through a compact container with index, using an existing attribute as parameter. But the reference becomes invalid when the underlying vector is reallocated.

A simple solution is to use reserve(size+1) before the allocation (thanks @lrineau for the advice).

_Please use the following template to help us managing pull requests._

## Summary of Changes

Add reserve before attribute creation.

## Release Management

* Affected package(s): CMap/GMap/LCC
* Issue(s) solved (if any): fix a local bug.

### CODE REVIEW

**Comment by sloriot** [comment]
Do you have an example showing the bug?

**Comment by gdamiand** [comment]
> Do you have an example showing the bug?

No sorry. I can try to write one.

**Comment by sloriot** [comment]
I'd be interested in being able to reproduce,  like you I'm a but surprised that the patch fixes a bug.

**Comment by gdamiand** [comment]
I added one example showing a bug for index and not for handle; not sure if this is the same bug. This one is not solved by adding cell attribute copy constructor.
The bug occurs for attribute 63, thus when the cc with index is full and reallocated.
But I am not (yet) able to understand why.

**Comment by gdamiand** [comment]
This is a bug; but cmap with index is for now only in master branch.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-198

**Pull request merged**
