### PR TITLE
Fix deprecated include path

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
See [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-I-87/Classification_Examples/TestReport_lrineau_ArchLinux-clang-CXX20-Release.gz) for example

**Comment by maxGimeno** [comment]
successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-98.shtml

**Comment by lrineau** [comment]
@sloriot You initially marked this PR with the milestone "5.1.4" but the base branch was `5.2.x-branch`. Let me know if you want to backport the fix into `5.1.x-branch`.

**Comment by sloriot** [comment]
It's OK, Thanks.

**Pull request merged**
