### PR TITLE
3D Demo: Fixes

### LINKED ISSUE #4498: Demo crash(es)
## Issue Details

Load polygon mesh, add a selection item, shuffle, orient --> crash

"Move point" is still crashing the demo randomly on vertex de-selection, but I don't know how to reproduce it consistently

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

More fixes:
 - the menu Operations is available in the context menu, even when several items are selected at once.
 - When using ctrl + spacebar for changing the visibility of one or more items, the bbox of the viewer is not updated anymore, so the position and visibility of the currently visible items is not changed when showing other items.

 - When shuffilng a mesh to a soup, the signal "itemAboutToBeDestroyed" is sent, in case an item present in the scene depends on this mesh that will be replaced. 

- In the c3t3_item the positions_grid vector was not cleared, so if someome called invalidate(), another grid was added.

- Fix polyline spheres

- Fix trigger of viewer's offset 
fixes #4498

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully testsed in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-63.shtml

**Comment by lrineau** [comment]
Please rebase on `releases/CGAL-5.0-branch`.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-75.shtml.

**Comment by lrineau** [comment]
`master` was merged by error in this PR. I have merged commit https://github.com/CGAL/cgal/pull/4481/commits/c51c7792b84e1b0039d9fb4afc872a38fcfc14cb in `releases/CGAL-5.0-branch`, and this PR in `master`.

**Pull request closed without merging**
