### PR TITLE
Create #8561dibya

### PR DESCRIPTION
**Pull request by debx4**
_Please use the following template to help us managing pull requests._

## Summary of Changes

_Describe what your pull request changes to CGAL (this can be skipped if it solves an issue already in the tracker or if it is a Feature or Small Feature submitted to the CGAL Wiki)._

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Review by debx4 — COMMENTED** [review]
done the edit in   set(CGAL_IPELETS ${CGAL_IPELETS} simple_triangulation)

**Comment by sloriot** [comment]
Your pull-request is not "valid", you should directly modify the file you want to patch in a branch from your remote and then open the PR against master like you did.

**Comment by debx4** [comment]
i open a new branch and try to patch up the branch but merging in the base branch is blocked

**Comment by MaelRL** [comment]
It's OK to work on this branch: https://github.com/debx4/cgal/tree/debx4-patch-1

What @sloriot meant is that you want to modify this file: https://github.com/debx4/cgal/blob/debx4-patch-1/CGAL_ipelets/demo/CGAL_ipelets/CMakeLists.txt. Instead, you created a new file: https://github.com/debx4/cgal/blob/debx4-patch-1/%238561dibya, at the root of the CGAL folder.

The following guide is quite complete: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Pull request closed without merging**
