### PR TITLE
Mouse binding modification

### PR DESCRIPTION
**Pull request by maxGimeno**
- When a selection item is selected, shift+left click does not call information requests
  for the selected point anymore. It makes the selection tool faster by far.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-16](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-16.shtml)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-17](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-17.shtml)

**Comment by sloriot** [comment]
@maxGimeno 
`/home/cgal_tester/build/src/cmake/platforms/Ubuntu-Latest/test/Polyhedron_Demo/Scene_polyhedron_selection_item.h:273:78: error: within this context
           viewer->setMouseBinding(Qt::ShiftModifier, Qt::LeftButton, Viewer::NO_CLICK_ACTION);`

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-20][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-20.shtml

**Comment by maxGimeno** [comment]
Error has disappeared, the PR seems ready to be definitively merged.

**Pull request merged**
