### PR TITLE
Fix a number of issues in CHANGES.md and add links for 5.1

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

Fix part of the 5.1 changelog being under a 5.0 tag, removed a bunch of duplicates, reorganized, uniformized, added links.

Online version: https://github.com/MaelRL/cgal/blob/CGAL-Format_CHANGES.md_5.1-GF/Installation/CHANGES.md

TODO:
- [x] @sloriot: the changelog for AABB tree was wrong (`do_not_accelerate_distance_queries` was introduced in `5.1`), I rewrote it, please check the new version
- [x] @maxGimeno: the changelog speaks of a free function called `CGAL::file_input` but it doesn't seem to exist?
- [x] @sgiraudot: I think we could put at the top (with the new packages) a link to your tutorials, what do you think?
- [x] @sgiraudot @maxGimeno @lrineau: should there be something at the top in general about all the CMake improvements?
- [x] any other general changes (supported compilers / lib version changes) ?
- [x] @MaelRL: Check all the links once 5.1 doc is online.

## Release Management

Integrate after remaining PRs that will still modify CHANGES.md (<s>#4568</s>, <s>#4620</s>, <s>#4659</s>)

* Affected package(s): `Installation`

### CODE REVIEW

**Comment by maxGimeno** [comment]
ping @sgiraudot @MaelRL

**Comment by lrineau** [comment]
The PR #4620 has been merged, without any addition to the `CHANGES.md`. I suggest it is done in this PR.

**Comment by lrineau** [comment]
> ping @sgiraudot @MaelRL

That is important. This PR blocks the release of CGAL-5.1-beta1.

**Comment by MaelRL** [comment]
I will update the branch, but:
- The doc for CGAL 5.1 (https://doc.cgal.org/5.1/Manual/index.html) needs to be online before I can do the link checking;
- Nobody has answered yet about the CMake scripts changes or about bumps-up of third party required versions.

**Comment by lrineau** [comment]
> I will update the branch, but:
> 
>     * The doc for CGAL 5.1 ([doc.cgal.org/5.1/Manual/index.html](https://doc.cgal.org/5.1/Manual/index.html)) needs to be online before I can do the link checking;

Done: I have uploaded the documentation of CGAL-5.1-I-165 at that URL.

>     * Nobody has answered yet about the CMake scripts changes or about bumps-up of third party required versions.

I do not think there is anything to report. Do we want to officially document about CMake API? @sgiraudot?

**Comment by maxGimeno** [comment]
> * Nobody has answered yet about the CMake scripts changes or about bumps-up of third party dependencies / compilers required versions.

I don't think either. This is not supposed to change the behaviour, and if it does, there is a warning explaining what to do.

**Comment by MaelRL** [comment]
> > I will update the branch, but:
> > ```
> > * The doc for CGAL 5.1 ([doc.cgal.org/5.1/Manual/index.html](https://doc.cgal.org/5.1/Manual/index.html)) needs to be online before I can do the link checking;
> > ```
> 
> Done: I have uploaded the documentation of CGAL-5.1-I-165 at that URL.
> 

Could you please use another release since Tetrahedral Remeshing was not part of that release ?

**Comment by lrineau** [comment]
> > > I will update the branch, but:
> > > ```
> > > * The doc for CGAL 5.1 ([doc.cgal.org/5.1/Manual/index.html](https://doc.cgal.org/5.1/Manual/index.html)) needs to be online before I can do the link checking;
> > > ```
> > 
> > 
> > Done: I have uploaded the documentation of CGAL-5.1-I-165 at that URL.
> 
> Could you please use another release since Tetrahedral Remeshing was not part of that release ?

You are right. It should be fine, now.

**Comment by MaelRL** [comment]
I'm done, see https://github.com/MaelRL/cgal/blob/CGAL-Format_CHANGES.md_5.1-GF/Installation/CHANGES.md.

**Comment by sgiraudot** [comment]
> > ```
> > * Nobody has answered yet about the CMake scripts changes or about bumps-up of third party required versions.
> > ```
> 
> I do not think there is anything to report. Do we want to officially document our CMake API? @sgiraudot?

The previous API was 0% documented so there's no "official" breaking change (and using the old version triggers warning but still works). The new third party imported targets have now a small documentation in the Third Party section of the manual, I think it's enough?

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-169.shtml

**Pull request merged**
