### PR TITLE
PMP : reorder variables for API consistency

### PR DESCRIPTION
**Pull request by janetournois**
To fit better in the PMP general framework, the order of variables in the following functions should be changed
- *border_halfedges*
- *isotropic_remeshing*
- *split_long_edges*

These functions are new in CGAL-4.8 so there is no breaking change.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-97

**Comment by lrineau** [comment]
Ic-97?

**Comment by janetournois** [comment]
merged in [CGAL-4.8-Ic-97](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml)

**Comment by janetournois** [comment]
re-merged in [CGAL-4.8-Ic-97](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml)

**Pull request merged**
