### PR TITLE
PMP isotropic_remeshing : fix assertion failure

### PR DESCRIPTION
**Pull request by janetournois**
This PR fixes the case where both faces incident to h are degenerate before the flip
and none of them is degenerate after the flip

it fixes issue #927

### CODE REVIEW

**Comment by lrineau** [comment]
@sloriot @janetournois Est-ce que vous avez suffisamment confiance en ce patch pour cibler CGAL-4.8, ou préférez-vous cible CGAL-4.8.1 ? La différence sera le temps de recul, et de test, entre aujourd'hui et la publication du code.

**Comment by lrineau** [comment]
This PR will be tested in [CGAL-4.9-Ic-7][i]...

[i]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-7.shtml

**Comment by janetournois** [comment]
I think I found another degenerate case where a fix is needed
So this fix is correct, but not complete

Maybe we should target 4.8.1

What do you think @sloriot ?

**Comment by sloriot** [comment]
It's up to you and @lrineau to decide if it is a blocking bug and if we're too late to get it into 4.8.

**Comment by janetournois** [comment]
ok. I'm still trying to fix the degenerate case. Let's postpone that to 4.8.1 then. I should get it fixed by then

**Pull request merged**
