### PR TITLE
Post processing for doc testsuite

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Fix a path and add post processing in the doc testsuite

## Release Management

* Affected package(s): Documentation

### CODE REVIEW

**Comment by lrineau** [comment]
@sloriot: Do you think the target `doc_and_postprocessing` can work with parallel make (`-j` option), now?

**Comment by sloriot** [comment]
It will but the postprocessing will not be parallel.

**Comment by sloriot** [comment]
I suspect the fix is not at the right place. I guess the runs with the doxygen output is not the one used when testing the compilation per package (since the output is redirected to /dev/null).

**Comment by maxGimeno** [comment]
Don't know what you mean. The fix is in test_doxygen_versions.sh, which is what replaces the original call in run_doxygen_testsuite script.

**Comment by sloriot** [comment]
I'm talking about the table [here](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-42) for example. Then maybe there are 3 runs one for the table, and one for each documentation.

**Comment by maxGimeno** [comment]
If I understand (or remember)  correctly, the doc is built once for master, once for 1.8.4, they are compared, then the python script that runs the testsuite is called on the 1.8.4 build dir, and generates the table you are talking about. And if this is not the case, this table is generated by something I didn't touch, so there is no reason anything changed.

**Comment by sloriot** [comment]
We'll see

**Comment by lrineau** [comment]
We can still read 
> Acknowledging %CGAL

in the side-nav widget.

https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-46/output/Manual/index.html

That means that the post-processing is not done for the build with Doxygen-1.8.4.

On the other hand, the build with Doxygen-master had the post-processing: https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-46/master/Manual/index.html

**Comment by maxGimeno** [comment]
Ok the doc was build twice with 1.8.4, I forgot to call the post-processing on the second pass.

**Comment by lrineau** [comment]
Thanks. That will be tested tonight, in CGAL-4.11-Ic-48.

... And for convenience, I give the (future) URLs to the results (to check if that worked):
- https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-48/output/Manual/index.html
- https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.11-Ic-48/master/Manual/index.html

**Pull request merged**
