### PR TITLE
Polyhedron Demo: Rework of VTK_io_plugin

### LINKED ISSUE #3612: Polyhedron demo: read VTU file with 3D cells is broken
## Issue Details

The PR https://github.com/CGAL/cgal/pull/763 (CGAL-4.8) added the possibility to read VTU files (unstructured grids of VTK) in the polyhedron demo. However, the loading code does not check the cell types of the cells in the file. Tetrahedra are loaded as if it was a planar face with four points. The result is aesthetic... but wrong anyway.

screenshot_20190122_105615

## Environment

* CGAL version: `master`, but the bug was introduced in CGAL-4.8

Please fix the release branches if possible. The loading code of `Polyhedron/demo/Polyhedron/Plugins/IO/VTK_io_plugin.cpp` is rather old, so it will probably be without conflicts. I suggest the patch is developed in `master`, and then you try to rebase it.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
The vtk_IO_plugin now detects what type of item it will create according to the type of cells in the vtkDataSet. 
It supports:
-  lines and polylines

image

-  triangles, quads and polygons

image

- tetrahedra

image

If several of these cell types are found, a group will be created:

image

If none of these cell types is found, a warning is displayed and a point set is created from the points of the dataset.

## Release Management

* Issue(s) solved (if any): fix #3612

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-116.shtml

**Comment by lrineau** [comment]
I have tested, on my Linux machine, with:
  - a VTU containing only 3D tetrahedra -> c3t3 item
  - a VTU containing 2D triangles, and 1D edges, and the result was a planar surface mesh, plus lines.

That is fine, in my opinion. Thanks you.

However, the demo crashed in the data set `Testing/Data/cube.vtu` from the paraview build tree. Maybe you should have a look at it.

**Comment by lrineau** [comment]
Works great after last commit https://github.com/CGAL/cgal/pull/3659/commits/535acc73a269a0520decdd17b3460d43815f4307.

But now it has to be re-tested in integration.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-122.shtml

**Pull request merged**
