### PR TITLE
Arrangement_on_surface_2 fixes

### LINKED ISSUE #7311: Pathological case of inserting rays in an arrangement
## Issue Details

I am inserting rays into an arrangement. I get the following runtime behavior when I insert the entire ray vector in a single CGAL::insert function call. However, it works fine if I insert the rays individually. This only happens for the specific rays given below.

> 	terminate called after throwing an instance of 'CGAL::Assertion_exception'
	  what():  CGAL ERROR: assertion violation!
	Expr: v != m_invalid_vertex
	File: CGAL/Surface_sweep_2/Arr_construction_ss_visitor.h
	Line: 987

## Source Code

```cpp
#include <CGAL/Arr_linear_traits_2.h>
#include <CGAL/Arrangement_2.h>
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>

typedef CGAL::Exact_predicates_exact_constructions_kernel K;
typedef K::Point_2 Point_2;
typedef K::Direction_2 Direction_2;
typedef K::Ray_2 Ray_2;
typedef K::Line_2 Line_2;

typedef CGAL::Arr_linear_traits_2<K> Traits_2;
typedef CGAL::Arrangement_2<Traits_2> Arrangement_2;

int main() {

	std::vector<Ray_2> rays;
	rays.push_back(Ray_2(Point_2(180.055441307383,924.254116005402), Direction_2(-229.144941997007,34.8855739060313)));
	rays.push_back(Ray_2(Point_2(156.104233328527,993.005647375856), Direction_2(-0,150.383759942161)));
	rays.push_back(Ray_2(Point_2(156.104233328527,993.005647375856), Direction_2(-60.1375275914886,22.2399807225157)));

	Arrangement_2 arr;

	// The following line causes a segfault

	/* terminate called after throwing an instance of 'CGAL::Assertion_exception' */
	/*   what():  CGAL ERROR: assertion violation! */
	/* Expr: v != m_invalid_vertex */
	/* File: CGAL/Surface_sweep_2/Arr_construction_ss_visitor.h */
	/* Line: 987 */
	CGAL::insert(arr, rays.begin(), rays.end());

	// Inserting individual rays works fine
	/* for (auto const &ray:rays) { */
	/* 	CGAL::insert(arr, ray); */
	/* } */

	return 0;
}
```

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64
* Compiler: g++ 12.2.1
* Release or debug mode: Debug
* Specific flags used (if any): -g -std=c++17 
* CGAL version: 5.5.2
* Boost version: 1.81.0-3

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

Several fixes:
1. Fix of issue #7311: Fixed handling unbounded curves that are both infinite on the left and infinite at the top
2. Tracing and counting traits: Added a parameter pack to the constructor and passed it to the underlying traits; also disabled the copy constructors.
3. Replaced copy-constructor of traits with simple conversion in Arr_traits_adaptor_2
4. Properly set the data of extended records using setters in Arr_text_formatter.h

## Release Management

* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): fix #7311
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by afabri** [comment]
Hi @efifogel would it make sense  (and easily possible) to rebase to the latest public release branch?

**Comment by efifogel** [comment]
Yes, I guess it would.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I have rebased the PR onto `5.5.x-branch` and forced-pushed it.

**Comment by afabri** [comment]
Hi @efifogel , I guess this PR is responsible for the 'N' in today's [testsuite](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.6-Ic-201.shtml#Arrangement_on_surface_2_Examples)

**Comment by efifogel** [comment]
No, the responsible PR is: Resurect The Conic Traits #6721
(Aos_2-conics-efif)
It fails on platforms I do not have access to.
Actually, I can use some help fixing it...
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by afabri** [comment]
There are 2 platforms without  Qt.   So your `draw()` with the 4 arguments is inside a disabled `#if` block.

**Comment by efifogel** [comment]
1. There is a failure on a Ubuntu platform, where only the draw() with the
3 arguments is picked up.
For some reason the draw() with the 4 arguments is ignored.
Both draw() functions are in the same block/namespace/etc.
This doesn't happen on other platforms.
2. There is a failure on an msvc 2015, where several types are unrecognized.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Successfully tested in 5.6-Ic-208

**Pull request merged**
