### PR TITLE
Test for OPENGL_FOUND

### PR DESCRIPTION
**Pull request by afabri**
in order to fix the testsuite of the [Surface_mesher_demo](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-140/Surface_mesher_Demo/TestReport_lrineau_CentOS6-32.gz)

### CODE REVIEW

**Comment by sloriot** [comment]
Merge CGAL-4.8-Ic-142

**Comment by sloriot** [comment]
The issue is still [here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-142/Surface_mesher_Demo/TestReport_lrineau_CentOS6-32.gz).

**Comment by afabri** [comment]
It needs someone more OpenGL and cmake savy than me.

**Comment by sgiraudot** [comment]
Okay, I fixed it. There were 2 things missing:
* `find_package(GLU)`
* Testing `OPENGL_GLU_FOUND` in the condition

Unfortunately there is now a warning:

_-- WARNING: you are using the obsolete 'GLU' package, please use 'OpenGL' instead_

But fixing it would require getting rid of GLU in the demo, so that's out of the scope of this PR...

(I tried to remove the GLU inclusion in the CMakeLists.txt file, but there are of course undefined references when compiling.)

**Comment by lrineau** [comment]
https://cmake.org/cmake/help/v3.0/module/FindOpenGL.html

The OpenGL module also searches for GLU.

**Comment by sgiraudot** [comment]
That is correct. Now the condition works fine and the warning is gone.
Thanks!

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-145

**Pull request merged**
