### PR TITLE
Surface mesh parametrisation - Replace OpenNL by Eigen as default

### PR DESCRIPTION
**Pull request by sgiraudot**
For the _LSCM parameterization_, the least square solve can be performed about 10x faster using the _Eigen_solver_traits_ instead of _OpenNL_ traits (current default behavior).

This branch implements this change of default behavior and completes the Polyhedron demo plugin. The OpenNL parameter is kept if Eigen3 is not available.

### CODE REVIEW

**Comment by lrineau** [comment]
No change of the documentation?

**Comment by lrineau** [comment]
Should there not be an entry in the changelog of CGAL?

**Comment by sgiraudot** [comment]
Oh yes, my bad, I thought this was not a documented behavior, but it turns out it is. I'll update the doc and the changelog.

**Comment by sloriot** [comment]
Merged in [4.8-Ic-4](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-4.shtml)

**Comment by sloriot** [comment]
Previous testsuite was incomplete.
Merged in [CGAL-4.8-Ic-5](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-5.shtml)

**Pull request merged**
