### PR TITLE
Fix clang/llvm 19 compilation issue in iterator.h (issue #8313)

### PR DESCRIPTION
**Pull request by tylermorganwall**
Patch to fix compilation issue in clang//llvm 19 (https://github.com/CGAL/cgal/issues/8313)

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-282

**Comment by lrineau** [comment]
Hi @mering, I have not yet officially announced CGAL-6.0 by email, because it has several last-minute bugs, that were detected by the CI tests of downstream package managers. I plan to publish a CGAL-6.0.1 pretty soon.

**Comment by mering** [comment]
> Hi @mering, I have not yet officially announced CGAL-6.0 by email, because it has several last-minute bugs, that were detected by the CI tests of downstream package managers. I plan to publish a CGAL-6.0.1 pretty soon.

Do you plan any further releases on the 5.6 branch? There are quite some commits since the last release there.

**Comment by lrineau** [comment]
> > Hi @mering, I have not yet officially announced CGAL-6.0 by email, because it has several last-minute bugs, that were detected by the CI tests of downstream package managers. I plan to publish a CGAL-6.0.1 pretty soon.
> 
> Do you plan any further releases on the 5.6 branch? There are quite some commits since the last release there.

Yes, that is planned to. I plan to release one bug-fix for 5.5.x and one for 5.6.x.

**Pull request merged**
