### PR TITLE
Do not perform the test for g++ <= 4.2

### PR DESCRIPTION
**Pull request by afabri**
as CGAL::Epick_d is not supported on these platforms.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-117

**Comment by sloriot** [comment]
Error is still [there](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-117/NewKernel_d/TestReport_lrineau_CentOS5.gz)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-118

**Comment by sloriot** [comment]
The warnings remains [here](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/NewKernel_d/TestReport_lrineau_CentOS6-CXX11-Boost157.gz) anf [there](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-118/Triangulation/TestReport_lrineau_CentOS6-CXX11-Boost157.gz)

**Comment by afabri** [comment]
I asked Simon to look at the file after the preprocessor has done its job

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-119

**Pull request merged**
