### PR TITLE
Add a filter in function to remove caps/needle

### PR DESCRIPTION
**Pull request by sloriot**
Addition to non-documented function

Depends on #5945

### CODE REVIEW

**Comment by lrineau** [comment]
Do you need to sneak it into CGAL-5.3 or will it be enough to delay it to CGAL-5.4?

**Comment by sloriot** [comment]
I'm not sure yet. I did something similar but not as good in another and I introduced new dependencies I would like to try to remove.

**Comment by sloriot** [comment]
I could update named parameters to accept non-copyable object \o/. However, since objects being non-copyable are usually large, I wonder if it wasn't actually only a problem of documentation. That is, a function using a named parameter might simply indicate that it accepts `std::reference_wrapper`.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-60

**Pull request merged**
