### PR TITLE
C map lcc add type in attribs gdamiand

### PR DESCRIPTION
**Pull request by gdamiand**
Add missing types in Cell_attribute and Cell_attribute_with_point in order to allow template specialization on these types.

Trivial modification.

### CODE REVIEW

**Comment by lrineau** [comment]
Guillaume, I let you merge the branch into `integration`. We will see tomorrow (actually on Monday) if it can be merged.

**Comment by lrineau** [comment]
What is closed by error?

**Comment by gdamiand** [comment]
No; it is because I have technical problems this this branch (which was created from my fork and not master thus there was many differences). I recreate a new proper branch.

**Comment by lrineau** [comment]
You can push to the same remote branch using `git push --force `. I think you can even reopen the pull request once done.

**Pull request closed without merging**
