### PR TITLE
Mesh 3 : add gray level image oracle

### PR DESCRIPTION
**Pull request by janetournois**
This PR introduces a new oracle for Mesh_3, able to deal with gray level images.

The corresponding [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Mesh_3_gray_images) was pre-approved on October 17 by @lrineau

### CODE REVIEW

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-50](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-50.shtml)

**Comment by sloriot** [comment]
There are runtime errors in the Mesh_3 testsuite

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-55.shtml)

**Comment by sloriot** [comment]
Testsuite is red

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-56](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-56.shtml)

**Comment by sloriot** [comment]
There a still some runtime errors.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-57

**Comment by lrineau** [comment]
Should be fixed by https://github.com/janetournois/cgal/commit/312962f4296c6408fea236cc13dd77740693d8c0.

Merged in [CGAL-4.8-Ic-76][i].

[i]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-76.shtml

**Comment by sloriot** [comment]
test_merge_of_branch reports no error

**Pull request merged**
