### PR TITLE
Polyhedron demo : display all cells in c3t3_item

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR allows the display of the cells that are not in the complex in the c3t3_item.

### CODE REVIEW

**Comment by lrineau** [comment]
@janetournois Please test the PR manually on Windows.

**Comment by janetournois** [comment]
It works, but the "far points" used for concurrency make the display not that nice. 

@lrineau do you think the edges incident to far points should be discarded?
I think they should (though the complete triangulation is not represented if we do so)

**Comment by lrineau** [comment]
I do not know. What was the goal of displaying the full triangulation?

**Comment by janetournois** [comment]
I wanted to see the egdes of the embedding T3, in particular in nearly planar regions, to check whether degenerate cases could cause errors in my problem.

**Comment by lrineau** [comment]
In that case, I think all edges should be displayed. In parallel tag, if you think that far points should be removed, maybe there should be an another option:
  - either to remove far points (calling the non-documented function `CGAL::remove_far_points_in_mesh_3`, from `<CGAL/remove_far_points_in_mesh_3.h>`,
  - or to display only edges that are not incident to far points.

I think far points can be detected because their `in_dimension()` is special.

**Comment by lrineau** [comment]
@janetournois I still do not know if one want to draw all (finite) edges, or "all (finite) edges but those incident to far points". That depends on what we want to see or debug. If we cannot have an option to choose between the two behavior, then decide arbitrarily. For the moment you are the only "user" of that new feature.

(I had the flag "question". @sloriot will remove it and merge in `master` next week, if the current *tested* implementation is the right one.)

**Comment by janetournois** [comment]
I would not draw the edges that are incident to far points

**Comment by lrineau** [comment]
@janetournois (https://github.com/CGAL/cgal/pull/1012#issuecomment-213451050):
> I would not draw the edges that are incident to far points

So the code of the PR has to change. (->"TODO")

**Comment by maxGimeno** [comment]
Done

**Comment by janetournois** [comment]
I tested this PR locally and did not get any issue

**Pull request merged**
