### PR TITLE
fix edge hash

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by sloriot** [comment]
@afabri The Hash_map test crashes because the test is trying to hash a default constructed edge_descriptor. Should it be hashable or should I update the  test?

**Comment by afabri** [comment]
Good question. Note that the boost::graph_traits<..>::null_vertex is in our implementations also the default constructed vertex_descriptor.   Such an object could be used as a sentinel with a special value in the hash map, so I am in favor of hashing it too.

**Comment by sloriot** [comment]
Do you mean that I should modified also all hash functions to handle the default constructed handle?

**Comment by sloriot** [comment]
There are errors on one platforms see [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.9-Ic-80/Hash_map/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Debug-64bits.gz)

**Pull request merged**
