### PR TITLE
Allow documentation builds from release

### PR DESCRIPTION
**Pull request by bo0ts**
This PR enables the CMake scripts to build the documentation from a release.

This comes with two visible changes to package developers in `Doxyfile.in`:

- `INPUT` is now computed and it is only necessary to specify it when in-source comments are used.
- When using in-source comments it is necessary to specify all source files with comments explicitly. This is necessary so that doxygen knows which files to process in a release where all include folders are collapsed. It is still possible to specify unique sub-folders. This has the added benefit of encouraging better include layout per package.

The documentation testsuite reports some warnings when the documentation is built from a release. This is caused by example files which are specified in `Package/doc/Package/examples.txt` but which are not present in a release due to `dont_submit` rules. This still requires verification and fixes. 

Output postprocessing seems to work but requires more checking.

I don't think this should go into 4.7 since I'm not comfortable with last minute changes in a crucial component like documentation. Please mark for 4.8.

### CODE REVIEW

**Comment by lrineau** [comment]
I agree this pull-request should not be merged in `master` before the branch for 4.7 is launched.

**Comment by lrineau** [comment]
I label the PR with "not yet approved", so that it is visible that is cannot be merged for now.

**Comment by sloriot** [comment]
I think the `Doxyfile.in` should be generated by cmake in order to avoid to have to specify by hand the list of files containing the doc sources that are in the include path. A developer would write something like `ALL_PACKAGE_INCLUDE` in the `INPUT` variable of `Doxyfile.in` and cmake would replace it with the list of include files. @bo0ts What do you think?

**Comment by lrineau** [comment]
> ALL_PACKAGE_INCLUDE

`ALL_PACKAGE_HEADERS` might be a better name. And even this name could be improved.

**Comment by bo0ts** [comment]
> I think the Doxyfile.in should be generated by cmake in order to avoid to have to specify by hand the list of files containing the doc sources that are in the include path. A developer would write something like ALL_PACKAGE_INCLUDE in the INPUT variable of Doxyfile.in and cmake would replace it with the list of include files. @bo0ts What do you think?

That sounds good. I think a good name would be `CGAL_PACKAGE_HEADERS` that would stay in-line with the rest of the CMake variables used.

**Comment by bo0ts** [comment]
> I think the Doxyfile.in should be generated by cmake in order to avoid to have to specify by hand the list of files containing the doc sources that are in the include path. A developer would write something like ALL_PACKAGE_INCLUDE in the INPUT variable of Doxyfile.in and cmake would replace it with the list of include files. @bo0ts What do you think?
> 
> That sounds good. I think a good name would be CGAL_PACKAGE_HEADERS that would stay in-line with the rest of the CMake variables used. We would need to check that variable against dont_submit to really make this work.

After thinking about this for a while I don't think it is possible. There is simply no way to know which files in include/CGAL belong to which package in a release. You *have* to specify them manually. I do not like this as it has a potential to easily create different output between releases and normal builds.

A check and a warning also seem hard since some packages actually only have parts of their comments in-source. I'm afraid this is as good as it gets without changing the layout of releases.

**Comment by sloriot** [comment]
The solution would be to use cmake to generate a release and thus the Doxyfile.in associated.
As a short time goal maybe we can update the release creation script to do the job but I don't know if it is worth it.
@lrineau what do you think?

**Comment by lrineau** [comment]
I think that development is for later, not for 4.7. I agree that the plan could be that CMake scripts are used to generate the internal release, including the `Doxyfile`.

**Comment by bo0ts** [comment]
I had an attempt at creating source releases with `cpack` already and it went so so. Some things don't work out of the box, others work fine, but we should discuss this in a separate issue.

IMO the solution of this PR is fine as long as we consider it to be a stop-gap solution. In total 20 packages (excluding the Documentation package) specify `INPUT` manually. Before this PR every Doxyfile.in had an INPUT line with some boilerplate variable.

The next steps would be to have release creation drop a file `ALL_HEADERS` in the `doc/` directories of packages and configure the appropriate variable `CGAL_PACKAGE_HEADERS` before `configure_file` of the `Doxyfile.in`.

**Comment by bo0ts** [comment]
I've just tried to add the above functionality to `create_internal_release`, but found yet another issue. Keeping track of include files works for most packages, but is impossible for "split" packages like `Kinetic_data_structures` or `Triangulation_2`, because it is not clear to which package the include files belong. We also can't solve this by creating a release with CMake. 

IMO those packages should simply be split. We already have a lot of code that has to work around sub-packages in infrastructure and I don't see a got reason for them in the first place.

I'll open an issue for this.

**Comment by lrineau** [comment]
@bo0ts, which issue was it? #249?

@afabri, can you tell us what is the status of this? #249 is still open, but it seems the work was done? Is there a branch that you be merged in `integration`/`master`?

**Comment by lrineau** [comment]
#364 (**split packages**) is merged, now.

**Comment by bo0ts** [comment]
I investigated how to finish this and it currently clashes with PR #339. I tried to salvage some things and rebased this branch to be less invasive but figuring out the changes will still take more time, which we haven't allocated for this. I'll close this for now.

**Pull request closed without merging**
