### PR TITLE
Add periodic regular triangulations

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

This PR adds a new periodic triangulation algorithm: Periodic_3_regular_triangulation_3.

This PR is based on PR https://github.com/CGAL/cgal/pull/2102. I'll rebase and fix conflicts once the other one is integrated.

## Release Management

* Affected package(s): `Triangulation_3`, `Periodic_3_triangulation_3`, `Mesh_3` (minor changes)
* Issue(s) solved (if any): --
* Feature/Small Feature (if any): [Periodic_3_regular_triangulation_3](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_Periodic_3_regular_triangulation_3) and [Add_new_locate_functions_and_geometric_access_functions](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Add_new_locate_functions_and_geometric_access_functions).

### CODE REVIEW

**Comment by lrineau** [comment]
This PR has a merge conflict with `master`, and cannot be tested for the moment.

**Comment by MaelRL** [comment]
Yes, the base of this branch is #2102 and I haven't bothered rebasing all my branches each time #2102 had a conflict.

If you think it's worth merging into master even while #2102 is open, I'll rebase this PR. (But #2102 looks pretty clean, looking at lc-51.)

**Comment by lrineau** [comment]
@MaelRL There are several conflicts to deal with, now that a bunch of pull-requests have been merged in `master`.

**Comment by MaelRL** [comment]
Is the travis error ( https://travis-ci.org/CGAL/cgal/jobs/249661823#L4860 ) related to Travis' configuration?

**Comment by lrineau** [comment]
It seems there is indeed an issue with clang-3.6. I will try to make it use libc++, as suggested in [this SO answer][*].

  [*]: https://stackoverflow.com/a/24342365/1728537

**Comment by lrineau** [comment]
`libc++` cannot be trusted on Linux. So I have removed the use of C++14 from the P3T3 testsuite, in https://github.com/CGAL/cgal/pull/2212/commits/729158e07e2c784e98a2d22a6b816965cc05c974.

**Comment by lrineau** [comment]
Have you seen the build error with T2 about boost property maps?

/mnt/testsuite/include/CGAL/Triangulation_2.h:50:56: error: boost/property_map/function_property_map.hpp: No such file or directory

**Comment by lrineau** [comment]
And same error with CentOS6.

**Comment by MaelRL** [comment]
Everything is fixed (but not pushed) except https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.11-Ic-57/Periodic_3_triangulation_3/TestReport_lrineau_CentOS7-ICC-Release.gz, I can't reproduce it. Valgrind does complain about something but it seems unrelated.

**Comment by lrineau** [comment]
You can try to compile one of those failing tests with a recent g++  or clang, and the flag `-fsanitize=address`, and then run the test. That flag adds instrumentation code (see [AddressSanitizer]) that checks for memory-related error.

  [AddressSanitizer]: https://github.com/google/sanitizers/wiki/AddressSanitizer

**Comment by MaelRL** [comment]
98f3211 is not in integration Ic-58 because filter-branch did require a force push in the end and a part of the branch was already in integration. This commit changed a test file so it'll probably have to be tested again (but the test runs fine locally at least).

**Comment by lrineau** [comment]
(In the right PR #2212, this time...)

@afabri A lot of Windows results of Periodic_3 did not finish before the timeout, but those that has finished did finish in a lot less than the time bound. That is strange. Could you have a look?

https://cgal.geometryfactory.com/CGAL/testsuite/results-4.11-Ic-61.shtml#Periodic_3_triangulation_3

**Pull request merged**
