### PR TITLE
Periodic 3 delaunay triangulation traits 3 a pelle

### PR DESCRIPTION
**Pull request by aympelle**
- Small Feature Reference :  https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/rename_p3tt3_p3dtt3
- Tested : https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-50.shtml

### CODE REVIEW

**Comment by afabri** [comment]
There is still a warning.

ex_periodic_alpha_shapes_3.cpp
C:\CGAL\test\CGAL-4.7-Ic-50\cmake\platforms\x64_Cygwin-Windows8_MSVC2012-Debug-64bits\test\Alpha_shapes_3_Examples\ex_periodic_alpha_shapes_3.cpp(11) 
: warning C4996: 'CGAL::Periodic_3_triangulation_traits_3<Kernel>': was 
declared deprecated



On 05/06/2015 18:09, Aymeric PELLE wrote:
>   * Small Feature Reference :
>     https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/rename_p3tt3_p3dtt3
>
>   * Tested :
>     https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-50.shtml
>
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/CGAL/cgal/pull/111
>
>
>         Commit Summary
>
>   * Rename Periodic_3_triangulation_traits_3
>     Periodic_3_Delaunay_triangulation_traits_3.
>   * Rename Periodic_3_triangulation_filtered_traits_3
>     Periodic_3_Delaunay_triangulation_filtered_traits_3.
>   * Create Periodic_3_triangulation_traits_3.
>   * Remove predicates unused by Periodic_3_triangulation_traits_3.
>   * Small changes in
>     Periodic_3_Delaunay_triangulation_statically_filtered_traits_3.
>   * Update Periodic_3_triangulation_3 doc.
>   * Corrections in the doc of Periodic_3_triangulation_3.
>   * Fix links and traits names.
>   * Remove doc of P3TT3 concept from doc of P3DTT3 concept.
>   * Missing \cgalRefines.
>   * Doc : Move types and functions from P3TT3 concept to P3DTT3 concept.
>   * Add a warning for P3TT3.
>   * Remove \cgalModif... macros and fix link problems.
>   * Minor fix : remove note in P3DTT3 concept.
>   * P3DTT_base_3 inherites from P3TT_base_3 now.
>   * Update changes.html.
>   * Fix : add an include for removing an error on Windows.
>
>
>         File Changes
>
>   * *M* Installation/changes.html
>     <https://github.com/CGAL/cgal/pull/111/files#diff-0> (6)
>   * *M*
>     Periodic_3_triangulation_3/benchmark/Periodic_3_triangulation_3/Periodic_3_Delaunay_3_bench.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-1> (4)
>   * *M*
>     Periodic_3_triangulation_3/demo/Periodic_3_triangulation_3/Scene_utils.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-2> (4)
>   * *M* Periodic_3_triangulation_3/demo/Periodic_Lloyd_3/typedefs.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-3> (4)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/CGAL/Periodic_3_Delaunay_triangulation_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-4> (1)
>   * *A*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/CGAL/Periodic_3_Delaunay_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-5> (25)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/CGAL/Periodic_3_triangulation_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-6> (2)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/CGAL/Periodic_3_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-7> (8)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3DelaunayTriangulationTraits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-8> (256)
>   * *A*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Concepts/Periodic_3TriangulationTraits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-9> (241)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/PackageDescription.txt
>     <https://github.com/CGAL/cgal/pull/111/files#diff-10> (5)
>   * *M*
>     Periodic_3_triangulation_3/doc/Periodic_3_triangulation_3/Periodic_3_triangulation_3.txt
>     <https://github.com/CGAL/cgal/pull/111/files#diff-11> (49)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/colored_vertices.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-12> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/covering.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-13> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/find_conflicts.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-14> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/geometric_access.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-15> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/large_point_set.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-16> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/periodic_adding_handles.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-17> (4)
>   * *M*
>     Periodic_3_triangulation_3/examples/Periodic_3_triangulation_3/simple_example.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-18> (4)
>   * *A*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_filtered_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-19> (161)
>   * *A*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_statically_filtered_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-20> (62)
>   * *A*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_Delaunay_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-21> (150)
>   * *A*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_construct_point_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-22> (31)
>   * *M*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_filtered_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-23> (27)
>   * *M*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_statically_filtered_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-24> (8)
>   * *M*
>     Periodic_3_triangulation_3/include/CGAL/Periodic_3_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-25> (156)
>   * *A*
>     Periodic_3_triangulation_3/include/CGAL/Traits_with_offsets_adaptor.h <https://github.com/CGAL/cgal/pull/111/files#diff-26>
>     (68)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/include/CGAL/_test_cls_periodic_3_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-27> (2)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/include/CGAL/_test_periodic_3_static_filters.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-28> (6)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_alpha_shape_3.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-29> (6)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_delaunay_3.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-30> (8)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_delaunay_hierarchy_3.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-31> (8)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_3.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-32> (28)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_tds.cpp
>     <https://github.com/CGAL/cgal/pull/111/files#diff-33> (2)
>   * *M*
>     Periodic_3_triangulation_3/test/Periodic_3_triangulation_3/test_periodic_3_triangulation_traits_3.h
>     <https://github.com/CGAL/cgal/pull/111/files#diff-34> (2)
>
>
>         Patch Links:
>
>   * https://github.com/CGAL/cgal/pull/111.patch
>   * https://github.com/CGAL/cgal/pull/111.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/pull/111>.
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by aympelle** [comment]
-Tested : https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-51.shtml

**Comment by lrineau** [comment]
The tests of Periodic_3 in [CGAL-4.7-Ic-51](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-51.shtml) were not good. There are several red cells, and the following two are new ones:
  - in [`Periodic_3_triangulation_3_Examples` of `x86-64_Linux-Fedora19_g++-4.8_ansi`](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-51/Periodic_3_triangulation_3_Examples/TestReport_lrineau_x86-64_Linux-Fedora19_g++-4.8_ansi.gz), 
  - in [`Periodic_3_triangulation_3_Examples` of `x86-64_Linux-Fedora19_g++-4.8_m32`](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-51/Periodic_3_triangulation_3_Examples/TestReport_lrineau_x86-64_Linux-Fedora19_g++-4.8_m32.gz).

**Comment by aympelle** [comment]
- Tested : https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml

The red cells in columns 21 (and 24) are not a consequence of this small feature.
We can see the same error at the line RangeSegmentTrees_Examples and in previous tests : https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-37.shtml.

**Comment by lrineau** [comment]
:white_check_mark: Testsuite seems OK
----------------
I agree with your conclusion. For the moment, the [testsuite of CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml) is not yet finished (two Windows columns and one MacOS columns are still not displayed). If nothing new pops up in the results with those three columns, then we can declare that this pull-request passes for the testsuite tests.

:x: License issues
-------------------
However, using a script, I have detected that two header files do not have copyright and license annotation:
```
renoir ~/Git/cgal $ ./Scripts/developer_scripts/licensecheck Periodic_3_triangulation_3/include/CGAL/**/*.* | grep -vF 'GPL (v3 or later)'
Periodic_3_triangulation_3/include/CGAL/Periodic_3_construct_point_3.h: *No copyright* UNKNOWN
Periodic_3_triangulation_3/include/CGAL/Traits_with_offsets_adaptor.h: *No copyright* UNKNOWN
```

:x: Testing of deprecated classes
--------------------------------------
I have the impression that the deprecated classes are no longer tested. There should be test files (at least one), that:
  - are protected by the macro `CGAL_NO_DEPRECATED_CODE`: if the macro is defined, then the test should be `int main() { return 0;}`
  - defines the macro `CGAL_NO_DEPRECATION_WARNINGS` before including any CGAL header,
  - and test all the deprecated classes (at least check that they still compile, even if the actual test at runtime is minimalistic).

**Comment by aympelle** [comment]
- Testing of deprecated classes
Periodic_3_triangulation_traits_3 (P3TT3) is set deprecated.
Periodic_3_Delaunay_triangulation_traits_3 (P3DTT3) replaces it. P3DTT3 is tested.
P3TT3 is just an empty heir of P3DTT3 now. So, P3TT3 is tested indirectly.

**Comment by lrineau** [comment]
- The deprecated classes, even the trivial wrappers, must be tested. :x: 
- The script `Scripts/developer_scripts/test_merge_of_branch` no longer any issue with your branch. :white_check_mark:

**Comment by aympelle** [comment]
- Tested : https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-58.shtml

**Comment by lrineau** [comment]
The result of testsuite 
[CGAL-4.7-Ic-58](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-58.shtml) are quite bad, but the lines of Periodic_3 are good: the warnings and errors are the same as in [CGAL-4.7-I-52](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-I-52.shtml). And I remember I already said that [the results for testsuite of CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml) was good for Periodic_3. :white_check_mark: 

I also see that the deprecated class `Periodic_3_triangulation_traits_3` is now tested, after commit 72f9d2c. :white_check_mark:

I can merge the branch.

**Comment by lrineau** [comment]
Aymeric (@aympelle), you can now remove the branch `Periodic_3_Delaunay_triangulation_traits_3-APelle` from mine (your fork of CGAL).

**Pull request merged**
