### PR TITLE
Accelerate TDS_3::print_cells()

### PR DESCRIPTION
**Pull request by afabri**
Use `CGAL::Unique_hash_map` instead of `std::map`; Replace `std::endl` with `'\n'`

### CODE REVIEW

**Comment by lrineau** [comment]
The PR seems incomplete. The use of hash maps is not pushed.

**Comment by lrineau** [comment]
The equivalent PR for `read_cells` is #989, and targets CGAL-4.9. Should I rebase it so that it targets CGAL-4.8.1?

**Comment by afabri** [comment]
I thought that minor releases only fix bugs, and  do not add improvements.

**Comment by lrineau** [comment]
Then why does *this* PR target CGAL-4.8.1?

**Comment by afabri** [comment]
by mistake. Do what takes less time for you.

**Comment by lrineau** [comment]
Merged in master.

**Pull request closed without merging**
