### PR TITLE
Documentation: Add missing updates after the fork of libQGLViewer

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Removes the instruction about libQGLViewer in the Installation Manual and adds a paragraph that explains the drop of the dependency in CHANGES.md.

### CODE REVIEW

**Comment by sloriot** [comment]
`Installation/INSTALL.md` should be updated

**Comment by sloriot** [comment]
I'm also suspicous about 
`Installation/cmake/modules/CGAL_Qt5_moc_and_resource_files.cmake`, `Installation/cmake/modules/FindQGLViewer.cmake`, and `Installation/cmake/modules/CGAL_SetupCGAL_Qt5Dependencies.cmake`

**Comment by lrineau** [comment]
@sloriot What now? Do you think this PR could be merged?

**Comment by sloriot** [comment]
It should be good from what I remember from my previous grep.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.13-Ic-26][*], and then merged (on Friday).

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-26.shtml

**Pull request merged**
