### PR TITLE
Mesh 3 - use triple line extraction together with weighted images

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

Add weighted images handling to PR #6129 

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: unchanged

Todo
- [x] demo code does not take weigths + features into account since [8915ea0](https://github.com/CGAL/cgal/pull/6327/commits/8915ea00241a8e7063a2e20cf4dab5659d6a6729)

### CODE REVIEW

**Comment by janetournois** [comment]
With a smaller `edge_size`, here is the type of results we get
image

**Comment by afabri** [comment]
> With a smaller `edge_size`, here is the type of results we get image

That looks REALLY good!

**Comment by sloriot** [comment]
Runtime errors:
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-211/Mesh_3_Examples/TestReport_lrineau_Ubuntu-Latest.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-211/Mesh_3_Examples/TestReport_lrineau_Ubuntu-Latest-CXX11.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-211/Mesh_3_Examples/TestReport_Christo_MSVC2017-Release-64bits.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-211/Mesh_3_Examples/TestReport_Christo_MSVC2017-Debug-64bits.gz

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-223

**Comment by janetournois** [comment]
There are some warnings in `postprocess_weights.h` [here](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-223/Mesh_3/TestReport_lrineau_Ubuntu-latest-GCC6-CXX1z.gz)
I'm fixing them

**Comment by sloriot** [comment]
I guess this PR is responsible for [this error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-227/Mesh_3/TestReport_lrineau_Fedora-rawhide.gz)

**Comment by janetournois** [comment]
@lrineau can you please give it a try on Fedora?

**Comment by janetournois** [comment]
Actually this error, with that seed, is in `master`, see issue #7406

**Comment by janetournois** [comment]
The plugin still has an issue and crashes when using weights together with triple lines

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-240

**Comment by sloriot** [comment]
The diff with the version tested are only whitespaces.

**Pull request merged**
