### PR TITLE
Update SPDX tags

### PR DESCRIPTION
**Pull request by sloriot**
Previous tags were deprecated

### CODE REVIEW

**Comment by sloriot** [comment]
@afabri  please review `Installation/LICENSE.COMMERCIAL`

**Comment by sloriot** [comment]
With the last commits I also removed the license notice from the headers from most headers (but OpenNL and 2 files from the arrangement demo).

**Comment by sloriot** [comment]
TODO: `licensecheck`  needs to be updated and travis will most probably crash for now.

**Comment by sloriot** [comment]
Travis should be happy now.

**Comment by sloriot** [comment]
I updated `licensecheck` to check for the absence of license notice in header files.

**Comment by sloriot** [comment]
I would appreciate if this could go into 5.0

**Comment by sloriot** [comment]
Note that the random forest license notice in the headers are not in the original distribution of the code. I added the license in `Installation/LICENSE,RFL` and update the SPDX tag to `LicenseRef-RFL`.

**Comment by maxGimeno** [comment]
https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-173.shtml

**Comment by sloriot** [comment]
@pombredanne Thanks for the useful discussion at the GSoC mentor summit, license/SPDX clean up is now part of our master branch.

**Comment by pombredanne** [comment]
@sloriot this is great :bowing_man: 
Glad I could be of help

**Pull request merged**
