### PR TITLE
Polygon Mesh Processing: Finer grain for license check

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes
Create license check files for the different subsections. 

## Release Management

* Affected package(s): Polygon_mesh_processing

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot As we know include internal files, what will replace these calls to internal functions in the long run?

**Comment by sloriot** [comment]
@afabri  I don't understand the question.

**Comment by lrineau** [comment]
Should not we actually define `CGAL_LICENSE_ERROR` and an appropriate set of `CGAL_<pkg>_COMMERCIAL_LICENSE` in a few .cpp test files, to actually check that it works?

**Comment by lrineau** [comment]
This PR blocks CGAL-4.10-beta1, and not CGAL-4.10. We cannot import such a important change after the beta release.

**Pull request merged**
