### PR TITLE
Small feature: Interpolation with vertices

### PR DESCRIPTION
**Pull request by MaelRL**
## Summary of Changes

* Generalized the API of natural and regular neighbor coordinates computation,  interpolation, and gradient fitting functions to be able to operate on vertices (or something else).
* Added a lot of missing tests
* Rewrote a good part of the user and reference manual. 

Further work to be done some day: the same generalization to surface neighbors.

## Release Management

* Affected package(s): Interpolation
* Issue(s) solved (if any): --
* Feature/Small Feature (if any): [Interpolation with vertices](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Interpolation_with_vertices#Status)

Pre-approved on 2018-03-12

### CODE REVIEW

**Comment by sloriot** [comment]
_Not done_ means it will not be covered by this PR or it will be done later? (just to know if we should flag it TODO).

**Comment by MaelRL** [comment]
To be done some day. Didn't feel like it deserved an issue.

**Comment by lrineau** [comment]
Travis detected an error:
https://travis-ci.org/CGAL/cgal/jobs/329564309#L1319
```
[  8%] Building CXX object CMakeFiles/surface_neighbor_coordinates_3.dir/surface_neighbor_coordinates_3.cpp.o
In file included from /home/travis/build/CGAL/cgal/Interpolation/examples/Interpolation/sibson_interpolation_vertex_with_info_2.cpp:6:
/home/travis/build/CGAL/cgal/Interpolation/examples/Interpolation/../../include/CGAL/natural_neighbor_coordinates_2.h:35:10: fatal error: 
      'boost/core/enable_if.hpp' file not found
#include <boost/core/enable_if.hpp>
         ^
In file included from /home/travis/build/CGAL/cgal/Interpolation/examples/Interpolation/surface_neighbor_coordinates_3.cpp:9:
In file included from /home/travis/build/CGAL/cgal/Interpolation/examples/Interpolation/../../include/CGAL/surface_neighbor_coordinates_3.h:31:
/home/travis/build/CGAL/cgal/Interpolation/examples/Interpolation/../../include/CGAL/regular_neighbor_coordinates_2.h:33:10: fatal error: 
      'boost/core/enable_if.hpp' file not found
#include <boost/core/enable_if.hpp>
         ^
1 error generated.
```

**Comment by afabri** [comment]
It should be `<boost/utility/enable_if.hpp>`

**Comment by MaelRL** [comment]
TODO: Update `changes.md`

**Comment by MaelRL** [comment]
Travis will probably fail again with the same error: https://travis-ci.org/CGAL/cgal/jobs/341378684 which seems independent from this PR (I saw it in some other PRs too).

**Comment by lrineau** [comment]
This change is [Reviewable](https://reviewable.io/reviews/cgal/cgal/2746)

**Comment by sloriot** [comment]
Successfully tested in CGAL-4.13-Ic-3

**Pull request merged**
