### PR TITLE
Triangulation_2 Demo: Read files with many WKT entities

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Instead of only reading one multipolygon the demo can now read files with points, polylines, and mltipolygons.

This PR is WIP as looking at the code there is room for  improvement.

## Release Management

* Affected package(s): Triangulation_2

### CODE REVIEW

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-133

**Comment by sloriot** [comment]
If it's a bug, why not in 5.4 or 5.5?

**Comment by afabri** [comment]
I started freshly and cherry picked.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-145

**Pull request merged**
