### PR TITLE
Ms 2 of holes efif

### PR DESCRIPTION
**Pull request by efifogel**
Small features: /Minkowski sum 2 polygons with holes and RC
Link: https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Minkowski_sum_2_polygons_with_holes_and_RC

Intended for 4.7.

### CODE REVIEW

**Comment by blinry** [comment]
Hey @lrineau, just to let you know: I still need a few days finishing up some things in my half of this small feature, and making sure the testsuite runs without warnings on all platforms. Will comment here when I'm done.

**Comment by lrineau** [comment]
Anyway formally you have to the end of June 2015, the code freeze.

**Comment by blinry** [comment]
Huh, I'm not sure why the Monday testsuite didn't turn up in the web interface. Did I miss something?

**Comment by efifogel** [comment]
It did and followed upon fixing some small things to satisfy platforms
other than ours.
Perhaps you refer to something else, I'm not sure/
Anyway, I'll merge with "integration" again this Sun.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Problems so far:
 - I feel uneasy that the small feature pulls significant changes to the documentation. As far as I know, that was not reviewed by the Editorial Board. I will ask for opinions on the board mailing list.
 - There are license issue with several files:
```
renoir ~/Git/cgal/Minkowski_sum_2 $ licensecheck include/**/* | grep -v GPL
include/CGAL/Minkowski_sum_2/AABB_segment_2_primitive.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/Hole_filter_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/AABB_collision_detector_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/AABB_traits_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/Minkowski_sum_by_reduced_convolution_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/AABB_collision_detector_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/AABB_segment_2_primitive.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/AABB_traits_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/Hole_filter_2.h: *No copyright* UNKNOWN
include/CGAL/Minkowski_sum_2/Minkowski_sum_by_reduced_convolution_2.h: *No copyright* UNKNOWN
```

**Comment by efifogel** [comment]
1. I've added the missing copyright statements.
2. I don't think that there is a need to upgrade the small feature into a full blown feature. I've changed the documentation based on the relevant content of chapter 9 entitled "Minkowski Sums and Offset Polygons" of our book entitled "CGAL Arrangement and their Applications". This chapter was written based on the corresponding CGAL documentation. It was improved and it was proof read by a professional hired by Springer (our publisher). The changes are only cosmetic (e.g., syntax, grammar, and figures). At the end, the new manual is really an improved version of the old plus the new stuff. I've already done this upgrade for the polyline section of the Arrangement chapter, and I intend to gradually do it for all relevant pieces of our book.

**Comment by efifogel** [comment]
Yes, I've just pushed it to my fork.
I do it before I merge with integration anyway.

**Comment by lrineau** [comment]
I see that the branch `MS_2-of_holes-efif` still receive commits in the `cgal-dev` repo. I will not merge that pull-request myself into integration until somebody explains the situation.

**Comment by blinry** [comment]
From my side, I'm still fixing errors and warnings which come up on different platforms in the test suite. As an optimistic estimation, that will be done by Friday afternoon.

I'll comment here again when I'm ready. I guess the pull request came a bit early, sorry for the confusion ;-)

**Comment by lrineau** [comment]
Actually, that's fine for me. At least using that pull-request we can track the integration attempts. Please let me know.

**Comment by lrineau** [comment]
The branch `MS_2-of_holes-efif` was tested in [CGAL-4.7-Ic-31](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-31.shtml). There are several new warnings in the Polyhedron demo, and the `Minkowski_sum_2` tests and examples.

**Comment by lrineau** [comment]
Please also do not merge your branch into `integration` today (Friday 15th May). Several pull-requests that are ready are just waiting for a good internal release to be merged into `master`. I hope to achieve that with tonight internal release.

**Comment by lrineau** [comment]
The only warning seems:
```
include/CGAL/Minkowski_sum_2/Minkowski_sum_by_reduced_convolution_2.h:327:67: warning: unused parameter 'p' [-Wunused-parameter]
```

As you can see, if you want to test locally, that warning is enabled with `-Wunused-parameter`. On my machine, I use `-Wall -Wextra`, that includes most warnings.

**Comment by blinry** [comment]
Already fixed that in https://github.com/CGAL/cgal-dev/commit/a69dd3f6c74af7348a4f34aa8c2948ccc1ad068c :-) (which I apparently forgot to merge into `integration` yesterday -.-). OK, will not merge today, so the next opportunity is monday, 9 pm, right?

**Comment by lrineau** [comment]
Sorry Sebastian, I had not seen that commit so far before the pull-request is not yet updated with it.

Efi has to update the branch `MS_2-of_holes-efif` in the repo `efifogel/cgal` (probably aliased to the name `mine` in his local config).

I have discovered that one can specify collaborators, even on a fork. That is configurable here:
   https://github.com/efifogel/cgal/settings/collaboration

**Comment by efifogel** [comment]
In the meantime I've pushed it to my fork.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by blinry** [comment]
Hey Laurent, the latest test suite run was error- and warning-free: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-35.shtml

Efi already brought this pull request up-to-date, it's ready to be merged from our side.

**Comment by lrineau** [comment]
The testsuite 4.7-Ic-35 is not warning-free. There are new warnings at least in the line Polygon_Demo, that are caused by your pull-request. I have a patch, and I have pushed it in a branch `Minkowski_sum_by_reduced_convolution_2-fix_warning-lrineau` on `cgal-dev`:
https://github.com/CGAL/cgal-dev/tree/Minkowski_sum_by_reduced_convolution_2-fix_warning-lrineau

The diff is just one commit https://github.com/CGAL/cgal-dev/commit/284116af488ec9a259d06aaa4b3fa42ac03fd67f. I avoids two things:
  - the warning,
  - and the use of the special value of `FT(-1)` as a sentinel, that is replaced by a sentinel that is the null pointer for `min_q`. That is less dangerous and less costly.

**Comment by efifogel** [comment]
Thank you Laurent!
I have merged both branches, namely

   1. MS_2-of_holes-efif
   2. Minkowski_sum_by_reduced_convolution_2-fix_warning-lrineau

with integration. We'll see the results tomorrow.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Efi, if you agree with my changes in `Minkowski_sum_by_reduced_convolution_2-fix_warning-lrineau`, please merge that branch in your branch `MS_2-of_holes-efif`, then push the result to your fork (`mine`) so that the pull request is updated. I would have liked to do it myself, but unfortunately I do not have the rights to modify your fork repository at https://github.com/efifogel/cgal

The results of CGAL-4.7-Ic-44 were horrible because too many warnings/errors have been introduced by other merges. I will merged again the pull request once it is updated.

**Comment by efifogel** [comment]
Hi Lauren,

Yes, of course, your changes are good.
I've merged them and pushed both to my branch and my fork.
No problem doing it myself whatsoever.

Thanks,
Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
The [tests in CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml) are good enough. That pull-request has not introduced new warnings or errors. I note that the test results for `Minkovski_sum_2` and `Boolean_set_operations_2` are very good, but the one for `Arrangement_on_surface_2` are not: memory leaks detected in the last column, several execution errors on various platforms.

Note that it would nice to fix the memory leaks about `Boolean_set_operations_2` detected here:
https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-53/Boolean_set_operations_2/TestReport_lrineau_x86-64_Linux-Fedora19_llvm-clang-with-g++-4.8.gz

**Comment by efifogel** [comment]
Hi Laurent,

First thanks for the merge.
Secondly, I'm aware of (at least some of) the problems you mention.
They are in my todo list and I plan to handle them one at a time, but
thanks also for pointing them out.

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Actually this PR also brough two other small features: [this one](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Minkowski_sum_2_reduced_convolutions) and [that one](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Minkowski_sum_2_polygon_with_holes).

**Pull request merged**
