### PR TITLE
Accelerete 3D version of inexact_locate as we do it for 2D

### PR DESCRIPTION
**Pull request by afabri**
this should even go into 4.7.1

### CODE REVIEW

**Comment by lrineau** [comment]
Was there a significant improvement in benchmarks?

**Comment by afabri** [comment]
The acceleration is enormeous for the `..exact_constructions_kernel..` , the fix trivial so it would even make sense to have it in 4.7.1

**Comment by lrineau** [comment]
I agree. @afabri @sloriot, can you please rebase the PR against 4.7?

**Comment by sloriot** [comment]
Done

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-138

**Comment by sloriot** [comment]
Merged in 4.7 and master

**Pull request merged**
