### PR TITLE
Fix links concerning Projection_traits_3

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add link [here](https://cgal.geometryfactory.com/CGAL/doc/master/Triangulation_2/classConstrainedTriangulationTraits__2.html)

Add namespace `Barycentric_coordinates` [here](https://cgal.geometryfactory.com/CGAL/doc/master/Kernel_23/classCGAL_1_1Projection__traits__xy__3.html).

### CODE REVIEW

**Comment by afabri** [comment]
The links are fixed now.   See [here](https://cgal.github.io/6161/v0/Kernel_23/classCGAL_1_1Projection__traits__3.html)

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-115

**Pull request merged**
