### PR TITLE
CGAL Examples: CGAL_assertion ->  assert

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Do not use `CGAL_assertion()`  as this is reserved to being used inside CGAL code. 

## Release Management

* Affected package(s): many

### CODE REVIEW

**Comment by afabri** [comment]
@mglisse I didn't change this in the package `Triangulation`   as I am not sure if it should be replaced to `assert` to illustrate the users what they can expect to be true after doing operations, or  if it is in reality a testsuite that only happens to be in the wrong directory.

**Comment by afabri** [comment]
@gdamiand @efifogel what I just wrote to Marc also holds for your packages.   Feel free to tell me what you expect me to do, unless you do the changes yourself.

**Comment by mglisse** [comment]
In Triangulation examples, `CGAL_assertion` seems to be used to document what the user can expect. `assert` is indeed probably better suited for that.
Of course any example could also be used as a test, but it doesn't seem to be their primary use here.

**Comment by gdamiand** [comment]
> 

@afabri I think you have more experience than me to decide when it is better to use assert or cgal assertion.
If it only concerns examples and tests, feel free to do what you want.

**Comment by afabri** [comment]
@gdamiand it is in fact more than changing to `assert()`.   For example  I would remove an `assert(lcc..is_valid()` if there is no reason not to be valid, for example when you have constucted it with `CGAL::make_hexahedron(lcc)`.   I would only assert for example that a file could be opened  and the file name comes as command line argument.

**Comment by gdamiand** [comment]
> @gdamiand it is in fact more than changing to `assert()`. For example I would remove an `assert(lcc.is_valid()` if there is no reason not to be valid, for example when you have constucted it with `CGAL::make_hexahedron(lcc)`. I would only assert for example that a file could be opened and the file name comes as command line argument.

Ok I understand. I the example you gave, I agree we can remove the assert.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-10

**Pull request merged**
