### PR TITLE
Mesh 3 - Improve Gray level images domain and fix warnings

### PR DESCRIPTION
**Pull request by janetournois**
This PR improves the gray level images oracle of Mesh_3, and its documentation.

In particular, the "inside" of the domain is now considered to be the side where the voxel values are higher than the isovalue. This makes more sense because it is intended to be used with medical images, where the "white" area is the area of interest.

This PR solves issue #624
This PR ships pull request #633

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-106

**Comment by lrineau** [comment]
[Doc bug][1]:
```
CGAL-4.8-Ic-106/doc/Mesh_3/Mesh_3.txt:607: Warning: unable to resolve reference to `Mesh_3/mesh_3D_gray_image.cpp' for \ref command
```
[1]: https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.8-Ic-106/Mesh_3.log

**Comment by sloriot** [comment]
Look at the commit done before your comment ;)

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-107

**Pull request merged**
