### PR TITLE
Fix all uninitialized members

### PR DESCRIPTION
**Pull request by GilesBathgate**
## Summary of Changes

Fix all uninitialized members for #5181

## Release Management

* Affected package(s): Multiple
* Issue(s) solved (if any): fix #5181
* License and copyright ownership: Returned to CGAL authors

Replaces #5182, #5183, #5184, ~#5185~, ~#5186~, #5187, #5188, #5189, #5190, #5191, ~#5192~, #5193, #5194, #5195, #5196, #5197, #5198, #5199, #5200, #5201, #5202, #5203, #5204.

### CODE REVIEW

**Comment by GilesBathgate** [comment]
@sloriot As requested. Please let me know if you want me to close the others or this PR.

Regards,
Giles

**Comment by mglisse** [comment]
Ah, I hadn't seen this general PR. Let me mention this here: sorry if I seem to resist those patches. For a few years now, I have seen people "fix" code based of gcc's broken -Wmaybe-uninitialized. In at least 90% of the cases I looked at, the warning was bogus and the "fix" made the code worse (to various degrees: less readable, less efficient, harder to debug, sometimes plain wrong). There was an almost even split among gcc developers about moving -Wmaybe-uninitialized from -Wall to -Wextra, but sadly a slight majority of C-centered maintainers chose to keep it in -Wall. So when I see people trying to "fix" even less relevant warnings, my knee-jerk reaction is :-1: . I do appreciate that you seem to have found 2 real issues with this tool though, thanks.

**Comment by lrineau** [comment]
> Ah, I hadn't seen this general PR.

My opinion is that the collection of smaller PRs is easier to review.


> In at least 90% of the cases I looked at, the warning was bogus and the "fix" made the code worse (to various degrees: less readable, less efficient, harder to debug, sometimes plain wrong).

That is my feeling too: the blind initialization of uninitialized variables is not a solution: that may generate slightly less efficient code, but more important that may hide future diagnostics about actual usage of uninitialized variable. For pointers, all the analysis tool know that `0` or `nullptr` is a sentinel value that cannot point to a real object, but for other types, like `int`, simply put a `0` to initialize the variable may be the wrong choice.

>  I do appreciate that you seem to have found 2 real issues with this tool though, thanks.

Great. :tada: Which ones?

**Comment by GilesBathgate** [comment]
> but more important that may hide future diagnostics about actual usage of uninitialized variable

I agree, However, I remember finding it particularly annoying trying to debug an issue in my own codebase where the opposite was true, i.e I had random behaviour because I had forgotten to initialise a member variable.

> Great. :tada: Which ones?

I guess he would be referring to the two High issues are fixed by #5169 and #5168 I just wanted to submit these PR's, in case any more were true positive.

**Comment by maxGimeno** [comment]
Warning:

>/Users/monet/Documents/test-suite/clang-default/CGAL-5.3-Ic-5/include/CGAL/Tools/chained_map.h:30:1: warning: 'chained_map_elem' defined as a struct template here but previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct chained_map_elem

**Comment by GilesBathgate** [comment]
>warning: 'chained_map_elem' defined as a struct template

@maxGimeno Fixed.

**Comment by maxGimeno** [comment]
Thank you. Can you also maintain the splitted PRs ? I am using this one for tests as it is easier, but we will use the others to merge and review.

**Comment by afabri** [comment]
> My opinion is that the collection of smaller PRs is easier to review.

I agree. Is the best policy then that in each PR  it gets approved by either the maintainer or the EB or GF ?

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-11.shtml

**Comment by lrineau** [comment]
I will not merge this PR because it is the one having all other PRs merged in it.

**Pull request closed without merging**
