### PR TITLE
Remove a broken link

### LINKED ISSUE #5755: Security risk regarding link to uni-bielefeld in package Surface_mesh
## Issue Details

Not 100% a CGAL problem, but the link to:
```
https://graphics.uni-bielefeld.de/publications/imr11/
```
in the package Surface_mesh (file: Surface_mesh/doc/Surface_mesh/Surface_mesh.txt) gives a security risk:
```
Warning: Potential Security Risk Ahead
```
this is not that good and might be best to contact uni-bielefeld about this issue (better from an institute than from a private person).

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Remove a broken link.

Fix #5755

### CODE REVIEW

**Comment by maxGimeno** [comment]
replaced by #5756

**Comment by MaelRL** [comment]
@maxGimeno The link is not removed in #5756, only https is added. The conclusion seemed to be that it ought to be removed completely anyway, so the 5756 doesn't actually replace this PR?

**Comment by maxGimeno** [comment]
@MaelRL Ok, I should have read the issue.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-148.shtml

**Pull request merged**
