### PR TITLE
Tetrahedral_remeshing - fix bad_alloc for very small input mesh

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR prevents a "bad_alloc" error that could happen when the size of the input object (in terms of size of the bbox) was very small and edge lengths even smaller, e.g. `cellSize = 1e-9`.
Thresholding the bbox size with `1e-3` was not consistent with the size of the object, leading to using `resize(n)` on a `std::vector` with `n` larger than `vector.max_size()`.

## Release Management

* Affected package(s): Tetrahedral_remeshing
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by maxGimeno** [comment]
runtime errors : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-69/Tetrahedral_remeshing/TestReport_lrineau_Debian-stable-Release.gz

**Comment by lrineau** [comment]
> runtime errors : [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-69/Tetrahedral_remeshing/TestReport_lrineau_Debian-stable-Release.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-69/Tetrahedral_remeshing/TestReport_lrineau_Debian-stable-Release.gz)

That is actually a segfault on all platforms. With MSVC in Debug, there is an assertion:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.3-Ic-69/Tetrahedral_remeshing/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Debug-64bits.gz
```
------------------------------------------------------------------
- ProgramOutput.test_mesh_and_remesh_polyhedral_domain_with_features.x64_Cygwin-Windows10_MSVC2017-Debug-64bits
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1614146829
valid data structure
valid triangulation
[...]\VC\Tools\MSVC\14.16.27023\include\vector(1733) : Assertion failed: vector subscript out of range
```

**Comment by sloriot** [comment]
@janetournois this one is getting urgent as it is one of the last targetting 5.1.3

**Comment by janetournois** [comment]
it should be fine now.
Sorry for the delay!

**Comment by sloriot** [comment]
Local ctest run:
`13/16 Test #14: execution___of__test_mesh_and_remesh_polyhedral_domain_with_features ...***Exception: SegFault 11.69 sec`

**Comment by sloriot** [comment]
```
    at /home/sloriot/CGAL/git/branch/Tetrahedral_remeshing/include/CGAL/Tetrahedral_remeshing/internal/FMLS.h:405
405	        if (LUT[index] == 0)
(gdb) p index
$1 = 0
(gdb) p LUT[index]
Cannot access memory at address 0x0
(gdb) p LUT
$2 = std::vector of length 0, capacity 0
```

**Comment by janetournois** [comment]
Full ctest (msvc 2019, debug mode, examples and tests) passed on my machine

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-78.shtml

**Pull request merged**
