### PR TITLE
Replace \internal by \cond + always use SKIP_IN_MANUAL as string

### LINKED ISSUE #2448: CGAL documentation: different ways skip things from the documentation
I am writing of piece of documentation for Mesh_3, using the "inline" method: 
having the documentation of a class directly in its header, in `Mesh_3/
include/CGAL/` (by opposition to having a dedicated file in `Mesh_3/doc/
Mesh_3/CGAL/`).

There are public types and methods that I do not want to document. To "hide" 
those methods from the documentation, I have already found three different 
ways:

1. Using `#ifdef/#ifndef DOXYGEN_RUNNING`

2. Using the Doxygen command `\internal`

3. Using the Doxygen pair of commands `\cond DEVELOPER` and `\endcond` (where 
`DEVELOPER` is a string of your choice).

In CGAL, 

- `DOXYGEN_RUNNING` is used 200 times,
- `\internal` is used 15 times,
- and `\cond` is used with multiple strings:
   - 1   `\cond SKIP`
   - 1   `\cond SKIP_DOXYGEN`
   - 1   `\cond SKIP_IN_DOC`
   - 3   `\cond` (without keyword)
   - 4   `\cond SKIP_FROM_MANUAL`
   - 8   `\cond CGAL_BEGIN_END`
   - 11  `\cond DEVELOPERS`
   - 15  `\cond CGAL_DOCUMENT_INTERNALS`
   - 18  `\cond CGAL_DOCUMENT_INTERNAL`
   - 229 `\cond SKIP_IN_MANUAL`

I think we should write recommandations. Currently, our guidelines [mention 
the three possibilities][1] but I think we should try to unify.

[1]: https://github.com/CGAL/cgal/wiki/Writing-Documentation#hiding-part-of-the-documentation

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #2448
TODO:
- [x] update the wiki guidelines)

### CODE REVIEW

**Comment by lrineau** [comment]
I disagree with this PR.

**Comment by sloriot** [comment]
Then I did not understand what you wanted to do to fix the issue. Could you be more precise about what you expected?

**Comment by lrineau** [comment]
First, a discussion, then a decision, and then the patch. I will go on with the discussion in 
https://github.com/CGAL/cgal/issues/2448.

**Comment by lrineau** [comment]
@sloriot Should we close https://github.com/CGAL/cgal/issues/2448 as well?

**Pull request closed without merging**
