### PR TITLE
Polyhedron demo: PLY and region growing fixes

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

Two fixes for the demo:
* removing typenames that produce errors on Windows in shape detection plugin
* adding a wait cursor when loading PLY files

## Release Management

* Affected package(s): Polyhedron demo

### CODE REVIEW

**Comment by lrineau** [comment]
Travis error: https://travis-ci.org/CGAL/cgal/jobs/266692777#L3914

**Comment by sgiraudot** [comment]
I forgot to push the latest fix… sorry about that.

**Comment by sgiraudot** [comment]
(My latest commit was wrong again, sorry.)

**Comment by lrineau** [comment]
That warning is back!
```
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\xutility(815) : warning C4244: '+=' : conversion from '__int64' to 'unsigned int', possible loss of data
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-24/Point_set_shape_detection_3_Examples/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz

How was it solved last time?

**Comment by janetournois** [comment]
I think this PR #1933 is the one you are looking for

**Comment by janetournois** [comment]
commit 60fd6aa27a6ccced2b1db67d720876613e47831d maybe...

**Comment by sgiraudot** [comment]
It should be fixed now… but I have no idea why this pop ups only now, the counting iterator with default types has been in the _Shape Detection_ package since the very beginning.

**Comment by lrineau** [comment]
There is still one warning:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.12-Ic-27/Point_set_shape_detection_3_Examples/TestReport_afabri_x64_Cygwin-Windows8_MSVC2012-Release-32bits.gz

**Comment by lrineau** [comment]
No idea for the warning?

**Comment by janetournois** [comment]
Isn't it yet the same as the one in PR #1933 by commit 60fd6aa27a6ccced2b1db67d720876613e47831d ?

**Comment by sgiraudot** [comment]
I applied the same patch and the warning is still there, I don't understand what's going on…

**Comment by janetournois** [comment]
I will make a try...

**Comment by janetournois** [comment]
let's recap the history of this warning, that appears while using `boost/iterator/counting_iterator.hpp`
- there used to be a pragma in `structure_point_set.h`
- the warning was fixed by commit 136a4806e89e3f0cf81e405942b957dcbf8df04e (dec 2016)
- it re-appeared and @lrineau wrote the issue #1924 (feb 2017)
- it was fixed again by commit 60fd6aa (feb 2017)

and now 
- the warning had to be made silent with a pragma for region growing
- the fix of commit 60fd6aa is still valid in point set structuring

**Pull request merged**
