### PR TITLE
Renamed minkowski_sum_{full_convolution,reduced_convolution} => minko…

### PR DESCRIPTION
**Pull request by efifogel**
…wski_sum_by_{full_convolution,reduced_convolution}

This is a bug fix.
Running the test suite locally shows no errors.
Observe that the free functions being (slightly) renamed haven't been exposed yet via a public release.

### CODE REVIEW

**Comment by lrineau** [comment]
Efi, can you give here the URL of the feature that introduced the names you are now fixing?

I would like to post a note on that feature page.

**Comment by efifogel** [comment]
This is the one: /Minkowski sum 2 polygons with holes and RC
<https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Minkowski_sum_2_polygons_with_holes_and_RC>

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I have merged in `integration` for testing tonight in [CGAL-4.7-Ic-73][Ic-73].

[Ic-73]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-73.shtml

**Comment by lrineau** [comment]
The test results in [CGAL-4.7-Ic-81][Ic-81] are really good. But I do not understand that [compilation error][error]. Andreas @fabri, do you have a way to reproduce it? Otherwise this pull request is ready to be merged.

[Ic-81]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-81.shtml#Minkowski_sum_2

[error]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.7-Ic-81/Minkowski_sum_2/TestReport_afabri_x64_Cygwin-Windows8_MSVC2010-Release-64bits.gz

**Comment by lrineau** [comment]
I have merged the pull request. If the compilation error is reproducible, then we will address it later.

**Comment by lrineau** [comment]
Efi, you can delete the branch `MS_2-add_proposition_to_function_name-efif` from your fork. The command is probably:

    git push mine --delete MS_2-add_proposition_to_function_name-efif

**Comment by efifogel** [comment]
I've deleted the branch from my fork.
Thanks!

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Pull request merged**
