### PR TITLE
Fix activation of local static filters

### PR DESCRIPTION
**Pull request by sloriot**
Fix typos preventing activation of local static filters

### CODE REVIEW

**Comment by lrineau** [comment]
I agree that this version should be faster, because the "predicate" is instantiated once per plane, and stores precomputed sub-expressions.

However, I disagree that is replaces #3357: if the kernel is `CGAL::Epick`, then the static filtered version of `Is_on_positive_side_of_plane_3` will be used, and will compute all the three steps of filtering. However, for all types of kernels, then the version of #3357 is simpler (less line of code), and even more efficient with `CGAL::Epeck`, because the static filters of `Epeck` will be used.

So both #3357 and this PR #3359 are relevant.

**Comment by sloriot** [comment]
You're missing something. This will be only used when the traits is `Convex_hull_traits_3` which should basically be used only if you have a kernel with exact predicates and inexact constructions. Indeed this traits presents a plane as a triple of points rather than a `CGAL::Plane_3`. This is not relevant to you if you have exact constructions or use inexact predicates.
If you keep the patch on #3357 , this will imply that the static filters will be done twice with Epick in case of failure.

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/blob/48bb90a36e42cb4f97bad676f57bae66fc32ccd7/Convex_hull_3/include/CGAL/convex_hull_3.h#L326-L347

**Comment by sloriot** [comment]
@lrineau I don't know what you want to show with the snapped code. Let's discuss this live to avoid useless rounds.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.14-Ic-10][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-10.shtml

**Pull request merged**
