### PR TITLE
Allow is_strongly_convex_3 with Surface_mesh.

### PR DESCRIPTION
**Pull request by mhsaar**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Allow instantiation of CGAL::is_strongly_convex_3 with Surface_mesh.

## Release Management

* Affected package(s):
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by afabri** [comment]
Hello Michael, can you explain why this is needed. Is the problem not  that a   `const` is missing [here](https://github.com/CGAL/cgal/blob/de69ca0897ab9b11eaefb1026e5e99511be82624/Convex_hull_3/include/CGAL/convexity_check_3.h#L196).

Also the license check file should remain the first one to get `#include`. @sloriot right?

**Comment by sloriot** [comment]
They are several issues that I'll fix asap.

**Comment by mhsaar** [comment]
Agreed. I was certainly expecting that this won't be the final version.

**Comment by afabri** [comment]
> 
> 
> Agreed. I was certainly expecting that this won't be the final version.

Thank you for pointing out !!!!

**Comment by mhsaar** [comment]
Yes, but more because I was explicitly including Surface_mesh.

**Comment by sloriot** [comment]
@mhsaar just to be clear the issues I mention are not in your patch but in the current code.

**Comment by sloriot** [comment]
Replaced by #5158

**Pull request closed without merging**
