### PR TITLE
GSoC 2018: 2D Boolean set Operations demo

### PR DESCRIPTION
**Pull request by apurvakbh**
Please add this branch to the master branch.

The brach contains 2D Boolean set Operations demo. It was done as a part of the gsoc 2018 project. It was done under mentor-ship of Efi Fogel and Andreas Fabri.

<b>TODO:</b>
- [ ] filter branch to reduce history size (@sloriot)
- [ ] handle degenerate polygons

### CODE REVIEW

**Comment by sloriot** [comment]
I have many warnings when using `-Wall and -Wextra`, you should fix them to pass the testsuite.

**Comment by lrineau** [comment]
Andreas, Efi, please comment/review this pull-request.

Cc: @afabri @efifogel

**Comment by efifogel** [comment]
This program demonstrates the 2D regularized Boolean operations. It's the 1st release of such a demo program based on Qt5. Currently (excluding this demo) the 2D regularized operations are not demonstrated by any demo program, so it's a good intensive to release it. It lacks several features, but it's in a satisfactory shape. I do recommend the release.

**Comment by lrineau** [comment]
This branch weights 2724kB. @sloriot, would you mind have a look if that is normal, or can be fixed?

**Comment by lrineau** [comment]
There are a lot of warnings or compilation errors, in the testsuite:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-Ic-14/Boolean_set_operations_2_Demo/TestReport_gimeno_CentOS6.gz

**Comment by efifogel** [comment]
Should be ok now.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
I do not see any push. What have you modified?

**Comment by efifogel** [comment]
cgal-public-dev/gsoc2018-bso_demo-apurva
commit cc91f5762e3e9fb3786fc351e674475f72980cb6
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
The push should be done in the `master` branch of the repo `git@github.com:apurva786/cgal.git`, that is the branch of this PR. If you do not have the rights for that, then either @apurva786 will have to do it, or we will replace this PR by another one you create.

**Comment by efifogel** [comment]
ok, I'll ask Apurva for write permissions and fix it myself in the right
branch.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by apurva786** [comment]
> This branch weights 2724kB. @sloriot, would you mind have a look if that is normal, or can be fixed?

The branch's size is big because it contains some images(in the resources folder). All of them are not used currently, but I have kept them in case they might be useful for future developers.

**Comment by efifogel** [comment]
ok, I've updated the remote branch.
The demo should compile now without warnings.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
There are still many warnings.
See [test results](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-31.shtml).

**Comment by efifogel** [comment]
I hope that this time I've nailed them all.
Committed & pushed.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@maxGimeno could you please have a look at cmake warnings in [4.14-Ic-33](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-33.shtml)?

**Comment by efifogel** [comment]
1. I've added some statements to CMakeLists to guard against platforms that
do not support C++1, and
2. I've added some policy related statements, which I had copied as is from
the Polyhedron demo.
Let's try now.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@maxGimeno  could you please check that all is good now? Also as our demo expert, I'd appreciate if you could try to play a bit with the demo to see if there is no major issue.

**Comment by sloriot** [comment]
@apurva786 could you please add me and @maxGimeno as [collaborators](https://github.com/apurva786/cgal/settings/collaboration)?

**Comment by sloriot** [comment]
Is this the expected windows? I don't see any of my input polygon in the list.
screenshot from 2018-11-05 16-55-12

Also if I draw an invalid polygon, the demo simply crashes. We should add a test that consider a polygon only if it is valid and otherwise display an error message (a bad click can happen to anyone and we don't want the whole session to be gone for a bad click).

**Comment by apurva786** [comment]
I have added @maxGimeno as a collaborator. 
The screenshot attached in the above comment is the expected window.
After reading the comment, again I did some testing and indeed the demo crashes when the user draws a polygon which intersects with itself and it crashes without a warning. I am trying to figure out a way how to prevent it from crashing. If there are any other cases where it happens please let me know.

@maxGimeno can you please elaborate the statement "I don't see any of my input polygon in the list."

I would like to mention the console, Infos and the buttons under Geometric objects are disabled, but the radio buttons and checkbox are working.

The demo is expected to work like as shown in this video [link](https://www.youtube.com/watch?v=uEJGw959nnM)

Regarding how to use the demo  
I have made a documentation about how to use the demo. It is in help folder with the name index.html.

**Comment by efifogel** [comment]
Hi Apurva,

First, thanks for the dedication. It is appreciated!

Regarding self intersections, any one of the Boolean operation accepts only
valid operations.
The definition of "valid" appears in the documentation. It goes beyond self
intersections.
There is a function that tests whether a polygon is a valid operand of a
Boolean operation.
All we need to do is add a call to this function and react.
There is a similar function for a polygon with holes; see

Gps_polygon_validation::is_valid_unknown_polygon(polygon, traits)
Gps_polygon_validation::is_valid_unknown_polygon(polygon-with-holes, traits)

Efi

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Hello, what is the status of this branch ? @sloriot it is written that you have some filtering to do, but also there is something to be done about degenerated polygons.

**Comment by lrineau** [comment]
@efifogel @apurva786 No change to the PR since November 2018. This PR will probably not make it into CGAL-4.14.

**Comment by maxGimeno** [comment]
Still no change, I move it to Attic/Trash

**Comment by sloriot** [comment]
@efifogel what is the status of this pull request?

**Comment by sloriot** [comment]
@efifogel If I got it right, we can close this PR?

**Comment by efifogel** [comment]
Naturally, I still would like to complete the demo and publish it.
It requires some more work, so if you think it's the right thing to do,
close it, and when the necessary improvements are done, I'll create a new
pull request.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
I don't want to close it but my understanding is that this work is obsolete and another branch does exist (but maybe I misunderstood)

**Comment by efifogel** [comment]
Aha; you are correct.
The branch that contains the most up-to-date version, and the only one that
matters, is gsoc2021-bso_demo-kedia.
So any pull-request of older versions is obsolete.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Pull request closed without merging**
