### PR TITLE
PMP - Improve isotropic remeshing

### PR DESCRIPTION
**Pull request by janetournois**
This pull request fixes the reprojection step at the end of each iteration of isotropic remeshing.
It is necessary that each vertex is reprojected to the same surface patch is "comes from".

It also introduces the ability to move vertices along the 1D constrained features.

~~The code of the filtered traits still contains a small hack to be fixed, but it works.~~
edit : fixed by commit cgal-dev@4715297

### CODE REVIEW

**Comment by janetournois** [comment]
Merged in [CGAL-4.8-Ic-95](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-95.shtml)

**Comment by lrineau** [comment]
While testing on Linux, I had to fix a compilation error with f29d6ffaaf75c7704e8ac8d100830fe058b6c804. A temporary object cannot be found to a non-const reference.

**Comment by sloriot** [comment]
Testsuite for the package is almost fully red

**Comment by janetournois** [comment]
I'm not merging this PR in integration today because it's conflicting with PR#613, already merged in merged in [CGAL-4.8-Ic-97](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-97.shtml)

**Comment by sloriot** [comment]
CGAL-4.8-Ic-98

**Comment by janetournois** [comment]
I have just rebased this branch onto cgal/master

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-102

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-103

**Pull request merged**
