### PR TITLE
Update the name of package names reference links

### LINKED ISSUE #3304: Package documentation labels: PkgXXXX and PkgXXXSummary
## Issue Details

For a package `XXX`, we define a bunch of labels such as `PkgXXX`, `PkgXXXConcepts`, `PkgXXXSummary`, etc. 

The issue is that when you want to refer to a package, the intuitive way is to use `\ref PkgXXX`. However, this points to the reference manual of the package, whose label is usually defined by `\defgroup PkgXXX XXX Reference`. Consequently, when you want to write "this is useful for package XXX" with a link via `\ref PkgXXX`, you get "this is useful for package XXX Reference.", which looks strange and links to the reference manual.

Usually I use `\ref PkgXXXSummary`, which gives you what you want, both from a location (it points to the package in the list of packages) and naming (no "reference"). It is however not intuitive and there are a lot of instances of this "reference" dangling around where it was.

The two labels could be swapped, or renamed, or something else.

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #3304 
+ make the name used uniform

Command used to generate package link name `sed -r 's/(^|_)(\w)/\U\2/g'`

- [ ] Update github wiki for the name scheme

### CODE REVIEW

**Comment by lrineau** [comment]
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-10/logs_master/Documentation.log
```
/home/cgal-testsuite/cgal_doc_build/CGAL-4.14-Ic-10/doc/Documentation/Installation.txt:682: warning: unable to resolve reference to `PkgBGLSummary' for \ref command
```

**Comment by sloriot** [comment]
I rebased the branch onto master and fixed the issue that was due to a change that happened in master after the creation of the initial branch.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.14-Ic-27][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-27.shtml

**Comment by lrineau** [comment]
@sloriot You have set the label "todo: wiki" for this PR #3311.

**Comment by sloriot** [comment]
Done

**Pull request merged**
