### PR TITLE
Aos 2: fixes

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

This contains a bunch of fixes. Some of  these fixes fix bugs of exposed features. Theses are mentioned in the changes file (for the release notes). Other fixes, fix bugs of features that haven't been exposed yet (but will soon be...). The pull request also contains few additional regression tests for the fixes above.

In particular, this pull request contains the implementation of a generic function object that lexicographically compares two x-monotone curves of a 2D arrangement. This (single) implementation applies to all traits. This new function object is now used by the test suite. I may decide to expose this feature in the future (as part of a small feature). Then, I will also introduce specific implementation for the various traits as an optimization.

## Release Management

* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): none
* Feature/Small Feature (if any): none
* Link to compiled documentation (obligatory for small feature) [link](https://mydoc/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by efifogel** [comment]
Fixed that, thanks.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
[**@efifogel**](https://github.com/efifogel) commented on [Sep 10, 2018, 8:35 PM GMT+2](https://github.com/CGAL/cgal/pull/3325#issuecomment-420015915 "2018-09-10T18:35:32Z - Replied by Github Reply Comments"):
> Fixed that, thanks.

Actually you did not.

I just pushed f29919a03af21fa035e58482fdba28f004ffbb73, that:
  - moved the changes in the section for CGAL-4.14,
  - and added the backquotes.

**Comment by lrineau** [comment]
The travis check reports compilation errors, for example:
```
[ 54%] Building CXX object CMakeFiles/arrangement_2.dir/ArrangementDemoTab.cpp.o
In file included from /home/travis/build/CGAL/cgal/Arrangement_on_surface_2/demo/Arrangement_on_surface_2/ArrangementDemoWindow.cpp:19:
In file included from /home/travis/build/CGAL/cgal/Arrangement_on_surface_2/demo/Arrangement_on_surface_2/./ArrangementDemoWindow.h:29:
In file included from /home/travis/build/CGAL/cgal/Arrangement_on_surface_2/demo/Arrangement_on_surface_2/./EnvelopeCallback.h:27:
In file included from /usr/local/lib/cmake/CGAL/../../../include/CGAL/envelope_2.h:32:
In file included from /usr/local/lib/cmake/CGAL/../../../include/CGAL/Envelope_2/Env_divide_and_conquer_2.h:377:
/usr/local/lib/cmake/CGAL/../../../include/CGAL/Envelope_2/Env_divide_and_conquer_2_impl.h:587:27: error: 
      no viable conversion from
      'CGAL::Arr_traits_adaptor_2<CGAL::Arr_segment_traits_2<Kernel>
      >::Compare_xy_2' to 'Compare_xy_2' (aka
      'CGAL::Arr_segment_traits_2<Kernel>::Compare_xy_2')
  Compare_xy_2            compare_xy = traits->compare_xy_2_object();
                          ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://travis-ci.org/CGAL/cgal/jobs/430461361#L2518

See also https://travis-ci.org/CGAL/cgal/builds/430461356

**Comment by efifogel** [comment]
I believe that I've fixed the problem.
The 2D Arrangement demo compiles and works now.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Indeed the Travis test ran fine. I will test the PR in `integration` soon.

**Comment by lrineau** [comment]
Unfortunately, there has been new conflicts with recent merges into `master`.

**Comment by efifogel** [comment]
Anything that I can or should solve?
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
Yes, Efi (@efifogel), you can try to merge `cgal/master` (after `git fetch cgal`) into the branch, then solve the conflicts pointed out by git, and then commit and push the result.

**Comment by efifogel** [comment]
Will do

**Comment by efifogel** [comment]
All done
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel There were some warnings when I compiled the upcoming integration. I added the commit 56a72950d7 in integration, please have a look at it.

**Comment by efifogel** [comment]
Your last commit looks right, thanks.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
I think there is a regression. If I look at results of `Ic-32` and `Ic-33`, both have failures on the same platforms compared to `I-29`.
See:
```
[sloriot@cgal ~]$ ~lrineau/bin/cgal_diff_results 4.14-I-29 4.14-Ic-32 | egrep "(\+.* (w|n)$|^\+\+\+)"
+++ CGAL-4.14-Ic-32/results_lrineau_CentOS5.txt	2018-11-01 00:25:04.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-32/results_lrineau_CentOS6-32.txt	2018-11-01 03:15:02.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-32/results_lrineau_CentOS6-CXX11-Boost157.txt	2018-11-01 10:35:02.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-32/results_lrineau_CentOS7-Release.txt	2018-11-01 00:25:02.000000000 +0100
+Arrangement_on_surface_2 n
```
```
[sloriot@cgal ~]$ ~lrineau/bin/cgal_diff_results 4.14-I-29 4.14-Ic-33 | egrep "(\+.* (w|n)$|^\+\+\+)"
+++ CGAL-4.14-Ic-33/results_lrineau_CentOS5.txt	2018-11-02 00:25:04.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-33/results_lrineau_CentOS6-32.txt	2018-11-02 03:15:02.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-33/results_lrineau_CentOS6-CXX11-Boost157.txt	2018-11-02 10:35:02.000000000 +0100
+Arrangement_on_surface_2 n
+++ CGAL-4.14-Ic-33/results_lrineau_CentOS7-Release.txt	2018-11-02 00:25:02.000000000 +0100
+Arrangement_on_surface_2 n
```

**Comment by efifogel** [comment]
ops, it seems that I had c++11 code.
Anyhow, I've replaced with non-c++11 code.
Let's try again....

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Successfully tested in [CGAL-4.14-Ic-43](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-43.shtml)

**Pull request merged**
