### PR TITLE
PMP hole filling: Add an option to only use Delaunay based versions

### PR DESCRIPTION
**Pull request by sloriot**
Add a way to avoid the cubic search space to be used, early exit without hole filled.

It is useful for very large holes

### CODE REVIEW

**Comment by sloriot** [comment]
what about `do_not_use_cubic_algorithm` -> `do_not_use_cubic_search_space`?

**Comment by afabri** [comment]
> what about `do_not_use_cubic_algorithm` -> `do_not_use_cubic_search_space`?

What about `use_only_delaunay_triangulation`

**Comment by sloriot** [comment]
I think it is ambiguous with which version can be used, 2D, 3D, both.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-36

**Pull request merged**
