### PR TITLE
Basic viewer: use compatibility shaders in basic_viewer

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Remove remaining `#version` from compatibility glsl and use shaders without #version in basic viewer in case the ES context is used to avoid glsl error.

### CODE REVIEW

**Comment by MaelRL** [comment]
It's better: I get the vertices and edges on each call of draw(), but on the other hand I have lost face colors at all iterations :).

Here is the error log I get now: https://gist.github.com/MaelRL/126694fb91f3332a3e1918df11c2da2a.

CC @gdamiand for info.

**Comment by maxGimeno** [comment]
Yes ! I knew there was more to it than I remembered. 
This should do it .

**Comment by MaelRL** [comment]
Some different error now: https://gist.github.com/MaelRL/656d0ab81b4b0d673fec21b86235e097

**Comment by maxGimeno** [comment]
Oops, sorry.

**Comment by MaelRL** [comment]
Colors and no errors on the first display, no color from 2nd iteration (but still vertices/edge).

Log: https://gist.github.com/MaelRL/73c9d6fd53304f5e43d5f6b63d0ab850

**Comment by maxGimeno** [comment]
Ok, I forgot a line. You can try again

**Comment by MaelRL** [comment]
Same: https://gist.github.com/MaelRL/994ef770363d33959cc89b0f1e458c4c

**Comment by maxGimeno** [comment]
Fixed. It's a real shame that I can't test by myself, it twould take a lot less time :(

**Comment by MaelRL** [comment]
Let's just settle this directly on my machine at some point.

**Comment by lrineau** [comment]
It is really annoying that our big 3D demo and the basic viewers do not use the same shaders.

I really would like to know why.

**Comment by maxGimeno** [comment]
The equivalent shaders in the demo are far more complicated, so I don't want to complexify everything in the Basic_viewer code to use them, and the shaders in the basic_viewer have some specificities (like the point size management) that we don't want in the demo for performence purpose.

**Comment by gdamiand** [comment]
I agree with @lrineau ; it could be better to factorize more code between the demo and the basic viewer.

**Comment by maxGimeno** [comment]
@maelRL we really need to find nome time to finish this.

Conflicts.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-106.shtml

**Pull request merged**
