### PR TITLE
Possible technical debt in sphere_predicates.h

### PR DESCRIPTION
**Pull request by GilesBathgate**
## Summary of Changes

Tidy up of code in sphere_predicates.h

In commit https://github.com/CGAL/cgal/commit/a3923877cf4d7f9363b820d13d24e30482f902b4 The code was changed so that the variables pS and pN are no longer needed until later on in the function:

https://github.com/CGAL/cgal/blob/16fc8d1fe27ff2ea79340d5c7a892083acbb24fe/Nef_S2/include/CGAL/Nef_S2/sphere_predicates.h#L87

pN is now an unused variable, and pS is initialised regardless of the when the function exits early. A switch also seems like an overkill when the only differing case is axis==1.

The proposed change cleans up the code and gives an unimaginably small performance increase :) (benchmarks to follow)
A commented-out function was also removed, for the usual reasons.

## Release Management

* Affected package(s): 2D Boolean Operations on Nef Polygons Embedded on the Sphere
* Feature/Small Feature (if any): Code tidy / performance?
* License and copyright ownership: Return to CGAL authors.

### CODE REVIEW

**Comment by GilesBathgate** [comment]
I used the following benchmark code:

```
#include <benchmark/benchmark.h>

#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Nef_S2/Sphere_geometry.h>
#include <CGAL/Nef_S2/sphere_predicates.h>

using namespace CGAL;
using K = Exact_predicates_exact_constructions_kernel;
static Sphere_point<K> p1(0,1,0);
static Sphere_point<K> p2(1,1,0);

void test_spherical_compare(benchmark::State& state)
{
	for(auto _ : state)
	{
		benchmark::DoNotOptimize(
			CGAL::spherical_compare(p1,p2,0,1)
		);
	}
}

BENCHMARK(test_spherical_compare);

BENCHMARK_MAIN();
```

With the results as follows:
```
python3 /usr/share/benchmark/compare.py benchmarks ./baseline ./contender --benchmark_repetitions=10 --benchmark_report_aggregates_only=true
RUNNING: ./baseline --benchmark_repetitions=10 --benchmark_report_aggregates_only=true --benchmark_out=/tmp/tmptfi7tbgx
2020-11-11 19:09:36
Running ./baseline
Run on (8 X 4200 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 8192K (x1)
Load Average: 1.47, 1.67, 1.70
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
test_spherical_compare_mean         4447 ns         4446 ns           10
test_spherical_compare_median       4355 ns         4353 ns           10
test_spherical_compare_stddev        556 ns          555 ns           10
RUNNING: ./contender --benchmark_repetitions=10 --benchmark_report_aggregates_only=true --benchmark_out=/tmp/tmpr1jhau4y
2020-11-11 19:09:44
Running ./contender
Run on (8 X 4200 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 8192K (x1)
Load Average: 2.34, 1.85, 1.76
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
test_spherical_compare_mean         3112 ns         3111 ns           10
test_spherical_compare_median       3103 ns         3103 ns           10
test_spherical_compare_stddev       62.4 ns         62.4 ns           10
Comparing ./baseline to ./contender
Benchmark                                       Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------------------
test_spherical_compare_mean                  -0.3003         -0.3004          4447          3112          4446          3111
test_spherical_compare_median                -0.2875         -0.2872          4355          3103          4353          3103
test_spherical_compare_stddev                -0.8876         -0.8876           556            62           555            62
```

**Review by afabri — APPROVED** [review]
I reviewed the code and the suggested changes make perfect sense.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-34.shtml

**Comment by maxGimeno** [comment]
Success in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-55.shtml

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-65.shtml

**Comment by lrineau** [comment]
Hi Giles, we have received the paperwork (CLA). I can start merging your pull-requests (once they have been properly tested, like this one).

**Pull request merged**
