### PR TITLE
[Small Feature] GIS Tutorial

### PR DESCRIPTION
**Pull request by sgiraudot**
## Rationale

CGAL offers many packages that can be used for applications in _Geographic Information System_ (GIS), althought people looking for "_GIS with CGAL_" won't find any documentation on how to proceed.

This tutorial proposes a list of standard GIS tools and algorithms that can be easily set up with CGAL, along with a compilable example.

## Summary of API changes

- A new tutorial GIS is added to the tutorial list of the manual. It covers:
  1. TIN (Triangulated Irregular Networks)
  2. DEM (Digital Elevation Modeling)
  3. Rastering
  4. Contouring
  5. Classifying
- For user-friendliness, a new constructor using an initializer list is added to `CGAL::Classification::Label_set`

## License and copyright ownership

GeometryFactory

## CHANGES.md

NA

## Submission

* [~~__GIS Tutorial__~~](https://cgal.geometryfactory.com/~sgiraudot/GIS_tutorial/Manual/tuto_gis.html)
* [~~__GIS Tutorial v2__~~](https://cgal.geometryfactory.com/~sgiraudot/GIS_tutorial_v2/Manual/tuto_gis.html)
* [~~__GIS Tutorial v3__~~](https://cgal.geometryfactory.com/~sgiraudot/GIS_tutorial_v3/Manual/tuto_gis.html)
* [__GIS Tutorial v4__](https://cgal.geometryfactory.com/~sgiraudot/GIS_tutorial_v4/Manual/tuto_gis.html) 

## Status

- Developed and locally tested (GNU/Linux)
- [Small Feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/GIS_Tutorial) Pre-approved Andreas Fabri 15:20, 18 March 2020 (CET) 

## Todo (after merge)

- [ ] News entry

### CODE REVIEW

**Comment by sloriot** [comment]
TODO: add news entry?

**Comment by oleg-alexandrov** [comment]
That is lovely. Something could be said as well about filling in missing parts (https://doc.cgal.org/latest/Advancing_front_surface_reconstruction/index.html) and hole-filling (https://doc.cgal.org/latest/Polygon_mesh_processing/index.html) (the latter will become more useful after my pull request (https://github.com/CGAL/cgal/pull/4455) is merged).
 
Those operations could be more accurate than the TIN thing, which as I see introduces artifacts where data was missing. In fact, before the TIN one may want to apply some Laplacian smoothing (https://doc.cgal.org/latest/Polygon_mesh_processing/index.html). In my own work, where I deal with clouds obtained form a depth camera such a smoothing step really improves things. 

Then, I don't know how the TIN is implemented. It looks like a triangulation thingy, and those can amply irregularities. A reasonably standard way of gridding a DEM from an irregular cloud is to take a weighted average of all points in a neighborhood of the future grid point with the neighborhood maybe of radius a little bigger than a grid point so that each cloud point contributes to more than one future grid point (https://opentopography.org/otsoftware/points2grid).

**Comment by sgiraudot** [comment]
@oleg-alexandrov thanks a lot for the spontaneous review!

Advancing Front seems hard to connect to this tutorial as it's a distinct reconstruction method (that will already be covered by [the Reconstruction tutorial](https://github.com/CGAL/cgal/pull/442) that should be integrated soon).

Covering hole filling seems like a good idea to me! It kind of drifts away from the 2.5D framework that I presented, but I agree that hole filling would produce a much better result after filtering out buildings. I'll see how I can integrate that nicely.

The TIN that I present is "just" a CGAL Delaunay Triangulation 2 using the projection of points on the XY planes as reference. The idea is mainly to show what is possible with the existing CGAL tools (although we are always interested in adding new algorithms to the library). Thanks for the pointer to this `points2grid` approach, it can indeed be a good postprocessing, I'll look into it.

**Comment by sgiraudot** [comment]
I updated the new version of the tutorial, including:
- clarified names an sections for TIN, DEM, DSM, DTM (as discussed with @afabri)
- hole filling and remeshing added as a postprocessing to DTM

**Comment by sgiraudot** [comment]
(I just realized I did not correct the "Figure [Figure X](#)" redundancies, I'll upload a new corrected version soon.)

**Comment by sgiraudot** [comment]
The V2 is fixed and ready to be reviewed.

**Comment by sgiraudot** [comment]
I got another offline review from @afabri and uploaded a V3 in accordance.

**Comment by sgiraudot** [comment]
V4 is online, this time changes are quite minor: new intro and new figure for polyline simplification (to show different outputs according to the tolerance).

**Comment by sloriot** [comment]
[Runtime error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-122/Classification_Examples/TestReport_lrineau_ArchLinux-CXX17-Release.gz) on all platforms.

**Comment by maxGimeno** [comment]
Compilation error here : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.1-Ic-127/Classification/TestReport_Blake_Windows_MSVCPreview-Release-64bits.gz

Don't bother with the execution errors though, it was a problem in the PATH.

**Comment by maxGimeno** [comment]
There are conflicts in that branch

**Comment by maxGimeno** [comment]
Thank you :)

**Comment by maxGimeno** [comment]
On MSVC 2019 : C:\cgal_test\CGAL-5.1-Ic-130\cmake\platforms\Windows_MSVC-2019-Community-Release-64bits\test\Classification_Examples\gis_tutorial_example.cpp(283): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\cgal_test\CGAL-5.1-Ic-130\cmake\platforms\Windows_MSVC-2019-Community-Release-64bits\test\Classification_Examples\gis_tutorial_example.cpp(335): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\numeric(35): warning C4267: '=': conversion from 'size_t' to '_Ty', possible loss of data

**Comment by maxGimeno** [comment]
Doc warning: source /home/cgal-testsuite/cgal_doc_build/CGAL-5.1-Ic-130/doc/Classification/examples is not a readable file or directory... skipping.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-137.shtml

**Comment by sloriot** [comment]
Branch has been filtered, I checked the diff with the original branch and rebuilt the doc.

**Pull request merged**
