### PR TITLE
Adding const to the rhs of equality check of Iso_box_d

### PR DESCRIPTION
**Pull request by freud14**
I did not run the tests because I don't know how, but I don't think that this change will break anything. Can you instruct me how to run the tests so that the build does not crash in case where the tests would fail? Thank you.

### CODE REVIEW

**Comment by Kar0t** [comment]
+1

**Comment by sloriot** [comment]
See http://doc.cgal.org/latest/Manual/devman_testing.html

**Comment by freud14** [comment]
I get

> #  error The test-suite needs no NDEBUG defined

when I tried to run the tests. I use the flag `-DCMAKE_BUILD_TYPE=Release` with the cmake command but it still does not work.

**Comment by sloriot** [comment]
Remove the NDEBUG flag from your `CMakeCache.txt`

**Comment by freud14** [comment]
Alright, I ran the tests and everything is good (at least with my configuration).

**Comment by lrineau** [comment]
Merged in `cgal/master`. Thanks for the patch.

**Pull request merged**
