### PR TITLE
add more repair functions in the Polyhedron demo

### PR DESCRIPTION
**Pull request by sloriot**
This brings a way to stitch halfedges that are closed (up to epsilon) and some improvement in the function to remove degenerate faces.

TODO for me:
 - [ ] update `PMP-restore_remove_deg_faces-sloriot` when the PR is merged

### CODE REVIEW

**Comment by lrineau** [comment]
Doc error:
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.12-Ic-55/Polygon_mesh_processing.log

**Comment by lrineau** [comment]
Multiple errors:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-55.shtml#Polygon_mesh_processing_Examples

**Comment by sloriot** [comment]
The error with OpenMesh is not related to this PR and fixed by #2492

**Comment by lrineau** [comment]
@sloriot: Now you have:
> TODO for me:
> - update PMP-restore_remove_deg_faces-sloriot when the PR is merged

**Comment by sloriot** [comment]
Done, thanks.

**Pull request merged**
