### PR TITLE
PMP: Replace parameter with named parameter

### LINKED ISSUE #6999: Move output iterator of hole filling functions in named parameters
Since they are optional they should be in the named parameter pack.

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Implementing feature request #6999 

## Release Management

* Affected package(s): Polygon_mesh_processing
* Issue(s) solved (if any): fix #6999

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot can you please take care of the return type.   Once this is done for the first function I will apply the recipe on the other functions.

**Comment by sloriot** [comment]
```
/Users/magritte/cgal_root/CGAL-5.6-Ic-128/test/Classification_Examples/gis_tutorial_example.cpp:476:38: warning: 'triangulate_refine_and_fair_hole<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick>>, CGAL::Emptyset_iterator, CGAL::Emptyset_iterator, bool, CGAL::internal_np::all_default_t, CGAL::internal_np::No_property>' is deprecated [-Wdeprecated-declarations]
```

**Comment by sloriot** [comment]
You should define `CGAL_NO_DEPRECATED_CODE` and try to compile the test of PMP and the demo.

**Comment by sloriot** [comment]
Successfully tested in 5.6-Ic-129

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-133

**Comment by sloriot** [comment]
CHANGES.md should be updated

**Comment by afabri** [comment]
> CHANGES.md should be updated

Done

**Pull request merged**
