### PR TITLE
Polytope_distance: Use Exact_integer

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Do not `#ifdef` for GMP or alternatives, but use `Exact_integer`.

Looking at other examples I am wondering if we should not introduce a type `CGAL::Exact_TBD`   to replace
```cpp
#ifdef CGAL_USE_GMP
#include <CGAL/Gmpzf.h>
typedef CGAL::Gmpzf ET;
#else
#include <CGAL/MP_Float.h>
typedef CGAL::MP_Float ET;
#endif
``` 
for examples [here](https://doc.cgal.org/latest/Polytope_distance_d/Polytope_distance_d_2polytope_distance_d_8cpp-example.html)   Any suggestion for a name @mglisse ?  

## Release Management

* Affected package(s): Polytope_distance
* Issue(s) solved (if any): fix #0000, fix #0000,...
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:  unchanged

### CODE REVIEW

**Comment by mglisse** [comment]
> Any suggestion for a name @mglisse ?

Exact_float? You seem to have named this Ring_for_float in Exact_NT_backend.

**Comment by afabri** [comment]
Because it does not offer division, right?   I am even wondering about `cpp_float` which we use in filtered predicates when GMP is not installed.

**Comment by afabri** [comment]
@sloriot needs retesting for the documentation testsuite.

**Comment by afabri** [comment]
Documentation testsuite for Polytope distance is ok in [I-c-338](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-6.0.1-Ic-338/).  And the link to `CGAL::Width_3` fixed in the [concept](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-6.0.1-Ic-338/output2/Polytope_distance_d/classWidthTraits__3.html#a3a4d02ea98c8a75350a88cf04f9bf989).

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0.1-Ic-345

**Pull request merged**
