### PR TITLE
WIP: Fix the testsuite with LEDA instead of GMP

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

The testsuite that uses LEDA instead of GMP/CGAL_Core is pretty bad. In particular Kernel_23 was not tested:

> This program requires the CGAL and CGAL_Core libraries, and will not be compiled.

At least now the Kernel_23 testsuite passes, with real tests. Well, almost:
```
95% tests passed, 2 tests failed out of 42

Label Time Summary:
Kernel_23_Tests    =  28.66 sec*proc (42 tests)

Total Test time (real) =   5.31 sec

The following tests FAILED:
        1085 - compilation_of__test_Has_conversion (Failed)
        1086 - execution___of__test_Has_conversion (Not Run)
```

## Work in progress

There are other `CMakeLists.txt` testing for `CGAL_Core`:
```
Arrangement_on_surface_2/demo/Arrangement_on_surface_2/CMakeLists.txt
CGAL_Core/examples/Core/CMakeLists.txt
CGAL_Core/src/CGAL_Core/CMakeLists.txt
Cone_spanners_2/examples/Cone_spanners_2/CMakeLists.txt
Cone_spanners_2/test/Cone_spanners_2/CMakeLists.txt
GraphicsView/demo/Polygon/CMakeLists.txt
Kernel_23/test/Kernel_23/CMakeLists.txt
Surface_mesh_shortest_path/test/Surface_mesh_shortest_path/CMakeLists.txt
Surface_sweep_2/test/Surface_sweep_2/CMakeLists.txt
```

It should be fixed, so that the tests are actually compiled.

Maybe `CGALConfig.cmake` could provide a CMake target
`CGAL::Exact_nt_with_sqrt` that would be an abstraction of CGAL_Core
and LEDA.

## Release Management

* Affected package(s): All CGAL
* License and copyright ownership: no change of license (maintenance by GF)

### CODE REVIEW

**Comment by maxGimeno** [comment]
warnings and errors remaing on platforms with LEDA:
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Algebraic_kernel_d
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Kernel_23
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Polygon_mesh_processing
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Arrangement_on_surface_2
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Bounding_volumes
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Envelope_3
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#NewKernel_d
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#QP_solver
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Segment_Delaunay_graph_Linf_2
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Segment_Delaunay_graph_Linf_2_Examples
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Triangulation
- [ ] https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-61.shtml#Visibility_2

**Comment by maxGimeno** [comment]
@lrineau should we postpone this ?

**Comment by lrineau** [comment]
No. The situation is improved by this PR: a lot of tests fail currently with LEDA in `master`, and this PR fixes some of them.

**Comment by maxGimeno** [comment]
So we integrate it but don't close the issue ?

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Jan 11, 2019, 9:50 AM GMT+1](https://github.com/CGAL/cgal/pull/3501#issuecomment-453435025 "2019-01-11T08:50:10Z - Replied by Github Reply Comments"):
> So we integrate it but don't close the issue ?

Right. Except that we will create an issue ticket, to remember the TODO list, because for the moment there is none.

**Comment by maxGimeno** [comment]
Ok.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-105.shtml.

**Comment by lrineau** [comment]
TODO: fill a new issue entry with the remaining bugs

**Comment by lrineau** [comment]
If have created the issue #3702 to spot out the remaining things to do. Let's merge this PR as it is...

**Pull request merged**
