### PR TITLE
Fixes in the Package Overview

### PR DESCRIPTION
**Pull request by afabri**
Add/Remove some cgalPkgDependsOn
Move Visibility package from Arrangements to Polygons
Add some ``  in the Visibility package
Add the keyword 'Geodesic' to the Shortest Path package.

### CODE REVIEW

**Comment by lrineau** [comment]
For 4.7 or 4.8?

**Comment by afabri** [comment]
for 4.7 unless you see a flaw, or it breaks the doxygen testsuite

**Comment by afabri** [comment]
still a doxygen error to fix
https://cgal.geometryfactory.com/CGAL/Members/Manual_doxygen_test/CGAL-4.7-Ic-140/Visibility_2.log

**Comment by sloriot** [comment]
Doc looks good now.

**Pull request merged**
