### PR TITLE
fix check-dependencies (4.14)

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

The detection of documented headers is buggy with recent versions of Doxygen. Fix it. Also support `CGAL_HEADER_ONLY` when possible.

## Release Management

* Affected package(s): Installation
* License and copyright ownership: maintenance by GF

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-95.shtml.

**Comment by maxGimeno** [comment]
Dependencies are all broken

**Comment by MaelRL** [comment]
@lrineau What happens to this PR with #4106 being pushed back indefinitely?

**Comment by lrineau** [comment]
Same effect: I moved it to Trash/stalled

**Pull request closed without merging**
