### PR TITLE
Testsuite: enhanced summary page with JSON generation and search functionality

### PR DESCRIPTION
**Pull request by SaillantNicolas**
## Summary of Changes
 The summary page is now generated using a JSON file.
 A search bar has been added to the summary page.

---
The version of this Pull Request can be reviewed at [this link](https://cgal.geometryfactory.com/~nsaillant/testsuite/TESTRESULTS/).

### CODE REVIEW

**Comment by lrineau** [comment]
That seems a very nice improvement. @sloriot Does it fit the needs?

**Comment by lrineau** [comment]
> That seems a very nice improvement. @sloriot Does it fit the needs?

@sloriot 

> The version of this Pull Request can be reviewed at [this link](https://cgal.geometryfactory.com/~nsaillant/testsuite/TESTRESULTS/).

Can you please check if that corresponds to the needs?

**Comment by sloriot** [comment]
Sorry, I remember discussing it on element. Looks good to me. The filtration could be improved. Indeed packages are filtered out globally but not depending on the selected case to be reported (n,w,o,...). But it is not a blocking point and could be merged as is as it is really helpful.

**Comment by lrineau** [comment]
> Sorry, I remember discussing it on element. Looks good to me. The filtration could be improved. Indeed packages are filtered out globally but not depending on the selected case to be reported (n,w,o,...). But it is not a blocking point and could be merged as is as it is really helpful.

I'll merge it, and later improvements will be another pull-request...

**Pull request merged**
