### PR TITLE
if a polyhedron is triangulated, print its volume (if closed) and its…

### PR DESCRIPTION
**Pull request by sloriot**
… surface area

### CODE REVIEW

**Comment by sloriot** [comment]
Branch merged in CGAL-4.7-Ic-26

**Comment by lrineau** [comment]
I have assigned to you, Sébastien.

**Comment by sloriot** [comment]
I'd prefer that you quickly look at the diff to see whether you agree with the changes. I can take care of the merge if the test results are good.

**Comment by lrineau** [comment]
The changes seems good and useful.

If you prefer I deal with the integration, reassign the issue to me. As you want.

**Comment by sloriot** [comment]
Merged into CGAL-4.7-Ic-29

**Comment by sloriot** [comment]
Re-merged in 4.7-Ic-32

**Comment by lrineau** [comment]
I have remerge that pull request #72 into integration. It seems that the last two commits were not in `integration`:
```
renoir ~/Git/cgal $ git log cgal-dev/integration..refs/pull/72/head
commit c3f637f567eeae8747f999cd999e614046fab035
Author: Sébastien Loriot <sebastien.loriot@cgal.org>
Date:   Mon May 11 10:48:27 2015 +0200

    fix typo

commit 83cc9513c583d192d4fef8539e058756e04b6126
Author: Sébastien Loriot <sebastien.loriot@cgal.org>
Date:   Thu May 7 09:50:21 2015 +0200

    if a polyhedron is triangulated, print its volume (if closed) and its surface area
```

**Comment by lrineau** [comment]
The tests in CGAL-4.7-Ic-33 were successful.

**Pull request merged**
