### PR TITLE
Add doc of functor class and concept corresponding to dihedral_angle()

### LINKED ISSUE #1561: Fill the documentation of CGAL::dihedral_angle
I have merged #1530 but I forgot that it included the addition of `CGAL::dihedral_angle` into the CGAL kernel.

Its [current documentation](https://cgal.geometryfactory.com/CGAL/doc/master/Kernel_23/namespaceCGAL.html#ab88c71fd1918c6b97134c39026da8f15) is:
> returns the dihedral angle of .... between -180 and 180 degree.

That must be fixed ASAP!
@afabri @janetournois 

Only `Kernel_23/doc/Kernel_23/CGAL/Kernel/global_functions.h` has been modified, so far, but there is also a new function `Compute_dihedral_angle_3` in the kernel.

### PR DESCRIPTION
**Pull request by afabri**
Also replace ... 

Fix #1561.

### CODE REVIEW

**Comment by sloriot** [comment]
We have `ComputeApproximateArea_3` why approximate is not part of the name of the functor/function ?

**Comment by lrineau** [comment]
@sloriot said:
> We have `ComputeApproximateArea_3` why approximate is not part of the name of the functor/function ?

@afabri Have you seen that comment from Sébastien?

**Comment by lrineau** [comment]
See the [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/kernel_23_CADA_3) Sébastien talked about.

**Comment by afabri** [comment]
After a discussion with Sébastien, we agreed that it is more coherent to add the prefix or infix `approximate` in the global function as well as in the functors.  This is done in the before mentioned commit.

**Comment by lrineau** [comment]
This PR leads to a compilation error in Polyhedron_Demo:
```
In file included from /cgal/Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp:16:0:
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h: In instantiation of ‘typename K::FT CGAL::Mesh_3::dihedral_angle(const typename K::Point_3&, const typename K::Point_3&, const typename K::Point_3&, const typename K::Point_3&, K) [with K = CGAL::Epick; typename K::FT = double; typename K::Point_3 = CGAL::Point_3<CGAL::Epick>]’:
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h:57:33:   required from ‘typename CGAL::Kernel_traits<T>::Kernel::FT CGAL::Mesh_3::dihedral_angle(const Point_3&, const Point_3&, const Point_3&, const Point_3&) [with Point_3 = CGAL::Weighted_point<CGAL::Point_3<CGAL::Epick>, double>; typename CGAL::Kernel_traits<T>::Kernel::FT = double]’
/cgal/Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp:565:70:   required from ‘std::vector<int> create_histogram(const C3t3&, double&, double&) [with C3t3 = CGAL::Mesh_complex_3_in_triangulation_3<CGAL::Regular_triangulation_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Mesh_3::Robust_intersection_traits_3_new<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> > >, CGAL::Triangulation_data_structure_3<CGAL::Mesh_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Mesh_3::Robust_intersection_traits_3_new<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> > >, CGAL::Polyhedral_mesh_domain_with_features_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, CGAL::Polyhedron_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, Polyhedron_demo_items<int>, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Triangle_accessor_3<CGAL::Polyhedron_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, Polyhedron_demo_items<int>, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> >, CGAL::Boolean_tag<true> >, CGAL::Triangulation_vertex_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Mesh_3::Robust_intersection_traits_3_new<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> > >, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Compact_mesh_cell_base_3<CGAL::Robust_weighted_circumcenter_filtered_traits_3<CGAL::Mesh_3::Robust_intersection_traits_3_new<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> > >, CGAL::Polyhedral_mesh_domain_with_features_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, CGAL::Polyhedron_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, Polyhedron_demo_items<int>, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Triangle_accessor_3<CGAL::Polyhedron_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, Polyhedron_demo_items<int>, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick> >, CGAL::Boolean_tag<true> >, void>, CGAL::Parallel_tag>, CGAL::Default> >]’
/cgal/Polyhedron/demo/Polyhedron/Scene_c3t3_item.cpp:638:78:   required from here
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h:44:12: error: ‘class CGAL::Epick’ has no member named ‘compute_dihedral_angle_3_object’; did you mean ‘compare_dihedral_angle_3_object’?
   return k.compute_dihedral_angle_3_object()(a, b, c, d);
          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
demo/Polyhedron/CMakeFiles/scene_c3t3_item.dir/build.make:62: recipe for target 'demo/Polyhedron/CMakeFiles/scene_c3t3_item.dir/Scene_c3t3_item.cpp.o' failed
make[3]: *** [demo/Polyhedron/CMakeFiles/scene_c3t3_item.dir/Scene_c3t3_item.cpp.o] Error 1

```
and also:
```
In file included from /cgal/Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cpp:16:0:
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h: In instantiation of ‘typename K::FT CGAL::Mesh_3::dihedral_angle(const typename K::Point_3&, const typename K::Point_3&, const typename K::Point_3&, const typename K::Point_3&, K) [with K = CGAL::Simple_cartesian<double>; typename K::FT = double; typename K::Point_3 = CGAL::Point_3<CGAL::Simple_cartesian<double> >]’:
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h:57:33:   required from ‘typename CGAL::Kernel_traits<T>::Kernel::FT CGAL::Mesh_3::dihedral_angle(const Point_3&, const Point_3&, const Point_3&, const Point_3&) [with Point_3 = CGAL::Point_3<CGAL::Simple_cartesian<double> >; typename CGAL::Kernel_traits<T>::Kernel::FT = double]’
/cgal/Surface_mesh_simplification/examples/Surface_mesh_simplification/edge_collapse_constrain_sharp_edges.cpp:112:136:   required from here
/cgal/Mesh_3/include/CGAL/Mesh_3/dihedral_angle_3.h:44:12: error: ‘struct CGAL::Simple_cartesian<double>’ has no member named ‘compute_dihedral_angle_3_object’; did you mean ‘compare_dihedral_angle_3_object’?
   return k.compute_dihedral_angle_3_object()(a, b, c, d);
          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/Surface_mesh_simplification/CMakeFiles/edge_collapse_constrain_sharp_edges.dir/build.make:62: recipe for target 'examples/Surface_mesh_simplification/CMakeFiles/edge_collapse_constrain_sharp_edges.dir/edge_collapse_constrain_sharp_edges.cpp.o' failed
make[3]: *** [examples/Surface_mesh_simplification/CMakeFiles/edge_collapse_constrain_sharp_edges.dir/edge_collapse_constrain_sharp_edges.cpp.o] Error 1
make[3]: Target 'examples/Surface_mesh_simplification/CMakeFiles/edge_collapse_constrain_sharp_edges.dir/build' not remade because of errors.
```

**Comment by afabri** [comment]
Must be compute_approximate ....

**Pull request merged**
