### PR TITLE
OFF loading fix

### PR DESCRIPTION
**Pull request by maxGimeno**
- Some items called `compute_normals_and_vertices` several times in a row. The fact that they don't anymore makes the loading of OFF files almost twice faster.

### CODE REVIEW

**Comment by sloriot** [comment]
`Polyhedron_Demo/Scene_polyhedron_selection_item.h:806:8: warning: 'Scene_polyhedron_selection_item::compute_elements' hides overloaded virtual function`

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-20][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-20.shtml

**Comment by maxGimeno** [comment]
The warning has disappeared, so the PR seems ready to be definitively merged.

**Pull request merged**
