### PR TITLE
Polyhedron demo : fix surf reader

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes
This PR intends to fix the behavior of the `.surf` reader when the input surface is non-manifold.
Because `CGAL::Polyhedron_3` cannot handle a non-manifold surface, the built polyhedron has holes wherever the builder tries to make a non-manifold configuration.

We use `PMP::orient_polygon_soup` and `PMP::polygon_soup_to_polygon_mesh` to build a valid polygon mesh, which can be a `CGAL::Polyhedron_3` with duplicated vertices on geometrically non-manifold edges/vertices.

## Release Management
* Affected package(s): Polyhedron demo

### CODE REVIEW

**Comment by janetournois** [comment]
note more patches need to be pushed before testing

**Comment by lrineau** [comment]
Is this PR now ready?

**Comment by janetournois** [comment]
It is. Unless we want to try to speed it up (?)

**Comment by janetournois** [comment]
let's say it's ready for now. The speedups would be in the repair functions from PMP, so they would be made in other PR(s).

**Pull request merged**
