### PR TITLE
Generalized map

### PR DESCRIPTION
**Pull request by gdamiand**
* [Accepted feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Generalized_map)

* Tested successfully in [CGAL-4.10-Ic-47](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.10-Ic-47.shtml)

* [changes.html](https://github.com/gdamiand/cgal/blob/Generalized_map-gdamiand/Installation/changes.html) updated.

### CODE REVIEW

**Comment by sloriot** [comment]
`test_merge_of_branch` did not report any error. The branch weights 4.8Mo which seems large.
The compressed size of  `Generalized_map` is 1.1Mo.  When squashing the commit, the size goes down to 2.4Mo.

**Comment by lrineau** [comment]
I think the branch should be rebased, because the commit 25a2639e82a31167afeb414aeb9c0d9bc860d999 has merged `master` into the branch.

**Comment by lrineau** [comment]
In the changes, ` <h3>Generalized Maps (new package)</h3>` should be moved near the top of the change log, in the "new packages" section.

**Comment by gdamiand** [comment]
Done (for changes.html).

**Comment by sloriot** [comment]
I've done the rebase

**Comment by sloriot** [comment]
I've reworked the history to have all fig modiffications in one commit. This reduced the history size to 3.4Mo. I've converted all `png` of `Combinatorial_map`, `Linear_cell_complex` and `Generalized_map` to 8bits and  now the history size is 1.7Mo

I've pushed it in https://github.com/sloriot/cgal/tree/Generalized_map-gdamiand 

@gdamiand  you should check that the converted png are fine.
@cjamin do you see any other trick to reduce the size of a png?

**Comment by gdamiand** [comment]
Figures in 8 bits are not good: text is now really hard to read and has very bad look.

**Comment by cjamin** [comment]
Guillaume, can you give an example of bad conversion? Because if I compare for example [this one](https://github.com/gdamiand/cgal/blob/Generalized_map-gdamiand/Generalized_map/doc/Generalized_map/fig/gmap_detailed_example.png) with [the 8-bit version](https://github.com/sloriot/cgal/blob/Generalized_map-gdamiand/Generalized_map/doc/Generalized_map/fig/gmap_detailed_example.png), I can't see any difference.

Am I comparing the correct images?

**Comment by gdamiand** [comment]
@cjamin In fact you are right; it was my image viewer which made a bad rescaling...
Sorry @sloriot .

**Comment by cjamin** [comment]
Ok, good.
@sloriot You might try to reduce the number of colors, but the gain is very limited (30% maybe) and you will have to tune it for each image.

**Comment by lrineau** [comment]
Anyway, I think PNG uses a lossless compression algorithm. If you manage to significantly reduce the image size, that means that you also degraded it. Images with gradients, or anti-aliasing, might be less precise in 8 bits.

**Comment by afabri** [comment]
I have no idea what you have in your images, but in the BGL package I used inkscape to produce svg.

**Comment by gdamiand** [comment]
xfig, much better than inkscape (I am just trolling ;)

I can export all my figures in svg instead of png in you think it is better. @sloriot tell me.

**Comment by afabri** [comment]
Just compare [this](http://doc.cgal.org/latest/BGL/group__PkgBGLEulerOperations.html#ga8666be89a7ffa73a5fe82b6b2bdc6f19)  with [that](http://doc.cgal.org/latest/Polyhedron/classCGAL_1_1Polyhedron__3.html#a73119c0c90bf8612da003305af25a52a)

**Comment by cjamin** [comment]
@lrineau Of course you're right, but the images being mainly B&W, 256 shades of gray are enough for anti-aliasing. I didn't see any gradient in the images, but I didn't check them all.

But SVG is far better, so go for it.

**Comment by gdamiand** [comment]
@sloriot can you just tell me in which branch I need to do the modification please ?

**Comment by sloriot** [comment]
Just add a commit to this branch, I'll rebase it when you're done.

**Comment by gdamiand** [comment]
Done (and doc tested locally).

**Comment by lrineau** [comment]
It seems the PR still has the old history. Am i wrong?

**Comment by gdamiand** [comment]
I think you are right.
@sloriot creates a new branch https://github.com/sloriot/cgal/tree/Generalized_map-gdamiand
I have no idea what to do with this now...

**Comment by sloriot** [comment]
I have a [rebased version](https://github.com/sloriot/cgal/tree/Generalized_map-gdamiand) which size is 1.5Mo

However I have the following errors:

```
Generalized_map/doc/Generalized_map/PackageDescription.txt:15: Warning: image file gmap_logo.svg is not found in IMAGE_PATH: assuming external image.
Generalized_map/doc/Generalized_map/Generalized_map.txt:16: Warning: image file gmap_non_orientable_objects.svg is not found in IMAGE_PATH: assuming external image.
Generalized_map/Generalized_map.txt:17: Warning: image file gmap_non_orientable_objects.svg is not found in IMAGE_PATH: assuming external image.
```

I think I've been also a bit more radical about png removal as there is no one left in CM, LC and GM packages.

**Comment by gdamiand** [comment]
Why you did not cherry picked my commit https://github.com/CGAL/cgal/pull/1697/commits/00d829ba07787ede458171245bb8e983d98b5196 ?

I (re) tested locally and do not have this error (because there are still some png files); and there are modifications in CMap, GMap and LCC.

**Comment by sloriot** [comment]
I've picked it but its not at the end of the list. I think now it should be OK, I've readded the two missing png files. Branch weight is 1.7Mo. However I have more png files removed in my branch.Let me know if it is OK.

**Comment by gdamiand** [comment]
Hi. 
I have a look at your branch and it seems ok for CMap and GMap.
But for LCC it seems you mixed figures from GMap and LCC and keep png...

And if I look in my branch, I have only 3 png remaining:  lcc_logo.png in LCC;  gmap_non_orientable_objects.png and gmap_logo.png for GMap.

Note that my correct branch is https://github.com/gdamiand/cgal/tree/Generalized_map-gdamiand (and not the one in CNRS repository) perhaps the errors come from that ?

**Comment by sloriot** [comment]
You were right, I did some crappy things. I've updated the branch on my remote and now we're good IMO. I let you do a final check. Branch weight is 1.1M now.

**Comment by gdamiand** [comment]
I just checked and this is ok. Thanks Sebastien.
Now you need to create a pull request based on your branch right ?

**Comment by lrineau** [comment]
I was about to say "No.", because usually we `git push --force` to the same branch to update the PR... but the discussion in this PR is mostly about the rebase. Maybe we should close it and open another one with the new branch, and a clean discussion page.

**Comment by sloriot** [comment]
I've update your branch, no need for a new PR IMO.

**Comment by sloriot** [comment]
`test_merge_of_branch` reported no error.

**Comment by gdamiand** [comment]
Ok perfect; thanks.

**Comment by lrineau** [comment]
I just merged the PR into `master`. I have updated the wiki page.

**Comment by gdamiand** [comment]
Great. Thank you Laurent.

**Pull request merged**
