### PR TITLE
Make the bibliography more uniform

### PR DESCRIPTION
**Pull request by bo0ts**
If a note is simply a URL turn it into a url. Also turn all occurrences
of \path|http://www.cgal.org| into \url{http://www.cgal.org}.

### CODE REVIEW

**Comment by lrineau** [comment]
Please first merge in `integration`.

**Comment by lrineau** [comment]
Philipp, is that a change targeting 4.6?

**Comment by lrineau** [comment]
Since nobody cared to answer my question. I will probably postpone that pull-request to 4.7.
@bo0ts , @afabri , speak now because tonight's internal release is supposed to be CGAL-4.6.

**Comment by lrineau** [comment]
After a Skype discussion with @bo0ts, I have merged the PR in `integration` for tonight.

**Comment by bo0ts** [comment]
The documentation testsuite 46-Ic-171 has no additional documentation errors and I checked the resulting bibliographic references for a few packages. IMO good to merge.

**Comment by lrineau** [comment]
@bo0ts, I let you clean up your branch in the fork. I do not see the button do delete it. Maybe it was already removed.

**Pull request merged**
