### PR TITLE
Make Triangulation_3 testsuite more verbose

### PR DESCRIPTION
**Pull request by afabri**
Add timer and print seed in order to make the testsuite verbose for fixing Issue #808

### CODE REVIEW

**Comment by lrineau** [comment]
I would prefer not to add `CGAL::Timer` in every example.

**Comment by afabri** [comment]
it's a throw away branch with the sole purpose to find out where it goes wrong.

**Comment by sloriot** [comment]
Merge CGAL-4.8-Ic-142

**Comment by sloriot** [comment]
@afabri Do you still need this PR in the testsuite or did you find what you looked for?

**Comment by afabri** [comment]
I didn't find it yet

**Comment by afabri** [comment]
I guess we have to extend it to the Mesh_3 testsuite as here is a [red](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-144/Mesh_3/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz) one.    The testsuite took 8000 sec instead of 400 sec the day before.

**Comment by lrineau** [comment]
Do we still need to merge this pull-request?

**Comment by afabri** [comment]
I think the PR that prints out the seed will do the job.

**Comment by lrineau** [comment]
This PR no only prints the seeds, it also adds a lot of `CGAL::Timer`.

**Comment by lrineau** [comment]
I close the PR. Please reopen it if necessary.

**Pull request closed without merging**
