### PR TITLE
CGAL headers only, step 0

### PR DESCRIPTION
**Pull request by cjamin**
Step 0, which doesn't change the API nor the ABI nor the way to compile CGAL. The code is there, but it's not activated for now.

Tested in CGAL-4.8-Ic-10: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-10.shtml

### CODE REVIEW

**Comment by lrineau** [comment]
I think this pull-request is ready for merging. As it changes *a lot* of files, that is important that it is merged quickly, to avoid future conflicts.

And as the merge window for CGAL-4.8 was opened no long ago, that is the right moment to merge risky branches.

**Comment by lrineau** [comment]
I have fixed in d6866de068f04b0cca39b36777dff66040a2015c a license issue detected by the script `Scripts/developer_scripts/test_merge_of_branch`.

**Comment by sloriot** [comment]
What's the name of the flag to switch the header only mode? I'd like to do a test with Core.

**Comment by gdamiand** [comment]
CGAL_HEADER_ONLY, but remind that functionality is not for this PR (step0) but for the next one (step1) which is not yet submitted.

**Comment by sloriot** [comment]
We have some doubts about Core.
Without defining CGAL_HEADER_ONLY, we observe link errors when the option `-fvisibility=hidden` is added in gcc.

For example compiling the example Bezier_curves triggers:
```
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::ConstRep::ConstRep()':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:473: undefined reference to `vtable for CORE::ConstRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::ConstRep::~ConstRep()':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:475: undefined reference to `vtable for CORE::ConstRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::ConstDoubleRep::ConstDoubleRep()':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:512: undefined reference to `vtable for CORE::ConstDoubleRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::ConstDoubleRep::ConstDoubleRep(double)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:514: undefined reference to `vtable for CORE::ConstDoubleRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::UnaryOpRep::UnaryOpRep(CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:706: undefined reference to `vtable for CORE::UnaryOpRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::UnaryOpRep::~UnaryOpRep()':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:710: undefined reference to `vtable for CORE::UnaryOpRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::NegRep::NegRep(CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:741: undefined reference to `vtable for CORE::NegRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::SqrtRep::SqrtRep(CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:771: undefined reference to `vtable for CORE::SqrtRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::BinOpRep::BinOpRep(CORE::ExprRep*, CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:801: undefined reference to `vtable for CORE::BinOpRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::BinOpRep::~BinOpRep()':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:806: undefined reference to `vtable for CORE::BinOpRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::MultRep::MultRep(CORE::ExprRep*, CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:1240: undefined reference to `vtable for CORE::MultRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o: In function `CORE::DivRep::DivRep(CORE::ExprRep*, CORE::ExprRep*)':
/home/sloriot/CGAL/git/branch/CGAL_Core/include/CGAL/CORE/ExprRep.h:1266: undefined reference to `vtable for CORE::DivRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o:(.rodata._ZTIN4CORE12ConstPolyRepINS_6BigIntEEE[_ZTIN4CORE12ConstPolyRepINS_6BigIntEEE]+0x10): undefined reference to `typeinfo for CORE::ConstRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o:(.rodata._ZTIN4CORE9AddSubRepINS_3SubEEE[_ZTIN4CORE9AddSubRepINS_3SubEEE]+0x10): undefined reference to `typeinfo for CORE::BinOpRep'
CMakeFiles/Bezier_curves.dir/__/__/__/__/Arrangement_on_surface_2/examples/Arrangement_on_surface_2/Bezier_curves.cpp.o:(.rodata._ZTIN4CORE9AddSubRepINS_3AddEEE[_ZTIN4CORE9AddSubRepINS_3AddEEE]+0x10): undefined reference to `typeinfo for CORE::BinOpRep'
collect2: error: ld returned 1 exit status
examples/Arrangement_on_surface_2/CMakeFiles/Bezier_curves.dir/build.make:100: recipe for target 'examples/Arrangement_on_surface_2/Bezier_curves' failed
make[3]: *** [examples/Arrangement_on_surface_2/Bezier_curves] Error 1
CMakeFiles/Makefile2:2876: recipe for target 'examples/Arrangement_on_surface_2/CMakeFiles/Bezier_curves.dir/all' failed
make[2]: *** [examples/Arrangement_on_surface_2/CMakeFiles/Bezier_curves.dir/all] Error 2
CMakeFiles/Makefile2:2884: recipe for target 'examples/Arrangement_on_surface_2/CMakeFiles/Bezier_curves.dir/rule' failed
make[1]: *** [examples/Arrangement_on_surface_2/CMakeFiles/Bezier_curves.dir/rule] Error 2
Makefile:748: recipe for target 'Bezier_curves' failed
make: *** [Bezier_curves] Error 2
```

**Comment by gdamiand** [comment]
I will do the test soon (I am away from my office for now).

**Comment by cjamin** [comment]
Maybe that's because in header-only mode, these lines:
    #if __GNUC__ >= 4
      #define CGAL_DLL_IMPORT __attribute__ ((visibility ("default")))
      #define CGAL_DLL_EXPORT __attribute__ ((visibility ("default")))
      #define CGAL_DLL_LOCAL  __attribute__ ((visibility ("hidden")))

are replaced by:
#  define CGAL_DLL_IMPORT
#  define CGAL_DLL_EXPORT
#  define CGAL_DLL_LOCAL

Maybe that's a mistake?

**Comment by gdamiand** [comment]
I had a look, and I found no reason for this problem since we did not modified anything in this case.

Then I just tested and I observe the same behaviour in master. @sloriot can you make also the test in master please ?

**Comment by sloriot** [comment]
I indeed observe even more link issues

**Comment by cjamin** [comment]
You mean, in master?

**Comment by gdamiand** [comment]
Do we want to solve the existing issues in master in this branch ?
I think it is better to distinguish the two things: 1) merge this branch 2) try to solve the link problems in another branch

**Comment by sloriot** [comment]
@cjamin yes in master

**Comment by sloriot** [comment]
I'm a coward on this PR, I let the release manager decide what to do.

**Comment by cjamin** [comment]
Oh, come on, it's only 263 modified files ;)

**Comment by lrineau** [comment]
I would like that the next step is tested in `integration`, before we merge such an important modification.

**Comment by gdamiand** [comment]
I think it is better to do the things progressively: merge step 0, then work on step 1.

Indeed, there will be probably some problems with the next step (for example on some specific computer), it will take some time to correct them, and more we wait to merge, more we will have conflicts to solve (and thus time to solve them, and possible errors reintroduce by the merge...).

But I am not the release manager...

**Comment by lrineau** [comment]
Here is what I propose:
  - we merge again this PR in `integration`,
  - *and* we add a commit, in `integration`, that defines `CGAL_HEADER_ONLY=1` by default, to check the behavior of that definition on all platforms. That will test the second code path of the patch.

**Comment by sloriot** [comment]
I'll do that tomorrow since integration is already filled.

**Comment by lrineau** [comment]
I suggest to add:
```cmake
  uniquely_add_flags( CGAL_CXX_FLAGS "-DCGAL_HEADER_ONLY" )
```
in `Installation/CMakeLists.txt`. That is how flags like `-frounding-math` are added globally.

**Comment by gdamiand** [comment]
Ok if you want...

But this is not enough; we need to remove the link with cgal library, otherwise we will have duplicated symbols.

**Comment by lrineau** [comment]
Unless I have misunderstood, where `CGAL_HEADER_ONLY` is defined, the .cpp files of all libraries are empty, because they are surrounded by `#ifndef CGAL_HEADER_ONLY`. With `CGAL_HEADER_ONLY` defined, the libraries contains thus no symbols.

**Comment by gdamiand** [comment]
Yes you are right.

I think Clement have some problem on windows because it seems windows find this is an error to generate an empty lib.

**Comment by cjamin** [comment]
I don't remember exactly, but it's something like MSVC not generating a lib file when it's empty. So, when you try to link something with the lib, it can't find it.

**Comment by lrineau** [comment]
Do you also disable the auto-link of CGAL libraries, when `CGAL_HEADER_ONLY` is defined?

**Comment by cjamin** [comment]
I don't think so. How do we do that?

**Comment by lrineau** [comment]
You can define `CGAL_NO_AUTOLINK`, in `<CGAL/config.h>` for example:
```C++
#if CGAL_HEADER_ONLY
#  define CGAL_NO_AUTOLINK 1
#endif
```
then `<CGAL/auto_link/auto_link.h>` will be disable, because it starts with `#ifndef CGAL_NO_AUTOLINK`.

**Comment by gdamiand** [comment]
@cjamin Could you make a try ?

**Comment by gdamiand** [comment]
I tested locally to add DCGAL_HEADER_ONLY flag globally.

It works for examples and test, but not for demo (due to moc): we need to change the cmakelist for that and this is planed for step 1.

@lrineau I think this could be enough to test the second code path of the patch ?

**Comment by cjamin** [comment]
When I build libCGAL, which is empty, the lib file `CGAL-vc120-mt-gd-4.8-I-900.lib` is not generated. But the other libs (CGAL_Core, CGAL_Qt5, CGAL_ImageIO) try to link with it and produce an error.

This is not related to autolink since those dependencies are explicit (I can see them in the project properties). Solving this requires to modify the CMake files.

**Comment by gdamiand** [comment]
Thanks Clement.
@lrineau and this is planed for step 1 ;)

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-Ic-19](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml) with `uniquely_add_flags( CGAL_CXX_FLAGS "-DCGAL_HEADER_ONLY" )` in `Installation/CMakeLists.txt`.

**Comment by lrineau** [comment]
Is CGAL_Qt5 handled by the change?

**Comment by cjamin** [comment]
Are talking about the files in `GraphicsView/src/CGAL_Qt5`? Yes, we took care of them.

**Comment by lrineau** [comment]
Please do not forget to remove the file `cppfiles.txt` at the root of the Git repository.

**Comment by cjamin** [comment]
We just fixed it in the "step 1" branch.
Thanks

**Comment by lrineau** [comment]
(For information, the "step 1" branch is [`CGAL_headers_only_step1-gdamiand_cjamin`][1].)

[1]: https://github.com/CGAL/cgal-dev/compare/CGAL_headers_only_step1-gdamiand_cjamin

**Comment by afabri** [comment]
What are the implications for the thread_local_storage branch???
Guillaume was so convincing when he recommended me to
merge the headers_only branch into it.

**Comment by gdamiand** [comment]
No implication because CGAL_headers_only-gdamiand_cjamin was merged in master (i.e. step 0). 
Thanks to that, you will have no conflict when merging your branch.

**Pull request merged**
