### PR TITLE
Use C++11 for loop in examples

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

WIP

## Release Management

* Affected package(s): Surface_mesh_segmentation, Surface_mesh_deformation

### CODE REVIEW

**Comment by afabri** [comment]
@maxGimeno it is WIP, but I would be glad to see it in the testsuite.

**Comment by maxGimeno** [comment]
[errors](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-52/Surface_mesh_segmentation_Examples/TestReport_afabri_x64_Cygwin-Windows10_MSVC2017-Release-64bits.gz)

**Comment by afabri** [comment]
@maxGimeno this is no longer WIP and could go into integration.

**Comment by maxGimeno** [comment]
Seems all good in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-59.shtml

**Pull request merged**
