### PR TITLE
Mesh_3 - bug fixes for `edge_distance` and `edge_min_size`

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

While experimenting on self-intersecting polyhedral surfaces, I met two bugs:
* `edge_min_size` was not enough taken into account in `Protect_edges_sizing_field`,
* `edge_distance` was missing the information of which `curve_id` the edge belongs to (available using internal code)
causing crashes.

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
The Mesh_3 testsuite is currrently running locally on my machine

**Comment by janetournois** [comment]
`test_meshing_3D_image_with_features` is still failing in Debug mode

**Comment by sloriot** [comment]
Tests failing in CGAL-6.0-Ic-305

See [here](https://cgal.geometryfactory.com/CGAL/testsuite/summary-6.0-Ic-305.html?package=Mesh_3)

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-311

**Pull request merged**
