### PR TITLE
Polygon Mesh Processing documenation - Correct spelling mistake

### PR DESCRIPTION
**Pull request by GilesBathgate**
## Summary of Changes
Change the word 'scenarii' to 'scenarios'

## Release Management

* Affected package(s): PMP documentation
* Feature/Small Feature (if any): none

### CODE REVIEW

**Comment by janetournois** [comment]
Because [wiktionnary](https://en.wiktionary.org/wiki/scenario#English) also mentions "scenarios" as valid, let's keep this merged, but please note that the plural of "scenario" is "scenarii", see [wiktionnary](https://en.wiktionary.org/wiki/scenarii) (though using only one "i" seems to be the modern version).

**Comment by lrineau** [comment]
> (nonstandard, rare) plural form of scenario

The officiel plural is "scenarios": https://en.wiktionary.org/wiki/scenario#Noun

**Comment by GilesBathgate** [comment]
@janetournois I think this is known as a "hypercorrection", but you are right is listed on wiktionary, all be it as a rare nonstandard word. I did check before making the PR https://english.stackexchange.com/questions/11775/what-is-the-plural-of-scenario
It's not in the Oxford English dictionary, nor the American ones listed on the link above, but who knows maybe it will come into common use. I guess as an English speaker I wouldn't expect this word, and perhaps I can save people looking it up to check (which is what I did when I saw it ;) )

**Comment by janetournois** [comment]
I understand your point @GilesBathgate.
Let's keep it this way then, thank you.

**Pull request merged**
