### PR TITLE
Fix the name of libraries, on Windows

### PR DESCRIPTION
**Pull request by afabri**
If `CGAL_FULL_VERSION` is not set in the cache, in the sub-directory `src/` its value is empty. That creates wrong  library names, on Windows, such as:

    libCGAL_ImageIO-vc120-mt-.lib

### CODE REVIEW

**Comment by lrineau** [comment]
@bo0ts @sloriot 

The bug was introduced in the PR #542, but only in branch-build (not tested by our testsuite).

The bug is strange, and it involves three directories:
  - `cgal/`
  - `cgal/Installation`
  - `cgal/Installation/src`

On Windows, `Installation/src/CMakeLists.txt` uses the variable `CGAL_FULL_VERSION` to construct the names of created libraries.

Before the PR #542, `Installation/CMakeLists.txt` had created the variable `CGAL_FULL_VERSION` with:
```cmake
set(CGAL_FULL_VERSION ${value})
```
and the variable was usable in the sub-directory `Installation/src`. The PR #542 has added `PARENT_SCOPE`:
```cmake
set(CGAL_FULL_VERSION ${value} PARENT_SCOPE)
```
so that the variable was accessible also from the top-directory `cgal/`

But, in that case, the variable is no longer accessible from the sub-directory `cgal/Installation/src/`. You might assume that it is because only the first level of sub-directory is allowed to read the variable, but that it wrong. If the variable was created directory in the top directory `cgal/` with:
```cmake
set(CGAL_FULL_VERSION ${value})
``` 
then it would have been available also in the sub-sub-directory `cgal/Installation/src`. It seems that `PARENT_SCOPE` mean "in the parent scope, and only in it!"

My fix puts the variable in the CMake cache, as an internal variable, that is then usable from any sub-directory of the project.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-98

**Comment by lrineau** [comment]
@sloriot, please try to merge that as soon as possible. Andreas complained that it is still buggy in today's `master`.

**Comment by bo0ts** [comment]
@lrineau Can we please open an issue for this? The way the version variable is build is a real problem, because it depends on so many files, variables and modes. It is also not really documented what the expected content of each variable really is.

**Comment by lrineau** [comment]
@bo0ts Open an issue for a solved problem? What do you expect in the content of that issue?

**Comment by bo0ts** [comment]
The immediate issue has been solved, but the problem remains: the way this variable and its associates are set is still complicated, (internally) undocumented and hard to understand.

**Comment by lrineau** [comment]
I agree. But that is true for everything in our CMake scripts. Another example is the "preconfigured-libs" stuff. I still do not know how it is supposed to work.

I hope that the "header-only" technical feature will improve the situation.

**Pull request merged**
