### PR TITLE
Aos_2: bug-fix for arrangements of geodesic arcs on a sphere

### PR DESCRIPTION
**Pull request by efifogel**
## Summary of Changes

Fixed a bug in the zone construction code applied to arrangements of geodesic arcs on a sphere, when inserting an arc that lies on the identification curve.
I seized the opportunity and added support for simple drawing of arrangements of geodesic arcs on a sphere. (I added it to ease the debugging...)

## Release Management

* Affected package(s): Arrangement_on_surface_2
* Issue(s) solved (if any): no issue
* Feature/Small Feature (if any): none
* Link to compiled documentation: irrelevant
* License and copyright ownership: TAU

### CODE REVIEW

**Comment by sloriot** [comment]
New warnings in CGAL-6.0-Ic--42

- `CGAL/Arr_geodesic_arc_on_sphere_traits_2.h:2891:55: warning: unused parameter 'l2r' [-Wunused-parameter]`
- `/mnt/testsuite/include/CGAL/Arrangement_2/Arrangement_zone_2_impl.h:584:8: warning: variable 'equal' set but not used [-Wunused-but-set-variable]`

There might be more, but I only spotted those 2 while having a quick look.

**Comment by efifogel** [comment]
"location type" indeed; fixed.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
Fixed.
Also added a note to CHANGES.md
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Could you please fix the conflicts with master?

**Comment by efifogel** [comment]
Merged with master
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
It seems this PR is responsible for those runtime and compilation errors:
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-49/Arrangement_on_surface_2/TestReport_Christo_MSVC2017-Debug-64bits.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-49/Arrangement_on_surface_2_Demo/TestReport_Christo_MSVC2017-Debug-64bits.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-49/Arrangement_on_surface_2_Examples/TestReport_Christo_MSVC2017-Debug-64bits.gz
- https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-6.0-Ic-49/BGL_arrangement_2_Examples/TestReport_Christo_MSVC2017-Debug-64bits.gz

**Comment by efifogel** [comment]
Fixed.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
Resolved

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-64

**Pull request merged**
