### PR TITLE
Nef_3 performance - robin hood

### LINKED ISSUE #5379: ~70% Performance speedup for polygon_mesh_to_nef_3
## Issue Details

I have been investigating the performance of nef polyhedron construction, and have noticed the calculation of normals using normal_newell_3, while this approach is suitable for convex/concave facets with an arbitrary number of vertices, I think it is suboptimal for triangular facets. The function CGAL::orthogonal_vector is much better for this task, and we can easily switch between these two methods based on the number of edges/vertices.

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits): Linux 64bit
* Compiler: clang++ 
* Release or debug mode: Release
* Specific flags used (if any): clang++ polyhedron_3_to_nef_3_benchmark.cpp -DCGAL_DO_NOT_USE_BOOST_MP -lgmp -lmpfr -lbenchmark
* CGAL version: 5.0.2
* Boost version: 1.71.0
* Other libraries versions if used (Eigen, TBB, etc.): Qt 5.12.8

### PR DESCRIPTION
**Pull request by GilesBathgate**
## Summary of Changes

This  pull request provides refined the previous attempt to bring in `robin_hood` hashmaps.

Either `robin_hood::unordered_set` or `robin_hood:unordered_map` are used as needed. Functions from the STL compatible interfaces are used appropriately on a case by case basis.

Double hash lookups are avoided by using various techniques where appropriate.

## Release Management

* Affected package(s): Nef_3/Nef_S2/Polyhedron/HalfedgeDS
* Issue(s) solved (if any): fix #5379 
* Feature/Small Feature (if any): performance/speed
Link to compiled documentation: Undocumented internal use only.
License and copyright ownership:
MIT license for additional code from https://github.com/martinus/robin-hood-hashing Copyright (c) 2018-2020 Martin Ankerl http://martin.ankerl.com

### CODE REVIEW

**Comment by afabri** [comment]
Hmmh,, I maybe did something wrong, but I have the impression that this branch is now slower than 2 days ago, that is the latest merging of master in this branch led to a performance regression.   This branch is still a little bit faster than master.

**Comment by GilesBathgate** [comment]
🤷‍♂️

**Comment by GilesBathgate** [comment]
Here are some results from the benchmark script I ran:


```
cad4094f20,6.2926,6.21773,6.22952,6.23768,6.32745,6.18259,6.21182,6.21177,6.25523,6.22276,
73682cd872,5.97245,6.36891,6.28938,5.99053,6.33038,6.26321,6.30136,6.26747,6.24329,6.23736,
3ea918d165,6.33227,6.30054,6.29247,6.27552,6.10188,6.16083,6.13055,6.24078,6.10994,6.14194,
f32c05ca31,6.16244,6.13818,6.15316,6.15484,6.13312,6.16392,6.09797,6.12687,6.14526,6.13877,
9cbf1290d1,
7536f4bace,5.57542,5.88968,5.82806,5.81011,5.83613,5.8457,5.58094,5.81838,5.76563,5.56293,
a2c28bf0c7,5.55761,5.59642,5.55941,5.57992,5.52087,5.60571,5.57944,5.54758,5.58356,5.59337,
9f3d16ca05,5.65425,5.587,5.78533,6.0651,5.66651,5.55615,5.46608,5.43297,5.65575,5.71429,
3c5206e22b,5.77772,5.79071,5.78273,5.74104,5.71427,5.72785,5.7158,5.7142,5.71709,5.69854,
6728491729,5.53713,5.75038,5.75409,5.75756,5.77545,5.69695,5.69938,5.77012,5.69201,5.7173,
344c26f020,5.50661,5.57441,5.62169,5.56461,5.81827,5.51659,5.74784,5.74702,5.75548,5.75656,
d48e98217c,6.0022,6.34768,6.12579,5.75171,5.73556,5.71291,5.70819,5.6102,5.63073,5.63536,
3ec22ec406,5.52897,5.83105,5.56205,5.56693,5.4739,5.77148,5.50041,5.83386,5.50935,5.56336,
8d654d766b,5.52619,5.54123,5.58697,5.51069,5.56428,5.51821,5.52247,5.54335,5.56651,5.69354,
7c4fe7fde4,5.84559,5.49333,5.51967,5.5546,5.55506,5.55031,5.57315,5.54351,5.49781,5.51643,
4c61549ab7,5.54471,5.53491,5.51857,5.51855,5.50167,5.4926,5.5465,5.52279,5.5063,5.49116,
1608d33f35,5.90165,5.84593,5.70538,5.79748,5.62308,5.64043,5.61953,5.68406,5.67131,5.73448,
cdb912bee1,
04fdd31791,
12c71ba601,
10ddc737f4,5.85083,5.78355,5.85041,5.92612,5.78301,5.77045,5.49332,5.80334,5.69452,5.74935,
2a66de67ec,5.78572,5.80997,5.82202,5.70195,5.68828,5.62627,5.66791,5.69999,5.6731,5.66778,
```


And these ones are from a previous run:

```
fd4acd2d7f,6.20445,6.29559,6.79428,6.25553,6.12995,6.08228,6.11624,6.09591,6.18072,6.27612,
c1e933dfab,6.22338,6.2787,6.22096,6.19955,6.20069,6.12592,6.2,6.17187,6.19624,6.22021,
d647939227,6.39867,6.3475,6.33833,6.31728,6.3057,6.2983,6.23894,6.30223,6.26537,6.28364,
1a343b42a1,6.41426,6.38605,6.37848,6.34432,6.02915,6.35704,6.28731,6.33175,6.34239,6.27512,
c33c266d28,
0049b9bade,5.90196,5.98679,5.94273,5.82004,5.85217,5.89794,5.89774,5.84322,5.94328,5.90359,
af122df98a,5.83305,5.92135,5.84288,5.96176,5.94879,5.86527,5.89364,5.91096,5.83773,5.87481,
eac28e86c6,5.94731,5.68984,5.91775,5.6424,5.653,5.62593,5.5993,5.60971,5.65219,5.64358,
8c397f05f1,5.68871,5.65773,5.66777,5.69101,5.68613,5.7121,5.84615,5.62805,5.65102,5.67972,
b3424caba8,6.00843,5.98644,5.9208,5.78885,5.77123,5.78091,5.74916,5.71199,5.74254,5.80217,
6fe503bfca,5.96817,5.79899,5.90163,5.87365,5.88228,5.83768,5.82356,5.81356,5.82378,5.83671,
3f4741b5eb,5.67595,5.86009,5.77619,5.55366,5.60947,5.60378,5.90449,5.59113,5.78941,5.57963,
fd014ba50a,5.94306,5.90177,5.90369,5.84405,5.84246,5.87402,5.82353,5.82504,5.79514,5.78333,
ce664c79ff,5.91699,5.89954,5.80405,5.87857,5.82362,5.75903,5.79638,5.82482,5.84229,5.79763,
934f694d9a,5.8859,5.88746,5.82633,5.8631,5.82472,5.81228,5.79477,5.78246,5.77343,5.83162,
c56ce52a03,5.90624,5.80406,5.86197,5.86287,5.78506,5.81745,5.8463,5.52288,5.57283,5.53974,
c1f08bf395,5.92793,5.89182,5.80859,5.62541,5.5925,5.92943,5.63125,5.58106,5.58274,5.92938,
e75762429d,
e7be54cc39,
1e263504d2,
d15c1533b1,6.0064,5.92888,5.93643,5.92145,5.9146,5.89116,5.89742,5.89998,5.84736,5.85812,
57a9276247,5.96971,5.96347,5.90577,5.90212,5.86151,5.857,5.74837,5.90806,5.84892,5.86147,
```

**Comment by afabri** [comment]
I just gave it a try with changing the minimum size of 512 to 32 in the `chained_map.h`.   When I then do the intersection of `data/spheregrid.off` and `data/shiftedspheregrid.off` this is faster in master than in this branch.   I guess it needs more benchmarking, that is with more diverse data sets.     @GilesBathgate can you give it a try

**Comment by GilesBathgate** [comment]
@afabri I did give that a try a few times. But I couldn't measure any difference. I can have another attempt.

**Comment by GilesBathgate** [comment]
The benchmark I was using was RapCAD with the following script:

```scad
import <data/refined_elephant.off> as a;
import <data/cheese.off> as b;

intersection(){
  a();
  b();
}
```

That isn't very portable, but the results are very comparable to `./intersection data/refined_elephant.off data/cheese.off`

**Comment by afabri** [comment]
For which I have _10.89 sec_ for master, _10.46 sec_ for this branch, and _10.39 sec_ for master with 512 changed to 32.

**Comment by afabri** [comment]
And it look similar for the sphere grid intersected with a single sphere.

**Comment by GilesBathgate** [comment]
@afabri It's certainly a simpler change. But ideally, you want your table size to be as close to the number of elements you will insert into it so that it doesn't have to rehash all the values when the table grows.

**Comment by afabri** [comment]
It's not about if the change is simple or not.  Your starting point was performance (with the 512 * 512 of the `UHM<UHM<..>>`).  And with `512->32` so far the robin hood map is not faster.    
I am also wondering where you measure time.  If you also want the time  of the destructor the Nef polyhedron must be in a nested scope, that is    `Timer t;  t.start();  {   Nef_3 A,B;    ....   A.intersection(B) ; }  t.time(); }`.

**Comment by GilesBathgate** [comment]
@afabri it's odd. I was definitely noticing performance increases as I made each change. But as discovered some of those changes only seemed to work well speeding up the loading of the elephant, whilst negatively impacting the performance of the boolean operation. I think I got carried away with thinking "this should be faster" with too much variance in the results to verify "its actually measurably faster"

I made a graph to see which commits increase and which decrease:
image

According to this I should revert 3c5206e22b and  d48e9821 and the last 4 commits.
However when I do that, I find that the speed stays at 5.7 sec

**Comment by afabri** [comment]
Remember my "Hmmh, maybe I did something wrong....".  So your graph is for elephant/cheese?

**Comment by GilesBathgate** [comment]
> So your graph is for elephant/cheese?
No, I ran benchmark `./intersection` without arguments. (which does data/sphere.off  intersected with data/shiftedspheregrid.off)

**Comment by GilesBathgate** [comment]
I've converted this back to a draft for now. I'd like to get to the bottom of why theory and reality don't match up. It seems like for an Identity hash function, Unique_hash_map has a very fast implementation. There is also https://github.com/Tessil/robin-map for which the authors say
>Use the prime version if there is a chance of repeating patterns in the lower bits of your hash (e.g. you are storing pointers with an identity hash function). See GrowthPolicy for details.

Things to try:
* Tessil/robin-map
* Hash the address for more random keys?
* Can reserve be added to Unique_hash_map?
* More representative data for https://github.com/GilesBathgate/hashmap-benchmarks ?

**Pull request closed without merging**
