### PR TITLE
force convertion to exact number type (avoid ambiguous call to cmp opera...

### PR DESCRIPTION
**Pull request by sloriot**
...tors)

### CODE REVIEW

**Comment by lrineau** [comment]
Is that for CGAL-4.6.1? How can we test that patch? `integration`? Should we create an `integration-4.6` branch?

**Comment by sloriot** [comment]
Without this patch, it does not compile on my machine while not using GMP. So the pb should appear in master as soon as the leda platform is back for example.

**Comment by lrineau** [comment]
I have merged it in `integration` for CGAL-4.7-Ic-7.

**Comment by lrineau** [comment]
[CGAL-4.7-Ic-7][7] was a bad internal release. I have remerged for testing in [CGAL-4.7-Ic-8][8] tonight.

[7]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-7.shtml
[8]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-8.shtml

**Pull request merged**
