### PR TITLE
Add keep_large_connected_components ()

### PR DESCRIPTION
**Pull request by afabri**
Add a function that keeps components with a number of faces above a threshold.

I added code, doc, and a test

### CODE REVIEW

**Comment by sloriot** [comment]
Looks like the commit contains the fix in #407

**Comment by sloriot** [comment]
Could you write a small feature ? For the API, [this link](https://github.com/CGAL/cgal/pull/408/files#diff-94686afc34baa7869fd62c8cc899db7c) is sufficiently clean to not duplicate the doc in the page.

**Comment by afabri** [comment]
That is where I discovered the bug.

Will it cause a merge coflict later?

**Comment by afabri** [comment]
done

On 08/10/2015 18:12, Sebastien Loriot wrote:
> Could you write a small feature ? For the API, this link
> <https://github.com/CGAL/cgal/pull/408/files#diff-94686afc34baa7869fd62c8cc899db7c>
> is sufficiently clean to not duplicate the doc in the page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/pull/408#issuecomment-146596032>.
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by sloriot** [comment]
`Changes.html` should be updated

**Comment by afabri** [comment]
done and pushed to mine

On 08/10/2015 21:11, Sebastien Loriot wrote:
> |Changes.html| should be updated
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/pull/408#issuecomment-146658930>.
>

-- 
Andreas Fabri, PhD
Chief Officer, GeometryFactory
Editor, The CGAL Project

phone: +33.492.954.912    skype: andreas.fabri

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by afabri** [comment]
passes the testsuite

**Pull request merged**
