### PR TITLE
Bugfix in Buffer_for_vao.h

### LINKED ISSUE #4380: Simple Viewer:  wrong type
## Issue Details

[Here ](https://github.com/CGAL/cgal/blob/master/GraphicsView/include/CGAL/Buffer_for_vao.h#L74)  `Local_point` should probably be `Local_kernel_point_3`.

### PR DESCRIPTION
**Pull request by gdamiand**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Bug fix; solves issue #4380.

## Release Management

* Affected package(s): GraphicsView
* Issue(s) solved (if any): fix #4380

### CODE REVIEW

**Comment by lrineau** [comment]
"Bugfix": if the bug was already in 4.14.2 or 5.0, then the PR should be against the corresponding release branch.

**Comment by gdamiand** [comment]
Replaced by #4383 to be integrated in CGAL 5.0.

**Comment by sloriot** [comment]
Note that you did not need to close this PR. If you click on `Edit` at the bottom, you can change the base of the PR. Then do a forced-pushed after the rebase of the branch and you'll be in the wanted state :)

**Comment by gdamiand** [comment]
Thanks @sloriot ; I will try to remember that for the next time ;)

**Pull request closed without merging**
