### PR TITLE
Replaced boost::(bind|bind2nd) with lambdas

### PR DESCRIPTION
**Pull request by rathod-sahaab**
## Summary of Changes
Implementation only
This branch aims to replace binds with lambdas where possible. 

[@lrineau 's comment](https://github.com/CGAL/cgal/pull/1449#pullrequestreview-722195)

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-33.shtml.

**Comment by lrineau** [comment]
Ping @sloriot This PR is waiting for you approval.

**Comment by sloriot** [comment]
I'm not a big fan of the `auto lesser = Traits::less_x`. I have a branch where I started to remove all the `bind` across CGAL but I have been over optimistic as there are a lot.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-41.shtml

**Comment by lrineau** [comment]
> I'm not a big fan of the `auto lesser = Traits::less_x`. I have a branch where I started to remove all the `bind` across CGAL but I have been over optimistic as there are a lot.

Should not we extract the patch for AABB tree from that branch?

**Comment by lrineau** [comment]
@sloriot We could use [`modernize-avoid-bind`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-bind.html) from clang tidy, to help that process.

**Comment by lrineau** [comment]
Replaced by https://github.com/CGAL/cgal/pull/5152.

**Pull request closed without merging**
