### PR TITLE
CGAL: Move from CGAL/internal  to CGAL/Pkg/internal

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Move internal header files.  @gdamiand  can I do this for Generalized map?

## Release Management

* Affected package(s): Surface_mesh_segmentation, Periodic_*
* TODO wiki: update guidelines after merge

### CODE REVIEW

**Comment by gdamiand** [comment]
Yes of course (as well as for Combinatorial maps). Thanks.

**Comment by lrineau** [comment]
https://travis-ci.org/CGAL/cgal/jobs/546852372#L2816
```
In file included from /home/travis/build/CGAL/cgal/Classification/examples/Classification/example_mesh_classification.cpp:12:
In file included from /usr/local/include/CGAL/Classification.h:26:
/usr/local/include/CGAL/Classification/classify.h:27:10: fatal error: 
      'CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h' file
      not found
#include <CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://travis-ci.org/CGAL/cgal/jobs/546852390
```
In file included from /home/travis/build/CGAL/cgal/Periodic_3_mesh_3/examples/Periodic_3_mesh_3/mesh_implicit_shape_with_features.cpp:7:
/usr/local/include/CGAL/Periodic_3_mesh_triangulation_3.h:34:10: fatal error: 
      'CGAL/internal/Robust_periodic_weighted_circumcenter_traits_3.h' file not
      found
#include <CGAL/internal/Robust_periodic_weighted_circumcenter_traits_3.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

https://travis-ci.org/CGAL/cgal/jobs/546852391
```
In file included from /home/travis/build/CGAL/cgal/Periodic_4_hyperbolic_triangulation_2/examples/Periodic_4_hyperbolic_triangulation_2/p4ht2_example_insertion.cpp:1:
/usr/local/include/CGAL/Hyperbolic_octagon_translation.h:26:10: fatal error: 
      'CGAL/Periodic_4_hyperbolic_triangulation_2/internal/Hyperbolic_octagon_translation_matrix.h'
      file not found
  ...<CGAL/Periodic_4_hyperbolic_triangulation_2/internal/Hyperbolic_octagon_translation_matrix.h>
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by maxGimeno** [comment]
```
/home/travis/build/CGAL/cgal/Surface_mesh_segmentation/test/Surface_mesh_segmentation/Expectation_maximization_test.cpp:2:10: fatal error: 
      'CGAL/internal/Surface_mesh_segmentation/Expectation_maximization.h' file
      not found
#include <CGAL/internal/Surface_mesh_segmentation/Expectation_maximization.h>
```
```/usr/local/include/CGAL/Hyperbolic_octagon_translation.h:26:10: fatal error: 
      'CGAL/Periodic_4_hyperbolic_triangulation_2/internal/Hyperbolic_octagon_translation_matrix.h'
      file not found
  ...<CGAL/Periodic_4_hyperbolic_triangulation_2/internal/Hyperbolic_octagon_translation_matrix.h>
```
```
/usr/local/include/CGAL/Periodic_3_mesh_triangulation_3.h:34:10: fatal error: 
      'CGAL/internal/Robust_periodic_weighted_circumcenter_traits_3.h' file not
      found
#include <CGAL/internal/Robust_periodic_weighted_circumcenter_traits_3.h>
```
```
CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h' file
      not found
#include <CGAL/internal/Surface_mesh_segmentation/Alpha_expansion_graph_cut.h>
```

**Comment by lrineau** [comment]
And there is also:
https://travis-ci.org/CGAL/cgal/jobs/546852364#L7199
```
/home/travis/build/CGAL/cgal/Installation/../Periodic_3_mesh_3/include/CGAL/Periodic_3_function_wrapper.h:26:10: fatal error: 'CGAL/internal/canonicalize_helper.h' file not found
#include <CGAL/internal/canonicalize_helper.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by afabri** [comment]
@mglisse can I do the same for internal/Triangulation ?

**Comment by sloriot** [comment]
@afabri  you don't have to ask to every maintainer. It is a choice that has been approved years ago and we should do it consistently for all packages.

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Jun 18, 2019, 10:57 AM GMT+2](https://github.com/CGAL/cgal/pull/4009#issuecomment-503013596 "2019-06-18T08:57:21Z - Replied by Github Reply Comments"):
> @afabri  you don't have to ask to each maintainer. It is a choice that has been approved years ago and we should do it consistently for all packages.

Please give pointers to that decision, because I disagree.

And I certainly do not want that for CGAL-5.0, to avoid yet another source of conflict with the branch for CGAL-4.14.

**Comment by lrineau** [comment]
I disagree to apply that blindly to former packages. I agree that is a good choice for new packages, or new features.

**Comment by afabri** [comment]
My motivation for this PR is Issue #257

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Jun 18, 2019, 11:37 AM GMT+2](https://github.com/CGAL/cgal/pull/4009#issuecomment-503028457 "2019-06-18T09:37:20Z - Replied by Github Reply Comments"):
> My motivation for this PR is Issue #257

The issue #257 is about namespaces, and not header paths.

And, anyway, if you want to solve issue #257, start cleaning `CGAL::internal::` in Kernel_23 and Filtered_kernel.

**Comment by mglisse** [comment]
> @mglisse can I do the same for internal/Triangulation ?

Yes, once y'all agree on what should be done.

**Comment by MaelRL** [comment]
This should also change https://doc.cgal.org/latest/Manual/devman_namespaces.html for consistency.

**Comment by sloriot** [comment]
PING @afabri

**Comment by MaelRL** [comment]
I also have a local branch where I have started working on what the issue was actually stipulating, which is putting code in CGAL::pkg::internal (rather than CGAL::internal or CGAL::internal::pkg), rather than what this PR is doing, which is actually moving files.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.4-Ic-38.
Doc error fixed by the latest commit, locally tested with doxygen master + doxygen 1.8.13.

**Comment by sloriot** [comment]
Guidelines updated in d8510d0fd39e7a100d5e8c1e36d5d698906ffef2

**Pull request merged**
