### PR TITLE
Patch usage of BUILD_TESTING to handle the case that CGAL is a subproject

### PR DESCRIPTION
**Pull request by puneetmatharu**
## Summary of Changes

Solves issue [#7121](https://github.com/CGAL/cgal/issues/7121).

Currently, CGAL overrides the `BUILD_TESTING` CMake variable. As is, if CGAL is pulled in as a subproject (without setting `BUILD_TESTING`), it will cause tests in parent projects to also be disabled. I have changed the name of this variable to `CGAL_ENABLE_TESTING` to be project-specific. 

In Scott Craig's book ["Professional CMake: A Practical Guide"](https://crascit.com/professional-cmake/), he states that it is best to avoid explicitly setting `BUILD_TESTING` in case the project is being consumed as a subproject:

```text
31.2. Don’t Assume A Top Level Build

...

Another common problem is modifying variables that have the potential to affect the whole build,
not just the project. A classic example is forcing the value of cache variables like BUILD_SHARED_LIBS,
BUILD_TESTING, CMAKE_BUILD_TYPE, CMAKE_MODULE_PATH or CMAKE_RUNTIME_OUTPUT_DIRECTORY. Using the FORCE
or INTERNAL keywords with the set() command on these variables prevents a parent project from
overriding that choice. Quite often, these variables shouldn’t be defined by the project as cache
variables at all, and maybe shouldn’t even be set by the project to begin with. For variables like
CMAKE_MODULE_PATH, append to existing values rather than replace them.
```

## Release Management

* Issue(s) solved (if any): fix [#7121](https://github.com/CGAL/cgal/issues/7121)
* Feature/Small Feature (if any): N/A
* Link to compiled documentation (obligatory for small feature): *Not run.*
* License and copyright ownership: [REUSE Compliance Check](https://github.com/puneetmatharu/cgal/actions/workflows/reuse.yml)
* [Link to triggered GitHub workflows](https://github.com/puneetmatharu/cgal/actions)

### CODE REVIEW

**Comment by puneetmatharu** [comment]
@lrineau here is the PR, as per your request in https://github.com/CGAL/cgal/issues/7121.

**Review by lrineau — APPROVED** [review]

**Comment by lrineau** [comment]
Thanks @puneetmatharu 

@sloriot I think this PR is ready to be tested. The only reserve I have is about the needed changes to `Scripts/developer_scripts/run_testsuite_with_ctest`:

https://github.com/CGAL/cgal/pull/7845/files#diff-c4688d05e1fdb810fb3c3410acfdedc7a188a0b424aec7d8ce638921a4e97234

But I think that script is called from `autotest_cgal_with_ctest` and found in the internal release itself. That should work.

**Comment by afabri** [comment]
No need to backport to the bug fix branch?

**Comment by lrineau** [comment]
> No need to backport to the bug fix branch?

I do not think so. It is a bug-fix because it does fix a bug report. But the scenario that is fixed is not mainstream (though it seems to be used more and more in the CMake ecosystem). And at the same time that is a small breaking change, because the name of the CMake option (in `CMakeCache.txt` and CMake GUI) changes. It seems right to make the change in `master` only (targeting CGAL-6.0).

**Comment by sloriot** [comment]
Testsuite showed that for docker `BUILD_TESTING=ON` should imply `CGAL_BUILD_TESTING=ON` (and it also seems reasonable).

**Comment by lrineau** [comment]
@puneetmatharu We tested this PR last night, and the result were not great:
https://cgal.geometryfactory.com/CGAL/testsuite/results-6.0-Ic-104.shtml

All those blue columns are because `-DBUILD_TESTING=ON` was passed to the CMake command line, but not `-DCGAL_BUILD_TESTING=ON`.

We could "fix" that, in our test scripts, but I think there might have other users of CGAL using `BUILD_TESTING` (in particular I think about the various CGAL packages in package managers). I think that one should add a compatibility: the default value of `CGAL_BUILD_TESTING` should be the value of `BUILD_TESTING`.

According to the [documentation of the CMake `option` command][doc], the default value can be empty. That is why I suggest to define `CGAL_BUILD_TESTING` that way:

```cmake
option(CGAL_ENABLE_TESTING "Build the testing tree." ${BUILD_TESTING})
```

If `BUILD_TESTING` is undefined, then it will evaluate to an empty value, and the default value of `CGAL_BUILD_TESTING`, according to [the documentation][doc], will be `OFF`.

[doc]: https://cmake.org/cmake/help/latest/command/option.html

**Comment by puneetmatharu** [comment]
> @puneetmatharu We tested this PR last night, and the result were not great: https://cgal.geometryfactory.com/CGAL/testsuite/results-6.0-Ic-104.shtml
> 
> All those blue columns are because `-DBUILD_TESTING=ON` was passed to the CMake command line, but not `-DCGAL_BUILD_TESTING=ON`.
> 
> We could "fix" that, in our test scripts, but I think there might have other users of CGAL using `BUILD_TESTING` (in particular I think about the various CGAL packages in package managers). I think that one should add a compatibility: the default value of `CGAL_BUILD_TESTING` should be the value of `BUILD_TESTING`.
> 
> According to the [documentation of the CMake `option` command](https://cmake.org/cmake/help/latest/command/option.html), the default value can be empty. That is why I suggest to define `CGAL_BUILD_TESTING` that way:
> 
> ```cmake
> option(CGAL_ENABLE_TESTING "Build the testing tree." ${BUILD_TESTING})
> ```
> 
> If `BUILD_TESTING` is undefined, then it will evaluate to an empty value, and the default value of `CGAL_BUILD_TESTING`, according to [the documentation](https://cmake.org/cmake/help/latest/command/option.html), will be `OFF`.

I absolutely agree -- this is an oversight on my side. Thank you for spotting and raising this. I have changed my code accordingly.

**Comment by puneetmatharu** [comment]
Brilliant, thank you.

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-116

**Pull request merged**
