### PR TITLE
Try to use LEDA without -ffriend-injection

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

According to @maxGimeno's tests, leda-numbers can be used without `-ffriend-injection`. Let's try that.

That will remove [warnings about `-ffriend-injection` being deprecated with recent gcc][1].

[1]: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.14-I-53/AABB_tree/TestReport_lrineau_Fedora-with-LEDA.gz

## Release Management

* Affected package(s): Installation, Number_types 

Cc: @afabri

### CODE REVIEW

**Comment by lrineau** [comment]
I have rebased the patch to `releases/CGAL-4.12-branch`, to clean the warnings of all our testsuites.

**Comment by maxGimeno** [comment]
The branch i used for my tests is the one pointed by @afabri, in which he changed some things. So only removing the flag and not using that version of LEDA might lead to errors.

**Comment by maxGimeno** [comment]
Do we want to fix the errors and warnings revealed by the removal of ffriend-injection or not?

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Dec 4, 2018, 3:55 PM GMT+1](https://github.com/CGAL/cgal/pull/3482#issuecomment-444128081 "2018-12-04T14:55:07Z - Replied by Github Reply Comments"):
> Do we want to fix the errors and warnings revealed by the removal of ffriend-injection or not?

The removal of `-ffriend-injection` has not revealed anything. What has changed is the addition of `-DCGAL_USE_LEDA`, by PR #3501. I think we should do the work in #3501.

**Pull request merged**
