### PR TITLE
Allow Mesh_3 to cope with a 2D initial triangulation

### PR DESCRIPTION
**Pull request by lrineau**
## Summary of Changes

In Mesh_3, the initial triangulation after the initialization was assumed with `dimension() == 3`. But, if the input domain is completely coplanar then the initial triangulation can only have `dimension() == 2`. This PR:
  - enables the first stage of Mesh_3 to deal with a 2D triangulation,
  - and adds 3D far points unconditionally, to ensure that the triangulation is 3D for the next stages.

## Release Management

* Affected package(s): Mesh_3
* License and copyright ownership: maintenance by GeometryFactory

### CODE REVIEW

**Comment by maxGimeno** [comment]
Errors in travis

**Comment by MaelRL** [comment]
Fixes https://github.com/CGAL/cgal/issues/866 ?

**Comment by maxGimeno** [comment]
```
  CMake Error at Mesh_3/examples/Mesh_3/CMakeLists.txt:140 (endforeach):
  endforeach An ENDFOREACH command was found outside of a proper FOREACH
  ENDFOREACH structure.  Or its arguments did not match the opening FOREACH
  command.
```

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Aug 19, 2019, 4:09 PM GMT+2](https://github.com/CGAL/cgal/pull/4157#issuecomment-522592257 "2019-08-19T14:09:35Z - Replied by Github Reply Comments"):
> ```
>   CMake Error at Mesh_3/examples/Mesh_3/CMakeLists.txt:140 (endforeach):
>   endforeach An ENDFOREACH command was found outside of a proper FOREACH
>   ENDFOREACH structure.  Or its arguments did not match the opening FOREACH
>   command.
> ```

Wouah. Sorry for that one. I have probably messed up the CMake code in a rebase and forgot to retest. It should be fine on the next run of Travis.

**Comment by sloriot** [comment]
Successfully tested in [CGAL-5.0-Ic-122](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-122.shtml)

(Up to this [error](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-122/Mesh_3/TestReport_lrineau_ArchLinux-clang-Release.gz) that I don't think is related to this PR)

**Pull request merged**
