### PR TITLE
Aos 2 sweep efif

### PR DESCRIPTION
**Pull request by efifogel**
This fixes a bug in the sweep line code.
It addresses issue #1272 (Assertion/precondition violation using aggregated insert into CGAL::Arrangement_2).

### CODE REVIEW

**Comment by efifogel** [comment]
Eventually, the changes were not that massive.
Most of the changes were in the code that helps debugging.
The real fix itself was 5 lines.

**Comment by sloriot** [comment]
@efifogel great you find a solution for it. Maybe you should add the test failing in the testsuite?

**Comment by sloriot** [comment]
@efifogel Shouldn't this patch target 4.9.1?

**Comment by efifogel** [comment]
1. Yes, it can target 4.9
2. I'll add tests later. I'm collecting a few...

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by efifogel** [comment]
I meant 4.9.1

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
@efifogel I've rebased the branch onto the 4.9 branch. To add new commits to this branch you'll need to reset your local branch first. Something like:
```
> git fetch  mine
> git checkout Aos_2-sweep-efif
> git reset --hard mine/Aos_2-sweep-efif
```

**Comment by lrineau** [comment]
Efi, I just pushed a new commit https://github.com/CGAL/cgal/pull/1487/commits/c9e1f7e746829081b2444d2a1884eb235e5febb3 in this PR, because the modifications you made in Arr_2 exposed a bug in the Qt demo: a conflict between Qt defining `foreach` as a macro, and some Boost headers.

**Comment by lrineau** [comment]
Efi, you can now remove your branch from your fork.

**Comment by efifogel** [comment]
Thanks.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Pull request merged**
