### PR TITLE
Polyhedron demo: fix camera presets

### PR DESCRIPTION
**Pull request by maxGimeno**
- The preset camera positions are now centered on the revolveAroundPoint of
  the camera, which makes it right when the item is not centered in the scene.

### CODE REVIEW

**Comment by lrineau** [comment]
I confirm the six preset buttons work well with this pull-request.

**Comment by sloriot** [comment]
Merged in [CGAL-4.8-ic-15](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-15.shtml)

**Comment by lrineau** [comment]
Maxime and I agreed that there is still something fishy with that code. Please hold it, until Maxime has a better fix.

**Comment by maxGimeno** [comment]
It is not the one. The problem is in the Axis branch.

2015-10-08 16:27 GMT+02:00 Laurent Rineau <notifications@github.com>:

**Comment by sloriot** [comment]
Which is merged AFAIK

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.8-Ic-19][t].

[t]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-19.shtml

**Comment by maxGimeno** [comment]
I didn't see any error/warning that could have been caused by this PR, I think it can be merged.

**Pull request merged**
