### PR TITLE
Polyhedron_demo: Degenerated_faces_plugin

### LINKED ISSUE #2177: Selecting degenerate faces and edges
In the demo, it would be nice to be able so select degenerate faces or degenerate edges (I mean in a selection item so that we can manipulate them).

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Add Degenerated_faces_plugin. It puts degenerated triangle faces in a selection_item.

## Release Management

* Affected package(s):Polyhedron_demo
* Issue(s) solved (if any): fix #2177

### CODE REVIEW

**Comment by sloriot** [comment]
It works great for degenerate faces. I can't find how to select degenerate edges. Did you forget it?

**Comment by maxGimeno** [comment]
Erf, yes I did

**Comment by maxGimeno** [comment]
Done.

**Comment by sloriot** [comment]
Works great. Thanks!

**Pull request merged**
