### PR TITLE
Tetrahedral remeshing - add edge flips on surfaces

### PR DESCRIPTION
**Pull request by janetournois**
## Summary of Changes

This PR introduces edge flips on surfaces in the tetrahedral remeshing pipeline.

It improves the minimal dihedral angles of the input, and the visual aspect of the surface, since it decreases the number of vertices with valence != 6 on surfaces.

## Release Management

* Affected package(s): Tetrahedral_remeshing
* License and copyright ownership: unchanged

### CODE REVIEW

**Comment by janetournois** [comment]
let's postpone it, it will not be ready before the release

**Comment by sloriot** [comment]
Same question as for 5.5, shall we postpone it to 5.7?

**Comment by janetournois** [comment]
yes? I postponed it

**Comment by janetournois** [comment]
At this state, here are the results of the example `mesh_and_remesh_polyhedral_domain_with_features.cpp`

Before remeshing :
image

After remeshing, with flips on surfaces :
image

**Comment by janetournois** [comment]
This PR is ready to be tested

**Comment by sloriot** [comment]
Successfully tested in CGAL-6.0-Ic-176

**Pull request merged**
