### PR TITLE
[Arrangement] Fix polycurve overlap intersection

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

When computing the intersection of two polycurves, there is a specific case that creates a wrong output: when 2 polycurves oriented right-to-left overlap, the output is wrongly oriented left-to-right. This makes boolean operations fail if the polyline traits is used instead segment traits.

This PR fixes this problem by inverting the output overlap polycurve in both curves are detected as right-to-left oriented. A test is also added to check this.

## Release Management

* Affected package(s): Arrangement and derivated packages (Boolean Operations, etc.)
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/4998

### CODE REVIEW

**Comment by lrineau** [comment]
As it is a bug-fix, I have to ask: why have you based the patch on `master`, instead of an existing release branch?

**Comment by sgiraudot** [comment]
Because `Arrangement` changed quite a lot since the latest releases, there are already 2 PRs which I originally based on a release branch and which I ended up rebasing on master because it was creating too many conflicts with master, so I thought it'd be safer to do it directly on master.

**Comment by sgiraudot** [comment]
Yet again, it's possible that the section I have changed has not been modified too much since latest releases, let me check and rebase if it's trivial.

**Comment by sgiraudot** [comment]
Alright, it's rebased on 5.1 (5.0 created conflicts as I expected).

**Comment by maxGimeno** [comment]
warnings : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-31/Arrangement_on_surface_2/TestReport_gimeno_Fedora-rawhide.gz

**Comment by maxGimeno** [comment]
Warnings: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-35/Arrangement_on_surface_2_Demo/TestReport_gimeno_Fedora-rawhide.gz

and maybe an error, see #4939

**Comment by efifogel** [comment]
Fixed the warning.
(I don't see an error, but if there is one, it's related to a different PR.)
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by lrineau** [comment]
> Fixed the warning.

You forgot to push in the branch of the PR.

**Comment by efifogel** [comment]
ops, I've done it to the right branch now.
@Simon, as far as I'm concerned, you can completely remove the branch on
cgal-public-dev
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Travis says it doens't work : 
```
78/368 Test #1319: test_traits_circular_arc_polycurve__data_Polycurves_circular_arcs_intersect__polycurve_circular_arc_traits .............................***Failed    0.01 sec
Performing test: traits type is polycurve_circular_arc_traits, input files are data/Polycurves_circular_arcs/points data/Polycurves_circular_arcs/xcurves data/Polycurves_circular_arcs/curves data/Polycurves_circular_arcs/intersect

case number : 1
Test: intersect( 2 (0/1 0/1 1/1 -1) [-1 0 --> 1 0] (3/1 0/1 4/1 -1) [1 0 --> 5 0],3 (0/1 0/1 1/1 -1) [-1 0 --> 1 0] (3/1 0/1 4/1 -1) [1 0 --> 5 0] (10/1 0/1 25/1 -1) [5 0 --> 15 0] ) ? Passed
case number : 2
Test: intersect( 2 (6/1 0/1 1/1 -1) [5 0 --> 7 0] (8/1 0/1 1/1 -1) [7 0 --> 9 0],2 (8/1 0/1 1/1 1) [9 0 --> 7 0] (6/1 0/1 1/1 1) [7 0 --> 5 0] ) ? Expected x-monotone curve: 2 (6/1 0/1 1/1 -1) [5 0 --> 7 0] (8/1 0/1 1/1 -1) [7 0 --> 9 0]
Obtained x-monotone curve: 2 (6/1 0/1 1/1 1) [7 0 --> 5 0] (8/1 0/1 1/1 1) [9 0 --> 7 0]
Failed
```
and 
```
102/368 Test #1345: test_traits_non_caching_polylines__data_polylines_intersect__non_caching_polyline_traits ...............................................***Failed    0.09 sec
Performing test: traits type is non_caching_polyline_traits, input files are data/polylines/intersect.pt data/polylines/intersect.xcv data/empty.zero data/polylines/intersect
```

**Comment by sgiraudot** [comment]
@efifogel the error seems to come from https://github.com/CGAL/cgal/pull/5091/commits/3f623d99dfef76e52d233e72435b5594242a84d6, if I revert it (and the latest one where you fixed the warning), then the testsuite passes without error. But I'm not sure removing it is the right thing to do. Would you have a clear idea how to fix this?

**Comment by efifogel** [comment]
Got it & fixed it.
If the resulting overlapping curve is directed left=>right (! invert_ocv),
the subcurves of the resulting curve must also be directed left=>right
The condition above may be violated with traits classes (of the subcurves)
that their intersection operator does not conform to the following
behaviour:

Let c1 and c2 be 2 input curves that overlap.
If both are directed right=>left, then their intersection curve is directed
right=>left.
In all other 3 cases the overlapping curve is directed left=>right.

Observe that the above behaviour is not mandatory.
According to the spec, if c1 and c2 have opposite directions the direction
of their intersection curve is nondeterministic.

This imposes a small difficulty when dealing with polylines or polycurves
(which rely on the traits of their subcurves).
We established an invariant that follows the behaviour above regardless of
the subcurve traits (for a good reason).
Therefore, we need to check and possibly "fix" the direction for those
traits that do not conform.

I'm outlining all this, mainly because this test could be avoided, if the
behaviour above is enforced on all traits.
Currently, the Arr_segment_traits_2 and Arr_non_caching_segment_traits_2
already conform, because they are based on the Kernel intersection functor,
which conforms.
The Arr_circle_segment_traits_2 traits does not. (This is how the bug was
detected.)
The rest, I don't know.

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Errors again : https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.2-Ic-38/Arrangement_on_surface_2/TestReport_lrineau_Ubuntu-Latest-CXX11.gz

**Comment by efifogel** [comment]
grrrr, fixed.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.2-Ic-41.shtml

**Pull request merged**
