### PR TITLE
[Small Feature] Surface Mesh PLY IO

### PR DESCRIPTION
**Pull request by sgiraudot**
## Rationale

The PLY format has 3 main advantages:
- it can embed any type of item that can be described by a sequence of numbers, and is in particular widely used by geometry processing software to store point sets and meshes
- it can read/write binary files, which is more efficient than parsing ASCII
- it can embed any property the user wants, which makes it very powerful especially when plugged-in to the `Surface_mesh` dynamic property maps.

The `Point_set_3` class (which is very similar to `Surface_mesh`) already uses this format to save and load point sets with properties. This small feature adds similar IO functions for `Surface_mesh`.

## Summary of API changes

- Methods `CGAL::read_ply()` and `CGAL::write_ply()` are added to the `Surface_mesh` package, following the same terminology as the existing `CGAL::read_off()` and `CGAL::write_off()` functions.
- An extra parameter is provided for the PLY IO functions of `Point_set_3` to load/save the comments embedded in the PLY header (the same parameter is put in the 2 new `Surface_mesh` functions described above).

## License and copyright ownership

(no change)

## CHANGES.md

TODO

## Status

-   Developed and locally tested (GNU/Linux)
-   (Empty) small feature page: [Surface Mesh PLY IO](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Surface_Mesh_PLY_IO)

## Submission

* [`CGAL::read_ply()`](https://cgal.geometryfactory.com/~sgiraudot/Surface_mesh-PLY/Surface_mesh/group__PkgSurface__mesh.html#ga42f6ad486ddab74e13d3dc53f511c343): new surface mesh reading function
* [`CGAL::write_ply()`](https://cgal.geometryfactory.com/~sgiraudot/Surface_mesh-PLY/Surface_mesh/group__PkgSurface__mesh.html#ga77bbb79d449c981895eedb6c3c23bd14): new surface mesh writing function
* [`CGAL::read_ply_point_set()`](https://cgal.geometryfactory.com/~sgiraudot/Surface_mesh-PLY/Point_set_3/group__PkgPointSet3IO.html#ga0d80f23b142818bba05869ee1bfc8c41): new documentation for point set reading function
* [`CGAL::write_ply_point_wet()`](https://cgal.geometryfactory.com/~sgiraudot/Surface_mesh-PLY/Point_set_3/group__PkgPointSet3IO.html#ga4dafa5ad1b9a33b84ad3467510791875): new documentation for pont set writing function

### CODE REVIEW

**Comment by sloriot** [comment]
@sgiraudot what is the status of this PR? There are still conflicts :)

**Comment by afabri** [comment]
@maxGimeno ready for testing.

**Comment by maxGimeno** [comment]
Conflicts (probably with #3355 ).

**Comment by afabri** [comment]
@maxGimeno where do you see conflicts???

**Comment by sloriot** [comment]
with #3355 while merging in integration I guess

**Comment by maxGimeno** [comment]
> @maxGimeno where do you see conflicts???

>probably with #3355

**Comment by sgiraudot** [comment]
I fixed the conflicts. I also changed the way UV values are handled in the parameterization and engrave text plugins, using 2 simple properties of type `float` (instead of 1 property of type `std::pair<float,float>`): this makes it straightforward to save/load with the PLY format.

**Comment by maxGimeno** [comment]
Execution errors:  https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-21.shtml#Surface_mesh

**Comment by sgiraudot** [comment]
Sorry, that was a stupid assertion... It's fixed.

**Comment by maxGimeno** [comment]
Warning in doc : 
/home/cgal-testsuite/cgal_doc_build/CGAL-5.0-Ic-22/include/CGAL/Surface_mesh/Surface_mesh.h:2183: warning: found multiple \relates, \relatesalso or \memberof commands in a comment block, using last definition

**Comment by maxGimeno** [comment]
Successfully testsed in [Ic-29](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-29.shtml)

**Comment by lrineau** [comment]
I am merged this PR, but it seems it forgot to modify the `CHANGES.md`.

**Pull request merged**
