### PR TITLE
Polyhedron: object generator tetrahedron -added line entry UI and logic

### PR DESCRIPTION
**Pull request by PriyanshJalan**
## Summary of Changes

Make it possible to have a multi line entry for tetrahedra (like points or polylines) instead of tedious point-by-point

## Release Management

* Affected package(s): Polyhedron_3
* Issue(s) solved (if any): partial fix of #6690
image

### CODE REVIEW

**Comment by PriyanshJalan** [comment]
image

**Comment by afabri** [comment]
I get the following warning with VC2022 locally:
````
Automatic MOC for target basic_generator_plugin
2>Generating Basic_generator_plugin.moc
2>Generating ui_Basic_generator_widget.h
2>C:\GitHub\cgal\Polyhedron\demo\Polyhedron\Plugins\PCA\Basic_generator_widget.ui : warning : The name 'tetraTab' (QWidget) is already in use, defaulting to 'tetraTab1'.
2>C:\GitHub\cgal\Polyhedron\demo\Polyhedron\Plugins\PCA\Basic_generator_widget.ui : warning : The name 'tetraTab' (QWidget) is already in use, defaulting to 'tetraTab2'.
2>Building Custom Rule C:/GitHub/cgal/Polyhedron/demo/Polyhedron/Plugins/PCA/CMakeLists.txt
2>Basic_generator_plugin.cpp
````

**Comment by afabri** [comment]
@PriyanshJalan can you replace the first image with the second one. You can Edit by pressing on the ....

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-216

**Pull request merged**
