### PR TITLE
I/O plugin for c3t3 meshes

### PR DESCRIPTION
**Pull request by maxGimeno**
- This is a fix for #46
- Addition of an IO plugin for the c3t3 meshes. The function try_load_other_binary_format() has been
  commented because it generates a compilation error that I couldn't fix.

### CODE REVIEW

**Comment by janetournois** [comment]
it would be nice that this plugin also offers the <code>.mesh</code> file extension (ASCII).

The "save as .mesh" operation is already implemented in Scene_c3t3_item but should be moved to this plugin

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-53

**Comment by sloriot** [comment]
From what I understand this adds the ability to write `.mesh`, `.cgal` and `.ma` but only the ability to read `.cgal`.
@janetournois @lrineau : could you please confirm ? If so does the missing loaders exists in CGAL code?

**Comment by lrineau** [comment]
I confirm.

I do not know any way to "load" an existing non-Delaunay and/or non-convex mesh into CGAL triangulations. We do not have any code for that.

**Comment by janetournois** [comment]
+1

**Comment by sloriot** [comment]
@maxGimeno There is an error on [this platform](https://cgal.geometryfactory.com/CGAL/Members/testsuite/CGAL-4.8-Ic-53/Polyhedron_Demo/TestReport_afabri_x64_Cygwin-Windows8_MSVC2013-Release-32bits.gz).

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-55

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-56

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-57

**Pull request merged**
