### PR TITLE
Improve create_internal_release

### LINKED ISSUE #615: Issues with the new `developer_scripts/create_internal_release`
I have several issues with the PR #542, already merged into `master`.

## runtime errors
Since it is in the internal releases, I have messages during the release creation:
```
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous errors
tar: ./include/**.h: Not found in archive
tar: Exiting with failure status due to previous error
```

The reason is the following lines:
```perl
    @filelistcmd = ('tar', '-tf', "$RELEASEDIR/temppack.tar", '--wildcards', "./include/\*\*.h",
                    "--transform=s/.\\\/include\\\///", '--show-transformed-names',
                    '--exclude=**/internal', "--index-file=/tmp/$package_name.txt");
    system(@filelistcmd);
```

## usage of `/tmp`

The new version of the script uses `/tmp/` with fixed names. That is highly unsecured on most Linux systems. The script should use:
```shell
TMP_DIR=`mktemp -dq /tmp/${0##*/}.XXXXXX`
```
or the perl equivalent, use sub-directories of `$TMP_DIR`, and remove that directory at the end in a trap function.

### PR DESCRIPTION
**Pull request by bo0ts**
Fixes #615

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-101

**Comment by sloriot** [comment]
There is this warning now: `Name "main::exit" used only once: possible typo at ./create_internal_release line 170.`

I suggest we use the following path, that will also remove the `Capture` dependency:
```
diff --git a/Scripts/developer_scripts/create_internal_release b/Scripts/developer_scripts/create_internal_release
index cd610aa..e106914 100755
--- a/Scripts/developer_scripts/create_internal_release
+++ b/Scripts/developer_scripts/create_internal_release
@@ -4,7 +4,6 @@
 use warnings;
 
 use Cwd;
-use Capture::Tiny ':all';
 use File::Find;
 use Getopt::Std;
 use File::Spec;
@@ -164,12 +163,13 @@ sub install_packages() {
 
     # generate the list of header file per package that not in an internal subdirectory. Files start with CGAL
     $tempdir = File::Temp->newdir();
-    @filelistcmd = ('tar', '-tf', "$RELEASEDIR/temppack.tar", '--wildcards', "./include/\*\*.h",
-                    "--transform=s/.\\\/include\\\///", '--show-transformed-names',
-                    '--exclude=**/internal', "--index-file=$tempdir/$package_name.txt");
-    ($stdout, $stderr, $exit) = capture {
+    if ( -d "$package_full_path/include")
+    {
+      @filelistcmd = ('tar', '-tf', "$RELEASEDIR/temppack.tar", '--wildcards', "./include/\*\*.h",
+                      "--transform=s/.\\\/include\\\///", '--show-transformed-names',
+                      '--exclude=**/internal', "--index-file=$tempdir/$package_name.txt");
       system(@filelistcmd);
-    };
+    }
 
     move("$RELEASEDIR/temppack.tar", "$RELEASEDIR/$VERSION/");
 
@@ -203,10 +203,12 @@ sub install_packages() {
       }
     }
     system('tar', '-xf', "temppack.tar");
-    if(-d "$RELEASEDIR/$VERSION/doc/$package_name/") {
-      system("mv", ,"$tempdir/$package_name.txt", "$RELEASEDIR/$VERSION/doc/$package_name/filelist.txt");
-    } else {
-      system("rm", ,"$tempdir/$package_name.txt");
+    if ( -e "$tempdir/$package_name.txt" ){
+      if(-d "$RELEASEDIR/$VERSION/doc/$package_name/") {
+        system("mv", ,"$tempdir/$package_name.txt", "$RELEASEDIR/$VERSION/doc/$package_name/filelist.txt");
+      } else {
+        system("rm", ,"$tempdir/$package_name.txt");
+      }
     }
 
 #    $tmp_package_name = "temp_${package_name}";
```

**Comment by sloriot** [comment]
Here is the same diff using  `git diff -w`
```
diff --git a/Scripts/developer_scripts/create_internal_release b/Scripts/developer_scripts/create_internal_release
index cd610aa..e106914 100755
--- a/Scripts/developer_scripts/create_internal_release
+++ b/Scripts/developer_scripts/create_internal_release
@@ -4,7 +4,6 @@
 use warnings;
 
 use Cwd;
-use Capture::Tiny ':all';
 use File::Find;
 use Getopt::Std;
 use File::Spec;
@@ -164,12 +163,13 @@ sub install_packages() {
 
     # generate the list of header file per package that not in an internal subdirectory. Files start with CGAL
     $tempdir = File::Temp->newdir();
+    if ( -d "$package_full_path/include")
+    {
       @filelistcmd = ('tar', '-tf', "$RELEASEDIR/temppack.tar", '--wildcards', "./include/\*\*.h",
                       "--transform=s/.\\\/include\\\///", '--show-transformed-names',
                       '--exclude=**/internal', "--index-file=$tempdir/$package_name.txt");
-    ($stdout, $stderr, $exit) = capture {
       system(@filelistcmd);
-    };
+    }
 
     move("$RELEASEDIR/temppack.tar", "$RELEASEDIR/$VERSION/");
 
@@ -203,11 +203,13 @@ sub install_packages() {
       }
     }
     system('tar', '-xf', "temppack.tar");
+    if ( -e "$tempdir/$package_name.txt" ){
       if(-d "$RELEASEDIR/$VERSION/doc/$package_name/") {
         system("mv", ,"$tempdir/$package_name.txt", "$RELEASEDIR/$VERSION/doc/$package_name/filelist.txt");
       } else {
         system("rm", ,"$tempdir/$package_name.txt");
       }
+    }
 
 #    $tmp_package_name = "temp_${package_name}";
 #    system("mv", "$package_name", "$tmp_package_name");
```

**Comment by bo0ts** [comment]
@sloriot Applied and tested your patch.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-106

**Pull request merged**
