### PR TITLE
Add autorefinement

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes
Add autorefinement and removal of self-intersection.

## Release Management

* Affected package(s): PMP
* Feature/Small Feature (if any): [link](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Autorefinement)

TODOS:
* [ ] There is an issue I need to address if there are locally more than 2 surfaces intersecting along an edge

### CODE REVIEW

**Comment by lrineau** [comment]
Since there was nothing urgent to test, I have tried this PR in latest internal release.

The [PMP line is fully red](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.12-Ic-22.shtml#Polygon_mesh_processing) because of a runtime error:
```
- ProgramOutput.test_autorefinement.ArchLinux-clang
------------------------------------------------------------------
CGAL::Random()::get_seed() = 1503459050
Running tests on data-autoref/test_01.off
CGAL error: assertion violation!
Expression : CGAL::is_border(h2, pmesh)
File       : /mnt/testsuite/include/CGAL/Polygon_mesh_processing/stitch_borders.h
Line       : 210
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
terminate called after throwing an instance of 'CGAL::Assertion_exception'
  what():  CGAL ERROR: assertion violation!
Expr: CGAL::is_border(h2, pmesh)
File: /mnt/testsuite/include/CGAL/Polygon_mesh_processing/stitch_borders.h
Line: 210
```

**Comment by sloriot** [comment]
I don't have the issue locally, it must be an issue with a more recent patch present in master

**Comment by sloriot** [comment]
The test was broken because it uses the fact that `operator>>()` clears the mesh before filling it (but this behavior was changed in the meantime). I added an explicit call to `clear()` to fix the issue.

**Comment by lrineau** [comment]
You should also fix the merge conflict. It seems easy to do using the Github UI.

**Comment by lrineau** [comment]
@sloriot: You should rebase this PR, and update its status. I do not know if I should try to test and get it integrated in `master`.

**Comment by sloriot** [comment]
The feature is not ready to be publicly release. I close the PR for now.

**Pull request closed without merging**
