### PR TITLE
Triangulation_2: Cleanup of CDT_plus_2

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Remove the deprecated API where a pair of vertex handles was considered as id of  a constraint.

## Release Management

* Affected package(s): Triangulation_2

### CODE REVIEW

**Comment by lrineau** [comment]
Do not forget to add a mention of that in `CHANGES.md`. Please also mention in `CHANGES.md` all the modifications you made in https://github.com/CGAL/cgal/pull/2938.

**Comment by afabri** [comment]
> 
> 
> Do not forget to add a mention of that in `CHANGES.md`. Please also mention in `CHANGES.md` all the modifications you made in #2938.

Do we announce as a change that we removed undocumented files and functions that were deprecated some releases before?

**Comment by afabri** [comment]
@maxGimeno resady for testing

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [May 3, 2019, 12:51 PM GMT+2](https://github.com/CGAL/cgal/pull/3890#issuecomment-489057515 "2019-05-03T10:51:59Z - Replied by Github Reply Comments"):
> > 
> > 
> > Do not forget to add a mention of that in `CHANGES.md`. Please also mention in `CHANGES.md` all the modifications you made in #2938.
> 
> Do we announce as a change that we removed undocumented files and functions that were deprecated some releases before?

For undocumented things, we have never announced any change. But for deprecated functions, yes: we did that each time. Users have the right to know that their code will break.

Examples: 

  - https://github.com/CGAL/cgal/blob/master/Installation/CHANGES.md#2d-and-3d-triangulations
  - https://github.com/CGAL/cgal/blob/master/Installation/CHANGES.md#3d-convex-hull-1

**Comment by afabri** [comment]
I just added:

> ### 2D Triangulations

-   **Breaking change**: Removed the functions `CGAL::Constrained_triangulation_plus_2::
    vertices_in_constraint_{begin/end}(Vertex_handle va, Vertex_handle vb) const;`,
    and `CGAL::Constrained_triangulation_plus_2::remove_constraint((Vertex_handle va, Vertex_handle vb)`,
    that is a pair of vertex handles is no longer a key for a polyline constraint.
    Users must use a version prior to 5.0 if they need this functionality.

**Comment by maxGimeno** [comment]
There are conflicts with master. 
Could this be responsible for [those](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-34.shtml#Periodic_4_hyperbolic_triangulation_2) ?

**Comment by lrineau** [comment]
The only conflict was in `CHANGES.md`, and completely trivial to fix.

**Comment by lrineau** [comment]
@afabri I do not understand this PR. It is supposed to remove deprecated API but it only changes the file `CHANGES.md` and nothing else.

**Comment by lrineau** [comment]
It seems #3891 did remove the deprecated functions, and this PR is only to modify the `CHANGES.md`.

**Pull request merged**
