### PR TITLE
Triangulation_2: Cleanup of include/CGAL

### PR DESCRIPTION
**Pull request by afabri**
_Please use the following template to help us managing pull requests._

## Summary of Changes

Move files to include/CGAL/Triangulation_2/internal and remove deprecated files

Remove unsused and undocumented files: Distance.h, Triangulation_iterator_adaptator.h, and Trivial_iterator.h

## Release Management

* Affected package(s): Triangulation_2

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot Any suggestion how to call the subnamespace? I guess it cannot be `Triangulation_2` as this is already a class name.

**Comment by sloriot** [comment]
`Triangulation_2_impl` ?
At some point, it was mentionned that we could use the same convention as in boost:
<i>The library's primary namespace (in parent ::boost) is given that same name, except when there's a component with that name (e.g., boost::tuple), in which case the namespace name is pluralized. For example, ::boost::filesystem. </i>
So `Triangulations_2`  can be a good candidate too.

**Comment by lrineau** [comment]
This PR has conflicts, and also seems under discussion.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Jun 7, 2018, 1:01 PM GMT+2](https://github.com/CGAL/cgal/pull/2938#issuecomment-395380539 "2018-06-07T11:01:00Z - Replied by Github Reply Comments"):
> This PR has conflicts, and also seems under discussion.

This PR does not seem important for anybody. Unless somebody stands up, it will not be in CGAL-4.13.

**Comment by maxGimeno** [comment]
@afabri What is the status on this ?

**Comment by afabri** [comment]
It's a minor cleanup that we can do either before or after the release based on travis.

**Comment by lrineau** [comment]
I have marked this PR as "ready to be tested", but for 4.15.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-10.shtml

**Comment by MaelRL** [comment]
Late to the party, but if you're going to remove Weighted_point due to old deprecation, it would be nice to also clean other useless classes/files in T2 such as `Triangulation_euclidean_traits_2`, `Regular_triangulation_euclidean_traits`, `Regular_triangulation_filtered_traits_2` etc.

I would also announce the removal of deprecated classes/functions in the changelog, but I don't know if it's mandatory.

**Comment by sloriot** [comment]
Maybe we can make a global pass on deprecated stuffs and merge this branch as is? If you agree let's open an issue to track that.

**Comment by MaelRL** [comment]
Sure.

**Comment by afabri** [comment]
I could live with doing that today or on Monday.

**Comment by afabri** [comment]
@sloriot successfully tested after the removal of deprecated files as suggested by Mael.

**Comment by maxGimeno** [comment]
I see warnings in the Triangulation package, but I don't think it is related.

**Comment by lrineau** [comment]
[**@afabri**](https://github.com/afabri) commented on [Apr 18, 2019, 1:41 PM GMT+2](https://github.com/CGAL/cgal/pull/2938#issuecomment-484468592 "2019-04-18T11:41:04Z - Replied by Github Reply Comments"):
> @sloriot successfully tested after the removal of deprecated files as suggested by Mael.

That should have been announced in the `CHANGES.md`.

**Pull request merged**
