### PR TITLE
Adding a timeout column to the testsuite

### PR DESCRIPTION
**Pull request by SaillantNicolas**
## Summary of Changes
Adding a timeout column to the test suite that Distinguish between error and time-out.
Testsuite improvements #2205

### CODE REVIEW

**Review by lrineau — APPROVED** [review]

**Comment by lrineau** [comment]
@sloriot I think this PR will have to be merged, and deployed, without testing in `integration`. Or at least I will have to update the content of `~/CGAL/branches/local-master.git` on cgal.gf.com.

**Comment by sloriot** [comment]
Sure, go ahead

**Comment by lrineau** [comment]
[CGAL-5.6-Ic-212](https://cgal.geometryfactory.com/CGAL/testsuite/results-5.6-Ic-212.shtml) is the first test results page with the new orange `o` column (with currently zero `o` results).

Screenshot_20230405_180218

Tomorrow will be the first test suite results page with explicit display of timeouts.

Note that for the moment, the Linux Docker tests will not report timeouts. @SaillantNicolas is still working on it.

**Comment by sloriot** [comment]
the testsuite diff script might also need to be modified to accommodate the o

**Comment by lrineau** [comment]
> the testsuite diff script might also need to be modified to accommodate the o

You are certainly right. I do not know how to modify it.

**Comment by sloriot** [comment]
Does not seem to be working: https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-213/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz

**Comment by lrineau** [comment]
> Does not seem to be working: [cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-213/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz](https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.6-Ic-213/Polygon_mesh_processing/TestReport_lrineau_Ubuntu-GCC_master_CXX20-Release.gz)

As I said, the Docker testsuites will not report any `o`, for the moment. We will have to switch to using CTest for them. @SaillantNicolas is working on it.

**Pull request merged**
