### PR TITLE
add an action to assign a color per cc of a polyhedron

### PR DESCRIPTION
**Pull request by sloriot**
Merged into [CGAL-4.7-Ic-51](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-51.shtml).

This branch only changes the polyhedron demo.

### CODE REVIEW

**Comment by sloriot** [comment]
There was one warning.
Remerged into  [CGAL-4.7-Ic-53](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml)

**Comment by lrineau** [comment]
Remerged into  [CGAL-4.7-Ic-55](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-55.shtml)

I see the commit cac397d after your message about CGAL-4.7-Ic-53. I have supposed that it means it was not tested in CGAL-4.7-Ic-53.

**Comment by sloriot** [comment]
No it was, otherwise it would not have compiled at all.

**Comment by lrineau** [comment]
As far as I can see, the tests in [CGAL-4.7-Ic-53, line `Polyhedron_Demo`](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-53.shtml#Polyhedron_Demo) seems good. The errors are in other plugins, and the warnings were already there in `master` (in [4.7-I-34](https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-I-34.shtml#Polyhedron_Demo) actually).

I propose to merge this PR (and you can proceed with the merge if you agree, or write a comment here).

**Pull request merged**
