### PR TITLE
Add triangulate_face and triangulate_faces range overload

### PR DESCRIPTION
**Pull request by bo0ts**
Adds a function to triangulate a single face and a function to triangulate a FaceRange for consistency with other parts of this package.

https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Triangulate_face

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-71

**Comment by sloriot** [comment]
Testsuite is red

**Comment by bo0ts** [comment]
The failure only appears in non-C++11 compilers or older compilers with C++11 enabled (gcc 4.8). I think the problem is caused by not having extended SFINAE kick-in for the new range overload. IMO this problem should also affect the measure function but there is a no test to exhibit it.

I'll try to reproduce it, add the necessary `enable_if` trickery and try to add a test-case for `measure` as well.

**Comment by bo0ts** [comment]
Tests failed due to a bug in Boost.Range. f8e8f5a fixes this. Tested on the docker images `ubuntu-latest` and `debian-stable`.

**Comment by bo0ts** [comment]
Merged to integration in 43cfe27

**Comment by bo0ts** [comment]
Testsuite in Ic-76 is good.

**Pull request merged**
