### PR TITLE
Classification: Fix bug + clean up has_points() method in Planimetric_grid

### PR DESCRIPTION
**Pull request by sgiraudot**
## Summary of Changes

The method `Planimetric_grid::has_points()` was not well implemented, it contained a test that was useless in most cases and should have been deported to specific parts where it was actually needed. In addition, this test was not done in all cases where it should have been, leading to bugs (see https://github.com/CGAL/cgal/issues/3176).

This issue deports the tests in parts where they are actually needed and cleans up the `has_points()` method (some additional assertions are also added to help future debugging). The bug is gone and the other examples/tests work well.

## Release Management

* Affected package(s): Classification
* Issue(s) solved (if any): fix https://github.com/CGAL/cgal/issues/3176

### CODE REVIEW

**Comment by lrineau** [comment]
This PR conflicts with #3126. We should discuss how to test it.

**Comment by sgiraudot** [comment]
This PR should pass the testsuite easily (quite self-contained changes). Maybe we should test it tonight, merge it tomorrow if everything's fine, and then update the other PR with the updated master?

**Comment by sgiraudot** [comment]
The testsuite looks goods, the only error that I see so far is the problem with OpenCV that's not related to this PR (and that should be fixed anyway by #3126).

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.13-Ic-42][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-42.shtml

**Pull request merged**
