### PR TITLE
Point set processing: improve outlier removal API

### PR DESCRIPTION
**Pull request by sgiraudot**
Pre-approved [small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Improve_Outlier_Removal_API).

note: the small feature was pre-approved 2nd of November 2016.

### CODE REVIEW

**Comment by sgiraudot** [comment]
The latest tests look good to me (PSP line is all red except for a platform that fails on all packages, and Polyhedron demo errors do not seem related to this PR unless I missed something).

**Comment by lrineau** [comment]
The PR is regularly tested, with others. Now that the small feature is approved (pre-approved for more than two weeks without protests), nothing blocks its integration. It will be merged as soon as we have a correct testsuite. Unless the merge is urgent, I'll wait for test results that are good for all lines. Is that urgent?

**Comment by sgiraudot** [comment]
No it's not urgent IMHO.

**Comment by sgiraudot** [comment]
Fixes https://github.com/CGAL/cgal/pull/1647

**Pull request merged**
