### PR TITLE
Mesh_3 simple fixes to use generic indexes for subdomains and surfacepatches

### PR DESCRIPTION
**Pull request by SLopezBRGM**
This pull request is about different non exhaustive fixes about bugs occuring when using non integer struct as indexes for subdomains and surfacepatches.

It is related to and should solve, at least partly, issues #37 and  #41.

Oddly, calling explicitely  the Surface_patch constructor in Refine_facets_3.h and C3T3_helpers.h where it should have been called implicitely solved a compilation failure with g++ with the aforementioned "struct indexes".

### CODE REVIEW

**Comment by lrineau** [comment]
Merged in the  `integration` branch for testing tonight.

**Comment by lrineau** [comment]
The results were not good, due to other branches that were merged at the same time. Will be re-tested tonight.

**Comment by lrineau** [comment]
[CGAL-4.7-Ic-7][7] was a bad internal release. I have remerged for testing in [CGAL-4.7-Ic-8][8] tonight.

[7]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-7.shtml
[8]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.7-Ic-8.shtml

**Comment by lrineau** [comment]
@SLopezBRGM Can you modify the title of the pull-request, so that the title is more generic, and includes the last changes you made?

In my opinion, the set of changes you made as rather small. There is:
  -  a systematic change that replaces `A != B` by `!(A == B)`,
  - the addition of the explicit call to the construct of `Surface_patch`,
  - plus a small fix of the use of `CGAL_MESH_3_NO_LONGER_CALLS_DO_INTERSECT_3`.

In my opinion, that set of changes does not modify the ownership of Mesh_3. But maybe to be on the safe side we should ask you to sign the [user contribution license agreement with GeometryFactory][CLA]. Do you think your employer would sign that CLA easily?

[CLA]: http://www.cgal.org/CLA/CLA-GF.html

**Comment by SLopezBRGM** [comment]
@lrineau It is quite clear to me that my few modifications does not change the ownership of Mesh_3. :-)
I'll have a try at having my employer sign the CLA... but it may take a few months ! :-(

**Comment by lrineau** [comment]
@SLopezBRGM The testing of the patch was good, in the internal release CGAL-4.7-Ic-11.

Can you sign the CLA of GeometryFactory? The patch is really small. I am not even sure it is significant for the ownership of the code.

**Comment by lrineau** [comment]
I have received the paperwork. I will continue with the tests and merge...

**Comment by lrineau** [comment]
The tests in CGAL-4.7-Ic-33 were successful. Thanks.

**Pull request merged**
