### PR TITLE
Subdivision: Add example for Linear_mask_3

### LINKED ISSUE #7310: subdivision
## Issue Details

 the midpoint subdivision does not introduce any geometry distortion, it simply adds vertices in the middle of edges

how to do it ？

## Source Code

image

## Environment

* Operating system (Windows/Mac/Linux, 32/64 bits):
* Compiler:
* Release or debug mode:
* Specific flags used (if any):
* CGAL version:
* Boost version:
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add an example for an not well documented class that does what was asked for in Issue #7310.  I had at the same time to  add a bug fix.    Before merging there are still some small improvements we can make in the documentation.

We initially also had the idea to replace `PolygonMesh` with `TriangleMesh` where it is required, but won't change for now.

TODO:
- [x] Put Linear_mask in the doc
- [x] Fix namespace appearing as class in ref manual

## Release Management

* Affected package(s): Subdivision_method_3
* Issue(s) solved (if any): fix #7310
* Link to compiled documentation (obligatory for small feature) [*wrong link name to be changed*](httpssss://wrong_URL_to_be_changed/Manual/Pkg)
* License and copyright ownership:  unchanged

### CODE REVIEW

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-198.
@afabri are the TODOs still valid?

**Comment by sloriot** [comment]
Successfully tested in 5.6-Ic-208

**Comment by afabri** [comment]
> @afabri: you marked this PR for `5.5.x-branch` ([#7329 (comment)](https://github.com/CGAL/cgal/pull/7329#event-8733768660)) but the branch is based on `master`. I will merge the PR as it is. Please tell us if it should be backported to CGAL-5.5.x.

It is ok if that is in the next release.

**Pull request merged**
