### PR TITLE
TDS_2/3: Cleanup in the documentation

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

- Use `\tparam ` and CamelCase for template parameters.

- Replace  the template parameter `TriangulationDSVertexBase_3`  with `VertexBase` as it makes no sense to write: `TriangulationDSVertexBase_3` must be a model of `TriangulationDSVertexBase_3`.

- Remove non-existing `Vertex_container_strategy,Cell_container_strategy` in the main page of the  Reference manual where we falsely write:  `CGAL::Triangulation_data_structure_3<TriangulationDSVertexBase_3,TriangulationDSCellBase_3,Vertex_container_strategy,Cell_container_strategy,Concurrency_tag>`.

- For the 2D TDS replace template parameters `Vb` and `Fb` with `VertexBase` and `FaceBase`, in order to unify.

- @MaelRL  plans to unify in the periodic versions later.
- Removing `_3` unifies with Alpha shapes_2/3, Mesh_2/3. I didn't check others.

## Release Management

* Affected package(s): TDS_3, TDS_2

### CODE REVIEW

**Comment by afabri** [comment]
@MoniqueTeillaud I changed the template parameter names in the TDS_2 and TDS_3 to `VertexBase`,  `FaceBase`, and `CellBase`.  
You can have a look in the manual testsuite for 
[TDS_3](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1-Ic-16/output1/TDS_3/classCGAL_1_1Triangulation__data__structure__3.html)  and [TDS_2](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1-Ic-16/output1/TDS_2/classCGAL_1_1Triangulation__data__structure__2.html).

The starting point was to use `\tparam".   If you agree to the change we can mark it as successfully tested.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-18.shtml

**Comment by MoniqueTeillaud** [comment]
The link given by Andreas does not work
Not Found
The requested URL /CGAL/Manual_doxygen_test/CGAL-5.1-Ic-16/output1/TDS_3/classCGAL_1_1Triangulation__data__structure__3.html was not found on this server.

**Comment by afabri** [comment]
https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.1-Ic-18/output1/TDS_3/classCGAL_1_1Triangulation__data__structure__3.html

**Comment by maxGimeno** [comment]
Doesn't work either. Documentation is erased every 8 days, IIRC.

**Comment by afabri** [comment]
@maxGimeno so please add it to tonight's testsuite.

**Comment by maxGimeno** [comment]
@afabri it is in every testsuite since it has been flagged "Under Testing", except for saturdays and sundays.

**Comment by MoniqueTeillaud** [comment]
Hi 
can't you put the relevant page(s) in some stable place?

**Comment by MoniqueTeillaud** [comment]
If you don't have a stable link, at least tell me which pages I should look at in the testsuite. 
I cannot reasonbly read the manual of the whole package and ask my eyes to detect the diffs...

**Comment by afabri** [comment]
> 
> 
> If you don't have a stable link, at least tell me which pages I should look at in the testsuite.
> I cannot reasonbly read the manual of the whole package and ask my eyes to detect the diffs...

The link was supposed to go the one fixed page. Having had a look at it of a recent release, I noticed that I had not fixed everything. Stay tuned. Sorry about that.

**Comment by afabri** [comment]
image

**Comment by MaelRL** [comment]
@MoniqueTeillaud The simplest way is probably to look at the diff directly, which is rather small (https://github.com/CGAL/cgal/pull/4363/files)

**Comment by MoniqueTeillaud** [comment]
Apart from using \tparam, I don't see why changing the names of the template parameters makes the manual better in any way... e.g., the _3 has disappeared, etc, which is not really a progress. 

Note that 
* The title of the PR and the summary of changes do not reflect the fact that TDS_2 is also affected. 
* I can only see what was actually changed. I cannot check whether similar changes have been forgotten in other places, which would potentially introduce inconsistencies. 

Conclusion: why not.

**Comment by afabri** [comment]
@MoniqueTeillaud I changed the title and address your points in the PR text.

**Comment by sloriot** [comment]
@MoniqueTeillaud According to your previous comment I'll assume you are fine with the changes (Andreas only implemented what you requested)

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.1-Ic-53.shtml

**Pull request merged**
