### PR TITLE
Polygon_mesh_slicer:  Fix orientation for master

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This is the master verison of #3910

### CODE REVIEW

**Comment by sloriot** [comment]
@maxGimeno I don't understand how you produce this PR. I think you should take master, merge the PR in it and then create a PR from this branch. This will avoid duplicated commits and rebasing issues.

**Comment by maxGimeno** [comment]
I produced it by rebasing the initial branch on master, and then correcting the conflicts and non-c++11 code.

**Comment by lrineau** [comment]
I have forced-push a better history for this PR. Now it shares all the commits with #3910, except for the merge commit.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-36.shtml.

**Pull request merged**
