### PR TITLE
Skipping degenerate tris in normal computation

### PR DESCRIPTION
**Pull request by soesau**
## Summary of Changes

Added a check for co-linear vertices before calculating normals.

## Release Management

* Affected package(s): PMP
* Issue(s) solved (if any): #6783

### CODE REVIEW

**Comment by lrineau** [comment]
@MaelRL @sloriot @soesau I wonder what will be the runtime impact.

- For a mesh with degenerate triangles, this pull-request will add filter failures.
- Even for a mesh without degenerate triangles, the code will be a bit slower, but how much?

I have the feeling that the current code (without this pull-request) is actually correct (and faster), and that the assertions should be modified.

**Comment by soesau** [comment]
I agree, it will certainly slow down the usually rather light computation.

After calculating the normal for each face the result is compared to the null vector and normalized afterwards. Thus, the very short normal is rescaled.

**Comment by sloriot** [comment]
If the bug you are trying to fix is the division by 0 when doing the normalization, then we can simply check that the normalization is not done using 0.

**Comment by MaelRL** [comment]
If you were to call `internal::triangle_normal()` (rather than `PMP::compute_face_normal()`), you'd currently still get the same issue. So, if the idea is to add a call to `Collinear_3` to ensure that a null vector is returned if the face is degenerate, that check should probably get down a level into the internal function.

On whether this should be done or not, this is the usual (almost philosophical) problem of whether constructions should be written to be as fast as possible, or as precise as possible when using a kernel not providing exact constructions. My opinion is that the kernel should be as fast as possible, and it's for the user to add extra checks if he decides to use an inexact construction kernel while still caring about having null normals for his degenerate faces.

**Comment by soesau** [comment]
Created new pull request which restricts certain tests to epeck #6880

**Pull request closed without merging**
