### PR TITLE
Update for cpp14

### PR DESCRIPTION
**Pull request by sloriot**
Initial changes for CGAL 5.0
 - remove BOOST_FOREACH
 - remove most of the workaround for cpp11
 - remove most of the classes in cpp11

### CODE REVIEW

**Comment by lrineau** [comment]
There is a conflict that prevents Travis from doing its job.

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal/pull/3781/commits/3a32f3f3ef12c6e1e2261ecfbe57097c98ce6c53 has added a compatibility. Once `CGAL::cpp11` can be removed completely, we will add a namespace alias to replace it, and a deprecation.

**Comment by maxGimeno** [comment]
A lot of red : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Apr 2, 2019, 12:04 PM GMT+2](https://github.com/CGAL/cgal/pull/3781#issuecomment-478930106 "2019-04-02T10:04:45Z - Replied by Github Reply Comments"):
> A lot of red : https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml

A few columns are expected to be fully-read, because their compiler cannot do C++14. The real question is if there are issues except for those red columns.

**Comment by maxGimeno** [comment]
Still, shouldn't we disable the tests in the absence of a suitable compiler or something ? That's 6 columns for now...

**Comment by lrineau** [comment]
[**@maxGimeno**](https://github.com/maxGimeno) commented on [Apr 2, 2019, 12:13 PM GMT+2](https://github.com/CGAL/cgal/pull/3781#issuecomment-478933057 "2019-04-02T10:13:55Z - Replied by Github Reply Comments"):
> Still, shouldn't we disable the tests in the absence of a suitable compiler or something ? That's 6 columns for now...

That is why I wrote the mail "CGAL-5.0, C++14, and the testsuite" today to the CGAL-develop mailing-list, 20 minutes ago. I do not have a solution for the moment.

**Comment by lrineau** [comment]
[**@lrineau**](https://github.com/lrineau) commented on [Apr 2, 2019, 12:10 PM GMT+2](https://github.com/CGAL/cgal/pull/3781#issuecomment-478931949 "2019-04-02T10:10:17Z - Replied by Github Reply Comments"):
> A few columns are expected to be fully-read, because their compiler cannot do C++14. The real question is if there are issues except for those red columns.

The three columns of AppleClang are not fully happy. They fail on:
- [Generator_Examples]
- [Mesh_3]
- [Mesh_3_Examples]
- [Periodic_3_mesh_3]
- [Periodic_3_mesh_3_Examples]
- [Polyhedron_Demo]
- [STL_Extension]
- [Surface_mesh_deformation]
- [Surface_mesh_deformation_Demo]
- [Surface_mesh_deformation_Examples]

[Generator_Examples]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Generator_Examples
[Mesh_3]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Mesh_3
[Mesh_3_Examples]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Mesh_3_Examples
[Periodic_3_mesh_3]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Periodic_3_mesh_3
[Periodic_3_mesh_3_Examples]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Periodic_3_mesh_3_Examples
[Polyhedron_Demo]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Polyhedron_Demo
[STL_Extension]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#STL_Extension
[Surface_mesh_deformation]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Surface_mesh_deformation
[Surface_mesh_deformation_Demo]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Surface_mesh_deformation_Demo
[Surface_mesh_deformation_Examples]: https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-1.shtml#Surface_mesh_deformation_Examples

**Comment by lrineau** [comment]
Commit https://github.com/CGAL/cgal/pull/3781/commits/67aee26a36737da349e3ca2187608af8ed2acb14 has fixed the issue with the `Iterator_range` (all mesh packaged).

Now the remaining issue is that one:
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-5.0-Ic-3/Generator_Examples/TestReport_cgaltester_x86-64_Darwin-13.0_Apple-clang-5.0_Release.gz
```
In file included from /Users/cgaltester/boost-cpp11/boost_1_54_0/boost/variant.hpp:17:
/Users/cgaltester/boost-cpp11/boost_1_54_0/boost/variant/variant.hpp:1751:9: error: call to member function 'convert_construct' is ambiguous
        convert_construct( detail::variant::move(operand), 1L);
        ^~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:354:15: note: in instantiation of function template specialization 'boost::variant<int, std::__1::pair<int, int>, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>::variant<const boost::variant<int, std::__1::pair<int, int>, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >' requested here
```

I found out it is caused by [this bug (Trac 8988)](https://svn.boost.org/trac10/ticket/8988) in Boost Variant 1.54, and fixed in Boost 1.55. Bad luck: the test machine `magritte` uses Boost 1.54. I have suggested @maxGimeno to install a newer version of Boost, in header-only. As we use C++11, and the compiler is not gcc, CGAL does not require Boost.Thread.

**Comment by lrineau** [comment]
Actually, @maxGimeno, the commit https://github.com/CGAL/cgal/commit/67aee26a36737da349e3ca2187608af8ed2acb14 should be cherry-picked to a new PR for `releases/CGAL-4.13-branch`, protected by a test of the macro `CGAL_CFG_NO_CPP0X_TUPLE`. That bug is a real bug in CGAL-4.13 and CGAL-4.14, for anyone wanting to use clang with `libc++` and C++11 or later.

**Comment by maxGimeno** [comment]
I removed the last commit so it won't fail in integration. The one in #3842 is cleaner anyway.

**Comment by maxGimeno** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-5.shtml

**Comment by lrineau** [comment]
@sloriot This PR forgot to announce in `INSTALL.md` everything that was changed, including the breaking changes.

cgal-swig-bindings has been broken by the removal of `CGAL_INTERSECTION_VERSION==1`. See https://github.com/CGAL/cgal-swig-bindings/issues/124.

**Pull request merged**
