### PR TITLE
Use the ability to build doc from a release

### PR DESCRIPTION
**Pull request by bo0ts**
PR #542 added the ability to build the doc from a release. Use it to create the documentation testsuite and remove an old hack.

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-94

**Comment by lrineau** [comment]
That seems good. However, that will be difficult to test. The old script will no work with this PR, and the new script will not work without it.

I think the script should be move to `Scripts/developer_scripts/`, both in master, in the PR, and in the release branch for CGAL-4.7. That way, I will be able to change the cron job, and make it work with:
 - integration with or without this PR,
 - master,
 - and the release branch.
What you do think of that proposal?

@sloriot: please revert your merge into `integration` until that issue is solved.

**Comment by sloriot** [comment]
It is too late for 4.7, the changes to build the doc from a release won't apply.
I reverted the merge. I don't see what you want to do...

**Comment by lrineau** [comment]
I want that we move the script `run_doxygen_testsuite` from Maintenance to Scripts/ so that it is part of internal releases. That will allow the cron job to use the version of the script always synced with the branch that is being tested. We can do that right now in master, and even in the release branch.

**Comment by bo0ts** [comment]
@lrineau :+1: The script is very similar to autotest_cgal and should really move to `Scripts/developer_scripts`.

**Comment by lrineau** [comment]
@sloriot, would you agree that we implement that move in `master` and the release branch, today?

**Comment by sloriot** [comment]
Now that I got your point, sure.

**Comment by bo0ts** [comment]
I also added the change from the 4.7-branch here.

**Comment by bo0ts** [comment]
Rebased against master to reflect the move of the script.

**Comment by sloriot** [comment]
@lrineau for 4.7 this does not prevent from using the ugly hack with `version.h` and the cron should be kept when 4.7 is tested

**Comment by lrineau** [comment]
I have a changed a symbolic link in my setup: now the cron job will use `/home/lrineau/latest-internal-release-branch/Scripts/developer_scripts/run_doxygen_testsuite`.

The next step will be to create a Docker container that creates the internal releases. I suggest the same container runs also the Doxygen testsuite just after. @sloriot, can you add that task to Philipp's task list? I do not know where it is, nowdays.

**Comment by lrineau** [comment]
Actually, the immediate next step is to test this PR #598. Now that the cron job setup uses the right script, this PR can be merged safely in `integration`.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-95

**Comment by lrineau** [comment]
@sloriot:
> for 4.7 this does not prevent from using the ugly hack with version.h and the cron should be kept when 4.7 is tested

`/tmp/version.h` will still be used by the CMake scripts of CGAL-4.7. And the creation of that file is done by a cron job of yours. Now that the `run_doxygen_testsuite` is taken from the internal release, it should work as before for older releases (`CGAL-4.7-branch`, or the current `master` without this PR merged).

**Comment by lrineau** [comment]
There was a runtime error, on Friday:
```
tar (child): </body></html>: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: directory /home/cgal-testsuite/cgal_doc_build/</body></html> does not exist
See /home/cgal-testsuite/doxygen_testsuite-08.log
```

I have modified the curl flags, in https://github.com/bo0ts/cgal/commit/c5af8ac61cef4191002251b1a5c2975d84aa98de.


Merged in [CGAL-4.8-Ic-96][i].
[i]: https://cgal.geometryfactory.com/CGAL/Members/testsuite/results-4.8-Ic-96.shtml

**Comment by lrineau** [comment]
The commit https://github.com/bo0ts/cgal/commit/c5af8ac61cef4191002251b1a5c2975d84aa98de did fix the error (I forgot that I had to add a `$HOME/.netrc` file in the home directory of the Unix user running the test).

But there are still errors:
```
Error: exit code 1 returned by CMake
See /home/cgal-testsuite/doxygen_testsuite-12.log
```
and the log file ends with:
```make

-- Found Doxygen: /home/cgal-testsuite/local/bin/doxygen (found version "1.8.4") 
-- Found PythonInterp: /home/cgal-testsuite/local/bin/python2 (found suitable version "2.7.5", minimum required is "2.6.7") 
CMake Error at doc/CMakeLists.txt:283 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "CMakeFiles_copy_doc_tags".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


-- Configuring incomplete, errors occurred!

```

@bo0ts, the machine run CMake-2.8.11. Could it be related?

**Comment by bo0ts** [comment]
@lrineau I don't think this is a CMake issue. It seems that the package list contains a directory `CMakeFiles`. This is probably caused by an in-source build.

I'll add some extra checks to exclude directories which are not truly packages.

**Comment by lrineau** [comment]
If there is a `CMakeFiles`, then that is the release creation script that is buggy.

**Comment by bo0ts** [comment]
@lrineau No, the script uses a nested build directory and that build directory is detected as a package by the script. This should not happen.

**Comment by lrineau** [comment]
All right, I understand now. Indeed, that build directory should be removed from the set of CGAL packages.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-101

**Comment by sloriot** [comment]
No documentation was produced. However I did not receive any error message. @lrineau do you have more information?

**Comment by lrineau** [comment]
I got a mail that said:
```mail
From: "(Cron Daemon)" <cgal-testsuite@cgal.geometryfactory.com>
To: cgal-testsuite@cgal.geometryfactory.com
Subject: Cron <cgal-testsuite@cgal> /home/lrineau/bin/run_doxygen_testsuite
Message-Id: <20160115202308.CD78E500065@cgal.geometryfactory.com>
Date: Fri, 15 Jan 2016 21:23:08 +0100 (CET)

Error: exit code 1 returned by CMake
See /home/cgal-testsuite/doxygen_testsuite-15.log
```

and `/home/cgal-testsuite/doxygen_testsuite-15.log` ends with:
```make
== Generating build files (DONE) ==

-- Found Doxygen: /home/cgal-testsuite/local/bin/doxygen (found version "1.8.4") 
-- Found PythonInterp: /home/cgal-testsuite/local/bin/python2 (found suitable version "2.7.5", minimum required is "2.6.7") 
CMake Error at doc/CMakeLists.txt:283 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "CMakeFiles_copy_doc_tags".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


-- Configuring incomplete, errors occurred!
[/home/lrineau/bin/run_doxygen_testsuite:74] error "exit code $? returned by CMake"

```

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-106

**Comment by sloriot** [comment]
Doc was build and it looks fine. There are some warnings in the BGL package that will need to be address but let's do this in another branch.

**Comment by lrineau** [comment]
Good! Now the next step, if you both agree, you be to Dockerize the Doxygen testsuite.

**Pull request merged**
