### PR TITLE
Polyhedron_demo: Fix Qt warning about duplicate filters

### LINKED ISSUE #2294: Polyhedron demo: error about file filters in I/O plugins
From `master`, version 15d9bc94d516316343b9e2ec727eb0da35558205. Open the Polyhedron demo with all plugins, then choose the action (from menu) "File"->"Open...". The text console shows those messages while the open dialog is displayed:
```
Duplicate Filter:  "selection_io_plugin"
This filter will not be available.
Duplicate Filter:  "surf_io_plugin"
This filter will not be available.
Duplicate Filter:  "vtk_plugin"
This filter will not be available.
Duplicate Filter:  "vtk_plugin"
This filter will not be available.
Duplicate Filter:  "vtk_plugin"
This filter will not be available.
```

That seems to mean that some I/O plugins will not work. That is almost certainly due to the way the plugins have been modified to support `Surface_mesh`.

Assigned to: @maxGimeno and @afabri. To be fixed ASAP for CGAL-4.11.

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

This PR modifies the nameFilters of the affected IO plugins to avoid duplication.
## Release Management

* Issue(s) solved (if any): fix #2294

### CODE REVIEW

**Comment by maxGimeno** [comment]
I could not reproduce the issue so someone please tries and validates that it works. Don't forget to remove old library files from your build directory before you try.

**Comment by lrineau** [comment]
The issue #2294 is also about the `surf_io_plugin`. Will this PR fix it as well?

**Comment by maxGimeno** [comment]
I didn't have any problem with the surf_io_plugin, which is the only plugin able to read Amira files, as far as I know. So there shouldn't be any problem. Wasn't there an old version of the surf_io_plugin or the surf_io_sm_plugin remaining in you build dir when you tested ?

**Comment by lrineau** [comment]
I confirm the fix. Tested locally on my Linux with https://github.com/CGAL/cgal/commit/5658adbc263aa01f0adcaecbfaf9148e2010e928 plus this PR merged in it.

**Pull request merged**
