### PR TITLE
Enable the use of Visual Leak Detector in CGAL

### PR DESCRIPTION
**Pull request by lrineau**
That is a small feature: 
https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/Visual_Leak_Detector

https://vld.codeplex.com/
> Visual Leak Detector is a free, robust, open-source memory leak detection system for Visual C++.

### CODE REVIEW

**Comment by sloriot** [comment]
I don't see why a small feature would be needed in that case.

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-52

**Comment by lrineau** [comment]
@sloriot The small feature was there for a long time. At least it constitutes a small documentation of the CMake variables involved.

I would not might if the PR was merged even before the two-weeks delay.

**Comment by lrineau** [comment]
@afabri: The support for Visual Leak Detector is now merged in CGAL. You can use it with Visual Studio.

**Pull request merged**
