### PR TITLE
Use mp_exp_t for Exponent

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by lrineau** [comment]
This PR seems related to the previous one, #1759, is not it?

**Comment by xantares** [comment]
I'm sure about the previous one, but for this one I don't really know what I'm doing.

**Comment by lrineau** [comment]
@mglisse Can you have a look at the proposed patch?

**Comment by mglisse** [comment]
I'll look at it, but it would help to know what your goal is with this patch series. Are you trying to get support for MPIR? Nothing wrong if you are, but I'll look at the patches under a different angle depending if you are fixing some crashes, removing some warnings, getting CGAL to compile on cray, etc.

**Comment by xantares** [comment]
yes it's mpir, turns out we had to replace this with mpir_si

**Pull request closed without merging**
