### PR TITLE
All Qt4-based demos now use -DQT_NO_KEYWORDS

### PR DESCRIPTION
**Pull request by afabri**
We had to replace the keywords emit, signals and slots
We had to replace some Qt foreach with BOOST_FOREACH
 
All demos of CGAL-4.7-Ic-25 pass

### CODE REVIEW

**Comment by lrineau** [comment]
Why using `BOOST_FOREACH` instead of `Q_FOREACH`? Is there any reason to prefer the Boost version?

**Comment by afabri** [comment]
to reduce diversity.

andreas

**Comment by lrineau** [comment]
@afabri If that is the only answer, then please revert that change.

Using Boost.Foreach in a compilation unit that uses only Qt does increase the complexity. The code of `Q_FOREACH` is a few lines (less than 10), perfectly readable, whereas the code of Boost.Foreach is ... well, you know how complex it is! And Boost.Foreach pulls 253 Boost headers, including a lot from Boost.MPL, Boost.TypeTraits. and Boost.Preprocessor. For simple usages in a code using only Qt, `Q_FOREACH` wins by far.

As for technical details:
  - `Q_FOREACH` documents that the container is copied, whereas Boost.Foreach tries not to copy the range, if it detects that it is a not a lightweight object,
  - all Qt containers are reference-counted, and use copy-on-write.

**Comment by afabri** [comment]
I reverted the change and pushed it to mine.

andreas

On 08/05/2015 16:58, Laurent Rineau wrote:
> @afabri <https://github.com/afabri> If that is the only answer, then
> please revert that change.
>
> Using Boost.Foreach in a compilation unit that uses only Qt does
> increase the complexity. The code of |Q_FOREACH| is a few lines (less
> than 10), perfectly readable, whereas the code of Boost.Foreach is ...
> well, you know how complex it is! And Boost.Foreach pulls 253 Boost
> headers, including a lot from Boost.MPL, Boost.TypeTraits. and
> Boost.Preprocessor. For simple usages in a code using only Qt,
> |Q_FOREACH| wins by far.
>
> As for technical details:
>
>   * |Q_FOREACH| documents that the container is copied, whereas
>     Boost.Foreach tries not to copy the range, if it detects that it is
>     a not a lightweight object,
>   * all Qt containers are reference-counted, and use copy-on-write.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGAL/cgal/pull/73#issuecomment-100262375>.
>

-

**Comment by lrineau** [comment]
Thanks.

I have merged the updated pull-request in `integration`.

**Comment by lrineau** [comment]
Successfully tested in CGAL-4.7-Ic-37.

**Pull request merged**
