### PR TITLE
Fix example mesh_3D_gray_vtk_image

### PR DESCRIPTION
**Pull request by ange-clement**
## Summary of Changes

Fixes example mesh_3D_gray_vtk_image.
Changed : Meshing all value **under** isovalue --> Meshing all values **over** isovalue.

## Release Management

* Affected package(s): Mesh_3
* Issue(s) solved (if any): 
* Feature/Small Feature (if any): n/a
* License and copyright ownership: no change

### CODE REVIEW

**Comment by janetournois** [comment]
Using `Less` or `More` actually depends on the input data.
`More` is the default behavior when using `isovalue` only, and using `Less` gives another example. This should be better documented

**Review by janetournois — COMMENTED** [review]
Using `Less` or `More` actually depends on the input data.
Using `More` is the default behavior when using `isovalue` only, and using `Less` gives another example. This should be better documented

**Comment by lrineau** [comment]
@janetournois @ange-clement As far as I understand, that pull-request is debated. I will not merge it, even if it was tested successfully.

**Comment by sloriot** [comment]
@janetournois what is the status of this PR?

**Comment by janetournois** [comment]
This modifies the example of Mesh_3 to make it work with different data sets, and it does not bring any new info or feature, so imho it can be closed.

**Comment by sloriot** [comment]
What about adding an option in the parameter to pick less or more?

**Comment by janetournois** [comment]
Good idea @sloriot !
However meshing this data will fail with `less=false`

**Comment by sloriot** [comment]
> Good idea @sloriot ! However meshing this data will fail with `less=false`

which is why the default is true

**Comment by sloriot** [comment]
Successfully tested in CGAL 6.1-Ic-14

**Pull request merged**
