### PR TITLE
Unification of the names of the IO plugins

### PR DESCRIPTION
**Pull request by maxGimeno**
This PR unifies the IO plugins so that their name is of form "xxxx_io_plugin".

### CODE REVIEW

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-86

**Comment by lrineau** [comment]
While you change the name of the plugins, I would like to discuss the naming convention. Why the capital letter? `Off_plugin` looks wrong, for me: it should be either fully lowercase, `off_plugin` (not long ago it was named `Polyhedron_demo_off_plugin`), or `OFF_plugin`. The reason is that `OFF` is an acronym (and same for `IO`, `VTK`, `XYZ`, at least).

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-87

**Comment by maxGimeno** [comment]
Well Polyhedron_demo_off_plugin starts with a capital letter, so I just kept it when I renamed all the plugins (because of the length of the path for windows). So now every plugin's name starts with a capital letter, I would find it weird that the IO plugins differ.

**Comment by afabri** [comment]
What Laurent means is that Nef_io_plugin is ok as capitalized, and that it should be uppercase for acronyms such as OFF, VTK, PLY,..

**Comment by maxGimeno** [comment]
Oh, ok. Then I'd vote for full caps rather than full lowercase.

**Comment by afabri** [comment]
It's not a question of voting.
Just write acronyms in upper case.

**Comment by maxGimeno** [comment]
Sir, yes sir.

**Comment by afabri** [comment]
:>

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-91

**Pull request merged**
