### PR TITLE
Fix wrong \ingroup statements

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Fix serveral labels reported by @albert-github 

Fixes issues #7793, #7791, #7790, #7788

### CODE REVIEW

**Comment by afabri** [comment]
@sloriot can you have a look at the problem with the label for the do_intersect label reported in Issue #7789

**Comment by albert-github** [comment]
@afabri, @sloriot see my comment https://github.com/CGAL/cgal/issues/7789#issuecomment-1766530635

**Comment by afabri** [comment]
> @afabri, @sloriot see my comment [#7789 (comment)](https://github.com/CGAL/cgal/issues/7789#issuecomment-1766530635)

What you suggest is indeed the fix.  Thanks.

**Comment by sloriot** [comment]
Successfully tested in 6.0-Ic-93

**Pull request merged**
