### PR TITLE
Convex hull 3 clean halfspace intersection sloriot

### PR DESCRIPTION
**Pull request by sloriot**
A few commits cleaning the code
Depends on #82

### CODE REVIEW

**Comment by lrineau** [comment]
Why two different pull-requests? It this one (#88) only for CGAL-4.7 or it is also for 4.6.1?

**Comment by sloriot** [comment]
One is a bug-fix, the other a clean-up

**Comment by lrineau** [comment]
If I read the pull-requests, #82 is against `releases/4.6-branch` (CGAL-4.6.1), and this one (#88) is against `master` (CGAL-4.7)...

**Comment by sloriot** [comment]
Yes, because this PR is not a bugfix so it cannot go into 4.6.1

**Comment by lrineau** [comment]
#82 is now merged.

**Comment by lrineau** [comment]
Successfully tested in CGAL-4.7-Ic-37.

**Pull request merged**
