### PR TITLE
Rename bbox_3 functions

### PR DESCRIPTION
**Pull request by sloriot**
## Summary of Changes

free functions in CGAL have no dimension suffix

## Release Management

* Affected package(s): PMP

### CODE REVIEW

**Comment by janetournois** [comment]
`vertex_bbox_3`, `edge_bbox_3` and `face_bbox_3` should also be added to the deprecated functions, right?

**Comment by sloriot** [comment]
They are introduced in 4.10

**Comment by janetournois** [comment]
oh ok, thanks!

**Comment by lrineau** [comment]
As [I said in PR #1517], in my opinion this should be documented in a small feature. That naming issue would probably have been spotted during the review if the small feature has been published.

[I said in PR #1517]: https://github.com/CGAL/cgal/pull/1517#issuecomment-250478606

**Comment by sloriot** [comment]
See [that small feature](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/Small_Features/add_PMP_measure_functions) that introduces the bad naming.

**Comment by lrineau** [comment]
The Travis CI check showed compilation errors.

**Comment by lrineau** [comment]
Polyhedron_Demo is all red:
```
/home/cgal_tester/build/src/cmake/platforms/Fedora-rawhide/test/Polyhedron_Demo/Plugins/Operations_on_polyhedra/Clip_polyhedron_plugin.cpp:195:84:   required from here
/mnt/testsuite/include/CGAL/Polygon_mesh_processing/internal/clip.h:344:27: error: no match for call to '(CGAL::Bbox_3) (CGAL::Polyhedron_3<CGAL::Mesh_3::Robust_intersection_traits_3<CGAL::Epick>, Polyhedron_demo_items<int>, CGAL::HalfedgeDS_default, std::allocator<int> >&)'
   CGAL::Bbox_3 bbox = bbox(tm);
                       ~~~~^~~~
```
https://cgal.geometryfactory.com/CGAL/testsuite/CGAL-4.10-Ic-116/Polyhedron_Demo/TestReport_lrineau_Fedora-rawhide.gz

**Pull request merged**
