### PR TITLE
Polyhedron demo - statistics - do not compute angles for null_faces

### PR DESCRIPTION
**Pull request by janetournois**
This PR fixes various issues about the "statistics" widget
* do not compute angles for null_faces : the angle should not be computed for "outside" faces, i.e. null_face()
* do not recompute all statistics for each type of statistics

### CODE REVIEW

**Comment by janetournois** [comment]
question to @lrineau @sloriot 
do you think statistics data should be kept in cache for edge lengths and angles?
More or less, the stats that are expensive to compute are computed as little as possible. For these, the values could be stored in cache too, but I'm not sure whether it's worth it

cc @maxGimeno

**Comment by sloriot** [comment]
What do you mean? In between two calls to statistics?

**Comment by janetournois** [comment]
@sloriot yes

btw, don't merge this PR into integration yet, it's still not ready

**Comment by janetournois** [comment]
this PR should be ready for testing now, thanks

**Comment by janetournois** [comment]
this PR is ready for testing now, thank you!

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-107

**Comment by sloriot** [comment]
Merged in CGAL-4.8-Ic-109

**Pull request merged**
