### PR TITLE
PMP: Add example for extrude_mesh()

### PR DESCRIPTION
**Pull request by afabri**
## Summary of Changes

Add an example for the function that enables to extrude a mesh.

Text  [subsection ](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.5-Ic-30/output2/Polygon_mesh_processing/index.html#title10 )and example [subsection ](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-5.5-Ic-30/output2/Polygon_mesh_processing/index.html#title15) in the User Manual.

## Release Management

* Affected package(s): PMP

### CODE REVIEW

**Comment by janetournois** [comment]
The example should be listed in the user manual, or at least in `PMP/doc/examples.txt`

**Comment by sloriot** [comment]
Some comments in the example would be nice to have. Do you really need to commit yet another mesh to use it in this example?

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-26

**Comment by lrineau** [comment]
@afabri The pull-request has been tested successfully, but that [remark/question from @sloriot](https://github.com/CGAL/cgal/pull/6341#issuecomment-1048025259) remains unanswered:
> Some comments in the example would be nice to have. Do you really need to commit yet another mesh to use it in this example?

**Comment by afabri** [comment]
@sloriot Does [this ](https://cgal.github.io/6341/v1/Polygon_mesh_processing/index.html#title15)fulfill the _todo_?

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-30

**Comment by sloriot** [comment]
I still find it is not necessary to add yet another .off and plane.off would be fine.

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.5-Ic-35

**Pull request merged**
