### PR TITLE
Bso validation efif

### LINKED ISSUE #3667: Joining valid Polygons creates PolygonSet with invalid PolygonWithHoles
## Issue Details

I found two valid polygons that when joined together into Polygon_set_2 form an invalid Polygon_with_holes_2.

Those two polygons are triangles with a common vertex.

The resulting Polygon_with_holes_2's outer boundary seems to have proper counter-clockwise vertex order, but fails the has_valid_orientation_polygon_with_holes() check.

This was done using Epeck kernel.

image

## Source Code

```c++
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Boolean_set_operations_2.h>
#include <CGAL/Polygon_set_2.h>
#include <memory>
#include <sstream>
#include <assert.h>

template <typename CGalType>
CGalType cgalTypeFromString(const std::string& str) {
    std::stringstream stream(str);
    CGalType value;
    stream >> value;

    return value;
}

int main()
{
    /**
    *  These two valid polygons when merged form a PolygonSet with invalid PolygonWithHoles
    */
    using K = CGAL::Exact_predicates_exact_constructions_kernel;
    using PolygonSet = CGAL::Polygon_set_2<K>;
    using Polygon = CGAL::Polygon_2<K>;
    using PolygonWithHoles = CGAL::Polygon_with_holes_2<K>;

    auto traits = std::make_unique<PolygonSet::Traits_2>();

    const std::string firstPolyString(
        "3 -9924612878548874890304733981971/20282409603651670423947251286016 "
        "17188006152006536578823865513759/81129638414606681695789005144064 "
        "-9519368606443823699966886983117/20282409603651670423947251286016 "
        "6637310640423212698853225948775/40564819207303340847894502572032 "
        "-8874718064193764428030739181071/20282409603651670423947251286016 "
        "1239265188467743494005293520325/10141204801825835211973625643008");

    const std::string secondPolyString(
        "3 -14112493806255234993030698361967/40564819207303340847894502572032 "
        "2857271125160752150753227128691/40564819207303340847894502572032 "
        "-9924612878548874890304733981971/20282409603651670423947251286016 "
        "17188006152006536578823865513759/81129638414606681695789005144064 "
        "-4017296560458822758487345961369/10141204801825835211973625643008 "
        "3667759669370854531428921126399/40564819207303340847894502572032");

    Polygon firstPoly(cgalTypeFromString<Polygon>(firstPolyString));
    Polygon secondPoly(cgalTypeFromString<Polygon>(secondPolyString));

    assert(CGAL::is_valid_unknown_polygon(firstPoly, *traits) &&
        firstPoly.is_counterclockwise_oriented());
    assert(CGAL::is_valid_unknown_polygon(secondPoly, *traits) &&             
        secondPoly.is_counterclockwise_oriented());

    // Create polygon set form the first polygon
    PolygonSet pSet;
    pSet.join(firstPoly);

    // Test that polygonset is made of valid polygons
    {
        std::vector<PolygonWithHoles> polys(pSet.number_of_polygons_with_holes());
        pSet.polygons_with_holes(polys.begin());
        for(PolygonWithHoles& poly : polys) {
            // This passes
            assert(CGAL::is_valid_polygon_with_holes(poly, *traits)); // This passes
        }
    }

    pSet.join(secondPoly);

    // Test that polygonset is made of valid polygons
    {
        std::vector<PolygonWithHoles> polys(pSet.number_of_polygons_with_holes());
        pSet.polygons_with_holes(polys.begin());
        for(PolygonWithHoles& poly : polys) {
            //This fails has_valid_orientation_polygon_with_holes check
            assert(CGAL::is_valid_polygon_with_holes(poly, *traits)); 
        }
    }
}
```

## Environment

* Operating system: Windows 10
* Compiler: MSVC 2017 15.9.4
* Release or debug mode: Tested in debug mode, likely happens in both
* Specific flags used (if any):
Preprocessor defines:
CGAL_USE_CORE=1
CGAL_HEADER_ONLY=1

* CGAL version: 4.13, from the installer
* Boost version: 1.68
* Other libraries versions if used (Eigen, TBB, etc.):

### PR DESCRIPTION
**Pull request by efifogel**
## Release Management

* Affected package(s): Boolean_set_operations_2
* Issue(s) solved (if any): fix #3667
* Feature/Small Feature (if any):
* Link to compiled documentation (obligatory for small feature) [link](https://mydoc/Manual/Pkg)
* License and copyright ownership:

### CODE REVIEW

**Comment by lrineau** [comment]
Do you think that patch can be applied to a release branch, like `CGAL-4.12-branch` or `CGAL-4.13-branch`?

**Comment by efifogel** [comment]
Yes, it's a simple fix to a real bug.
However, the bug was only in the code that validates polygons, which is
usually executed in debug mode only.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
Warning here : 
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-127.shtml#Boolean_set_operations_2

**Comment by efifogel** [comment]
This was not caused by my changes, but I've fixed it nevertheless.
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by maxGimeno** [comment]
> This was not caused by my changes, but I've fixed it nevertheless.

Thank you, then :)

**Comment by Fro-Z** [comment]
I found a valid PolygonWithHoles that triggers a precondition fail during orientation test.
```c++
using K = CGAL::Exact_predicates_exact_constructions_kernel;
using PolygonSet = CGAL::Polygon_set_2<K>;
using PolygonWithHoles = CGAL::Polygon_with_holes_2<K>;
auto traits = std::make_unique<PolygonSet::Traits_2>();

std::stringstream sstream("6  2 1  3 0  5 4  2 1  1 3  0 2  0");
PolygonWithHoles poly;
sstream >> poly;

assert(CGAL::is_valid_polygon_with_holes(poly, *traits)); //This fails
```
This is the polygon:
img

The precondition triggered is one in Arr_segment_traits, that got called from line 144 of your code.

Because this problem is happening in both current master version and your patch, I've made it into a separate issue #3697

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-130.shtml

**Comment by lrineau** [comment]
Maxime has marked this PR as `Tested`, but I will block its merge in CGAL until @efifogel has confirmed if bug #3697 should be also fixed in this PR.

**Comment by efifogel** [comment]
So this pull request fixes #3697 as well.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-135.shtml

**Pull request merged**
