### PR TITLE
Allow FT that isn't floating point.

### PR DESCRIPTION
**Pull request by benlaurie**
## Summary of Changes

What it says on the tin.

## Release Management

* Affected package(s): `BGL`
* Issue(s) solved (if any): -
* Feature/Small Feature (if any): -
* License and copyright ownership:

### CODE REVIEW

**Comment by lrineau** [comment]
@MaelRL What do you think of the patch? It looks good to me.

**Comment by maxGimeno** [comment]
I would like a test for that, but I'm not sure there is one already for the bgl generators

**Review by sloriot — COMMENTED** [review]
I would remove the c-style cast that is harmful and useless IMHO

**Comment by MaelRL** [comment]
> I would remove the c-style cast that is harmful and useless IMHO

That was the reason for the flag. At best it should be `FT(i)`, but it's still useless.

**Comment by lrineau** [comment]
> > I would remove the c-style cast that is harmful and useless IMHO
> 
> That was the reason for the flag. At best it should be `FT(i)`, but it's still useless.

If the type `typename boost::graph_traits<Graph>::vertices_size_type` is a 64 bits integer, then compilers emit a warning about implicit casting to `double` loosing precision, because `double` has only 53 bits of mantissa. That is probably the reason of the explicit cast.

**Comment by benlaurie** [comment]
Some kind of cast is actually needed - try it.

Agree I should've used a C++ cast - I'm a bit rusty on C++ these days!

**Comment by benlaurie** [comment]
Without the cast, you get:

```
//home/ben/local/include/CGAL/boost/graph/generators.h:592:39: error: use of
      overloaded operator '*' is ambiguous (with operand types 'typename
      boost::graph_traits<Surface_mesh<Point_3<Epeck> > >::vertices_size_type'
      (aka 'unsigned int') and 'const FT' (aka 'const
      Lazy_exact_nt<boost::multiprecision::number<boost::multiprecision::backends::gmp_rational,
      boost::multiprecision::et_on> >'))
        P(0.5*diameter*cos(to_double(i*precision*to_rad))+base_center.x(),
                                     ~^~~~~~~~~~
```

**Comment by MaelRL** [comment]
Ah, you're right indeed, sorry.

Then `FT(i)` should be correct.

**Comment by benlaurie** [comment]
Update coming soon.

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.3-Ic-34.shtml

**Comment by lrineau** [comment]
@benlaurie Thanks for your contribution. It will be merged into `master` today.

I have checked your patch, and it *does not* require the signature of a contributor agreement with the CGAL project, because the patch is really small.

**Pull request merged**
