### PR TITLE
Modify flipping criteria in PMP::isotropic_remeshing and PMP::refine

### LINKED ISSUE #6982: PMP::triangulate_refine_and_fair_hole() creates pairs of intersecting triangles.
## Issue Details

PMP::triangulate_refine_and_fair_hole() creates pairs of intersecting triangles. As a consequence, boolean operations on meshes do not work.

The following parameters were used:
```
use_delaunay_triangulation = true
use_2d_constrained_delaunay_triangulation = true
threshold_distance = 0.25
fairing_continuity = 0
density_control_factor = root_two
```

The [original](https://github.com/CGAL/cgal/files/9854619/original.zip) and [resulting](https://github.com/CGAL/cgal/files/9854625/after_hole_filling.zip) meshes are attached.

After hole filling (invalid pairs of triangles highlighted):

Before hole filling + invalid pairs of triangles:

Two pairs of intersecting triangles:

[33468-9376.zip](https://github.com/CGAL/cgal/files/9854662/33468-9376.zip)

[33468-9381.zip](https://github.com/CGAL/cgal/files/9854666/33468-9381.zip)

These triangle pairs are found by the [PMP::self_intersections()](https://doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__intersection__grp.html#ga5c8f1c1aba66b32be12d88f852f87fb0) function.

In addition to these triangles, the hole filling function adds another [triangle](https://github.com/CGAL/cgal/files/9854703/non_manifold.zip) (the triangle is shown after the removal of intersecting pairs of triangles):

## Source Code

A slightly modified [Polygon_mesh_processing/hole_filling_example_SM.cpp](https://doc.cgal.org/latest/Polygon_mesh_processing/Polygon_mesh_processing_2hole_filling_example_SM_8cpp-example.html) for working with arbitrary meshes.

## Environment

* Operating system: Windows, 64 bits
* Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31629 for x64
* Release or debug mode: Release
* Specific flags used (if any):
* CGAL version: 5.5
* Boost version: 1.71.0

### PR DESCRIPTION
**Pull request by MaelRL**
### Criterion in `PMP::isotropic_remeshing()`

The criterion that takes the scalar_product of the cross products  is maybe adapted to minimize the curvature when triangulating faces,  but should_flip() is used in `PMP::isotropic_remeshing()`, `PMP::refine()`, and `PMP::remove_almost_degenerate_faces()`. These algorithms aim to produce well-shaped elements. The criterion is not adapted to these algorithms: for example, on a flat mesh the scalar product is meaningless so it will pick the diagonal which maximizes the product of the lengths and product of sines, but this might create very anisotropic elements since the sine of obtuse angles is still positive. In `PMP::isotropic_remeshing()`, we actually do not notice how bad the flip is because other operations (smoothing, collapsing, splitting) counter balance it.
 
The "new" criterion is simply the criterion used in mesh smoothing and the typical Delaunay criterion for surfaces. The old criterion is still used in `PMP::triangulate_faces()` since we care for a nice surface and not nice elements.

Below is an example of `PMP::isotropic_remeshing()` without collapse (left - input, middle - master, right - new flip criterion)

image

### Criterion in `PMP::refine()`

The current criterion is some kind of Delaunay ball (it calls `side_of_bounded_sphere()`), which might work OK for flat regions, but can produce super thin wedges (see issue: https://github.com/CGAL/cgal/issues/6982) when the mesh is not flat.

The criterion used instead is the one used in `PMP::isotropic_remeshing()` and `PMP::remove_almost_degenerate_faces()`, which is the typical angle-based surface Delaunay criterion.

Below is input, hole filling with old refine criterion, old filling with new refine criterion.

image

## Release Management

* Affected package(s): `PMP`
* Issue(s) solved (if any): fix #6982
* Feature/Small Feature (if any): -
* License and copyright ownership: no change

### CODE REVIEW

**Comment by sloriot** [comment]
```
/Users/magritte/cgal_root/CGAL-5.6-Ic-144/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h:305:75: warning: unused typedef 'FT' [-Wunused-local-typedef]
  typedef typename Traits::FT                                             FT;
                                                                          ^
/Users/magritte/cgal_root/CGAL-5.6-Ic-144/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h:307:75: warning: unused typedef 'Vector_3' [-Wunused-local-typedef]
  typedef typename Traits::Vector_3                                       Vector_3;
```

**Comment by sloriot** [comment]
compilation issue:
/mnt/testsuite/include/CGAL/Polygon_mesh_processing/repair_degeneracies.h:318:16: error: cannot convert 'CGAL::Lazy_exact_nt<__gmp_expr<__mpq_struct [1], __mpq_struct [1]> >' to 'const double' in initialization
  318 |   const double ap1 = angle(p0,p1,p2);

**Comment by sloriot** [comment]
Successfully tested in CGAL-5.6-Ic-160

**Comment by lrineau** [comment]
@MaelRL @sloriot @janetournois 

This PR is still marked https://github.com/CGAL/cgal/labels/under%20discussion. Do you all agreed on it?

**Comment by sloriot** [comment]
ping @janetournois :)

**Comment by janetournois** [comment]
We had discussed that with Mael internally.
I approve the changes, thank you

**Pull request merged**
