### PR TITLE
Polyhedron demo: add some OpenGL debugging information 

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

Add a QOpenGLDebugLogger to the viewer to easily track errors and warning from OpenGL. 
Unfortunately this will probably not help us tracking context errors, as this system is dependant of the said context.

### CODE REVIEW

**Comment by sloriot** [comment]
conflicts

**Comment by lrineau** [comment]
@maxGimeno This PR now has a conflict with `master`.

**Comment by maxGimeno** [comment]
I rebased the branch.

**Comment by lrineau** [comment]
Successfully tested in [CGAL-4.13-Ic-37][*], and then merged.

  [*]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.13-Ic-37.shtml

**Pull request merged**
