### PR TITLE
Polyhedron demo: isotropic remeshing preserves duplicated edges

### PR DESCRIPTION
**Pull request by sloriot**
Update the isotropic remeshing package so that when remeshing a bunch of polyhedra, you have the option to preserve the identical edges. This means that those edges will be automatically split to match the target edge length and those edges will be protected during the remeshing

cc @janetournois & @afabri

### CODE REVIEW

**Comment by lrineau** [comment]
Should not it target 4.8?

**Comment by sloriot** [comment]
Up to you, no constraint on my side

**Comment by lrineau** [comment]
There are warnings at https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-3.shtml#Polyhedron_Demo

**Comment by lrineau** [comment]
All the warnings are:
```
Plugins/PMP/Isotropic_remeshing_plugin.cpp:126:40: warning: unused typedef 'face_descriptor' [-Wunused-local-typedef]
Plugins/PMP/Isotropic_remeshing_plugin.cpp:93:23: warning: unused variable 'opposite_hd' [-Wunused-variable]
```

**Comment by sloriot** [comment]
Updated

**Comment by lrineau** [comment]
Will be in 4.9-Ic-6.

**Comment by lrineau** [comment]
There is still a warning reported by clang on MacOS or ArchLinux:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-6.shtml#Polyhedron_Demo
```
Plugins/PMP/Isotropic_remeshing_plugin.cpp:123:45: warning: unused typedef 'GT' [-Wunused-local-typedef]
  typedef boost::graph_traits<TriangleMesh> GT;
                                            ^
```

**Comment by sloriot** [comment]
Fixed

**Comment by lrineau** [comment]
This PR will be tested in [CGAL-4.9-Ic-7][i]...

[i]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-7.shtml

**Pull request merged**
