### PR TITLE
PMP: make triangulate_faces works with non filtered kernels

### LINKED ISSUE #873: triangulate_faces_example does not compile with Simple_cartesian<double>

### PR DESCRIPTION
**Pull request by sloriot**
Fixes #873

### CODE REVIEW

**Comment by sloriot** [comment]
@lrineau Please set the milestone

**Comment by lrineau** [comment]
Will be tested in [CGAL-4.9-Ic-6][6].

[6]: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-6.shtml

**Comment by lrineau** [comment]
TODO: decide if the backward-compatibility of the undocumented header is important or not. Cf. #1013.

**Comment by sloriot** [comment]
If we observe only compilation errors, I don't see the need to bother trying to preserve the compatibiily

**Comment by sloriot** [comment]
@lrineau ping

**Comment by lrineau** [comment]
@sloriot TODO:
- Re-add a trivial  `<CGAL/Triangulation_2_filtered_projection_traits_3.h>` that includes `<CGAL/Triangulation_2_projection_traits_3.h>`
- Add the deprecation macros in `<CGAL/Triangulation_2_filtered_projection_traits_3.h>`
- Add the deprecation notice in `changes.html`.

**Comment by lrineau** [comment]
*update:* I was wrong. The header was never used in the examples of the manual. No notice in `changes.html`.

**Pull request merged**
