### PR TITLE
Polyhedron_demo : adding edges to the self selection item

### PR DESCRIPTION
**Pull request by maxGimeno**
Adds edges to the self_selection item.

### CODE REVIEW

**Comment by lrineau** [comment]
Is not it the pull-request for which Andreas @afabri reported a runtime error?

**Comment by maxGimeno** [comment]
Yes it is.

**Comment by lrineau** [comment]
@maxGimeno @afabri Please check if the runtime error is still there.

**Comment by maxGimeno** [comment]
No runtime error actually. We tested it from the branch and everything runs fine, it is ready to merge.

**Comment by lrineau** [comment]
Can somebody try this PR manually at @CGAL/geometryfactory ?

**Comment by lrineau** [comment]
It seems Andreas has already tested it.

**Pull request merged**
