### PR TITLE
Fix for the doc of a release built from an Ic

### PR DESCRIPTION
**Pull request by sloriot**

### CODE REVIEW

**Comment by maxGimeno** [comment]
Successfully tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14-Ic-158.shtml

**Comment by sloriot** [comment]
There is something fishy. The patch in `Documentation/doc/scripts/generate_how_to_cite.py` should also fix the link issue of all http [here](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-158/output2/Manual/how_to_cite_cgal.html) but it's not. However the rest of the fix for 4.14 instead of 4.14-Ic-158 is good.

**Comment by lrineau** [comment]
[**@sloriot**](https://github.com/sloriot) commented on [Mar 27, 2019, 5:07 PM GMT+1](https://github.com/CGAL/cgal/pull/3798#issuecomment-477229411 "2019-03-27T16:07:59Z - Replied by Github Reply Comments"):
> There is something fishy. The patch in `Documentation/doc/scripts/generate_how_to_cite.py` should also fix the link issue of all http [here](https://cgal.geometryfactory.com/CGAL/Manual_doxygen_test/CGAL-4.14-Ic-158/output2/Manual/how_to_cite_cgal.html) but it's not.

It is fixed: the links are not relative.

**Comment by sloriot** [comment]
Got it, only the first misses a fix. Will fix that.

**Pull request merged**
