### PR TITLE
Ms 2 decomposition optimization efif

### PR DESCRIPTION
**Pull request by efifogel**
Implements the [2D Minkowski sum optimization](https://cgal.geometryfactory.com/CGAL/Members/wiki/Features/2D_Minkowski_sum_by_decomposition) feature.

### CODE REVIEW

**Comment by sloriot** [comment]
The [example line](https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-63.shtml) is all red but on windows

**Comment by efifogel** [comment]
This is a problem.

We use to have:

1. ms(p1, p2, decomp, traits)
2. ms(p1, p2, decomp)

where the latter constructs a traits and calls the former.

I've introduced:

3. ms(p1, p2, decomp1, decomp2, traits)
4. ms(p1, p2, decomp1, decomp2)

Again, the latter calls the former.
Now the call:

ms(p1, p2, decomp, traits)

is ambiguous as it can match either 1 or 4.

Notice that the call:

ms(p1, p2, decomp1, decomp2)

is not ambiguous, because traits in (1) is of a type that is a template
parameter directly.

One option is to give up on (4). It's not terrible, but definitely less
convenient, as users will have to do the following always:

typename Minkowski_sum_by_decomposition_2<DecompositionStrategy1_,
                                          DecompositionStrategy2_,
                                          Container_>::Traits_2 traits;
ms(p1, p2, decomp1, decomp2,traits);

(where DecompositionStrategy1_, DecompositionStrategy2_, and Container_ are
the template parameters).

Can you see a better solution?


   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Replacing
```
minkowski_sum_2(const Polygon_with_holes_2<Kernel_, Container_>& pgn1,
                const Polygon_with_holes_2<Kernel_, Container_>& pgn2,
                const DecompositionStrategy1_& decomposition_strategy1,
                const typename
                CGAL::Gps_segment_traits_2<typename DecompositionStrategy1_::Kernel,
                                           Container_,
                                           Minkowski_sum_by_decomposition_2<DecompositionStrategy1_,
                                                 DecompositionStrategy1_,
                                                 Container_>::Traits_2 & traits)
```
by
```
minkowski_sum_2(const Polygon_with_holes_2<Kernel_, Container_>& pgn1,
                const Polygon_with_holes_2<Kernel_, Container_>& pgn2,
                const DecompositionStrategy1_& decomposition_strategy1,
                const typename
                CGAL::Gps_segment_traits_2<typename DecompositionStrategy1_::Kernel,
                                           Container_,
                                           CGAL::Arr_segment_traits_2<typename DecompositionStrategy1_::Kernel> >&  traits)
```

fixed the issue on my machine. It simply makes the type requirement explicit.

**Comment by efifogel** [comment]
Indeed. Thanks!

Actually, I can (and should) use 'Kernel_' instead of 'typename
DecompositionStrategy1_::Kernel' (Don't know why it was there in the the
first place...)

   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/

**Comment by sloriot** [comment]
Testsuite looks good and `test_merge_of_branch` reported no error.

**Comment by sloriot** [comment]
@efifogel If you have nothing more to add in this branch, I'll merge the PR.

**Comment by sloriot** [comment]
@efifogel  `changes.html` has not been updated

**Pull request merged**
