### PR TITLE
Mesh_3: New Attributes Type for VTU Output

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes
Change the APi of `output_to_vtu_with_attributes()` to allow Double, uchar and ulong as possible types for attributes.
## Release Management

* Affected package(s):Mesh_3

### CODE REVIEW

**Comment by lrineau** [comment]
I have selected this PR for 4.14-branch, because:
  - it does not add documented features,
  - it does not break existing code,
  - and that eases its deployment to users (no dependency to C++14).

**Comment by maxGimeno** [comment]
Tested in https://cgal.geometryfactory.com/CGAL/testsuite/results-5.0-Ic-5.shtml

**Comment by lrineau** [comment]
This PR introduced compilation errors in CGAL-4.14-branch, when C++11 is not available:
https://cgal.geometryfactory.com/CGAL/testsuite/results-4.14.1-I-166.shtml#Mesh_3_Examples

**Comment by lrineau** [comment]
Fixed in 450efd39124.

**Pull request merged**
